#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

export GCP_PROJECT="${GCP_PROJECT:-openagentsgemini}"
export GCP_REGION="${GCP_REGION:-us-central1}"
export GCP_ZONE="${GCP_ZONE:-us-central1-a}"

export OA_VPC="${OA_VPC:-oa-lightning}"
export OA_SUBNET="${OA_SUBNET:-oa-lightning-us-central1}"

export NEXUS_VM="${NEXUS_VM:-nexus-mainnet-1}"
export NEXUS_MACHINE_TYPE="${NEXUS_MACHINE_TYPE:-e2-standard-4}"
export NEXUS_SERVICE_ACCOUNT_NAME="${NEXUS_SERVICE_ACCOUNT_NAME:-nexus-mainnet}"
export NEXUS_SERVICE_ACCOUNT_EMAIL="${NEXUS_SERVICE_ACCOUNT_EMAIL:-${NEXUS_SERVICE_ACCOUNT_NAME}@${GCP_PROJECT}.iam.gserviceaccount.com}"
export NEXUS_TAG="${NEXUS_TAG:-nexus-host}"
export NEXUS_IAP_SSH_FIREWALL_RULE="${NEXUS_IAP_SSH_FIREWALL_RULE:-oa-allow-${NEXUS_TAG}-iap-ssh}"

export NEXUS_BUILDER_VM="${NEXUS_BUILDER_VM:-nexus-builder-1}"
export NEXUS_BUILDER_MACHINE_TYPE="${NEXUS_BUILDER_MACHINE_TYPE:-c3d-standard-8}"
export NEXUS_BUILDER_SERVICE_ACCOUNT_EMAIL="${NEXUS_BUILDER_SERVICE_ACCOUNT_EMAIL:-${NEXUS_SERVICE_ACCOUNT_EMAIL}}"
export NEXUS_BUILDER_TAG="${NEXUS_BUILDER_TAG:-nexus-builder}"
export NEXUS_BUILDER_IAP_SSH_FIREWALL_RULE="${NEXUS_BUILDER_IAP_SSH_FIREWALL_RULE:-oa-allow-${NEXUS_BUILDER_TAG}-iap-ssh}"
export NEXUS_BUILDER_BOOT_DISK_SIZE_GB="${NEXUS_BUILDER_BOOT_DISK_SIZE_GB:-100}"
export NEXUS_BUILDER_BOOT_DISK_TYPE="${NEXUS_BUILDER_BOOT_DISK_TYPE:-pd-ssd}"
export NEXUS_BUILDER_CACHE_DISK="${NEXUS_BUILDER_CACHE_DISK:-nexus-builder-cache-1}"
export NEXUS_BUILDER_CACHE_DISK_DEVICE_NAME="${NEXUS_BUILDER_CACHE_DISK_DEVICE_NAME:-nexus-builder-cache}"
export NEXUS_BUILDER_CACHE_DISK_SIZE_GB="${NEXUS_BUILDER_CACHE_DISK_SIZE_GB:-200}"
export NEXUS_BUILDER_CACHE_DISK_TYPE="${NEXUS_BUILDER_CACHE_DISK_TYPE:-pd-ssd}"
export NEXUS_BUILDER_IMAGE_FAMILY="${NEXUS_BUILDER_IMAGE_FAMILY:-ubuntu-2204-lts}"
export NEXUS_BUILDER_IMAGE_PROJECT="${NEXUS_BUILDER_IMAGE_PROJECT:-ubuntu-os-cloud}"
export NEXUS_BUILDER_CACHE_MOUNT_POINT="${NEXUS_BUILDER_CACHE_MOUNT_POINT:-/mnt/disks/nexus-builder-cache}"
export NEXUS_BUILDER_USER="${NEXUS_BUILDER_USER:-nexus-builder}"
export NEXUS_BUILDER_RUST_TOOLCHAIN="${NEXUS_BUILDER_RUST_TOOLCHAIN:-1.88.0}"
export NEXUS_BUILDER_SCCACHE_VERSION="${NEXUS_BUILDER_SCCACHE_VERSION:-0.8.2}"
export NEXUS_BUILDER_BUILD_PROFILE="${NEXUS_BUILDER_BUILD_PROFILE:-fast-release}"

export NEXUS_RELEASE_ROOT="${NEXUS_RELEASE_ROOT:-/opt/nexus-relay}"
export NEXUS_RELEASES_DIR="${NEXUS_RELEASES_DIR:-${NEXUS_RELEASE_ROOT}/releases}"
export NEXUS_CURRENT_LINK="${NEXUS_CURRENT_LINK:-${NEXUS_RELEASE_ROOT}/current}"
export NEXUS_PREVIOUS_LINK="${NEXUS_PREVIOUS_LINK:-${NEXUS_RELEASE_ROOT}/previous}"
export NEXUS_SHARED_DIR="${NEXUS_SHARED_DIR:-${NEXUS_RELEASE_ROOT}/shared}"
export NEXUS_SERVICE_USER="${NEXUS_SERVICE_USER:-nexus}"
export NEXUS_SERVICE_GROUP="${NEXUS_SERVICE_GROUP:-${NEXUS_SERVICE_USER}}"
export NEXUS_SERVICE_UID="${NEXUS_SERVICE_UID:-60000}"
export NEXUS_RUNTIME_CONFIG_DIR="${NEXUS_RUNTIME_CONFIG_DIR:-/etc/nexus-relay}"
export NEXUS_RUNTIME_ENV_PATH="${NEXUS_RUNTIME_ENV_PATH:-${NEXUS_RUNTIME_CONFIG_DIR}/nexus-relay.env}"
export NEXUS_UPSTREAM_CONFIG_PATH="${NEXUS_UPSTREAM_CONFIG_PATH:-${NEXUS_RUNTIME_CONFIG_DIR}/upstream-config.toml}"
export NEXUS_SYSTEMD_UNIT_PATH="${NEXUS_SYSTEMD_UNIT_PATH:-/etc/systemd/system/nexus-relay.service}"
export NEXUS_IMAGE_UNIT_BACKUP_PATH="${NEXUS_IMAGE_UNIT_BACKUP_PATH:-${NEXUS_SYSTEMD_UNIT_PATH}.image-backup}"
export VERIFY_PUBLIC_CHECKS_ENABLED="${VERIFY_PUBLIC_CHECKS_ENABLED:-true}"

export NEXUS_DATA_DISK="${NEXUS_DATA_DISK:-nexus-relay-data-mainnet}"
export NEXUS_DATA_DISK_DEVICE_NAME="${NEXUS_DATA_DISK_DEVICE_NAME:-nexus-relay-data}"
export NEXUS_DATA_DISK_SIZE_GB="${NEXUS_DATA_DISK_SIZE_GB:-200}"
export NEXUS_DATA_DISK_TYPE="${NEXUS_DATA_DISK_TYPE:-pd-ssd}"

export NEXUS_LDK_VM="${NEXUS_LDK_VM:-nexus-ldk-mainnet-1}"
export NEXUS_LDK_MACHINE_TYPE="${NEXUS_LDK_MACHINE_TYPE:-e2-standard-4}"
export NEXUS_LDK_SERVICE_ACCOUNT_NAME="${NEXUS_LDK_SERVICE_ACCOUNT_NAME:-nexus-ldk-mainnet}"
export NEXUS_LDK_SERVICE_ACCOUNT_EMAIL="${NEXUS_LDK_SERVICE_ACCOUNT_EMAIL:-${NEXUS_LDK_SERVICE_ACCOUNT_NAME}@${GCP_PROJECT}.iam.gserviceaccount.com}"
export NEXUS_LDK_TAG="${NEXUS_LDK_TAG:-nexus-ldk-host}"
export NEXUS_LDK_IAP_SSH_FIREWALL_RULE="${NEXUS_LDK_IAP_SSH_FIREWALL_RULE:-oa-allow-${NEXUS_LDK_TAG}-iap-ssh}"
export NEXUS_LDK_GRPC_FIREWALL_RULE="${NEXUS_LDK_GRPC_FIREWALL_RULE:-oa-allow-${NEXUS_LDK_TAG}-grpc-private}"
export NEXUS_LDK_P2P_FIREWALL_RULE="${NEXUS_LDK_P2P_FIREWALL_RULE:-oa-allow-${NEXUS_LDK_TAG}-p2p}"
export NEXUS_LDK_PRIVATE_P2P_FIREWALL_RULE="${NEXUS_LDK_PRIVATE_P2P_FIREWALL_RULE:-oa-allow-${NEXUS_LDK_TAG}-p2p-private}"
export NEXUS_LDK_PRIVATE_P2P_SOURCE_TAGS="${NEXUS_LDK_PRIVATE_P2P_SOURCE_TAGS:-oa-lnd}"
export NEXUS_LDK_DATA_DISK="${NEXUS_LDK_DATA_DISK:-nexus-ldk-data-mainnet}"
export NEXUS_LDK_DATA_DISK_DEVICE_NAME="${NEXUS_LDK_DATA_DISK_DEVICE_NAME:-nexus-ldk-data}"
export NEXUS_LDK_DATA_DISK_SIZE_GB="${NEXUS_LDK_DATA_DISK_SIZE_GB:-200}"
export NEXUS_LDK_DATA_DISK_TYPE="${NEXUS_LDK_DATA_DISK_TYPE:-pd-ssd}"
export NEXUS_LDK_BOOT_DISK_SIZE_GB="${NEXUS_LDK_BOOT_DISK_SIZE_GB:-100}"
export NEXUS_LDK_IMAGE_FAMILY="${NEXUS_LDK_IMAGE_FAMILY:-ubuntu-2204-lts}"
export NEXUS_LDK_IMAGE_PROJECT="${NEXUS_LDK_IMAGE_PROJECT:-ubuntu-os-cloud}"
export NEXUS_LDK_STORAGE_DIR="${NEXUS_LDK_STORAGE_DIR:-/var/lib/ldk-server}"
export NEXUS_LDK_CONFIG_DIR="${NEXUS_LDK_CONFIG_DIR:-/etc/ldk-server}"
export NEXUS_LDK_CONFIG_PATH="${NEXUS_LDK_CONFIG_PATH:-${NEXUS_LDK_CONFIG_DIR}/ldk-server.toml}"
export NEXUS_LDK_GRPC_PORT="${NEXUS_LDK_GRPC_PORT:-3536}"
export NEXUS_LDK_P2P_PORT="${NEXUS_LDK_P2P_PORT:-9735}"
export NEXUS_LDK_NETWORK="${NEXUS_LDK_NETWORK:-bitcoin}"
export NEXUS_LDK_ALIAS="${NEXUS_LDK_ALIAS:-openagents-nexus-ldk}"
export NEXUS_LDK_SERVER_REF="${NEXUS_LDK_SERVER_REF:-main}"
export NEXUS_LDK_ALLOW_PUBLIC_P2P="${NEXUS_LDK_ALLOW_PUBLIC_P2P:-false}"
export NEXUS_LDK_TOPOLOGY_DRY_RUN="${NEXUS_LDK_TOPOLOGY_DRY_RUN:-false}"
export NEXUS_LDK_INSTALL_DRY_RUN="${NEXUS_LDK_INSTALL_DRY_RUN:-false}"
export NEXUS_LDK_INSTALL_ALLOW_PLACEHOLDER_BITCOIND="${NEXUS_LDK_INSTALL_ALLOW_PLACEHOLDER_BITCOIND:-false}"
export NEXUS_LDK_BACKUP_DRY_RUN="${NEXUS_LDK_BACKUP_DRY_RUN:-false}"
export NEXUS_LDK_RESTORE_DRY_RUN="${NEXUS_LDK_RESTORE_DRY_RUN:-false}"
export NEXUS_LDK_REMOTE_SMOKE="${NEXUS_LDK_REMOTE_SMOKE:-false}"
export NEXUS_LDK_BACKUP_BUCKET="${NEXUS_LDK_BACKUP_BUCKET:-gs://${GCP_PROJECT}-nexus-ldk-backups}"
export NEXUS_LDK_BACKUP_PREFIX="${NEXUS_LDK_BACKUP_PREFIX:-ldk-server}"
export NEXUS_LDK_RESTORE_DRILL_VM="${NEXUS_LDK_RESTORE_DRILL_VM:-nexus-ldk-restore-drill}"
export NEXUS_LDK_RESTORE_DRILL_DISK="${NEXUS_LDK_RESTORE_DRILL_DISK:-nexus-ldk-restore-drill-data}"

export NEXUS_BITCOIND_VM="${NEXUS_BITCOIND_VM:-oa-bitcoind}"
export NEXUS_BITCOIND_TAG="${NEXUS_BITCOIND_TAG:-oa-bitcoind}"
export NEXUS_BITCOIND_RPC_FIREWALL_RULE="${NEXUS_BITCOIND_RPC_FIREWALL_RULE:-oa-allow-${NEXUS_BITCOIND_TAG}-rpc-from-${NEXUS_LDK_TAG}}"
export NEXUS_BITCOIND_RPC_HOST="${NEXUS_BITCOIND_RPC_HOST:-127.0.0.1}"
export NEXUS_BITCOIND_RPC_PORT="${NEXUS_BITCOIND_RPC_PORT:-8332}"
export NEXUS_BITCOIND_RPC_USER="${NEXUS_BITCOIND_RPC_USER:-openagents-ldk}"
export NEXUS_BITCOIND_RPC_PASSWORD_PATH="${NEXUS_BITCOIND_RPC_PASSWORD_PATH:-/etc/ldk-server/bitcoind-rpc-password}"

export NEXUS_ARTIFACT_REPO="${NEXUS_ARTIFACT_REPO:-openagents-nexus}"
export NEXUS_IMAGE_NAME="${NEXUS_IMAGE_NAME:-nexus-relay}"
export NEXUS_IMAGE_TAG="${NEXUS_IMAGE_TAG:-latest}"
export NEXUS_IMAGE="${NEXUS_IMAGE:-${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${NEXUS_ARTIFACT_REPO}/${NEXUS_IMAGE_NAME}:${NEXUS_IMAGE_TAG}}"
export NEXUS_BUILD_UPDATE_LATEST_TAG="${NEXUS_BUILD_UPDATE_LATEST_TAG:-true}"
export NEXUS_BUILD_PROFILE="${NEXUS_BUILD_PROFILE:-fast-release}"
export NEXUS_BUILD_TIMEOUT="${NEXUS_BUILD_TIMEOUT:-7200s}"
export NEXUS_BUILD_MACHINE_TYPE="${NEXUS_BUILD_MACHINE_TYPE:-e2-highcpu-32}"
export NEXUS_BUILD_DISK_SIZE_GB="${NEXUS_BUILD_DISK_SIZE_GB:-200}"
export NEXUS_BUILD_CACHE_IMAGE="${NEXUS_BUILD_CACHE_IMAGE:-${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${NEXUS_ARTIFACT_REPO}/${NEXUS_IMAGE_NAME}:buildcache-${NEXUS_BUILD_PROFILE}}"
export NEXUS_BUILD_SCCACHE_ENABLED="${NEXUS_BUILD_SCCACHE_ENABLED:-false}"
export NEXUS_BUILD_SCCACHE_BUCKET="${NEXUS_BUILD_SCCACHE_BUCKET:-${GCP_PROJECT}-nexus-build-cache}"
export NEXUS_BUILD_SCCACHE_KEY_PREFIX="${NEXUS_BUILD_SCCACHE_KEY_PREFIX:-nexus-relay/${NEXUS_BUILD_PROFILE}}"

export NEXUS_PUBLIC_HOST="${NEXUS_PUBLIC_HOST:-nexus.openagents.com}"
export NEXUS_PUBLIC_URL="${NEXUS_PUBLIC_URL:-https://${NEXUS_PUBLIC_HOST}/}"
export NEXUS_PUBLIC_WS_URL="${NEXUS_PUBLIC_WS_URL:-wss://${NEXUS_PUBLIC_HOST}/}"
export NEXUS_PUBLIC_HEALTH_URL="${NEXUS_PUBLIC_HEALTH_URL:-${NEXUS_PUBLIC_URL%/}/healthz}"
export NEXUS_BINARY_RELEASE_STEP_TIMEOUT_SECONDS="${NEXUS_BINARY_RELEASE_STEP_TIMEOUT_SECONDS:-900}"
export NEXUS_BINARY_RELEASE_UPLOAD_TIMEOUT_SECONDS="${NEXUS_BINARY_RELEASE_UPLOAD_TIMEOUT_SECONDS:-900}"
export NEXUS_BINARY_RELEASE_ACTIVATION_TIMEOUT_SECONDS="${NEXUS_BINARY_RELEASE_ACTIVATION_TIMEOUT_SECONDS:-600}"
export NEXUS_BINARY_RELEASE_CLEANUP_TIMEOUT_SECONDS="${NEXUS_BINARY_RELEASE_CLEANUP_TIMEOUT_SECONDS:-90}"
export NEXUS_BINARY_RELEASE_PUBLIC_PROBE_TIMEOUT_SECONDS="${NEXUS_BINARY_RELEASE_PUBLIC_PROBE_TIMEOUT_SECONDS:-20}"
export NEXUS_BINARY_RELEASE_PUBLIC_PROBE_ATTEMPTS="${NEXUS_BINARY_RELEASE_PUBLIC_PROBE_ATTEMPTS:-5}"
export NEXUS_BINARY_RELEASE_PUBLIC_PROBE_RETRY_DELAY_SECONDS="${NEXUS_BINARY_RELEASE_PUBLIC_PROBE_RETRY_DELAY_SECONDS:-5}"

export NEXUS_HEALTH_RUNNER_SERVICE_ACCOUNT_NAME="${NEXUS_HEALTH_RUNNER_SERVICE_ACCOUNT_NAME:-nexus-health-runner}"
export NEXUS_HEALTH_RUNNER_SERVICE_ACCOUNT_EMAIL="${NEXUS_HEALTH_RUNNER_SERVICE_ACCOUNT_EMAIL:-${NEXUS_HEALTH_RUNNER_SERVICE_ACCOUNT_NAME}@${GCP_PROJECT}.iam.gserviceaccount.com}"
export NEXUS_HEALTH_RUNNER_JOB="${NEXUS_HEALTH_RUNNER_JOB:-nexus-health-runner}"
export NEXUS_HEALTH_RUNNER_SERVICE="${NEXUS_HEALTH_RUNNER_SERVICE:-nexus-health-runner-service}"
export NEXUS_HEALTH_RUNNER_REGION="${NEXUS_HEALTH_RUNNER_REGION:-${GCP_REGION}}"
export NEXUS_HEALTH_RUNNER_IMAGE="${NEXUS_HEALTH_RUNNER_IMAGE:-${NEXUS_IMAGE}}"
export NEXUS_HEALTH_RUNNER_NEXUS_BASE_URL="${NEXUS_HEALTH_RUNNER_NEXUS_BASE_URL:-${NEXUS_PUBLIC_URL%/}}"
export NEXUS_HEALTH_RUNNER_FORGE_BASE_URL="${NEXUS_HEALTH_RUNNER_FORGE_BASE_URL:-}"
export NEXUS_HEALTH_RUNNER_PROJECT_ID="${NEXUS_HEALTH_RUNNER_PROJECT_ID:-openagents}"
export NEXUS_HEALTH_RUNNER_ACTOR_ID="${NEXUS_HEALTH_RUNNER_ACTOR_ID:-nexus-health-runner}"
export NEXUS_HEALTH_RUNNER_JOB_ARGS="${NEXUS_HEALTH_RUNNER_JOB_ARGS:---json}"
export NEXUS_HEALTH_RUNNER_SERVER_ARGS="${NEXUS_HEALTH_RUNNER_SERVER_ARGS:---dry-run,--json}"
export NEXUS_HEALTH_RUNNER_EXTERNAL_VANTAGE_ID="${NEXUS_HEALTH_RUNNER_EXTERNAL_VANTAGE_ID:-gcp-${NEXUS_HEALTH_RUNNER_REGION}-cloud-run}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_NAME="${NEXUS_HEALTH_RUNNER_SCHEDULER_NAME:-nexus-health-runner-every-minute}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_INTERVAL_SECONDS="${NEXUS_HEALTH_RUNNER_SCHEDULER_INTERVAL_SECONDS:-60}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_CRON="${NEXUS_HEALTH_RUNNER_SCHEDULER_CRON:-* * * * *}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_TIME_ZONE="${NEXUS_HEALTH_RUNNER_SCHEDULER_TIME_ZONE:-Etc/UTC}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_DESCRIPTION="${NEXUS_HEALTH_RUNNER_SCHEDULER_DESCRIPTION:-Run OpenAgents Nexus health runner continuously from hosted GCP identity}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_OAUTH_SERVICE_ACCOUNT_EMAIL="${NEXUS_HEALTH_RUNNER_SCHEDULER_OAUTH_SERVICE_ACCOUNT_EMAIL:-${NEXUS_HEALTH_RUNNER_SERVICE_ACCOUNT_EMAIL}}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_OIDC_SERVICE_ACCOUNT_EMAIL="${NEXUS_HEALTH_RUNNER_SCHEDULER_OIDC_SERVICE_ACCOUNT_EMAIL:-${NEXUS_HEALTH_RUNNER_SERVICE_ACCOUNT_EMAIL}}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_AUTH_MODE="${NEXUS_HEALTH_RUNNER_SCHEDULER_AUTH_MODE:-oauth}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_OIDC_AUDIENCE="${NEXUS_HEALTH_RUNNER_SCHEDULER_OIDC_AUDIENCE:-}"
export NEXUS_HEALTH_RUNNER_SCHEDULER_URI="${NEXUS_HEALTH_RUNNER_SCHEDULER_URI:-https://${NEXUS_HEALTH_RUNNER_REGION}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${GCP_PROJECT}/jobs/${NEXUS_HEALTH_RUNNER_JOB}:run}"
export NEXUS_HEALTH_RUNNER_CPU="${NEXUS_HEALTH_RUNNER_CPU:-1}"
export NEXUS_HEALTH_RUNNER_MEMORY="${NEXUS_HEALTH_RUNNER_MEMORY:-512Mi}"
export NEXUS_HEALTH_RUNNER_SERVICE_MIN_INSTANCES="${NEXUS_HEALTH_RUNNER_SERVICE_MIN_INSTANCES:-1}"
export NEXUS_HEALTH_RUNNER_SERVICE_MAX_INSTANCES="${NEXUS_HEALTH_RUNNER_SERVICE_MAX_INSTANCES:-1}"
export NEXUS_HEALTH_RUNNER_TASK_TIMEOUT="${NEXUS_HEALTH_RUNNER_TASK_TIMEOUT:-300s}"
export NEXUS_HEALTH_RUNNER_MAX_RETRIES="${NEXUS_HEALTH_RUNNER_MAX_RETRIES:-0}"
export NEXUS_HEALTH_RUNNER_ATTACH_FORGE_SECRETS="${NEXUS_HEALTH_RUNNER_ATTACH_FORGE_SECRETS:-true}"
export NEXUS_HEALTH_RUNNER_ATTACH_NEXUS_ADMIN_SECRET="${NEXUS_HEALTH_RUNNER_ATTACH_NEXUS_ADMIN_SECRET:-false}"
export NEXUS_HEALTH_RUNNER_SECRET_FORGE_BEARER_TOKEN="${NEXUS_HEALTH_RUNNER_SECRET_FORGE_BEARER_TOKEN:-nexus-health-agent-forge-bearer-token}"
export NEXUS_HEALTH_RUNNER_SECRET_FORGE_ACTOR_JWT="${NEXUS_HEALTH_RUNNER_SECRET_FORGE_ACTOR_JWT:-nexus-health-agent-forge-actor-jwt}"
export NEXUS_HEALTH_RUNNER_SECRET_NEXUS_ADMIN_BEARER_TOKEN="${NEXUS_HEALTH_RUNNER_SECRET_NEXUS_ADMIN_BEARER_TOKEN:-nexus-health-agent-nexus-admin-bearer-token}"
export NEXUS_HEALTH_RUNNER_DRY_RUN="${NEXUS_HEALTH_RUNNER_DRY_RUN:-false}"
export NEXUS_HEALTH_RUNNER_SECRET_SMOKE_ENABLED="${NEXUS_HEALTH_RUNNER_SECRET_SMOKE_ENABLED:-false}"
export NEXUS_HEALTH_RUNNER_LOG_SECRET_SCAN_ENABLED="${NEXUS_HEALTH_RUNNER_LOG_SECRET_SCAN_ENABLED:-true}"
export NEXUS_CLOUDFLARE_TUNNEL_NAME="${NEXUS_CLOUDFLARE_TUNNEL_NAME:-nexus-mainnet}"
export NEXUS_CLOUDFLARE_TUNNEL_IMAGE="${NEXUS_CLOUDFLARE_TUNNEL_IMAGE:-cloudflare/cloudflared:2025.10.0}"
export NEXUS_CLOUDFLARE_TUNNEL_ORIGIN_URL="${NEXUS_CLOUDFLARE_TUNNEL_ORIGIN_URL:-http://127.0.0.1:8080}"
export NEXUS_CLOUDFLARE_TUNNEL_TOKEN="${NEXUS_CLOUDFLARE_TUNNEL_TOKEN:-}"
export NEXUS_CLOUDFLARE_SKIP_DNS_SETUP="${NEXUS_CLOUDFLARE_SKIP_DNS_SETUP:-false}"

export NEXUS_LISTEN_ADDR="${NEXUS_LISTEN_ADDR:-0.0.0.0:8080}"
export NEXUS_UPSTREAM_LISTEN_ADDR="${NEXUS_UPSTREAM_LISTEN_ADDR:-127.0.0.1:42111}"
export NEXUS_DATA_DIR="${NEXUS_DATA_DIR:-/var/lib/nexus-relay}"
export NEXUS_RECEIPT_LOG_PATH="${NEXUS_RECEIPT_LOG_PATH:-${NEXUS_DATA_DIR}/nexus-control-receipts.jsonl}"
export NEXUS_CONTROL_TREASURY_ENABLED="${NEXUS_CONTROL_TREASURY_ENABLED:-false}"
export NEXUS_CONTROL_TREASURY_PAYOUT_SATS_PER_WINDOW="${NEXUS_CONTROL_TREASURY_PAYOUT_SATS_PER_WINDOW:-0}"
export NEXUS_CONTROL_TREASURY_PAYOUT_INTERVAL_SECONDS="${NEXUS_CONTROL_TREASURY_PAYOUT_INTERVAL_SECONDS:-3600}"
export NEXUS_CONTROL_TREASURY_REQUIRE_SELLABLE="${NEXUS_CONTROL_TREASURY_REQUIRE_SELLABLE:-true}"
export NEXUS_CONTROL_TREASURY_DAILY_BUDGET_CAP_SATS="${NEXUS_CONTROL_TREASURY_DAILY_BUDGET_CAP_SATS:-21000}"
export NEXUS_CONTROL_TREASURY_RECONCILIATION_HORIZON_SECONDS="${NEXUS_CONTROL_TREASURY_RECONCILIATION_HORIZON_SECONDS:-86400}"
export NEXUS_CONTROL_TREASURY_STATE_PATH="${NEXUS_CONTROL_TREASURY_STATE_PATH:-${NEXUS_DATA_DIR}/treasury/treasury-state.json}"
export NEXUS_CONTROL_TREASURY_WALLET_MNEMONIC_PATH="${NEXUS_CONTROL_TREASURY_WALLET_MNEMONIC_PATH:-${NEXUS_DATA_DIR}/treasury/treasury.mnemonic}"
export NEXUS_CONTROL_TREASURY_WALLET_STORAGE_DIR="${NEXUS_CONTROL_TREASURY_WALLET_STORAGE_DIR:-${NEXUS_DATA_DIR}/treasury/wallet}"
export NEXUS_CONTROL_TREASURY_WALLET_NETWORK="${NEXUS_CONTROL_TREASURY_WALLET_NETWORK:-mainnet}"
export NEXUS_CONTROL_TREASURY_WALLET_REAL_TIME_SYNC_ENABLED="${NEXUS_CONTROL_TREASURY_WALLET_REAL_TIME_SYNC_ENABLED:-false}"
export NEXUS_CONTROL_TREASURY_WALLET_STATUS_REFRESH_SECONDS="${NEXUS_CONTROL_TREASURY_WALLET_STATUS_REFRESH_SECONDS:-3}"
export NEXUS_CONTROL_TREASURY_MAX_CONCURRENT_SENDS="${NEXUS_CONTROL_TREASURY_MAX_CONCURRENT_SENDS:-16}"
export TOKIO_WORKER_THREADS="${TOKIO_WORKER_THREADS:-16}"
export NEXUS_RELAY_AUTHORITY_TOKIO_WORKER_THREADS="${NEXUS_RELAY_AUTHORITY_TOKIO_WORKER_THREADS:-4}"
export NEXUS_ALLOW_ZERO_TREASURY_IN_PRODUCTION="${NEXUS_ALLOW_ZERO_TREASURY_IN_PRODUCTION:-false}"
export NEXUS_TREASURY_WATCHDOG_ENABLED="${NEXUS_TREASURY_WATCHDOG_ENABLED:-true}"
export NEXUS_TREASURY_WATCHDOG_INTERVAL_SECONDS="${NEXUS_TREASURY_WATCHDOG_INTERVAL_SECONDS:-300}"
export NEXUS_TREASURY_WATCHDOG_MAX_IDLE_SECONDS="${NEXUS_TREASURY_WATCHDOG_MAX_IDLE_SECONDS:-300}"
export NEXUS_TREASURY_WATCHDOG_MAX_CONFIRM_LAG_SECONDS="${NEXUS_TREASURY_WATCHDOG_MAX_CONFIRM_LAG_SECONDS:-900}"
export NEXUS_TREASURY_WATCHDOG_MAX_RESTARTS_PER_HOUR="${NEXUS_TREASURY_WATCHDOG_MAX_RESTARTS_PER_HOUR:-12}"
export NEXUS_TREASURY_WATCHDOG_STARTUP_GRACE_SECONDS="${NEXUS_TREASURY_WATCHDOG_STARTUP_GRACE_SECONDS:-180}"
export NEXUS_TREASURY_WATCHDOG_LOCAL_STATUS_URL="${NEXUS_TREASURY_WATCHDOG_LOCAL_STATUS_URL:-http://127.0.0.1:8080/v1/treasury/status}"
export NEXUS_TREASURY_WATCHDOG_SERVICE_NAME="${NEXUS_TREASURY_WATCHDOG_SERVICE_NAME:-nexus-relay}"
export NEXUS_TREASURY_WATCHDOG_RESTART_MODE="${NEXUS_TREASURY_WATCHDOG_RESTART_MODE:-service_inactive_only}"
export NEXUS_PUBLIC_WATCHDOG_ENABLED="${NEXUS_PUBLIC_WATCHDOG_ENABLED:-true}"
export NEXUS_PUBLIC_WATCHDOG_INTERVAL_SECONDS="${NEXUS_PUBLIC_WATCHDOG_INTERVAL_SECONDS:-60}"
export NEXUS_PUBLIC_WATCHDOG_STARTUP_GRACE_SECONDS="${NEXUS_PUBLIC_WATCHDOG_STARTUP_GRACE_SECONDS:-180}"
export NEXUS_PUBLIC_WATCHDOG_MAX_RESTARTS_PER_HOUR="${NEXUS_PUBLIC_WATCHDOG_MAX_RESTARTS_PER_HOUR:-12}"
export NEXUS_PUBLIC_WATCHDOG_LOCAL_HEALTH_URL="${NEXUS_PUBLIC_WATCHDOG_LOCAL_HEALTH_URL:-http://127.0.0.1:8080/healthz}"
export NEXUS_PUBLIC_WATCHDOG_PUBLIC_HEALTH_URL="${NEXUS_PUBLIC_WATCHDOG_PUBLIC_HEALTH_URL:-${NEXUS_PUBLIC_HEALTH_URL}}"
export NEXUS_PUBLIC_WATCHDOG_PUBLIC_STATS_URL="${NEXUS_PUBLIC_WATCHDOG_PUBLIC_STATS_URL:-${NEXUS_PUBLIC_URL%/}/api/stats}"
export NEXUS_PUBLIC_WATCHDOG_RELAY_SERVICE_NAME="${NEXUS_PUBLIC_WATCHDOG_RELAY_SERVICE_NAME:-nexus-relay}"
export NEXUS_PUBLIC_WATCHDOG_TUNNEL_SERVICE_NAME="${NEXUS_PUBLIC_WATCHDOG_TUNNEL_SERVICE_NAME:-nexus-cloudflared}"
export NEXUS_PUBLIC_WATCHDOG_EDGE_REBOOT_ENABLED="${NEXUS_PUBLIC_WATCHDOG_EDGE_REBOOT_ENABLED:-true}"
export NEXUS_PUBLIC_WATCHDOG_EDGE_REBOOT_AFTER_FAILURES="${NEXUS_PUBLIC_WATCHDOG_EDGE_REBOOT_AFTER_FAILURES:-2}"
export NEXUS_PUBLIC_WATCHDOG_EDGE_RECHECK_SECONDS="${NEXUS_PUBLIC_WATCHDOG_EDGE_RECHECK_SECONDS:-15}"
export NEXUS_PUBLIC_WATCHDOG_RECOVERY_PROXY_ENABLED="${NEXUS_PUBLIC_WATCHDOG_RECOVERY_PROXY_ENABLED:-true}"
export NEXUS_PUBLIC_WATCHDOG_RECOVERY_PROXY_SERVICE_NAME="${NEXUS_PUBLIC_WATCHDOG_RECOVERY_PROXY_SERVICE_NAME:-nexus-http-recovery-proxy}"
export NEXUS_PUBLIC_WATCHDOG_RECOVERY_PROXY_ORIGIN_URL="${NEXUS_PUBLIC_WATCHDOG_RECOVERY_PROXY_ORIGIN_URL:-http://127.0.0.1:8081}"
export NEXUS_PUBLIC_WATCHDOG_NORMAL_ORIGIN_URL="${NEXUS_PUBLIC_WATCHDOG_NORMAL_ORIGIN_URL:-${NEXUS_CLOUDFLARE_TUNNEL_ORIGIN_URL}}"
export NEXUS_PUBLIC_WATCHDOG_CLOUDFLARED_ENV_PATH="${NEXUS_PUBLIC_WATCHDOG_CLOUDFLARED_ENV_PATH:-${NEXUS_RUNTIME_CONFIG_DIR}/nexus-cloudflared.env}"
export NEXUS_DEPLOY_POST_RESTART_SMOKE_ENABLED="${NEXUS_DEPLOY_POST_RESTART_SMOKE_ENABLED:-true}"
export NEXUS_DEPLOY_POST_RESTART_SMOKE_TIMEOUT_SECONDS="${NEXUS_DEPLOY_POST_RESTART_SMOKE_TIMEOUT_SECONDS:-360}"
export NEXUS_DEPLOY_POST_RESTART_WARMUP_GRACE_SECONDS="${NEXUS_DEPLOY_POST_RESTART_WARMUP_GRACE_SECONDS:-${NEXUS_TREASURY_WATCHDOG_STARTUP_GRACE_SECONDS}}"
export NEXUS_DEPLOY_POST_RESTART_SMOKE_POLL_SECONDS="${NEXUS_DEPLOY_POST_RESTART_SMOKE_POLL_SECONDS:-10}"
export NEXUS_SKIP_POST_DEPLOY_SMOKE_CHECK="${NEXUS_SKIP_POST_DEPLOY_SMOKE_CHECK:-false}"

log() {
  printf '[nexus-deploy] %s\n' "$*" >&2
}

die() {
  printf '[nexus-deploy] ERROR: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    die "Missing required command: ${cmd}"
  fi
}

run_with_timeout() {
  local timeout_seconds="$1"
  local label="$2"
  shift 2
  python3 - "$timeout_seconds" "$label" "$@" <<'PY'
import subprocess
import sys

timeout_seconds = float(sys.argv[1])
label = sys.argv[2]
command = sys.argv[3:]
if not command:
    print(f"timeout wrapper received no command for {label}", file=sys.stderr)
    sys.exit(2)

try:
    completed = subprocess.run(command, timeout=timeout_seconds)
except subprocess.TimeoutExpired:
    print(
        f"[nexus-deploy] ERROR: timed out label={label} timeout_seconds={timeout_seconds:g}",
        file=sys.stderr,
    )
    sys.exit(124)
sys.exit(completed.returncode)
PY
}

verify_nexus_public_edge_healthy() {
  local phase="$1"
  if [[ "${VERIFY_PUBLIC_CHECKS_ENABLED}" != "true" ]]; then
    log "Skipping public edge check phase=${phase}; VERIFY_PUBLIC_CHECKS_ENABLED=${VERIFY_PUBLIC_CHECKS_ENABLED}"
    return 0
  fi

  require_cmd curl

  local attempts delay attempt body_path http_code body last_http_code last_body
  attempts="${NEXUS_BINARY_RELEASE_PUBLIC_PROBE_ATTEMPTS}"
  delay="${NEXUS_BINARY_RELEASE_PUBLIC_PROBE_RETRY_DELAY_SECONDS}"
  last_http_code="000"
  last_body=""

  for ((attempt = 1; attempt <= attempts; attempt++)); do
    body_path="$(mktemp)"
    http_code="$(
      curl -sS \
        --max-time "${NEXUS_BINARY_RELEASE_PUBLIC_PROBE_TIMEOUT_SECONDS}" \
        -o "$body_path" \
        -w '%{http_code}' \
        "$NEXUS_PUBLIC_HEALTH_URL" || true
    )"
    body="$(cat "$body_path" 2>/dev/null || true)"
    rm -f "$body_path"
    last_http_code="$http_code"
    last_body="$body"

    if [[ "$http_code" == "200" ]]; then
      log "Public edge healthy phase=${phase} url=${NEXUS_PUBLIC_HEALTH_URL} http_code=${http_code} attempt=${attempt}/${attempts}"
      return 0
    fi

    if (( attempt < attempts )); then
      log "Public edge probe retrying phase=${phase} url=${NEXUS_PUBLIC_HEALTH_URL} http_code=${http_code} attempt=${attempt}/${attempts}"
      sleep "$delay"
    fi
  done

  if [[ "$last_http_code" == "530" || "$last_body" == *"error code: 1033"* || "$last_body" == *"Error 1033"* || "$last_http_code" == "000" ]]; then
    die "Public edge unhealthy phase=${phase} url=${NEXUS_PUBLIC_HEALTH_URL} http_code=${last_http_code} attempts=${attempts}; restore Nexus/cloudflared before continuing"
  fi

  die "Public edge check failed phase=${phase} url=${NEXUS_PUBLIC_HEALTH_URL} http_code=${last_http_code} attempts=${attempts}"
}

timestamp_unix_ms() {
  python3 - <<'PY'
import time
print(int(time.time() * 1000))
PY
}

ensure_gcloud_context() {
  require_cmd gcloud

  local active_project active_account
  active_project="$(gcloud config get-value project 2>/dev/null || true)"
  active_account="$(gcloud config get-value account 2>/dev/null || true)"

  [[ -n "$active_account" ]] || die "No active gcloud account. Run: gcloud auth login"

  if [[ "$active_project" != "$GCP_PROJECT" ]]; then
    log "Switching gcloud project from '${active_project}' to '${GCP_PROJECT}'"
    gcloud config set project "$GCP_PROJECT" >/dev/null
  fi

  gcloud config set compute/region "$GCP_REGION" >/dev/null
  gcloud config set compute/zone "$GCP_ZONE" >/dev/null
}

ensure_services() {
  if [[ "${NEXUS_SKIP_ENABLE_SERVICES:-false}" == "true" ]]; then
    log "Skipping gcloud services enable because NEXUS_SKIP_ENABLE_SERVICES=true"
    return 0
  fi

  gcloud services enable \
    compute.googleapis.com \
    artifactregistry.googleapis.com \
    cloudbuild.googleapis.com \
    iam.googleapis.com \
    run.googleapis.com \
    cloudscheduler.googleapis.com \
    secretmanager.googleapis.com \
    logging.googleapis.com \
    monitoring.googleapis.com \
    --project "$GCP_PROJECT" >/dev/null
}

instance_exists() {
  gcloud compute instances describe "$1" --project "$GCP_PROJECT" --zone "$GCP_ZONE" >/dev/null 2>&1
}

disk_exists() {
  gcloud compute disks describe "$1" --project "$GCP_PROJECT" --zone "$GCP_ZONE" >/dev/null 2>&1
}

firewall_rule_exists() {
  gcloud compute firewall-rules describe "$1" --project "$GCP_PROJECT" >/dev/null 2>&1
}
