#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

export GCP_PROJECT="${GCP_PROJECT:-openagentsgemini}"
export GCP_REGION="${GCP_REGION:-us-central1}"
export GCP_ZONE="${GCP_ZONE:-us-central1-a}"

export OA_VPC="${OA_VPC:-oa-lightning}"
export OA_SUBNET="${OA_SUBNET:-oa-lightning-us-central1}"

export NEXUS_VM="${NEXUS_VM:-nexus-mainnet-1}"
export NEXUS_MACHINE_TYPE="${NEXUS_MACHINE_TYPE:-e2-standard-4}"
export NEXUS_SERVICE_ACCOUNT_NAME="${NEXUS_SERVICE_ACCOUNT_NAME:-nexus-mainnet}"
export NEXUS_SERVICE_ACCOUNT_EMAIL="${NEXUS_SERVICE_ACCOUNT_EMAIL:-${NEXUS_SERVICE_ACCOUNT_NAME}@${GCP_PROJECT}.iam.gserviceaccount.com}"
export NEXUS_TAG="${NEXUS_TAG:-nexus-host}"
export NEXUS_IAP_SSH_FIREWALL_RULE="${NEXUS_IAP_SSH_FIREWALL_RULE:-oa-allow-${NEXUS_TAG}-iap-ssh}"

export NEXUS_BUILDER_VM="${NEXUS_BUILDER_VM:-nexus-builder-1}"
export NEXUS_BUILDER_MACHINE_TYPE="${NEXUS_BUILDER_MACHINE_TYPE:-c3d-standard-8}"
export NEXUS_BUILDER_SERVICE_ACCOUNT_EMAIL="${NEXUS_BUILDER_SERVICE_ACCOUNT_EMAIL:-${NEXUS_SERVICE_ACCOUNT_EMAIL}}"
export NEXUS_BUILDER_TAG="${NEXUS_BUILDER_TAG:-nexus-builder}"
export NEXUS_BUILDER_IAP_SSH_FIREWALL_RULE="${NEXUS_BUILDER_IAP_SSH_FIREWALL_RULE:-oa-allow-${NEXUS_BUILDER_TAG}-iap-ssh}"
export NEXUS_BUILDER_BOOT_DISK_SIZE_GB="${NEXUS_BUILDER_BOOT_DISK_SIZE_GB:-100}"
export NEXUS_BUILDER_BOOT_DISK_TYPE="${NEXUS_BUILDER_BOOT_DISK_TYPE:-pd-ssd}"
export NEXUS_BUILDER_CACHE_DISK="${NEXUS_BUILDER_CACHE_DISK:-nexus-builder-cache-1}"
export NEXUS_BUILDER_CACHE_DISK_DEVICE_NAME="${NEXUS_BUILDER_CACHE_DISK_DEVICE_NAME:-nexus-builder-cache}"
export NEXUS_BUILDER_CACHE_DISK_SIZE_GB="${NEXUS_BUILDER_CACHE_DISK_SIZE_GB:-200}"
export NEXUS_BUILDER_CACHE_DISK_TYPE="${NEXUS_BUILDER_CACHE_DISK_TYPE:-pd-ssd}"
export NEXUS_BUILDER_IMAGE_FAMILY="${NEXUS_BUILDER_IMAGE_FAMILY:-ubuntu-2204-lts}"
export NEXUS_BUILDER_IMAGE_PROJECT="${NEXUS_BUILDER_IMAGE_PROJECT:-ubuntu-os-cloud}"
export NEXUS_BUILDER_CACHE_MOUNT_POINT="${NEXUS_BUILDER_CACHE_MOUNT_POINT:-/mnt/disks/nexus-builder-cache}"
export NEXUS_BUILDER_USER="${NEXUS_BUILDER_USER:-nexus-builder}"
export NEXUS_BUILDER_RUST_TOOLCHAIN="${NEXUS_BUILDER_RUST_TOOLCHAIN:-1.88.0}"
export NEXUS_BUILDER_SCCACHE_VERSION="${NEXUS_BUILDER_SCCACHE_VERSION:-0.8.2}"
export NEXUS_BUILDER_BUILD_PROFILE="${NEXUS_BUILDER_BUILD_PROFILE:-fast-release}"

export NEXUS_RELEASE_ROOT="${NEXUS_RELEASE_ROOT:-/opt/nexus-relay}"
export NEXUS_RELEASES_DIR="${NEXUS_RELEASES_DIR:-${NEXUS_RELEASE_ROOT}/releases}"
export NEXUS_CURRENT_LINK="${NEXUS_CURRENT_LINK:-${NEXUS_RELEASE_ROOT}/current}"
export NEXUS_PREVIOUS_LINK="${NEXUS_PREVIOUS_LINK:-${NEXUS_RELEASE_ROOT}/previous}"
export NEXUS_SHARED_DIR="${NEXUS_SHARED_DIR:-${NEXUS_RELEASE_ROOT}/shared}"
export NEXUS_SERVICE_USER="${NEXUS_SERVICE_USER:-nexus}"
export NEXUS_SERVICE_GROUP="${NEXUS_SERVICE_GROUP:-${NEXUS_SERVICE_USER}}"
export NEXUS_SERVICE_UID="${NEXUS_SERVICE_UID:-60000}"
export NEXUS_RUNTIME_CONFIG_DIR="${NEXUS_RUNTIME_CONFIG_DIR:-/etc/nexus-relay}"
export NEXUS_RUNTIME_ENV_PATH="${NEXUS_RUNTIME_ENV_PATH:-${NEXUS_RUNTIME_CONFIG_DIR}/nexus-relay.env}"
export NEXUS_UPSTREAM_CONFIG_PATH="${NEXUS_UPSTREAM_CONFIG_PATH:-${NEXUS_RUNTIME_CONFIG_DIR}/upstream-config.toml}"
export NEXUS_SYSTEMD_UNIT_PATH="${NEXUS_SYSTEMD_UNIT_PATH:-/etc/systemd/system/nexus-relay.service}"
export NEXUS_IMAGE_UNIT_BACKUP_PATH="${NEXUS_IMAGE_UNIT_BACKUP_PATH:-${NEXUS_SYSTEMD_UNIT_PATH}.image-backup}"
export VERIFY_PUBLIC_CHECKS_ENABLED="${VERIFY_PUBLIC_CHECKS_ENABLED:-true}"

export NEXUS_DATA_DISK="${NEXUS_DATA_DISK:-nexus-relay-data-mainnet}"
export NEXUS_DATA_DISK_DEVICE_NAME="${NEXUS_DATA_DISK_DEVICE_NAME:-nexus-relay-data}"
export NEXUS_DATA_DISK_SIZE_GB="${NEXUS_DATA_DISK_SIZE_GB:-200}"
export NEXUS_DATA_DISK_TYPE="${NEXUS_DATA_DISK_TYPE:-pd-ssd}"

export NEXUS_ARTIFACT_REPO="${NEXUS_ARTIFACT_REPO:-openagents-nexus}"
export NEXUS_IMAGE_NAME="${NEXUS_IMAGE_NAME:-nexus-relay}"
export NEXUS_IMAGE_TAG="${NEXUS_IMAGE_TAG:-latest}"
export NEXUS_IMAGE="${NEXUS_IMAGE:-${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${NEXUS_ARTIFACT_REPO}/${NEXUS_IMAGE_NAME}:${NEXUS_IMAGE_TAG}}"
export NEXUS_BUILD_UPDATE_LATEST_TAG="${NEXUS_BUILD_UPDATE_LATEST_TAG:-true}"
export NEXUS_BUILD_PROFILE="${NEXUS_BUILD_PROFILE:-fast-release}"
export NEXUS_BUILD_TIMEOUT="${NEXUS_BUILD_TIMEOUT:-7200s}"
export NEXUS_BUILD_MACHINE_TYPE="${NEXUS_BUILD_MACHINE_TYPE:-e2-highcpu-32}"
export NEXUS_BUILD_DISK_SIZE_GB="${NEXUS_BUILD_DISK_SIZE_GB:-200}"
export NEXUS_BUILD_CACHE_IMAGE="${NEXUS_BUILD_CACHE_IMAGE:-${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${NEXUS_ARTIFACT_REPO}/${NEXUS_IMAGE_NAME}:buildcache-${NEXUS_BUILD_PROFILE}}"
export NEXUS_BUILD_SCCACHE_ENABLED="${NEXUS_BUILD_SCCACHE_ENABLED:-false}"
export NEXUS_BUILD_SCCACHE_BUCKET="${NEXUS_BUILD_SCCACHE_BUCKET:-${GCP_PROJECT}-nexus-build-cache}"
export NEXUS_BUILD_SCCACHE_KEY_PREFIX="${NEXUS_BUILD_SCCACHE_KEY_PREFIX:-nexus-relay/${NEXUS_BUILD_PROFILE}}"

export NEXUS_PUBLIC_HOST="${NEXUS_PUBLIC_HOST:-nexus.openagents.com}"
export NEXUS_PUBLIC_URL="${NEXUS_PUBLIC_URL:-https://${NEXUS_PUBLIC_HOST}/}"
export NEXUS_PUBLIC_WS_URL="${NEXUS_PUBLIC_WS_URL:-wss://${NEXUS_PUBLIC_HOST}/}"
export NEXUS_CLOUDFLARE_TUNNEL_NAME="${NEXUS_CLOUDFLARE_TUNNEL_NAME:-nexus-mainnet}"
export NEXUS_CLOUDFLARE_TUNNEL_IMAGE="${NEXUS_CLOUDFLARE_TUNNEL_IMAGE:-cloudflare/cloudflared:2025.10.0}"
export NEXUS_CLOUDFLARE_TUNNEL_ORIGIN_URL="${NEXUS_CLOUDFLARE_TUNNEL_ORIGIN_URL:-http://127.0.0.1:8080}"
export NEXUS_CLOUDFLARE_TUNNEL_TOKEN="${NEXUS_CLOUDFLARE_TUNNEL_TOKEN:-}"
export NEXUS_CLOUDFLARE_SKIP_DNS_SETUP="${NEXUS_CLOUDFLARE_SKIP_DNS_SETUP:-false}"

export NEXUS_LISTEN_ADDR="${NEXUS_LISTEN_ADDR:-0.0.0.0:8080}"
export NEXUS_UPSTREAM_LISTEN_ADDR="${NEXUS_UPSTREAM_LISTEN_ADDR:-127.0.0.1:42111}"
export NEXUS_DATA_DIR="${NEXUS_DATA_DIR:-/var/lib/nexus-relay}"
export NEXUS_RECEIPT_LOG_PATH="${NEXUS_RECEIPT_LOG_PATH:-${NEXUS_DATA_DIR}/nexus-control-receipts.jsonl}"
export NEXUS_CONTROL_TREASURY_ENABLED="${NEXUS_CONTROL_TREASURY_ENABLED:-false}"
export NEXUS_CONTROL_TREASURY_PAYOUT_SATS_PER_WINDOW="${NEXUS_CONTROL_TREASURY_PAYOUT_SATS_PER_WINDOW:-0}"
export NEXUS_CONTROL_TREASURY_PAYOUT_INTERVAL_SECONDS="${NEXUS_CONTROL_TREASURY_PAYOUT_INTERVAL_SECONDS:-3600}"
export NEXUS_CONTROL_TREASURY_REQUIRE_SELLABLE="${NEXUS_CONTROL_TREASURY_REQUIRE_SELLABLE:-true}"
export NEXUS_CONTROL_TREASURY_DAILY_BUDGET_CAP_SATS="${NEXUS_CONTROL_TREASURY_DAILY_BUDGET_CAP_SATS:-21000}"
export NEXUS_CONTROL_TREASURY_RECONCILIATION_HORIZON_SECONDS="${NEXUS_CONTROL_TREASURY_RECONCILIATION_HORIZON_SECONDS:-86400}"
export NEXUS_CONTROL_TREASURY_STATE_PATH="${NEXUS_CONTROL_TREASURY_STATE_PATH:-${NEXUS_DATA_DIR}/treasury/treasury-state.json}"
export NEXUS_CONTROL_TREASURY_WALLET_MNEMONIC_PATH="${NEXUS_CONTROL_TREASURY_WALLET_MNEMONIC_PATH:-${NEXUS_DATA_DIR}/treasury/treasury.mnemonic}"
export NEXUS_CONTROL_TREASURY_WALLET_STORAGE_DIR="${NEXUS_CONTROL_TREASURY_WALLET_STORAGE_DIR:-${NEXUS_DATA_DIR}/treasury/wallet}"
export NEXUS_CONTROL_TREASURY_WALLET_NETWORK="${NEXUS_CONTROL_TREASURY_WALLET_NETWORK:-mainnet}"
export NEXUS_CONTROL_TREASURY_WALLET_REAL_TIME_SYNC_ENABLED="${NEXUS_CONTROL_TREASURY_WALLET_REAL_TIME_SYNC_ENABLED:-false}"
export NEXUS_CONTROL_TREASURY_WALLET_STATUS_REFRESH_SECONDS="${NEXUS_CONTROL_TREASURY_WALLET_STATUS_REFRESH_SECONDS:-3}"
export NEXUS_CONTROL_TREASURY_MAX_CONCURRENT_SENDS="${NEXUS_CONTROL_TREASURY_MAX_CONCURRENT_SENDS:-16}"
export TOKIO_WORKER_THREADS="${TOKIO_WORKER_THREADS:-16}"
export NEXUS_ALLOW_ZERO_TREASURY_IN_PRODUCTION="${NEXUS_ALLOW_ZERO_TREASURY_IN_PRODUCTION:-false}"
export NEXUS_TREASURY_WATCHDOG_ENABLED="${NEXUS_TREASURY_WATCHDOG_ENABLED:-true}"
export NEXUS_TREASURY_WATCHDOG_INTERVAL_SECONDS="${NEXUS_TREASURY_WATCHDOG_INTERVAL_SECONDS:-300}"
export NEXUS_TREASURY_WATCHDOG_MAX_IDLE_SECONDS="${NEXUS_TREASURY_WATCHDOG_MAX_IDLE_SECONDS:-300}"
export NEXUS_TREASURY_WATCHDOG_MAX_CONFIRM_LAG_SECONDS="${NEXUS_TREASURY_WATCHDOG_MAX_CONFIRM_LAG_SECONDS:-300}"
export NEXUS_TREASURY_WATCHDOG_MAX_RESTARTS_PER_HOUR="${NEXUS_TREASURY_WATCHDOG_MAX_RESTARTS_PER_HOUR:-12}"
export NEXUS_TREASURY_WATCHDOG_STARTUP_GRACE_SECONDS="${NEXUS_TREASURY_WATCHDOG_STARTUP_GRACE_SECONDS:-180}"
export NEXUS_TREASURY_WATCHDOG_LOCAL_STATUS_URL="${NEXUS_TREASURY_WATCHDOG_LOCAL_STATUS_URL:-http://127.0.0.1:8080/v1/treasury/status}"
export NEXUS_TREASURY_WATCHDOG_SERVICE_NAME="${NEXUS_TREASURY_WATCHDOG_SERVICE_NAME:-nexus-relay}"
export NEXUS_TREASURY_WATCHDOG_RESTART_MODE="${NEXUS_TREASURY_WATCHDOG_RESTART_MODE:-service_inactive_only}"
export NEXUS_PUBLIC_WATCHDOG_ENABLED="${NEXUS_PUBLIC_WATCHDOG_ENABLED:-true}"
export NEXUS_PUBLIC_WATCHDOG_INTERVAL_SECONDS="${NEXUS_PUBLIC_WATCHDOG_INTERVAL_SECONDS:-60}"
export NEXUS_PUBLIC_WATCHDOG_STARTUP_GRACE_SECONDS="${NEXUS_PUBLIC_WATCHDOG_STARTUP_GRACE_SECONDS:-180}"
export NEXUS_PUBLIC_WATCHDOG_MAX_RESTARTS_PER_HOUR="${NEXUS_PUBLIC_WATCHDOG_MAX_RESTARTS_PER_HOUR:-12}"
export NEXUS_PUBLIC_WATCHDOG_LOCAL_HEALTH_URL="${NEXUS_PUBLIC_WATCHDOG_LOCAL_HEALTH_URL:-http://127.0.0.1:8080/healthz}"
export NEXUS_PUBLIC_WATCHDOG_PUBLIC_STATS_URL="${NEXUS_PUBLIC_WATCHDOG_PUBLIC_STATS_URL:-${NEXUS_PUBLIC_URL%/}/api/stats}"
export NEXUS_PUBLIC_WATCHDOG_RELAY_SERVICE_NAME="${NEXUS_PUBLIC_WATCHDOG_RELAY_SERVICE_NAME:-nexus-relay}"
export NEXUS_PUBLIC_WATCHDOG_TUNNEL_SERVICE_NAME="${NEXUS_PUBLIC_WATCHDOG_TUNNEL_SERVICE_NAME:-nexus-cloudflared}"
export NEXUS_DEPLOY_POST_RESTART_SMOKE_ENABLED="${NEXUS_DEPLOY_POST_RESTART_SMOKE_ENABLED:-true}"
export NEXUS_DEPLOY_POST_RESTART_SMOKE_TIMEOUT_SECONDS="${NEXUS_DEPLOY_POST_RESTART_SMOKE_TIMEOUT_SECONDS:-360}"
export NEXUS_DEPLOY_POST_RESTART_WARMUP_GRACE_SECONDS="${NEXUS_DEPLOY_POST_RESTART_WARMUP_GRACE_SECONDS:-${NEXUS_TREASURY_WATCHDOG_STARTUP_GRACE_SECONDS}}"
export NEXUS_DEPLOY_POST_RESTART_SMOKE_POLL_SECONDS="${NEXUS_DEPLOY_POST_RESTART_SMOKE_POLL_SECONDS:-10}"
export NEXUS_SKIP_POST_DEPLOY_SMOKE_CHECK="${NEXUS_SKIP_POST_DEPLOY_SMOKE_CHECK:-false}"

log() {
  printf '[nexus-deploy] %s\n' "$*" >&2
}

die() {
  printf '[nexus-deploy] ERROR: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    die "Missing required command: ${cmd}"
  fi
}

timestamp_unix_ms() {
  python3 - <<'PY'
import time
print(int(time.time() * 1000))
PY
}

ensure_gcloud_context() {
  require_cmd gcloud

  local active_project active_account
  active_project="$(gcloud config get-value project 2>/dev/null || true)"
  active_account="$(gcloud config get-value account 2>/dev/null || true)"

  [[ -n "$active_account" ]] || die "No active gcloud account. Run: gcloud auth login"

  if [[ "$active_project" != "$GCP_PROJECT" ]]; then
    log "Switching gcloud project from '${active_project}' to '${GCP_PROJECT}'"
    gcloud config set project "$GCP_PROJECT" >/dev/null
  fi

  gcloud config set compute/region "$GCP_REGION" >/dev/null
  gcloud config set compute/zone "$GCP_ZONE" >/dev/null
}

ensure_services() {
  gcloud services enable \
    compute.googleapis.com \
    artifactregistry.googleapis.com \
    cloudbuild.googleapis.com \
    logging.googleapis.com \
    monitoring.googleapis.com \
    --project "$GCP_PROJECT" >/dev/null
}

instance_exists() {
  gcloud compute instances describe "$1" --project "$GCP_PROJECT" --zone "$GCP_ZONE" >/dev/null 2>&1
}

disk_exists() {
  gcloud compute disks describe "$1" --project "$GCP_PROJECT" --zone "$GCP_ZONE" >/dev/null 2>&1
}

firewall_rule_exists() {
  gcloud compute firewall-rules describe "$1" --project "$GCP_PROJECT" >/dev/null 2>&1
}
