// GENERATED by scripts/changelog.ts — DO NOT EDIT BY HAND.
// Source of truth: the dated release files in docs/changelog/.
// Regenerate with: pnpm changelog sync

export type ChangelogHumanBlock =
  | Readonly<{ kind: "paragraph"; text: string }>
  | Readonly<{ kind: "bullets"; items: ReadonlyArray<string> }>;

export type ChangelogRelease = Readonly<{
  version: string;
  channel: string;
  date: string;
  title: string;
  blocks: ReadonlyArray<ChangelogHumanBlock>;
  agentChangelogUrl: string;
}>;

/** Newest release first. */
export const CHANGELOG_RELEASES: ReadonlyArray<ChangelogRelease> =
  [
    {
      "agentChangelogUrl": "https://github.com/OpenAgentsInc/openagents/blob/main/docs/changelog/2026-07-16-desktop-0.1.0-rc.13.md",
      "blocks": [
        {
          "kind": "paragraph",
          "text": "OpenAgents Desktop is available as a release candidate for Apple silicon Macs. This first changelog entry covers what the current candidate, version 0.1.0-rc.13, gives you today."
        },
        {
          "items": [
            "A local-first desktop workroom around your existing Codex session. Your ordinary Codex login stays in charge, and OpenAgents Desktop does not require a separate account.",
            "Your sessions survive. Conversations keep the same identity across navigation, reloads, and app restarts, and interrupted work reconciles into an honest state instead of silently rerunning.",
            "The whole turn stays visible while work happens: streaming, waiting, blocked, complete, and interrupted states, along with the commands, file reads, and results that produced them.",
            "Repository review is read-only by design. You can inspect status and exact diffs for the active work without the review surface changing your files.",
            "The app is signed and notarized for macOS and updates itself over the release-candidate channel. Every update is verified against the pinned OpenAgents release key before it installs, and versions only move forward.",
            "This is a release candidate, not the stable release. It supports Apple silicon Macs only; Intel Macs, Windows, and Linux are not supported yet."
          ],
          "kind": "bullets"
        }
      ],
      "channel": "rc",
      "date": "2026-07-16",
      "title": "OpenAgents Desktop 0.1.0-rc.13 — 2026-07-16",
      "version": "0.1.0-rc.13"
    }
  ];
