// GENERATED by scripts/changelog.ts — DO NOT EDIT BY HAND.
// Source of truth: the dated release files in docs/changelog/.
// Regenerate with: pnpm changelog sync

export type ChangelogHumanBlock =
  | Readonly<{ kind: "paragraph"; text: string }>
  | Readonly<{ kind: "bullets"; items: ReadonlyArray<string> }>;

export type ChangelogRelease = Readonly<{
  version: string;
  channel: string;
  date: string;
  title: string;
  blocks: ReadonlyArray<ChangelogHumanBlock>;
  agentChangelogUrl: string;
  attribution: Readonly<{
    triggerKind: string;
    triggeredBy: string;
    releaseActor: string;
    authorityRef: string;
    releaseUrl: string;
    sourceFeedback: string;
  }>;
}>;

/** Newest release first. */
export const CHANGELOG_RELEASES: ReadonlyArray<ChangelogRelease> =
  [
    {
      "agentChangelogUrl": "https://github.com/OpenAgentsInc/openagents/blob/main/docs/changelog/2026-07-18-desktop-0.1.0-rc.21.md",
      "blocks": [
        {
          "items": [
            "Full Auto now starts from one mission prompt. Advanced provider, model, workspace, budget, and completion controls stay available without blocking the quick path.",
            "You can run several independent Full Auto missions at once. Each mission gets its own conversation, lifecycle, progress row, and stop control, while duplicate work on the same conversation remains fenced.",
            "Codex and Claude handoffs retain the mission, selected model, provider state, and reviewed outcome across navigation and restart. Terminal Claude results now settle cleanly instead of leaving a hidden process or misleading running state.",
            "Pause waits for the active provider turn to drain before reporting Paused, and provider failures remain visible and typed for recovery instead of being silently converted into success.",
            "Isolated acceptance runs no longer inspect the owner's real Codex or Claude history. Ordinary user history behavior is unchanged.",
            "The release page and changelog now show what triggered an update, who published it, the source feedback, and the exact delegated authority. GitHub candidate assets are immutable; a correction always receives a newer RC.",
            "This remains a release candidate. macOS builds are signed and notarized; Linux and experimental Windows availability is described by the candidate's published limitations and does not create a signed-feed support claim."
          ],
          "kind": "bullets"
        }
      ],
      "channel": "rc",
      "date": "2026-07-18",
      "title": "OpenAgents Desktop 0.1.0-rc.21 — 2026-07-18",
      "version": "0.1.0-rc.21",
      "attribution": {
        "authorityRef": "AUTHORITY.md revision 2; program.full_auto_release; grant.autonomous_rc_release_and_communication",
        "releaseActor": "OpenAgents release operator",
        "releaseUrl": "https://github.com/OpenAgentsInc/openagents/releases/tag/openagents-desktop-v0.1.0-rc.21",
        "sourceFeedback": "https://github.com/OpenAgentsInc/openagents/issues/8995",
        "triggeredBy": "OpenAgents owner request for autonomous Full Auto release delivery",
        "triggerKind": "owner_direction"
      }
    },
    {
      "agentChangelogUrl": "https://github.com/OpenAgentsInc/openagents/blob/main/docs/changelog/2026-07-18-desktop-0.1.0-rc.20.md",
      "blocks": [
        {
          "items": [
            "The model selector now uses the visible catalog from the user's installed Codex app-server, including each model's supported reasoning choices.",
            "Model and reasoning controls became normal select menus instead of click-to-cycle controls.",
            "Compatibility diagnostics and unchanged specification receipts stay out of the conversation, while genuinely changed specification information remains visible.",
            "Existing Codex conversations resume across the newly observed pagination fields without accepting unrelated protocol drift.",
            "The release retained the installed-Codex architecture from the prior corrective candidate and shipped the five-platform package set."
          ],
          "kind": "bullets"
        }
      ],
      "channel": "rc",
      "date": "2026-07-18",
      "title": "OpenAgents Desktop 0.1.0-rc.20 — 2026-07-18",
      "version": "0.1.0-rc.20",
      "attribution": {
        "authorityRef": "owner release direction recorded on #8995 before AUTHORITY.md revision 2",
        "releaseActor": "OpenAgents release agent (historical)",
        "releaseUrl": "https://github.com/OpenAgentsInc/openagents/releases/tag/openagents-desktop-v0.1.0-rc.20",
        "sourceFeedback": "https://github.com/OpenAgentsInc/openagents/issues/8995",
        "triggeredBy": "#8995 owner acceptance and follow-up testing",
        "triggerKind": "tester_feedback"
      }
    },
    {
      "agentChangelogUrl": "https://github.com/OpenAgentsInc/openagents/blob/main/docs/changelog/2026-07-18-desktop-0.1.0-rc.19.md",
      "blocks": [
        {
          "items": [
            "OpenAgents stopped packaging, copying, or re-signing a second Codex executable. The Desktop app now discovers and uses the compatible Codex installation already owned and authenticated by the user.",
            "Missing or incompatible Codex installations became an honest prerequisite message instead of a broken repair path.",
            "The corrected packages shipped for macOS, Linux, and experimental Windows x64, and every package was checked to ensure it contained no bundled Codex runtime.",
            "This architecture removed the signed-app runtime and Keychain failure reported during the previous candidate retest."
          ],
          "kind": "bullets"
        }
      ],
      "channel": "rc",
      "date": "2026-07-18",
      "title": "OpenAgents Desktop 0.1.0-rc.19 — 2026-07-18",
      "version": "0.1.0-rc.19",
      "attribution": {
        "authorityRef": "owner architecture direction recorded on #8995 before AUTHORITY.md revision 2",
        "releaseActor": "OpenAgents release agent (historical)",
        "releaseUrl": "https://github.com/OpenAgentsInc/openagents/releases/tag/openagents-desktop-v0.1.0-rc.19",
        "sourceFeedback": "https://github.com/OpenAgentsInc/openagents/issues/8995",
        "triggeredBy": "signed-candidate feedback from @lathe-agent-oa",
        "triggerKind": "release_incident"
      }
    },
    {
      "agentChangelogUrl": "https://github.com/OpenAgentsInc/openagents/blob/main/docs/changelog/2026-07-17-desktop-0.1.0-rc.18.md",
      "blocks": [
        {
          "items": [
            "The candidate addressed the first external Desktop test report: default Codex behavior, account status, navigation, and other high-friction development-mode problems were repaired and packaged for retest.",
            "Full Auto and the local coding workroom were included in a signed macOS candidate alongside the Linux and experimental Windows packages.",
            "The signed retest then found a deeper blocker: packaged Codex chat could not start reliably. That feedback led directly to the corrective releases that followed."
          ],
          "kind": "bullets"
        }
      ],
      "channel": "rc",
      "date": "2026-07-17",
      "title": "OpenAgents Desktop 0.1.0-rc.18 — 2026-07-17",
      "version": "0.1.0-rc.18",
      "attribution": {
        "authorityRef": "owner-directed tester follow-up before the admitted AUTHORITY.md profile",
        "releaseActor": "OpenAgents release agent (historical)",
        "releaseUrl": "https://github.com/OpenAgentsInc/openagents/releases/tag/openagents-desktop-v0.1.0-rc.18",
        "sourceFeedback": "https://github.com/OpenAgentsInc/openagents/issues/8983",
        "triggeredBy": "@lathe-agent-oa",
        "triggerKind": "tester_feedback"
      }
    },
    {
      "agentChangelogUrl": "https://github.com/OpenAgentsInc/openagents/blob/main/docs/changelog/2026-07-17-desktop-0.1.0-rc.17.md",
      "blocks": [
        {
          "items": [
            "OpenAgents Desktop became available as a hands-on release candidate for macOS, Linux, and experimental Windows x64 testing.",
            "Ordinary startup became Keychain-free. The replacement build stopped account credential custody from initializing during a normal local launch.",
            "The candidate added the local Codex workroom, durable conversations, repository context, the coding composer, local history, and an early Full Auto preview.",
            "macOS packages were signed and notarized. Linux packages were built for both supported architectures, while Windows remained an unsigned experimental portable package."
          ],
          "kind": "bullets"
        }
      ],
      "channel": "rc",
      "date": "2026-07-17",
      "title": "OpenAgents Desktop 0.1.0-rc.17 — 2026-07-17",
      "version": "0.1.0-rc.17",
      "attribution": {
        "authorityRef": "owner direction recorded on release issues before the admitted AUTHORITY.md profile",
        "releaseActor": "OpenAgents release agent (historical)",
        "releaseUrl": "https://github.com/OpenAgentsInc/openagents/releases/tag/openagents-desktop-v0.1.0-rc.17",
        "sourceFeedback": "https://github.com/OpenAgentsInc/openagents/issues/8919",
        "triggeredBy": "OpenAgents owner release direction",
        "triggerKind": "owner_direction"
      }
    },
    {
      "agentChangelogUrl": "https://github.com/OpenAgentsInc/openagents/blob/main/docs/changelog/2026-07-16-desktop-0.1.0-rc.13.md",
      "blocks": [
        {
          "kind": "paragraph",
          "text": "OpenAgents Desktop is available as a release candidate for Apple silicon Macs. This first changelog entry covers what the current candidate, version 0.1.0-rc.13, gives you today."
        },
        {
          "items": [
            "A local-first desktop workroom around your existing Codex session. Your ordinary Codex login stays in charge, and OpenAgents Desktop does not require a separate account.",
            "Your sessions survive. Conversations keep the same identity across navigation, reloads, and app restarts, and interrupted work reconciles into an honest state instead of silently rerunning.",
            "The whole turn stays visible while work happens: streaming, waiting, blocked, complete, and interrupted states, along with the commands, file reads, and results that produced them.",
            "Repository review is read-only by design. You can inspect status and exact diffs for the active work without the review surface changing your files.",
            "The app is signed and notarized for macOS and updates itself over the release-candidate channel. Every update is verified against the pinned OpenAgents release key before it installs, and versions only move forward.",
            "This is a release candidate, not the stable release. It supports Apple silicon Macs only; Intel Macs, Windows, and Linux are not supported yet."
          ],
          "kind": "bullets"
        }
      ],
      "channel": "rc",
      "date": "2026-07-16",
      "title": "OpenAgents Desktop 0.1.0-rc.13 — 2026-07-16",
      "version": "0.1.0-rc.13",
      "attribution": {
        "authorityRef": "owner-directed release before the admitted AUTHORITY.md profile",
        "releaseActor": "OpenAgents release operator (historical)",
        "releaseUrl": "https://updates.openagents.com/desktop/openagents/rc/release.json",
        "sourceFeedback": "none recorded",
        "triggeredBy": "OpenAgents owner",
        "triggerKind": "owner_direction"
      }
    }
  ];
