import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, test } from 'vitest'

import { SplashPage } from './-splash-page'

describe('Desktop splash', () => {
  test('server-renders the landing hero around the live workroom and its accessible controls', () => {
    const html = renderToStaticMarkup(<SplashPage />)

    expect(html).toContain('data-route="splash"')
    expect(html).toContain('Primary navigation')
    expect(html).toContain('Your last agent IDE.')
    expect(html).toContain('Download for Mac')
    expect(html).toContain('Or build from source')
    expect(html).toContain('Introducing OpenAgents Desktop')
    expect(html).toContain('href="/blog/introducing-openagents-desktop"')
    expect(html).toContain('OpenAgents on GitHub')
    expect(html).not.toContain('href="#product"')
    expect(html).toContain('splash-product')
    expect(html).toContain('splash-window-bar')
    expect(html).toContain('OpenAgents Desktop live product preview')
    expect(html).toContain('APPSERVER')
    expect(html).toContain('T3CODE YOINK')
    expect(html).toContain('Show the whole Codex app-server workflow')
    expect(html).toContain('data-en-react-surface="true"')
    expect(html).toContain('data-chat-composer="true"')
    expect(html).toContain('data-composer-button-kind="action"')
    expect(html).toContain('data-composer-button-kind="toggle"')
    expect(html).toContain('data-composer-button-kind="submit"')
    expect(html).toContain('data-composer-button-kind="stop"')
    expect(html).toContain('packages/ui')
    expect(html).toContain('Steer a Codex message')
    expect(html).toContain('spawnAgent · implementation swarm')
    expect(html).toContain('a11y-oracle')
    expect(html).toContain('collabAgentToolCall')
    expect(html).toContain('data-kind="commandExecution"')
    expect(html).toContain('data-kind="fileChange"')
    expect(html).toContain('data-kind="mcpToolCall"')
    expect(html).toContain('data-kind="webSearch"')
    expect(html).toContain('data-kind="imageView"')
    expect(html).toContain('data-kind="contextCompaction"')
    expect(html).toContain('Command approval')
    expect(html).toContain('Queued follow-up (#1)')
    expect(html).not.toContain('<img')
  })
})
