[package]
name = "acp-event-translator"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Translate provider event streams (Codex, Claude Code, OpenCode) into ACP SessionUpdate notifications"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
agent-client-protocol = "0.7.0"
