#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

export OPENAGENTS_HEADLESS_DATA_MARKET_RELAY_URLS="${OPENAGENTS_HEADLESS_DATA_MARKET_RELAY_URLS:-wss://relay.damus.io,wss://relay.primal.net}"
export OPENAGENTS_HEADLESS_DATA_MARKET_WAIT_TIMEOUT_MS="${OPENAGENTS_HEADLESS_DATA_MARKET_WAIT_TIMEOUT_MS:-240000}"
export OPENAGENTS_HEADLESS_DATA_MARKET_REQUEST_TIMEOUT_SECONDS="${OPENAGENTS_HEADLESS_DATA_MARKET_REQUEST_TIMEOUT_SECONDS:-300}"
export OPENAGENTS_HEADLESS_DATA_MARKET_E2E_RUN_DIR="${OPENAGENTS_HEADLESS_DATA_MARKET_E2E_RUN_DIR:-$ROOT_DIR/target/headless-data-market-public-e2e}"

exec "$ROOT_DIR/scripts/autopilot/headless-data-market-e2e.sh"
