[package]
name = "wow-import"
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
publish = false

[workspace]

[dependencies]
anyhow = "1"
benilla-formats = { git = "https://github.com/samwhosung/benilla", rev = "cf891dc3756a36dc0af4376f861ffb0c847ba5e9", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
verse-wow = { path = "../crates/verse-wow" }
png = "0.18.1"
sha2 = "0.10"
glam = "0.30.10"
