import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { isDeepStrictEqual } from "node:util";

const PACKAGE_ROOT = fileURLToPath(new URL("../", import.meta.url));
const SOURCE_PATH = new URL("../contract/SOURCE.json", import.meta.url);
const CONTRACT_PATH = new URL("../contract/immortal-contract.json", import.meta.url);
const FIXTURE_MANIFEST_PATH = new URL("../contract/immortal-fixtures.json", import.meta.url);
const OUTPUT_PATH = new URL("../src/generated.ts", import.meta.url);

const ENUM_SCHEMA_NAMES = {
  cancel_action: "CancelActionSchema",
  close_outcome: "CloseOutcomeSchema",
  descriptor_status: "DescriptorStatusSchema",
  offering_status: "OfferingStatusSchema",
  provider_status: "ProviderStatusSchema",
  public_receipt_outcome: "PublicReceiptOutcomeSchema",
  quote: "QuoteTypeSchema",
  reservation: "ReservationSchema",
  status_state: "StatusStateSchema",
};

const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
const literal = (value) => JSON.stringify(value, null, 2);

const [sourceBytes, contractBytes, fixtureManifestBytes] = await Promise.all([
  readFile(SOURCE_PATH),
  readFile(CONTRACT_PATH),
  readFile(FIXTURE_MANIFEST_PATH),
]);
const source = JSON.parse(sourceBytes.toString("utf8"));
const contract = JSON.parse(contractBytes.toString("utf8"));
const fixtureManifest = JSON.parse(fixtureManifestBytes.toString("utf8"));

if (source.schema !== "openagents.nip-mkt.contract-source.v1") {
  throw new Error("Unsupported NIP-MKT contract source record");
}
if (source.contract_sha256 !== sha256(contractBytes)) {
  throw new Error("Vendored Immortal contract does not match SOURCE.json");
}
if (source.fixture_manifest_sha256 !== sha256(fixtureManifestBytes)) {
  throw new Error("Vendored Immortal fixture manifest does not match SOURCE.json");
}
if (!isDeepStrictEqual(fixtureManifest.contract_identity, contract.identity)) {
  throw new Error("Vendored fixture manifest contract identity does not match the contract");
}

const kinds = contract.kinds.filter((definition) => definition.identifier === "NIP-MKT");
const expectedKinds = [
  [39600, "provider_profile"],
  [39601, "offering"],
  [39602, "profile_descriptor"],
  [39603, "public_market_receipt"],
  [39604, "rfq"],
  [39605, "quote"],
  [39606, "order"],
  [39607, "status"],
  [39608, "cancel"],
  [39609, "close"],
];
if (
  !isDeepStrictEqual(
    kinds.map(({ kind, name }) => [kind, name]),
    expectedKinds,
  )
) {
  throw new Error("Unsupported NIP-MKT kind allocation or name in the vendored contract");
}
const publicKinds = kinds.filter((definition) => definition.publication === "public_head");
const privateKinds = kinds.filter((definition) => definition.publication === "private_wrapped");
const tagRequirementsByKind = Object.fromEntries(
  kinds.map((definition) => [
    definition.kind,
    [
      ...(definition.publication === "private_wrapped"
        ? contract.mkt.required_tags.private_common
        : []),
      ...contract.mkt.required_tags[definition.name],
    ],
  ]),
);
const supportedTagRequirements = /^(?:[a-z_]+|[a-z_]+ [epa]|previous e when seq > 0)$/;
for (const [kind, requirements] of Object.entries(tagRequirementsByKind)) {
  for (const requirement of requirements) {
    if (!supportedTagRequirements.test(requirement)) {
      throw new Error(`Unsupported required-tag syntax for kind ${kind}: ${requirement}`);
    }
  }
}
const okReasons = Object.fromEntries(
  contract.reasons.ok.map(({ code, message }) => [code, message]),
);
const closedReasons = Object.fromEntries(
  contract.reasons.closed.map(({ code, message }) => [code, message]),
);

const lines = [
  "// Generated by scripts/generate.mjs. Do not edit by hand.",
  "",
  'import { Schema } from "effect"',
  "",
  `export const CONTRACT_SOURCE_COMMIT = ${JSON.stringify(source.commit)} as const`,
  `export const CONTRACT_SHA256 = ${JSON.stringify(sha256(contractBytes))} as const`,
  `export const FIXTURE_MANIFEST_SHA256 = ${JSON.stringify(sha256(fixtureManifestBytes))} as const`,
  `export const CONTRACT_IDENTITY = ${literal(contract.identity)} as const`,
  `export const FIXTURE_MANIFEST_IDENTITY = ${literal({
    schema: fixtureManifest.schema,
    manifest_version: fixtureManifest.manifest_version,
    algorithm: fixtureManifest.algorithm,
  })} as const`,
  "",
  `export const MKT_KIND_DEFINITIONS = ${literal(kinds)} as const`,
  `export const MKT_KINDS = ${literal(kinds.map(({ kind }) => kind))} as const`,
  `export const PUBLIC_MKT_KINDS = ${literal(publicKinds.map(({ kind }) => kind))} as const`,
  `export const PRIVATE_MKT_KINDS = ${literal(privateKinds.map(({ kind }) => kind))} as const`,
  `export const MKT_KIND_NAMES = ${literal(Object.fromEntries(kinds.map(({ kind, name }) => [kind, name])))} as const`,
  `export const GATEWAY_LIMITS = ${literal(contract.limits.gateway)} as const`,
  `export const MKT_LIMITS = ${literal(contract.limits.mkt)} as const`,
  `export const MKT_CLIENT_LIMITS = ${literal({
    discoveryContentBytes: contract.limits.mkt.discovery_content_bytes,
    receiptContentBytes: contract.limits.mkt.receipt_content_bytes,
    privateSignedRecordBytes: contract.limits.mkt.private_signed_record_bytes,
    tags: contract.limits.mkt.tags,
    counterparties: contract.limits.mkt.counterparties,
    causalOrEvidenceReferences: contract.limits.mkt.causal_or_evidence_references,
    profiles: contract.limits.mkt.profiles,
    relayOrEndpointHints: contract.limits.mkt.relay_or_endpoint_hints,
  })} as const`,
  `export const REQUIRED_TAGS = ${literal(contract.mkt.required_tags)} as const`,
  `export const MKT_TAG_REQUIREMENTS_BY_KIND = ${literal(tagRequirementsByKind)} as const`,
  `export const OPAQUE_TRANSPORT = ${literal(contract.mkt.opaque_transport)} as const`,
  `export const OK_REASONS = ${literal(okReasons)} as const`,
  `export const CLOSED_REASONS = ${literal(closedReasons)} as const`,
  `export const REASON_PREFIXES = ${literal(contract.reasons.prefixes)} as const`,
  "",
  `export const MktKindSchema = Schema.Literals(${literal(kinds.map(({ kind }) => kind))})`,
  "export type MktKind = typeof MktKindSchema.Type",
  `export const PublicMktKindSchema = Schema.Literals(${literal(publicKinds.map(({ kind }) => kind))})`,
  "export type PublicMktKind = typeof PublicMktKindSchema.Type",
  `export const PrivateMktKindSchema = Schema.Literals(${literal(privateKinds.map(({ kind }) => kind))})`,
  "export type PrivateMktKind = typeof PrivateMktKindSchema.Type",
  `export const OkReasonCodeSchema = Schema.Literals(${literal(Object.keys(okReasons))})`,
  "export type OkReasonCode = typeof OkReasonCodeSchema.Type",
  `export const ClosedReasonCodeSchema = Schema.Literals(${literal(Object.keys(closedReasons))})`,
  "export type ClosedReasonCode = typeof ClosedReasonCodeSchema.Type",
  "",
];

for (const [contractName, schemaName] of Object.entries(ENUM_SCHEMA_NAMES)) {
  lines.push(
    `export const ${schemaName} = Schema.Literals(${literal(contract.mkt.enums[contractName])})`,
  );
  lines.push(`export type ${schemaName.replace(/Schema$/, "")} = typeof ${schemaName}.Type`);
  lines.push("");
}

const hexIdentifier = contract.mkt.identifiers.private_d_and_session;
const namedIdentifier = contract.mkt.identifiers.provider_id_offering_id_profile_id;
lines.push(
  `export const HexIdentifierSchema = Schema.String.check(`,
  `  Schema.isPattern(/${hexIdentifier.pattern}/),`,
  `  Schema.isMaxLength(${hexIdentifier.maximum_bytes}),`,
  ")",
  "export type HexIdentifier = typeof HexIdentifierSchema.Type",
  "",
  `export const NamedIdentifierSchema = Schema.String.check(`,
  `  Schema.isPattern(/^${namedIdentifier.pattern.replace(/^\^/, "").replace(/\$$/, "")}$/),`,
  `  Schema.isMaxLength(${namedIdentifier.maximum_bytes}),`,
  ")",
  "export type NamedIdentifier = typeof NamedIdentifierSchema.Type",
  "",
  `export const MKT_ENVELOPE_SCHEMA = ${JSON.stringify(contract.mkt.schema)} as const`,
  "export const ProfileEnvelopeSchema = Schema.StructWithRest(",
  "  Schema.Struct({",
  "    schema: Schema.Literal(MKT_ENVELOPE_SCHEMA),",
  "    profile: NamedIdentifierSchema,",
  "    profile_version: Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(1)),",
  "    session_id: HexIdentifierSchema,",
  "  }),",
  "  [Schema.Record(Schema.String, Schema.Json)],",
  ")",
  "export type ProfileEnvelope = typeof ProfileEnvelopeSchema.Type",
  "",
  "export const NostrTagSchema = Schema.NonEmptyArray(Schema.String)",
  "export type NostrTag = typeof NostrTagSchema.Type",
  "const DecimalTimestampSchema = Schema.String.check(Schema.isPattern(/^(0|[1-9][0-9]*)$/))",
  "const PositiveDecimalSchema = Schema.String.check(Schema.isPattern(/^[1-9][0-9]*$/))",
  "const NonEmptyTagValueSchema = Schema.String.check(Schema.isMinLength(1))",
  'export const PublicIdentifierTagSchema = Schema.Tuple([Schema.Literal("d"), NamedIdentifierSchema])',
  "export const PublicReceiptIdentifierTagSchema = Schema.Tuple([",
  '  Schema.Literal("d"),',
  "  NonEmptyTagValueSchema,",
  "])",
  'export const PrivateIdentifierTagSchema = Schema.Tuple([Schema.Literal("d"), HexIdentifierSchema])',
  'export const SessionTagSchema = Schema.Tuple([Schema.Literal("session"), HexIdentifierSchema])',
  "export const ProfileTagSchema = Schema.Tuple([",
  '  Schema.Literal("profile"),',
  "  NamedIdentifierSchema,",
  "  PositiveDecimalSchema,",
  "])",
  "export const CounterpartyTagSchema = Schema.Tuple([",
  '  Schema.Literal("p"),',
  "  HexIdentifierSchema,",
  "  Schema.String,",
  '  Schema.Literals(["requester", "provider"]),',
  "])",
  "export const EventReferenceTagSchema = Schema.Tuple([",
  '  Schema.Literal("e"),',
  "  HexIdentifierSchema,",
  "  Schema.String,",
  "  Schema.Literals([",
  '    "rfq",',
  '    "quote",',
  '    "order",',
  '    "previous",',
  '    "status",',
  '    "cancel",',
  '    "close",',
  '    "evidence",',
  '    "settlement",',
  "  ]),",
  "])",
  "export const OfferingReferenceTagSchema = Schema.Tuple([",
  '  Schema.Literal("a"),',
  "  Schema.String.check(Schema.isPattern(/^39601:[0-9a-f]{64}:[a-z0-9][a-z0-9._-]*$/)),",
  "  Schema.String,",
  '  Schema.Literal("offering"),',
  "])",
  'export const AltTagSchema = Schema.Tuple([Schema.Literal("alt"), NonEmptyTagValueSchema])',
  "export const ProviderStatusTagSchema = Schema.Tuple([",
  '  Schema.Literal("status"),',
  "  ProviderStatusSchema,",
  "])",
  "export const OfferingStatusTagSchema = Schema.Tuple([",
  '  Schema.Literal("status"),',
  "  OfferingStatusSchema,",
  "])",
  "export const DescriptorStatusTagSchema = Schema.Tuple([",
  '  Schema.Literal("status"),',
  "  DescriptorStatusSchema,",
  "])",
  "export const PublishedAtTagSchema = Schema.Tuple([",
  '  Schema.Literal("published_at"),',
  "  DecimalTimestampSchema,",
  "])",
  "export const ProviderReferenceTagSchema = Schema.Tuple([",
  '  Schema.Literal("provider"),',
  "  Schema.String.check(Schema.isPattern(/^39600:[0-9a-f]{64}:[a-z0-9][a-z0-9._-]*$/)),",
  "])",
  'export const VersionTagSchema = Schema.Tuple([Schema.Literal("version"), PositiveDecimalSchema])',
  'export const DigestTagSchema = Schema.Tuple([Schema.Literal("x"), HexIdentifierSchema])',
  "export const RetrievalTagSchema = Schema.Tuple([",
  '  Schema.Literal("r"),',
  "  Schema.String.check(Schema.isPattern(/^https?:\\/\\/\\S+$/)),",
  "])",
  "export const PublicReceiptOutcomeTagSchema = Schema.Tuple([",
  '  Schema.Literal("outcome"),',
  "  PublicReceiptOutcomeSchema,",
  "])",
  'export const RoleTagSchema = Schema.Tuple([Schema.Literal("role"), NamedIdentifierSchema])',
  "export const ExpirationTagSchema = Schema.Tuple([",
  '  Schema.Literal("expiration"),',
  "  DecimalTimestampSchema,",
  "])",
  'export const QuoteTypeTagSchema = Schema.Tuple([Schema.Literal("quote"), QuoteTypeSchema])',
  "export const ReservationTagSchema = Schema.Tuple([",
  '  Schema.Literal("reservation"),',
  "  ReservationSchema,",
  "])",
  'export const SequenceTagSchema = Schema.Tuple([Schema.Literal("seq"), DecimalTimestampSchema])',
  'export const StatusStateTagSchema = Schema.Tuple([Schema.Literal("state"), StatusStateSchema])',
  "export const CancelActionTagSchema = Schema.Tuple([",
  '  Schema.Literal("action"),',
  "  CancelActionSchema,",
  "])",
  "export const CancelReasonTagSchema = Schema.Tuple([",
  '  Schema.Literal("reason"),',
  "  NonEmptyTagValueSchema,",
  "])",
  "export const CloseOutcomeTagSchema = Schema.Tuple([",
  '  Schema.Literal("outcome"),',
  "  CloseOutcomeSchema,",
  "])",
  "export const TerminalAtTagSchema = Schema.Tuple([",
  '  Schema.Literal("terminal_at"),',
  "  DecimalTimestampSchema,",
  "])",
  "const isProfileEnvelope = Schema.is(ProfileEnvelopeSchema)",
  "const isPrivateIdentifierTag = Schema.is(PrivateIdentifierTagSchema)",
  "const isSessionTag = Schema.is(SessionTagSchema)",
  "const isProfileTag = Schema.is(ProfileTagSchema)",
  "const isCounterpartyTag = Schema.is(CounterpartyTagSchema)",
  "const isEventReferenceTag = Schema.is(EventReferenceTagSchema)",
  "const isOfferingReferenceTag = Schema.is(OfferingReferenceTagSchema)",
  "const isAltTag = Schema.is(AltTagSchema)",
  "const isPublicIdentifierTag = Schema.is(PublicIdentifierTagSchema)",
  "const isProviderStatusTag = Schema.is(ProviderStatusTagSchema)",
  "const isPublishedAtTag = Schema.is(PublishedAtTagSchema)",
  "const isOfferingStatusTag = Schema.is(OfferingStatusTagSchema)",
  "const isProviderReferenceTag = Schema.is(ProviderReferenceTagSchema)",
  "const isVersionTag = Schema.is(VersionTagSchema)",
  "const isDigestTag = Schema.is(DigestTagSchema)",
  "const isRetrievalTag = Schema.is(RetrievalTagSchema)",
  "const isDescriptorStatusTag = Schema.is(DescriptorStatusTagSchema)",
  "const isPublicReceiptIdentifierTag = Schema.is(PublicReceiptIdentifierTagSchema)",
  "const isPublicReceiptOutcomeTag = Schema.is(PublicReceiptOutcomeTagSchema)",
  "const isRoleTag = Schema.is(RoleTagSchema)",
  "const isExpirationTag = Schema.is(ExpirationTagSchema)",
  "const isQuoteTypeTag = Schema.is(QuoteTypeTagSchema)",
  "const isReservationTag = Schema.is(ReservationTagSchema)",
  "const isSequenceTag = Schema.is(SequenceTagSchema)",
  "const isStatusStateTag = Schema.is(StatusStateTagSchema)",
  "const isCancelActionTag = Schema.is(CancelActionTagSchema)",
  "const isCancelReasonTag = Schema.is(CancelReasonTagSchema)",
  "const isCloseOutcomeTag = Schema.is(CloseOutcomeTagSchema)",
  "const isTerminalAtTag = Schema.is(TerminalAtTagSchema)",
  "",
  "function matchesTagRequirement(",
  "  tags: ReadonlyArray<readonly string[]>,",
  "  requirement: string,",
  "): boolean {",
  '  if (requirement === "previous e when seq > 0") {',
  '    const sequence = tags.find((tag) => tag[0] === "seq")?.[1]',
  '    return sequence === "0" || tags.some((tag) => tag[0] === "e" && tag[3] === "previous")',
  "  }",
  '  const [markerOrName, tagName] = requirement.split(" ")',
  "  return tags.some((tag) =>",
  '    tagName === "e" || tagName === "p" || tagName === "a"',
  "      ? tag[0] === tagName && tag[3] === markerOrName",
  "      : tag[0] === markerOrName,",
  "  )",
  "}",
  "",
  "function tagGrammarCheck(kind: MktKind, requirements: readonly string[]) {",
  "  return Schema.makeFilter((tags: ReadonlyArray<readonly string[]>) => {",
  "    const issues: string[] = []",
  "    const missing = requirements.filter(",
  "      (requirement) => !matchesTagRequirement(tags, requirement),",
  "    )",
  '    if (missing.length > 0) issues.push(`kind ${kind} is missing required tags: ${missing.join(", ")}`)',
  "    const named = (name: string) => tags.filter((tag) => tag[0] === name)",
  "    const marked = (name: string, marker: string) =>",
  "      tags.filter((tag) => tag[0] === name && tag[3] === marker)",
  "    const one = (label: string, candidates: ReadonlyArray<readonly string[]>, valid: (tag: unknown) => boolean) => {",
  "      if (candidates.length !== 1) issues.push(`${label} must occur exactly once`)",
  "      else if (!valid(candidates[0])) issues.push(`${label} has invalid grammar`)",
  "    }",
  '    if (tags.length > MKT_LIMITS.tags) issues.push("too many tags")',
  '    if (named("p").length > MKT_LIMITS.counterparties) issues.push("too many counterparties")',
  '    if (named("profile").length > MKT_LIMITS.profiles) issues.push("too many profiles")',
  '    if (named("e").length > MKT_LIMITS.causal_or_evidence_references) issues.push("too many references")',
  '    for (const tag of named("e")) {',
  '      if (!isEventReferenceTag(tag)) issues.push("event reference has invalid grammar")',
  "    }",
  '    for (const tag of marked("a", "offering")) {',
  '      if (!isOfferingReferenceTag(tag)) issues.push("offering reference has invalid grammar")',
  "    }",
  "    if (kind >= 39604) {",
  '      one("d", named("d"), isPrivateIdentifierTag)',
  '      one("session", named("session"), isSessionTag)',
  '      one("profile", named("profile"), isProfileTag)',
  '      one("alt", named("alt"), isAltTag)',
  '      const counterparties = named("p")',
  '      if (counterparties.length === 0) issues.push("a counterparty must occur")',
  '      else if (!counterparties.every(isCounterpartyTag)) issues.push("counterparty has invalid grammar")',
  "    }",
  "    switch (kind) {",
  "      case 39600:",
  '        one("d", named("d"), isPublicIdentifierTag)',
  '        one("status", named("status"), isProviderStatusTag)',
  '        one("published_at", named("published_at"), isPublishedAtTag)',
  '        if (!named("profile").every(isProfileTag)) issues.push("profile has invalid grammar")',
  "        break",
  "      case 39601:",
  '        one("d", named("d"), isPublicIdentifierTag)',
  '        one("profile", named("profile"), isProfileTag)',
  '        one("status", named("status"), isOfferingStatusTag)',
  '        one("provider", named("provider"), isProviderReferenceTag)',
  '        one("published_at", named("published_at"), isPublishedAtTag)',
  "        break",
  "      case 39602:",
  '        one("d", named("d"), isPublicIdentifierTag)',
  '        one("version", named("version"), isVersionTag)',
  '        one("x", named("x"), isDigestTag)',
  '        one("r", named("r"), isRetrievalTag)',
  '        one("status", named("status"), isDescriptorStatusTag)',
  "        break",
  "      case 39603:",
  '        one("d", named("d"), isPublicReceiptIdentifierTag)',
  '        one("profile", named("profile"), isProfileTag)',
  '        one("outcome", named("outcome"), isPublicReceiptOutcomeTag)',
  '        one("x", named("x"), isDigestTag)',
  '        one("role", named("role"), isRoleTag)',
  "        break",
  "      case 39604:",
  '        if (marked("p", "provider").length === 0) issues.push("provider counterparty is required")',
  '        one("offering reference", marked("a", "offering"), isOfferingReferenceTag)',
  '        one("expiration", named("expiration"), isExpirationTag)',
  "        break",
  "      case 39605:",
  '        one("rfq reference", marked("e", "rfq"), isEventReferenceTag)',
  '        one("requester counterparty", marked("p", "requester"), isCounterpartyTag)',
  '        one("expiration", named("expiration"), isExpirationTag)',
  '        one("quote", named("quote"), isQuoteTypeTag)',
  '        one("reservation", named("reservation"), isReservationTag)',
  "        break",
  "      case 39606:",
  '        one("quote reference", marked("e", "quote"), isEventReferenceTag)',
  '        one("provider counterparty", marked("p", "provider"), isCounterpartyTag)',
  "        break",
  "      case 39607: {",
  '        one("order reference", marked("e", "order"), isEventReferenceTag)',
  '        one("seq", named("seq"), isSequenceTag)',
  '        one("state", named("state"), isStatusStateTag)',
  '        const sequence = named("seq")[0]?.[1]',
  '        const previous = marked("e", "previous")',
  '        if (sequence === "0" && previous.length !== 0) issues.push("sequence zero must not have previous")',
  '        if (sequence !== undefined && sequence !== "0") one("previous reference", previous, isEventReferenceTag)',
  "        break",
  "      }",
  "      case 39608:",
  '        one("order reference", marked("e", "order"), isEventReferenceTag)',
  '        one("action", named("action"), isCancelActionTag)',
  '        one("reason", named("reason"), isCancelReasonTag)',
  "        break",
  "      case 39609:",
  '        one("order reference", marked("e", "order"), isEventReferenceTag)',
  '        one("outcome", named("outcome"), isCloseOutcomeTag)',
  '        one("terminal_at", named("terminal_at"), isTerminalAtTag)',
  "        break",
  "    }",
  "    return issues",
  "  })",
  "}",
  "",
  "function eventContentCheck(kind: MktKind) {",
  "  return Schema.makeFilter((event: { readonly tags: ReadonlyArray<readonly string[]>; readonly content: string }) => {",
  "    let content: unknown",
  "    try {",
  "      content = JSON.parse(event.content)",
  "    } catch {",
  "      return `kind ${kind} content must be valid JSON`",
  "    }",
  '    if (typeof content !== "object" || content === null || Array.isArray(content)) {',
  "      return `kind ${kind} content must be a JSON object`",
  "    }",
  "    if (kind < 39604) return undefined",
  "    if (!isProfileEnvelope(content)) {",
  "      return `kind ${kind} content must use the MKT profile envelope`",
  "    }",
  '    const profile = event.tags.find((tag) => tag[0] === "profile")',
  '    const session = event.tags.find((tag) => tag[0] === "session")',
  "    if (",
  "      profile?.[1] !== content.profile ||",
  "      profile?.[2] !== String(content.profile_version) ||",
  "      session?.[1] !== content.session_id",
  "    ) {",
  "      return `kind ${kind} content envelope must agree with profile and session tags`",
  "    }",
  "    return undefined",
  "  })",
  "}",
  "",
  "const EventSignatureSchema = Schema.String.check(Schema.isPattern(/^[0-9a-f]{128}$/))",
  "export const NostrEventSchema = Schema.Struct({",
  "  id: HexIdentifierSchema,",
  "  pubkey: HexIdentifierSchema,",
  "  created_at: Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)),",
  "  kind: Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)),",
  "  tags: Schema.Array(NostrTagSchema),",
  "  content: Schema.String,",
  "  sig: EventSignatureSchema,",
  "})",
  "export type NostrEvent = typeof NostrEventSchema.Type",
);

const eventSchemaNames = {
  provider_profile: "ProviderProfileEventSchema",
  offering: "OfferingEventSchema",
  profile_descriptor: "ProfileDescriptorEventSchema",
  public_market_receipt: "PublicMarketReceiptEventSchema",
  rfq: "RfqEventSchema",
  quote: "QuoteEventSchema",
  order: "OrderEventSchema",
  status: "StatusEventSchema",
  cancel: "CancelEventSchema",
  close: "CloseEventSchema",
};
lines.push("");
for (const definition of kinds) {
  const schemaName = eventSchemaNames[definition.name];
  if (schemaName === undefined) {
    throw new Error(`No generated event schema mapping for ${definition.name}`);
  }
  lines.push(`export const ${schemaName} = Schema.Struct({`);
  lines.push("  ...NostrEventSchema.fields,");
  lines.push(`  kind: Schema.Literal(${definition.kind}),`);
  lines.push(
    `  tags: Schema.Array(NostrTagSchema).check(tagGrammarCheck(${definition.kind}, MKT_TAG_REQUIREMENTS_BY_KIND[${definition.kind}])),`,
  );
  lines.push(`}).check(eventContentCheck(${definition.kind}))`);
  lines.push(`export type ${schemaName.replace(/Schema$/, "")} = typeof ${schemaName}.Type`);
  lines.push("");
}
lines.push(
  `export const MktEventSchema = Schema.Union([${Object.values(eventSchemaNames).join(", ")}])`,
);
lines.push("export type MktEvent = typeof MktEventSchema.Type");
lines.push("");

const unformattedOutput = `${lines.join("\n")}\n`;
const format = spawnSync("vp", ["fmt", "--stdin-filepath", fileURLToPath(OUTPUT_PATH)], {
  cwd: PACKAGE_ROOT,
  encoding: "utf8",
  input: unformattedOutput,
});
if (format.status !== 0) {
  throw new Error(format.stderr || "Failed to format generated contract");
}
const output = format.stdout;
const check = process.argv.includes("--check");
if (process.argv.includes("--stdout")) {
  process.stdout.write(output);
} else if (check) {
  const current = await readFile(OUTPUT_PATH, "utf8").catch(() => "");
  if (current !== output) {
    process.stderr.write(`Generated contract is stale: ${PACKAGE_ROOT}src/generated.ts\n`);
    process.exitCode = 1;
  }
} else {
  await writeFile(OUTPUT_PATH, output);
}
