// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  eventRef: __t.string(),
  runRef: __t.string(),
  eventKind: __t.string(),
  entityRef: __t.string(),
  sourceRef: __t.string(),
  sourceGeneratedAt: __t.string(),
  summary: __t.string(),
};
