// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  settlementRef: __t.string().primaryKey().name("settlement_ref"),
  runRef: __t.string().name("run_ref"),
  entityRef: __t.string().name("entity_ref"),
  receiptRef: __t.string().name("receipt_ref"),
  movementMode: __t.string().name("movement_mode"),
  realBitcoinMoved: __t.bool().name("real_bitcoin_moved"),
  amountSats: __t.u64().name("amount_sats"),
  url: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
