// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  entityRef: __t.string(),
  runRef: __t.string(),
  entityKind: __t.string(),
  label: __t.string(),
  lane: __t.string(),
  status: __t.string(),
  sourceRef: __t.string(),
  proofCount: __t.u32(),
};
