// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  regionRef: __t.string(),
  runRef: __t.string(),
  label: __t.string(),
  minX: __t.f64(),
  minY: __t.f64(),
  minZ: __t.f64(),
  maxX: __t.f64(),
  maxY: __t.f64(),
  maxZ: __t.f64(),
  roadDirectionX: __t.f64(),
  roadDirectionY: __t.f64(),
  roadDirectionZ: __t.f64(),
  localOriginX: __t.f64(),
  localOriginY: __t.f64(),
  localOriginZ: __t.f64(),
  starterPylonSiteOffsetX: __t.f64(),
  starterPylonSiteOffsetY: __t.f64(),
  starterPylonSiteOffsetZ: __t.f64(),
  streetPrevRegionRef: __t.string(),
  streetNextRegionRef: __t.string(),
  proximityRadiusMeters: __t.f64(),
  avatarPositionMinIntervalMs: __t.i64(),
  staleAvatarPositionMs: __t.i64(),
};
