// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  edgeRef: __t.string().primaryKey().name("edge_ref"),
  runRef: __t.string().name("run_ref"),
  fromEntityRef: __t.string().name("from_entity_ref"),
  toEntityRef: __t.string().name("to_entity_ref"),
  edgeKind: __t.string().name("edge_kind"),
  sourceRef: __t.string().name("source_ref"),
  updatedAt: __t.timestamp().name("updated_at"),
});
