//! Shared terminal drawing and native adapters, mounted by Verse or a standalone window.
#[cfg(test)]
use crate::integration;
use crate::{draw, glyphs, pty};
use coder_ui::theme::Intensity;
use layout::{PaneId, Rect};
use pty::Program;
use std::collections::BTreeMap;
use std::time::{Duration, Instant};
pub use terminal_control as control;
pub use terminal_core::{
    HELP, PANE_BYTES, UPDATE_BUDGET, copy, layout, mouse, opening, paper, select, stats,
};
use ui::{Atlas, UiBatch, UiVertex};
pub use verse_gfx::ui;
use winit::keyboard::{Key as Logical, KeyCode, ModifiersState};

pub const GLYPH_ROWS: u32 = 1024;
/// The sheet's size in points, fixed at compile time: 3:2, like a page.
/// The standalone window is exactly this size and cannot be resized; the
/// Grid draws the same sheet, anchored at the center of the screen.
pub const SHEET_POINTS: [f32; 2] = [1200.0, 800.0];
const BLINK: Duration = Duration::from_millis(530);
const FLASH: Duration = Duration::from_millis(180);
#[derive(Clone, Debug)]
pub struct KeyIn {
    pub code: KeyCode,
    pub logical: Logical,
    pub text: Option<String>,
    pub plain: Option<String>,
    pub pressed: bool,
    pub repeat: bool,
    /// Focus synchronization generated by the OS is not a person's approval.
    pub synthetic: bool,
}
#[derive(Clone, Copy, PartialEq)]
struct CacheKey {
    generation: u64,
    revision: u64,
    scroll: usize,
    rect: [u32; 4],
    focused: bool,
    title: u64,
    flash: bool,
    atlas: u64,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Mount {
    #[default]
    Overlay,
    Window,
}

pub struct Overlay {
    pub mount: Mount,
    /// The display's backing scale, which the mount sets.
    pub scale: f32,
    pub core: terminal_core::Application,
    fallback: Option<glyphs::Fallback>,
    cache: BTreeMap<PaneId, (CacheKey, Vec<UiVertex>)>,
    control: Option<control::Listener>,
}
impl std::ops::Deref for Overlay {
    type Target = terminal_core::Application;
    fn deref(&self) -> &Self::Target {
        &self.core
    }
}
impl std::ops::DerefMut for Overlay {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.core
    }
}
impl std::fmt::Debug for Overlay {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.core.fmt(f)
    }
}
/// Where a mount keeps the read-only auto-run opt-in, under its home.
pub const AUTORUN_FILE: &str = ".openagents/terminal/autorun.json";

impl Default for Overlay {
    fn default() -> Self {
        Self::new()
    }
}
impl Overlay {
    pub fn new() -> Self {
        #[cfg_attr(test, allow(unused_mut))]
        let mut core = terminal_core::Application::new(pty::for_user());
        // The read-only auto-run opt-in lives beside the user's other
        // OpenAgents state; tests never read the real home.
        #[cfg(not(test))]
        if let Some(home) = std::env::var_os("HOME") {
            core.smart.autorun = terminal_core::autorun::AutoRun::load(
                std::path::Path::new(&home).join(AUTORUN_FILE),
            );
        }
        Self::mount(core)
    }
    pub fn with(root: &std::path::Path, shell: std::path::PathBuf, first: Program) -> Self {
        let mut core = terminal_core::Application::new(pty::isolated(root, shell));
        core.first = Some(first);
        core.smart.autorun = terminal_core::autorun::AutoRun::load(root.join(AUTORUN_FILE));
        Self::mount(core)
    }
    pub fn mount(core: terminal_core::Application) -> Self {
        let mut core = core;
        core.paper.on = true;
        Self {
            mount: Mount::Overlay,
            scale: 1.0,
            core,
            fallback: None,
            cache: BTreeMap::new(),
            control: None,
        }
    }
    pub fn key(&mut self, key: &KeyIn) -> bool {
        let taken = self.core.key(&input(key));
        // In the Grid, F10 puts the sheet away; the window's mount quits.
        if self.mount == Mount::Overlay && self.core.paper.quit {
            self.core.paper.quit = false;
            self.core.open = false;
            self.core.focused = false;
        }
        taken
    }
    pub fn modifiers(&mut self, mods: ModifiersState) {
        self.core.modifiers(modifiers(mods));
    }
    fn pane_area(&self, size: [f32; 2], cell: [f32; 2]) -> Rect {
        match self.mount {
            Mount::Overlay => Self::area_for(size, cell),
            Mount::Window => Rect::new(
                8.0,
                cell[1] + 16.0,
                (size[0] - 16.0).max(cell[0]),
                (size[1] - 3.0 * cell[1] - 32.0).max(cell[1] * 4.0),
            ),
        }
    }
    pub fn fit(&mut self, atlas: &Atlas, size: [f32; 2]) {
        self.core.fit_metrics(draw::cell_size(atlas), size);
        self.core.area = self.pane_area(size, self.core.cell);
    }
    pub fn press(&mut self, point: [f32; 2]) -> bool {
        self.core.press(point)
    }
    pub fn release(&mut self, point: [f32; 2]) -> bool {
        self.core.release(point)
    }
    pub fn wheel(&mut self, point: [f32; 2], lines: f32) -> bool {
        self.core.wheel(point, lines)
    }
    pub fn pointer(&mut self, point: [f32; 2]) {
        self.core.pointer(point);
    }
    pub fn button(&mut self, button: mouse::Button, pressed: bool, point: [f32; 2]) -> bool {
        self.core.button(button, pressed, point)
    }
    pub fn shutdown(&mut self) {
        self.core.shutdown();
        self.cache.clear();
    }
    pub fn tick(&mut self) {
        self.serve();
        self.core.tick();
        self.cache.retain(|id, _| self.core.panes.contains_key(id));
    }
    pub fn status(&self) -> serde_json::Value {
        let mut value = self.core.status();
        value["socket"] = serde_json::json!(self.control_path());
        value
    }
    pub fn apply(&mut self, request: &control::Request) -> Result<serde_json::Value, String> {
        let mut value = self.core.apply(request)?;
        if value.get("socket").is_some() {
            value["socket"] = serde_json::json!(self.control_path());
        }
        Ok(value)
    }
    pub fn button_for(size: [f32; 2], scale: f32, tray: Option<[f32; 4]>) -> Rect {
        terminal_core::Application::button_for(size, scale, tray)
    }
    pub fn area_for(size: [f32; 2], cell: [f32; 2]) -> Rect {
        terminal_core::Application::area_for(size, cell)
    }
    pub fn card_for(size: [f32; 2], button: Rect, card: [f32; 2], overlay: Option<Rect>) -> Rect {
        terminal_core::Application::card_for(size, button, card, overlay)
    }
    pub fn listen(&mut self, path: &std::path::Path) -> Result<(), String> {
        self.control = Some(control::Listener::bind(path)?);
        Ok(())
    }

    /// Where the control socket listens, when it does.
    #[must_use]
    pub fn control_path(&self) -> Option<&std::path::Path> {
        self.control.as_ref().map(control::Listener::path)
    }

    /// Answers the requests the control socket holds. Runs between frames.
    fn serve(&mut self) {
        let mut served = 0;
        while served < 32 {
            let Some((request, reply)) = self.control.as_ref().and_then(control::Listener::next)
            else {
                return;
            };
            let value = match self.apply(&request) {
                Ok(mut value) => {
                    if let Some(map) = value.as_object_mut() {
                        map.insert("ok".into(), serde_json::Value::Bool(true));
                    }
                    value
                }
                Err(error) => serde_json::json!({ "ok": false, "error": error }),
            };
            let _ = reply.try_send(value);
            served += 1;
        }
    }

    /// Draws the overlay over a window of `size` pixels with `atlas`, and
    /// the terminal's hotbar button when it has a place. Characters the
    /// atlas lacks are rasterized into it from fallback fonts; a renderer
    /// uploads it again when its [`Atlas::revision`] changes.
    pub fn draw(&mut self, batch: &mut UiBatch, atlas: &mut Atlas, size: [f32; 2]) {
        self.draw_overlay(batch, atlas, size);
        if let Some(rect) = self.core.button {
            self.draw_button(batch, atlas, size, rect);
        }
    }

    /// The button: a hotbar slot with a prompt icon and its key, and a
    /// card beside it while the pointer rests on it. The card never covers
    /// the open overlay.
    fn draw_button(&self, batch: &mut UiBatch, atlas: &Atlas, size: [f32; 2], rect: Rect) {
        let [cw, ch] = draw::cell_size(atlas);
        let lit = self.core.open || rect.contains(self.core.pointer);
        batch.rect(atlas, rect.x, rect.y, rect.w, rect.h, draw::field(0.85));
        batch.frame(
            atlas,
            rect.x,
            rect.y,
            rect.w,
            rect.h,
            (rect.w / 32.0).round().max(1.0),
            draw::white(
                if lit {
                    Intensity::Full
                } else {
                    Intensity::Half
                },
                1.0,
            ),
        );
        let icon = ">_";
        let x = rect.x + (rect.w - 2.0 * cw) / 2.0;
        let y = rect.y + (rect.h - ch) / 2.0;
        let color = draw::white(
            if lit {
                Intensity::Full
            } else {
                Intensity::ThreeQuarters
            },
            1.0,
        );
        batch.text(atlas, x, y, icon, color);
        batch.text(atlas, x + 1.0, y, icon, color);
        batch.text(
            atlas,
            rect.x + 3.0,
            rect.y + 1.0,
            "T",
            draw::white(Intensity::Half, 1.0),
        );
        if !rect.contains(self.core.pointer) {
            return;
        }
        let lines = [
            ("Terminal", Intensity::Full),
            (
                "Opens your login shell over the world.",
                Intensity::ThreeQuarters,
            ),
            (
                "Ctrl+B splits and opens agent threads.",
                Intensity::ThreeQuarters,
            ),
            ("T or click · Ctrl+` focus", Intensity::Half),
        ];
        let width = lines
            .iter()
            .map(|(line, _)| line.chars().count())
            .max()
            .unwrap_or(0) as f32
            * cw
            + 2.0 * cw;
        let height = lines.len() as f32 * (ch + 2.0) + ch;
        let card = Overlay::card_for(
            size,
            rect,
            [width, height],
            self.core.open.then(|| self.bounds()),
        );
        batch.rect(atlas, card.x, card.y, width, height, draw::field(0.95));
        batch.frame(
            atlas,
            card.x,
            card.y,
            width,
            height,
            1.0,
            draw::white(Intensity::Half, 1.0),
        );
        let mut line_y = card.y + ch / 2.0;
        for (line, step) in lines {
            batch.text(atlas, card.x + cw, line_y, line, draw::white(step, 1.0));
            line_y += ch + 2.0;
        }
    }

    fn draw_overlay(&mut self, batch: &mut UiBatch, atlas: &mut Atlas, size: [f32; 2]) {
        if !self.core.open {
            // Sessions keep running hidden; their output still applies.
            self.tick();
            return;
        }
        self.core.cell = draw::cell_size(atlas);
        self.core.area = self.pane_area(size, self.core.cell);
        self.ensure_started();
        if self.core.tabs.is_empty() {
            self.core.open = false;
            self.core.focused = false;
            return;
        }
        if self.core.paper.on {
            self.draw_paper(batch, atlas, size);
            return;
        }
        self.tick();
        if !self.core.open {
            return;
        }
        let drawing = self.core.stats.active().then(Instant::now);
        self.draw_panes(batch, atlas);
        self.draw_smart(batch, atlas);
        if let Some(drawing) = drawing {
            self.core.stats.add_draw(drawing.elapsed());
        }
    }

    fn draw_panes(&mut self, batch: &mut UiBatch, atlas: &mut Atlas) {
        let bounds = self.bounds();
        batch.rect(
            atlas,
            bounds.x,
            bounds.y,
            bounds.w,
            bounds.h,
            draw::field(0.94),
        );
        batch.frame(
            atlas,
            bounds.x,
            bounds.y,
            bounds.w,
            bounds.h,
            1.0,
            draw::white(
                if self.core.focused {
                    Intensity::Half
                } else {
                    Intensity::Quarter
                },
                1.0,
            ),
        );
        // The header: tabs, the prefix state, and focus.
        let [cw, ch] = self.core.cell;
        let mut x = bounds.x + cw;
        let y = bounds.y + 4.0;
        x += batch.text(atlas, x, y, "Terminal", draw::white(Intensity::Full, 1.0)) + 2.0 * cw;
        for index in 0..self.core.tabs.len() {
            let label = format!("{}", index + 1);
            let step = if index == self.core.active {
                Intensity::Full
            } else {
                Intensity::Half
            };
            if index == self.core.active {
                batch.rect(
                    atlas,
                    x - cw * 0.5,
                    y - 1.0,
                    cw * (label.len() as f32 + 1.0),
                    ch + 2.0,
                    draw::white(Intensity::Quarter, 0.6),
                );
            }
            x += batch.text(atlas, x, y, &label, draw::white(step, 1.0)) + cw;
        }
        let state = self.state_line();
        let columns = ((bounds.x + bounds.w - x - 2.0 * cw) / cw).max(0.0) as usize;
        let state: String = state.chars().take(columns).collect();
        batch.text(
            atlas,
            x + cw,
            y,
            &state,
            draw::white(
                if self.core.prefix || self.core.copy.is_some() || self.core.stats.shown {
                    Intensity::Full
                } else {
                    Intensity::Half
                },
                1.0,
            ),
        );
        let help_y = self.core.area.y + self.core.area.h + 6.0;
        let held = self.core.paste_prompt().or_else(|| self.core.find_prompt());
        let help = match (&self.core.copy, &self.core.notice) {
            (Some(_), _) => copy::HELP.to_owned(),
            (None, _) if held.is_some() => held.unwrap_or_default(),
            (None, Some(notice)) => notice.clone(),
            (None, None) => {
                if self.mount == Mount::Window {
                    HELP.replace("world", "window")
                } else {
                    HELP.to_owned()
                }
            }
        };
        let columns = ((bounds.w - 2.0 * cw) / cw).max(0.0) as usize;
        let help: String = help.chars().take(columns).collect();
        batch.text(
            atlas,
            bounds.x + cw,
            help_y,
            &help,
            draw::white(Intensity::Half, 1.0),
        );

        let Some(tab) = self.core.tabs.get(self.core.active) else {
            return;
        };
        let focus = tab.layout.focus();
        let zoomed = tab.zoomed;
        let pane_focused = self.core.focused;
        let now = Instant::now();
        let blink_on =
            (now.duration_since(self.core.typed).as_millis() / BLINK.as_millis()) % 2 == 0;
        let copy_at = self.core.copy.as_ref().map(|c| (c.pane, c.cursor));
        let shown = self.shown();
        let fallback = self.fallback.get_or_insert_with(glyphs::Fallback::new);
        for (id, rect) in shown {
            let Some(pane) = self.core.panes.get_mut(&id) else {
                continue;
            };
            let focused = id == focus && pane_focused;
            let vt = &pane.session.vt;
            self.core.stats.drawn(id, vt.generation());
            let mut title = if vt.title().is_empty() {
                pane.label.clone()
            } else {
                format!("{} — {}", pane.label, vt.title())
            };
            if let Some(typist) = &pane.typist {
                title = format!("{title}  [driven by {typist}; any key takes it back]");
            }
            let mut detail = pane.session.cwd.clone().unwrap_or_default();
            if pane.scroll > 0 {
                detail = format!("{detail}  [scrolled back {} lines]", pane.scroll);
            }
            if zoomed {
                detail = format!("{detail}  [zoomed]");
            }
            let flash = pane.flash.is_some_and(|at| now.duration_since(at) < FLASH);
            let rows = visible(vt, pane.scroll);
            let mut key = CacheKey {
                generation: vt.generation(),
                revision: pane.render_revision,
                scroll: pane.scroll,
                rect: [rect.x, rect.y, rect.w, rect.h].map(f32::to_bits),
                focused,
                title: hash(&(title.as_str(), detail.as_str())),
                flash,
                atlas: atlas.revision(),
            };
            let cached = self.cache.get(&id).is_some_and(|(k, _)| *k == key);
            if cached {
                if let Some((_, vertices)) = &self.cache.get(&id) {
                    batch.vertices.extend_from_slice(vertices);
                }
            } else {
                // Characters the atlas lacks come from fallback fonts first.
                for row in &rows {
                    let unusual = |c: &&coder_vt::Cell| {
                        c.width != 0 && (!c.ch.is_ascii() || !c.combining.is_empty())
                    };
                    for cell in row.cells.iter().filter(unusual) {
                        let c = draw::substitute(cell.ch);
                        if !c.is_ascii() && !draw::shaped(c) {
                            fallback.ensure(atlas, c);
                        }
                        for &mark in &cell.combining {
                            fallback.ensure(atlas, mark);
                        }
                    }
                }
                key.atlas = atlas.revision();
                let mut own = UiBatch::default();
                let inner = draw::chrome(&mut own, atlas, rect, &title, &detail, focused, flash);
                draw::grid(
                    &mut own,
                    atlas,
                    [inner.x, inner.y],
                    &draw::Grid { rows: rows.clone() },
                );
                batch.vertices.extend_from_slice(&own.vertices);
                self.cache.insert(id, (key, own.vertices));
            }
            let inner = draw::inner(rect, [cw, ch]);
            let top = select::top(vt, pane.scroll);
            // Advisory command gutters and collapsed output stay on their absolute lines.
            if !vt.alternate_screen() {
                let absolute_top = vt.history_dropped() + top as u64;
                for block in &pane.session.blocks.records {
                    let end = block.end.as_ref().map_or(block.start.line, |end| end.line);
                    let from = block.start.line.max(absolute_top);
                    let to = end.min(absolute_top + rows.len() as u64);
                    if to < from {
                        continue;
                    }
                    let step = if block.status.is_some_and(|status| status != 0) {
                        Intensity::Full
                    } else {
                        Intensity::Half
                    };
                    for absolute in from..to {
                        let y = inner.y + (absolute - absolute_top) as f32 * ch;
                        batch.rect(atlas, inner.x - 3.0, y, 2.0, ch, draw::white(step, 1.0));
                        if block.collapsed {
                            batch.rect(atlas, inner.x, y, inner.w, ch, draw::field(1.0));
                            if absolute == block.start.line {
                                let summary = format!(
                                    "[block {} · exit {:?} · output collapsed]",
                                    block.id, block.status
                                );
                                batch.text(
                                    atlas,
                                    inner.x,
                                    y,
                                    &summary,
                                    draw::white(Intensity::Half, 1.0),
                                );
                            }
                        }
                    }
                }
            }
            // The selection, over the text.
            if let Some(selection) = pane.selection.filter(|s| !s.empty()) {
                for (r, row) in rows.iter().enumerate() {
                    let line = select::absolute(vt, top + r);
                    if let Some((from, to)) = selection.columns(vt, line, row.cells.len()) {
                        batch.rect(
                            atlas,
                            inner.x + from as f32 * cw,
                            inner.y + r as f32 * ch,
                            (to - from) as f32 * cw,
                            ch,
                            draw::white(Intensity::ThreeQuarters, 0.35),
                        );
                    }
                }
            }
            // Copy mode's cursor, or the program's.
            if let Some((copy_pane, point)) = copy_at
                && copy_pane == id
            {
                if let Some(index) = select::index(vt, point.line)
                    && index >= top
                    && index < top + rows.len()
                {
                    let r = index - top;
                    batch.frame(
                        atlas,
                        inner.x + point.col as f32 * cw,
                        inner.y + r as f32 * ch,
                        cw,
                        ch,
                        2.0,
                        draw::white(Intensity::Full, 1.0),
                    );
                }
            } else if pane.scroll == 0 && vt.cursor_visible() {
                let style = vt.cursor_style();
                let (row, col) = vt.cursor();
                if !(focused && style.blink && !blink_on) {
                    draw::cursor(
                        batch,
                        atlas,
                        [inner.x + col as f32 * cw, inner.y + row as f32 * ch],
                        vt.row(row).and_then(|r| r.cells.get(col)),
                        style.shape,
                        focused,
                    );
                }
                // The caret's live routing: a dim label at the end of its row.
                if focused && let Some(decision) = self.core.routing(id) {
                    let label = decision.label();
                    let columns = (inner.w / cw).floor() as usize;
                    let at = columns.saturating_sub(label.len() + 1);
                    if at > col + 1 {
                        batch.text(
                            atlas,
                            inner.x + at as f32 * cw,
                            inner.y + row as f32 * ch,
                            label,
                            draw::white(Intensity::Half, 1.0),
                        );
                    }
                }
            }
        }
    }

    /// The header's state text.
    fn state_line(&self) -> String {
        if self.core.stats.shown {
            return self.core.stats.line();
        }
        if let Some(copy) = &self.core.copy {
            return copy.state();
        }
        if self.core.prefix {
            "prefix: waiting for a command".to_owned()
        } else if self.core.focused {
            match self.focus_id().and_then(|id| self.core.routing(id)) {
                Some(decision) if decision.route == terminal_core::route::Route::Ask => {
                    "Enter asks OpenAgents · Up in the request runs it as a command".to_owned()
                }
                Some(_) => "Enter runs the command".to_owned(),
                None => "Type a command or a question, then Enter".to_owned(),
            }
        } else {
            match self.mount {
                Mount::Overlay => "the world has focus: click a pane or press Ctrl+`",
                Mount::Window => "click a pane or press Ctrl+` to focus the shell",
            }
            .to_owned()
        }
    }
    pub fn draw_smart(&self, batch: &mut verse_gfx::ui::UiBatch, atlas: &verse_gfx::ui::Atlas) {
        use coder_ui::theme::Intensity;
        let lines = if let Some(draft) = self
            .core
            .smart
            .draft
            .as_ref()
            .filter(|draft| self.focus_id() == Some(draft.pane))
        {
            format!(
                "Request: {}\n{}\nEnter sends · Ctrl+D removes context · PgUp/PgDn scroll · Esc cancels",
                draft.text,
                draft.context.preview()
            )
        } else if let Some((_, key)) = self
            .core
            .smart
            .pending
            .as_ref()
            .filter(|(pane, _)| self.focus_id() == Some(*pane))
        {
            let entry = &self.core.smart.book.entries[key];
            let proposal = &entry.proposal;
            let warning = if matches!(entry.phase, terminal_core::proposals::Phase::Warned { .. }) {
                match self.core.smart.policy.0.get(&proposal.command) {
                    Some(terminal_core::proposals::Effect::Destructive(warning)) => {
                        warning.as_str()
                    }
                    _ => "Press Enter again to approve this command.",
                }
            } else {
                "Enter approves · PgUp/PgDn scroll · Esc dismisses"
            };
            format!(
                "Pending command · {}\nThread {} · proposal {} revision {}\n$ {}\n{}",
                proposal.binding.cwd,
                proposal.thread,
                proposal.id,
                proposal.revision,
                proposal.command,
                warning
            )
        } else {
            return;
        };
        let [cw, ch] = self.core.cell;
        let rect = self.core.area;
        batch.rect(atlas, rect.x, rect.y, rect.w, rect.h, draw::field(0.98));
        let rows = (rect.h / ch).max(1.0) as usize;
        let columns = (rect.w / cw).max(1.0) as usize;
        let scroll = self
            .smart
            .draft
            .as_ref()
            .map_or(self.core.smart.proposal_scroll, |draft| draft.scroll);
        let wrapped = lines
            .lines()
            .flat_map(|line| {
                let chars = line.chars().collect::<Vec<_>>();
                if chars.is_empty() {
                    vec![String::new()]
                } else {
                    chars
                        .chunks(columns.saturating_sub(2).max(1))
                        .map(|chunk| chunk.iter().collect::<String>())
                        .collect()
                }
            })
            .collect::<Vec<_>>();
        let scroll = scroll.min(wrapped.len().saturating_sub(rows));
        for (index, line) in wrapped.iter().skip(scroll).take(rows).enumerate() {
            batch.text(
                atlas,
                rect.x + cw,
                rect.y + index as f32 * ch,
                line,
                draw::white(Intensity::ThreeQuarters, 1.0),
            );
        }
    }
}
fn hash(value: &impl std::hash::Hash) -> u64 {
    use std::hash::Hasher;
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    value.hash(&mut hasher);
    hasher.finish()
}

/// The rows a pane shows, `scroll` lines back from the bottom.
fn visible(vt: &coder_vt::Terminal, scroll: usize) -> Vec<&coder_vt::Row> {
    let top = select::top(vt, scroll);
    (top..top + vt.rows()).filter_map(|i| vt.line(i)).collect()
}

#[cfg(test)]
#[path = "bash_tests.rs"]
mod bash_tests;
#[cfg(test)]
#[path = "fish_tests.rs"]
mod fish_tests;
#[cfg(test)]
#[path = "kitty_tests.rs"]
mod kitty_tests;
#[cfg(test)]
#[path = "tests.rs"]
mod tests;
fn input(key: &KeyIn) -> terminal_core::KeyIn {
    use terminal_core::input as core;
    let code = match key.code {
        KeyCode::AltLeft => core::KeyCode::AltLeft,
        KeyCode::AltRight => core::KeyCode::AltRight,
        KeyCode::ArrowDown => core::KeyCode::ArrowDown,
        KeyCode::ArrowLeft => core::KeyCode::ArrowLeft,
        KeyCode::ArrowRight => core::KeyCode::ArrowRight,
        KeyCode::ArrowUp => core::KeyCode::ArrowUp,
        KeyCode::Backquote => core::KeyCode::Backquote,
        KeyCode::Backslash => core::KeyCode::Backslash,
        KeyCode::Backspace => core::KeyCode::Backspace,
        KeyCode::BracketLeft => core::KeyCode::BracketLeft,
        KeyCode::BracketRight => core::KeyCode::BracketRight,
        KeyCode::CapsLock => core::KeyCode::CapsLock,
        KeyCode::Comma => core::KeyCode::Comma,
        KeyCode::ControlLeft => core::KeyCode::ControlLeft,
        KeyCode::ControlRight => core::KeyCode::ControlRight,
        KeyCode::Digit0 => core::KeyCode::Digit0,
        KeyCode::Digit1 => core::KeyCode::Digit1,
        KeyCode::Digit2 => core::KeyCode::Digit2,
        KeyCode::Digit3 => core::KeyCode::Digit3,
        KeyCode::Digit4 => core::KeyCode::Digit4,
        KeyCode::Digit5 => core::KeyCode::Digit5,
        KeyCode::Digit6 => core::KeyCode::Digit6,
        KeyCode::Digit7 => core::KeyCode::Digit7,
        KeyCode::Digit8 => core::KeyCode::Digit8,
        KeyCode::Digit9 => core::KeyCode::Digit9,
        KeyCode::Enter => core::KeyCode::Enter,
        KeyCode::Equal => core::KeyCode::Equal,
        KeyCode::Escape => core::KeyCode::Escape,
        KeyCode::F1 => core::KeyCode::F1,
        KeyCode::Fn => core::KeyCode::Fn,
        KeyCode::KeyA => core::KeyCode::KeyA,
        KeyCode::KeyB => core::KeyCode::KeyB,
        KeyCode::KeyC => core::KeyCode::KeyC,
        KeyCode::KeyD => core::KeyCode::KeyD,
        KeyCode::KeyE => core::KeyCode::KeyE,
        KeyCode::KeyF => core::KeyCode::KeyF,
        KeyCode::KeyG => core::KeyCode::KeyG,
        KeyCode::KeyH => core::KeyCode::KeyH,
        KeyCode::KeyI => core::KeyCode::KeyI,
        KeyCode::KeyJ => core::KeyCode::KeyJ,
        KeyCode::KeyK => core::KeyCode::KeyK,
        KeyCode::KeyL => core::KeyCode::KeyL,
        KeyCode::KeyM => core::KeyCode::KeyM,
        KeyCode::KeyN => core::KeyCode::KeyN,
        KeyCode::KeyO => core::KeyCode::KeyO,
        KeyCode::KeyP => core::KeyCode::KeyP,
        KeyCode::KeyQ => core::KeyCode::KeyQ,
        KeyCode::KeyR => core::KeyCode::KeyR,
        KeyCode::KeyS => core::KeyCode::KeyS,
        KeyCode::KeyT => core::KeyCode::KeyT,
        KeyCode::KeyU => core::KeyCode::KeyU,
        KeyCode::KeyV => core::KeyCode::KeyV,
        KeyCode::KeyW => core::KeyCode::KeyW,
        KeyCode::KeyX => core::KeyCode::KeyX,
        KeyCode::KeyY => core::KeyCode::KeyY,
        KeyCode::KeyZ => core::KeyCode::KeyZ,
        KeyCode::Minus => core::KeyCode::Minus,
        KeyCode::Numpad0 => core::KeyCode::Numpad0,
        KeyCode::Numpad1 => core::KeyCode::Numpad1,
        KeyCode::Numpad2 => core::KeyCode::Numpad2,
        KeyCode::Numpad3 => core::KeyCode::Numpad3,
        KeyCode::Numpad4 => core::KeyCode::Numpad4,
        KeyCode::Numpad5 => core::KeyCode::Numpad5,
        KeyCode::Numpad6 => core::KeyCode::Numpad6,
        KeyCode::Numpad7 => core::KeyCode::Numpad7,
        KeyCode::Numpad8 => core::KeyCode::Numpad8,
        KeyCode::Numpad9 => core::KeyCode::Numpad9,
        KeyCode::NumpadAdd => core::KeyCode::NumpadAdd,
        KeyCode::NumpadComma => core::KeyCode::NumpadComma,
        KeyCode::NumpadDecimal => core::KeyCode::NumpadDecimal,
        KeyCode::NumpadDivide => core::KeyCode::NumpadDivide,
        KeyCode::NumpadEnter => core::KeyCode::NumpadEnter,
        KeyCode::NumpadEqual => core::KeyCode::NumpadEqual,
        KeyCode::NumpadMultiply => core::KeyCode::NumpadMultiply,
        KeyCode::NumpadSubtract => core::KeyCode::NumpadSubtract,
        KeyCode::PageDown => core::KeyCode::PageDown,
        KeyCode::PageUp => core::KeyCode::PageUp,
        KeyCode::Period => core::KeyCode::Period,
        KeyCode::Quote => core::KeyCode::Quote,
        KeyCode::Semicolon => core::KeyCode::Semicolon,
        KeyCode::ShiftLeft => core::KeyCode::ShiftLeft,
        KeyCode::ShiftRight => core::KeyCode::ShiftRight,
        KeyCode::Slash => core::KeyCode::Slash,
        KeyCode::Space => core::KeyCode::Space,
        KeyCode::SuperLeft => core::KeyCode::SuperLeft,
        KeyCode::SuperRight => core::KeyCode::SuperRight,
        _ => core::KeyCode::Unidentified,
    };
    let logical = match &key.logical {
        Logical::Character(text) => core::Logical::Character(text.to_string()),
        Logical::Named(named) => core::Logical::Named(match named {
            winit::keyboard::NamedKey::ArrowDown => core::NamedKey::ArrowDown,
            winit::keyboard::NamedKey::ArrowLeft => core::NamedKey::ArrowLeft,
            winit::keyboard::NamedKey::ArrowRight => core::NamedKey::ArrowRight,
            winit::keyboard::NamedKey::ArrowUp => core::NamedKey::ArrowUp,
            winit::keyboard::NamedKey::Backspace => core::NamedKey::Backspace,
            winit::keyboard::NamedKey::Delete => core::NamedKey::Delete,
            winit::keyboard::NamedKey::End => core::NamedKey::End,
            winit::keyboard::NamedKey::Enter => core::NamedKey::Enter,
            winit::keyboard::NamedKey::Escape => core::NamedKey::Escape,
            winit::keyboard::NamedKey::F1 => core::NamedKey::F1,
            winit::keyboard::NamedKey::F10 => core::NamedKey::F10,
            winit::keyboard::NamedKey::F11 => core::NamedKey::F11,
            winit::keyboard::NamedKey::F12 => core::NamedKey::F12,
            winit::keyboard::NamedKey::F13 => core::NamedKey::F13,
            winit::keyboard::NamedKey::F14 => core::NamedKey::F14,
            winit::keyboard::NamedKey::F15 => core::NamedKey::F15,
            winit::keyboard::NamedKey::F16 => core::NamedKey::F16,
            winit::keyboard::NamedKey::F17 => core::NamedKey::F17,
            winit::keyboard::NamedKey::F18 => core::NamedKey::F18,
            winit::keyboard::NamedKey::F19 => core::NamedKey::F19,
            winit::keyboard::NamedKey::F2 => core::NamedKey::F2,
            winit::keyboard::NamedKey::F20 => core::NamedKey::F20,
            winit::keyboard::NamedKey::F21 => core::NamedKey::F21,
            winit::keyboard::NamedKey::F22 => core::NamedKey::F22,
            winit::keyboard::NamedKey::F23 => core::NamedKey::F23,
            winit::keyboard::NamedKey::F24 => core::NamedKey::F24,
            winit::keyboard::NamedKey::F3 => core::NamedKey::F3,
            winit::keyboard::NamedKey::F4 => core::NamedKey::F4,
            winit::keyboard::NamedKey::F5 => core::NamedKey::F5,
            winit::keyboard::NamedKey::F6 => core::NamedKey::F6,
            winit::keyboard::NamedKey::F7 => core::NamedKey::F7,
            winit::keyboard::NamedKey::F8 => core::NamedKey::F8,
            winit::keyboard::NamedKey::F9 => core::NamedKey::F9,
            winit::keyboard::NamedKey::Home => core::NamedKey::Home,
            winit::keyboard::NamedKey::Insert => core::NamedKey::Insert,
            winit::keyboard::NamedKey::PageDown => core::NamedKey::PageDown,
            winit::keyboard::NamedKey::PageUp => core::NamedKey::PageUp,
            winit::keyboard::NamedKey::Space => core::NamedKey::Space,
            winit::keyboard::NamedKey::Tab => core::NamedKey::Tab,
            _ => core::NamedKey::Unidentified,
        }),
        Logical::Dead(character) => core::Logical::Dead(*character),
        _ => core::Logical::Unidentified,
    };
    terminal_core::KeyIn {
        code,
        logical,
        text: key.text.clone(),
        plain: key.plain.clone(),
        pressed: key.pressed,
        repeat: key.repeat,
        synthetic: key.synthetic,
    }
}
fn modifiers(mods: ModifiersState) -> terminal_core::input::ModifiersState {
    use terminal_core::input::ModifiersState as Core;
    let mut out = Core::empty();
    for (enabled, flag) in [
        (mods.shift_key(), Core::SHIFT),
        (mods.control_key(), Core::CONTROL),
        (mods.alt_key(), Core::ALT),
        (mods.super_key(), Core::SUPER),
    ] {
        if enabled {
            out = out | flag;
        }
    }
    out
}

/// Native key compatibility at the mount boundary.
pub mod keys {
    pub fn encode(
        key: &super::KeyIn,
        modifiers: coder_vt::Modifiers,
        vt: &coder_vt::Terminal,
        option_as_meta: bool,
        macos: bool,
    ) -> Option<Vec<u8>> {
        terminal_core::keys::encode(&super::input(key), modifiers, vt, option_as_meta, macos)
    }
}

impl Overlay {
    /// Where the sheet sits: the whole window, or in the Grid a fixed 3:2
    /// frame at the center of the screen.
    #[must_use]
    pub fn sheet_rect(&self, size: [f32; 2]) -> Rect {
        match self.mount {
            Mount::Window => Rect::new(0.0, 0.0, size[0], size[1]),
            Mount::Overlay => {
                let mut w = SHEET_POINTS[0] * self.scale;
                let mut h = SHEET_POINTS[1] * self.scale;
                if w > size[0] * 0.96 || h > size[1] * 0.96 {
                    let shrink = (size[0] * 0.96 / w).min(size[1] * 0.96 / h);
                    w *= shrink;
                    h *= shrink;
                }
                Rect::new(
                    ((size[0] - w) / 2.0).round(),
                    ((size[1] - h) / 2.0).round(),
                    w,
                    h,
                )
            }
        }
    }

    /// Draws the sheet: every row of ASCII spans at its fixed cell, in the
    /// four whites, with a steady caret.
    fn draw_paper(&mut self, batch: &mut UiBatch, atlas: &mut Atlas, size: [f32; 2]) {
        let [cw, ch] = draw::cell_size(atlas);
        self.core.cell = [cw, ch];
        let frame = self.sheet_rect(size);
        let columns = (frame.w / cw).floor() as usize;
        let rows = (frame.h / ch).floor() as usize;
        // Keep the grid the program sees in step before reading output.
        self.core.area = frame;
        self.tick();
        if !self.core.open {
            return;
        }
        let sheet = self.core.paper_sheet(columns, rows, &clock(), &load());
        let x0 = (frame.x + (frame.w - columns as f32 * cw) / 2.0).round();
        let y0 = (frame.y + (frame.h - rows as f32 * ch) / 2.0).round();
        batch.rect(atlas, frame.x, frame.y, frame.w, frame.h, draw::field(1.0));
        for (r, spans) in sheet.rows.iter().enumerate() {
            let y = y0 + r as f32 * ch;
            let mut col = 0usize;
            for span in spans {
                let x = x0 + col as f32 * cw;
                let width = span.text.len();
                let color = match span.tone {
                    terminal_core::paper::Tone::Reversed => {
                        batch.rect(
                            atlas,
                            x,
                            y,
                            width as f32 * cw,
                            ch,
                            draw::white(Intensity::ThreeQuarters, 1.0),
                        );
                        draw::field(1.0)
                    }
                    tone => draw::white(intensity(tone), 1.0),
                };
                if !span.text.trim().is_empty() {
                    batch.text(atlas, x, y, &span.text, color);
                }
                col += width;
            }
        }
        if let Some((row, col)) = sheet.caret
            && self.core.focused
        {
            let x = x0 + col as f32 * cw;
            let y = y0 + row as f32 * ch;
            batch.rect(atlas, x, y, cw, ch, draw::white(Intensity::Full, 1.0));
            let under = sheet.rows[row]
                .iter()
                .flat_map(|span| span.text.chars())
                .nth(col)
                .filter(|c| *c != ' ');
            if let Some(c) = under {
                batch.text(atlas, x, y, &c.to_string(), draw::field(1.0));
            }
        }
    }
}

fn intensity(tone: terminal_core::paper::Tone) -> Intensity {
    use terminal_core::paper::Tone;
    match tone {
        Tone::Loud => Intensity::Full,
        Tone::Present | Tone::Reversed => Intensity::ThreeQuarters,
        Tone::Quiet => Intensity::Half,
        Tone::Receded => Intensity::Quarter,
    }
}

/// The local time as `HH:MM:SS`.
fn clock() -> String {
    // SAFETY: `time` and `localtime_r` fill the plain values passed.
    unsafe {
        let now = libc::time(std::ptr::null_mut());
        let mut tm: libc::tm = std::mem::zeroed();
        if libc::localtime_r(&now, &mut tm).is_null() {
            return "--:--:--".into();
        }
        format!("{:02}:{:02}:{:02}", tm.tm_hour, tm.tm_min, tm.tm_sec)
    }
}

/// The one-minute load average.
fn load() -> String {
    let mut loads = [0f64; 3];
    // SAFETY: `getloadavg` writes at most the three values it is given.
    let got = unsafe { libc::getloadavg(loads.as_mut_ptr(), 3) };
    if got < 1 {
        return "?".into();
    }
    format!("{:.2}", loads[0])
}
