#!/usr/bin/env bun
import { createHash, generateKeyPairSync, sign as edSign } from 'node:crypto'
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

import {
  REACTOR_EXAMPLE_POLICIES,
  REACTOR_MODEL_CATALOG_SEED,
  REACTOR_SERVER_CLASS_HYDRALISK_PROFILE,
  buildReactorAirgapUpdateBundleManifest,
  buildReactorInstallOpsReceipt,
} from '../src/index'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = resolve(packageRoot, '../..')
const verifierPath = resolve(repoRoot, 'apps/oa-updates/scripts/verify-release.ts')
const workDir = mkdtempSync(resolve(tmpdir(), 'reactor-install-smoke-'))
const bundlePath = resolve(workDir, 'reactor-update-bundle.json')
const signaturePath = resolve(workDir, 'reactor-update-bundle.sig.json')
const publicKeyPath = resolve(workDir, 'release-pubkey.json')
const receiptsDir = resolve(workDir, 'receipts')
const signatureKid = 'reactor-smoke-test-key'
const generatedAt = '2026-07-04T12:30:00.000Z'

mkdirSync(receiptsDir)

const { privateKey, publicKey } = generateKeyPairSync('ed25519')
const publicJwk = publicKey.export({ format: 'jwk' }) as { x: string }
writeFileSync(
  publicKeyPath,
  JSON.stringify(
    {
      alg: 'ed25519',
      created: generatedAt.slice(0, 10),
      crv: 'Ed25519',
      kid: signatureKid,
      kty: 'OKP',
      note: 'Test key generated by Reactor install smoke; not a production trust root.',
      use: 'release-provenance',
      x: publicJwk.x,
    },
    null,
    2,
  ),
)

const bundleBytes = new TextEncoder().encode(
  JSON.stringify(
    {
      bundleRef: 'reactor.airgap_bundle.smoke.gpt_oss.20260704',
      bundleVersion: '2026-07-04.rx5.smoke',
      modelRef: REACTOR_SERVER_CLASS_HYDRALISK_PROFILE.modelRef,
      nodeProfileRef: REACTOR_SERVER_CLASS_HYDRALISK_PROFILE.nodeProfileRef,
      policyRef: REACTOR_EXAMPLE_POLICIES.usOnly.policyRef,
      policyVersion: REACTOR_EXAMPLE_POLICIES.usOnly.version,
    },
    null,
    2,
  ),
)
writeFileSync(bundlePath, bundleBytes)

const artifactSha256 = createHash('sha256').update(bundleBytes).digest('hex')
const signature = edSign(null, bundleBytes, privateKey).toString('base64url')
writeFileSync(
  signaturePath,
  JSON.stringify(
    {
      alg: 'ed25519',
      kid: signatureKid,
      schema: 'openagents.release_signature.v1',
      sha256: artifactSha256,
      signature,
      signedAt: generatedAt,
    },
    null,
    2,
  ),
)

const verify = (artifact: string) =>
  spawnSync(process.execPath, [verifierPath, artifact, signaturePath], {
    encoding: 'utf8',
    env: {
      ...process.env,
      OPENAGENTS_RELEASE_PUBKEY_PATH: publicKeyPath,
    },
  })

const validVerify = verify(bundlePath)
if (validVerify.status !== 0) {
  throw new Error(`expected signed bundle to verify: ${validVerify.stderr}`)
}

const tamperedPath = resolve(workDir, 'reactor-update-bundle-tampered.json')
writeFileSync(tamperedPath, `${Buffer.from(bundleBytes).toString('utf8')}\n`)
const tamperedVerify = verify(tamperedPath)
if (tamperedVerify.status === 0) {
  throw new Error('expected tampered bundle to fail signature verification')
}

const bundle = buildReactorAirgapUpdateBundleManifest({
  artifactSha256,
  bundleRef: 'reactor.airgap_bundle.smoke.gpt_oss.20260704',
  bundleVersion: '2026-07-04.rx5.smoke',
  createdAt: generatedAt,
  modelRef: REACTOR_SERVER_CLASS_HYDRALISK_PROFILE.modelRef,
  nodeProfile: REACTOR_SERVER_CLASS_HYDRALISK_PROFILE,
  policyRef: REACTOR_EXAMPLE_POLICIES.usOnly.policyRef,
  policyVersion: REACTOR_EXAMPLE_POLICIES.usOnly.version,
  publicKeyRef: publicKeyPath,
  signatureKid,
  signatureRef: signaturePath,
  sourceRefs: [
    'github:OpenAgentsInc/openagents#8275',
    'packages/reactor-contracts/scripts/install-smoke.ts',
  ],
  verifierRef: verifierPath,
})

const freshInstall = buildReactorInstallOpsReceipt({
  action: 'fresh_install',
  bundle,
  catalog: REACTOR_MODEL_CATALOG_SEED,
  decidedAt: generatedAt,
  nodeProfile: REACTOR_SERVER_CLASS_HYDRALISK_PROFILE,
  policy: REACTOR_EXAMPLE_POLICIES.usOnly,
  receiptRef: 'reactor.install_ops.smoke.fresh.20260704',
})
const upgrade = buildReactorInstallOpsReceipt({
  action: 'upgrade',
  bundle,
  catalog: REACTOR_MODEL_CATALOG_SEED,
  decidedAt: generatedAt,
  nodeProfile: REACTOR_SERVER_CLASS_HYDRALISK_PROFILE,
  policy: REACTOR_EXAMPLE_POLICIES.usOnly,
  receiptRef: 'reactor.install_ops.smoke.upgrade.20260704',
})
const rollback = buildReactorInstallOpsReceipt({
  action: 'rollback',
  bundle,
  catalog: REACTOR_MODEL_CATALOG_SEED,
  decidedAt: generatedAt,
  nodeProfile: REACTOR_SERVER_CLASS_HYDRALISK_PROFILE,
  policy: REACTOR_EXAMPLE_POLICIES.usOnly,
  receiptRef: 'reactor.install_ops.smoke.rollback.20260704',
  rollbackFromBundleRef: 'reactor.airgap_bundle.smoke.bad.20260704',
})

const receipts = { bundle, freshInstall, rollback, upgrade }
for (const [name, receipt] of Object.entries(receipts)) {
  writeFileSync(resolve(receiptsDir, `${name}.json`), JSON.stringify(receipt, null, 2))
}

console.log(
  JSON.stringify(
    {
      ok: true,
      receiptRefs: [
        freshInstall.receiptRef,
        upgrade.receiptRef,
        rollback.receiptRef,
      ],
      verifierRef: verifierPath,
      workDir,
    },
    null,
    2,
  ),
)
