// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncWatchedDirTs = { provider: string, base: string, files: bigint, last_read: bigint, };
