// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSummaryTs = { id: string, thread_id: string | null, title: string, project_id: string | null, resume_id: string | null, rollout_path: string | null, source: string | null, created_at: bigint, updated_at: bigint, message_count: bigint | null, last_message_ts: bigint | null, };
