// OB-3 (#8560): hosted, public-safe, tokenized agent-readiness reports.
//
// Stores the OB-3 15-step rubric projection
// (`openagents.agent_readiness_fifteen_step_assessment.v1`, built by
// `renderAgentReadinessFifteenStepAssessment` in `@openagentsinc/agent-readiness`)
// keyed by an unguessable `reportToken`. The stored assessment only ever
// contains facts about the prospect's OWN public domain — their own score,
// their own findings, their own evidence refs pointing at their own site —
// so the full assessment is safe to return from the unauthenticated public
// read route. `pipelineRef` and `sourceRef` are internal CRM/attribution
// refs; `readPublicReportByToken` never returns them. `recordReportClick`
// returns the `sourceRef` ONLY so the caller (the public route handler) can
// wire the click into the existing LG-6 funnel counters
// (`business_funnel_events`); it is never rendered to the prospect.

import { Schema as S } from 'effect'

import {
  type AgentReadinessFifteenStepAssessment,
  AgentReadinessFifteenStepAssessment as AgentReadinessFifteenStepAssessmentSchema,
  AgentReadinessGrade,
} from '@openagentsinc/agent-readiness'

import { compactRandomId, currentIsoTimestamp } from './runtime-primitives'

export const AGENT_READINESS_PUBLIC_REPORT_SCHEMA_VERSION =
  'openagents.agent_readiness_public_report.v1' as const

export const AgentReadinessPublicReportProjection = S.Struct({
  schemaVersion: S.Literal(AGENT_READINESS_PUBLIC_REPORT_SCHEMA_VERSION),
  reportToken: S.String,
  domain: S.String,
  score: S.Number,
  grade: AgentReadinessGrade,
  createdAt: S.String,
  assessment: AgentReadinessFifteenStepAssessmentSchema,
})
export type AgentReadinessPublicReportProjection =
  typeof AgentReadinessPublicReportProjection.Type

export class AgentReadinessPublicReportValidationError extends S.TaggedErrorClass<AgentReadinessPublicReportValidationError>()(
  'AgentReadinessPublicReportValidationError',
  { reason: S.String },
) {}

export type AgentReadinessPublicReportCreateInput = Readonly<{
  pipelineRef: string
  sourceRef: string
  domain: string
  assessment: AgentReadinessFifteenStepAssessment
}>

export type AgentReadinessPublicReportCreateResult = Readonly<{
  reportToken: string
  receiptRef: string
  domain: string
  score: number
  grade: typeof AgentReadinessGrade.Type
  createdAt: string
}>

export type AgentReadinessPublicReportClickResult = Readonly<{
  sourceRef: string
  clickCount: number
}>

export type AgentReadinessPublicReportRuntime = Readonly<{
  makeToken: () => string
  nowIso: () => string
}>

export const systemAgentReadinessPublicReportRuntime: AgentReadinessPublicReportRuntime = {
  makeToken: () => compactRandomId('rr'),
  nowIso: currentIsoTimestamp,
}

export type AgentReadinessPublicReportStore = Readonly<{
  createPublicReport: (
    input: AgentReadinessPublicReportCreateInput,
    runtime?: AgentReadinessPublicReportRuntime,
  ) => Promise<AgentReadinessPublicReportCreateResult>
  readPublicReportByToken: (
    reportToken: string,
  ) => Promise<AgentReadinessPublicReportProjection | null>
  recordReportClick: (
    reportToken: string,
    runtime?: AgentReadinessPublicReportRuntime,
  ) => Promise<AgentReadinessPublicReportClickResult | null>
}>

type AgentReadinessPublicReportD1Row = Readonly<{
  report_token: string
  domain: string
  score: number
  grade: string
  assessment_json: string
  created_at: string
}>

// Deliberately loose but bounded: refs are opaque identifiers generated by
// our own systems (pipelineRef, sourceRef), not free-text user input.
const SAFE_REF_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.:/=#-]{0,240}$/
const REPORT_TOKEN_PATTERN = /^[A-Za-z0-9_]{4,80}$/
// Bounded hostname shape (no scheme, no path, no port). The scanner already
// normalizes/validates the target before producing a report; this is a
// defense-in-depth re-check at the storage boundary.
const DOMAIN_PATTERN =
  /^(?!-)[a-z0-9-]{1,63}(?<!-)(\.(?!-)[a-z0-9-]{1,63}(?<!-))+$/i

const assertSafeRef = (field: string, value: string): void => {
  if (!SAFE_REF_PATTERN.test(value)) {
    throw new AgentReadinessPublicReportValidationError({
      reason: `${field} must be a bounded public-safe ref`,
    })
  }
}

const assertDomain = (value: string): void => {
  if (value.length > 253 || !DOMAIN_PATTERN.test(value)) {
    throw new AgentReadinessPublicReportValidationError({
      reason: 'domain must be a bounded hostname',
    })
  }
}

const assertReportToken = (value: string): void => {
  if (!REPORT_TOKEN_PATTERN.test(value)) {
    throw new AgentReadinessPublicReportValidationError({
      reason: 'reportToken must be a bounded token',
    })
  }
}

const decodeAssessment = (json: string): AgentReadinessFifteenStepAssessment =>
  S.decodeUnknownSync(AgentReadinessFifteenStepAssessmentSchema)(
    JSON.parse(json) as unknown,
  )

const projectionFromD1Row = (
  row: AgentReadinessPublicReportD1Row,
): AgentReadinessPublicReportProjection =>
  S.decodeUnknownSync(AgentReadinessPublicReportProjection)({
    schemaVersion: AGENT_READINESS_PUBLIC_REPORT_SCHEMA_VERSION,
    reportToken: row.report_token,
    domain: row.domain,
    score: row.score,
    grade: row.grade,
    createdAt: row.created_at,
    assessment: decodeAssessment(row.assessment_json),
  })

export const makeD1AgentReadinessPublicReportStore = (
  db: D1Database,
): AgentReadinessPublicReportStore => {
  const createPublicReport = async (
    input: AgentReadinessPublicReportCreateInput,
    runtime: AgentReadinessPublicReportRuntime = systemAgentReadinessPublicReportRuntime,
  ): Promise<AgentReadinessPublicReportCreateResult> => {
    assertSafeRef('pipelineRef', input.pipelineRef)
    assertSafeRef('sourceRef', input.sourceRef)
    assertDomain(input.domain)

    const nowIso = runtime.nowIso()
    let reportToken = runtime.makeToken()
    assertReportToken(reportToken)

    for (let attempt = 0; attempt < 5; attempt += 1) {
      try {
        await db
          .prepare(
            `INSERT INTO agent_readiness_public_reports (
              id,
              report_token,
              pipeline_ref,
              source_ref,
              domain,
              score,
              grade,
              assessment_json,
              click_count,
              last_clicked_at,
              created_at,
              updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, NULL, ?, ?)`,
          )
          .bind(
            compactRandomId('agent_readiness_public_report'),
            reportToken,
            input.pipelineRef,
            input.sourceRef,
            input.domain,
            input.assessment.overallScore,
            input.assessment.overallGrade,
            JSON.stringify(input.assessment),
            nowIso,
            nowIso,
          )
          .run()

        return {
          reportToken,
          receiptRef: `agent_readiness_report:${reportToken}`,
          domain: input.domain,
          score: input.assessment.overallScore,
          grade: input.assessment.overallGrade,
          createdAt: nowIso,
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        if (!message.toLowerCase().includes('unique')) {
          throw new AgentReadinessPublicReportValidationError({
            reason: `agent_readiness_public_report insert failed: ${message}`,
          })
        }
        // Token collision (astronomically unlikely with 122-bit tokens) —
        // mint a fresh token and retry rather than ever leaking a partial
        // write or reusing another prospect's URL.
        reportToken = runtime.makeToken()
        assertReportToken(reportToken)
      }
    }

    throw new AgentReadinessPublicReportValidationError({
      reason: 'could not mint a unique report token',
    })
  }

  const readPublicReportByToken = async (
    reportToken: string,
  ): Promise<AgentReadinessPublicReportProjection | null> => {
    if (!REPORT_TOKEN_PATTERN.test(reportToken)) return null
    const row = await db
      .prepare(
        `SELECT report_token, domain, score, grade, assessment_json, created_at
           FROM agent_readiness_public_reports
          WHERE report_token = ?`,
      )
      .bind(reportToken)
      .first<AgentReadinessPublicReportD1Row>()

    return row === null ? null : projectionFromD1Row(row)
  }

  const recordReportClick = async (
    reportToken: string,
    runtime: AgentReadinessPublicReportRuntime = systemAgentReadinessPublicReportRuntime,
  ): Promise<AgentReadinessPublicReportClickResult | null> => {
    if (!REPORT_TOKEN_PATTERN.test(reportToken)) return null
    const nowIso = runtime.nowIso()
    const result = await db
      .prepare(
        `UPDATE agent_readiness_public_reports
            SET click_count = click_count + 1,
                last_clicked_at = ?,
                updated_at = ?
          WHERE report_token = ?`,
      )
      .bind(nowIso, nowIso, reportToken)
      .run()

    if ((result.meta?.changes ?? 0) === 0) return null

    const row = await db
      .prepare(
        `SELECT source_ref, click_count
           FROM agent_readiness_public_reports
          WHERE report_token = ?`,
      )
      .bind(reportToken)
      .first<Readonly<{ source_ref: string; click_count: number }>>()

    return row === null
      ? null
      : { sourceRef: row.source_ref, clickCount: Number(row.click_count) }
  }

  return { createPublicReport, readPublicReportByToken, recordReportClick }
}
