// OB-5 (#8562): reply-to-conversation handoff link issuance.
//
// The Sarah spec (docs/fable/2026-07-07-sarah-sales-agent-spec.md §5) names an
// opaque `prospect_ref` as the continuity join key across web and email, bound
// to a `crm_contacts` row. This module is the LINK ISSUANCE side owned by this
// repo: mint an unguessable handoff token, bind it to a CRM contact (+
// optional opportunity + LG-6 sourceRef), and produce a URL into
// sarah.openagents.com carrying that token. The durable prospect-session
// machinery that reads/exchanges the token lives in the separate private
// `OpenAgentsInc/sarah` repo (S-1/S-3) and is out of scope here — see
// migrations/0311_crm_sarah_handoff_links.sql for the cross-repo boundary
// note.
//
// Mirrors the OB-3 `agent-readiness-public-report-store.ts` shape: unguessable
// token primary lookup, defensive bounded-ref validation at the storage
// boundary, and click tracking. Deliberately NOT part of the khala-sync
// Postgres mirror registry (same precedent as OB-3's report store).

import { coerceStoredBusinessSourceRef } from './business-source-attribution'
import { compactRandomId, currentIsoTimestamp } from './runtime-primitives'

export const CRM_SARAH_HANDOFF_DEFAULT_BASE_URL =
  'https://sarah.openagents.com' as const

// Bounded, opaque identifiers generated by our own systems (contactId,
// opportunityId, replyEventId are all `compactRandomId` refs elsewhere in the
// CRM domain) — not free-text user input.
const SAFE_REF_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.:/=#-]{0,240}$/
const HANDOFF_TOKEN_PATTERN = /^[A-Za-z0-9_]{4,80}$/

export class CrmSarahHandoffValidationError extends Error {
  constructor(reason: string) {
    super(reason)
    this.name = 'CrmSarahHandoffValidationError'
  }
}

const assertSafeRef = (field: string, value: string): void => {
  if (!SAFE_REF_PATTERN.test(value)) {
    throw new CrmSarahHandoffValidationError(
      `${field} must be a bounded public-safe ref`,
    )
  }
}

const assertHandoffToken = (value: string): void => {
  if (!HANDOFF_TOKEN_PATTERN.test(value)) {
    throw new CrmSarahHandoffValidationError(
      'handoffToken must be a bounded token',
    )
  }
}

export type CrmSarahHandoffLink = Readonly<{
  id: string
  handoffToken: string
  tenantRef: string
  contactId: string
  opportunityId: string | null
  sourceRef: string
  replyEventId: string | null
  clickCount: number
  lastClickedAt: string | null
  createdAt: string
  updatedAt: string
}>

export type CrmSarahHandoffIssueInput = Readonly<{
  tenantRef: string
  contactId: string
  opportunityId?: string | null
  sourceRef?: string | null
  replyEventId?: string | null
}>

export type CrmSarahHandoffIssueResult = Readonly<{
  handoffToken: string
  url: string
  receiptRef: string
  sourceRef: string
}>

export type CrmSarahHandoffClickResult = Readonly<{
  sourceRef: string
  contactId: string
  clickCount: number
}>

export type CrmSarahHandoffRuntime = Readonly<{
  makeToken: () => string
  nowIso: () => string
}>

export const systemCrmSarahHandoffRuntime: CrmSarahHandoffRuntime = {
  makeToken: () => compactRandomId('sh'),
  nowIso: currentIsoTimestamp,
}

/** Build the prospect-facing URL. `baseUrl` defaults to the production Sarah
 * app; callers may pass an env-configured base for staging/local. */
export const buildSarahHandoffUrl = (
  baseUrl: string,
  handoffToken: string,
): string => {
  const origin = baseUrl.trim().replace(/\/+$/u, '') || CRM_SARAH_HANDOFF_DEFAULT_BASE_URL
  return `${origin}/continue/${handoffToken}`
}

type CrmSarahHandoffD1Row = Readonly<{
  id: string
  handoff_token: string
  tenant_ref: string
  contact_id: string
  opportunity_id: string | null
  source_ref: string
  reply_event_id: string | null
  click_count: number
  last_clicked_at: string | null
  created_at: string
  updated_at: string
}>

const linkFromRow = (row: CrmSarahHandoffD1Row): CrmSarahHandoffLink => ({
  id: row.id,
  handoffToken: row.handoff_token,
  tenantRef: row.tenant_ref,
  contactId: row.contact_id,
  opportunityId: row.opportunity_id,
  sourceRef: row.source_ref,
  replyEventId: row.reply_event_id,
  clickCount: Number(row.click_count),
  lastClickedAt: row.last_clicked_at,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
})

export type CrmSarahHandoffStore = Readonly<{
  issueHandoffLink: (
    input: CrmSarahHandoffIssueInput,
    baseUrl?: string,
    runtime?: CrmSarahHandoffRuntime,
  ) => Promise<CrmSarahHandoffIssueResult>
  readHandoffLinkByToken: (
    handoffToken: string,
  ) => Promise<CrmSarahHandoffLink | null>
  recordHandoffClick: (
    handoffToken: string,
    runtime?: CrmSarahHandoffRuntime,
  ) => Promise<CrmSarahHandoffClickResult | null>
}>

export const makeD1CrmSarahHandoffStore = (
  db: D1Database,
): CrmSarahHandoffStore => {
  const issueHandoffLink = async (
    input: CrmSarahHandoffIssueInput,
    baseUrl: string = CRM_SARAH_HANDOFF_DEFAULT_BASE_URL,
    runtime: CrmSarahHandoffRuntime = systemCrmSarahHandoffRuntime,
  ): Promise<CrmSarahHandoffIssueResult> => {
    assertSafeRef('tenantRef', input.tenantRef)
    assertSafeRef('contactId', input.contactId)
    if (input.opportunityId != null) {
      assertSafeRef('opportunityId', input.opportunityId)
    }
    if (input.replyEventId != null) {
      assertSafeRef('replyEventId', input.replyEventId)
    }
    const sourceRef = coerceStoredBusinessSourceRef(input.sourceRef ?? null)

    const nowIso = runtime.nowIso()
    let handoffToken = runtime.makeToken()
    assertHandoffToken(handoffToken)

    for (let attempt = 0; attempt < 5; attempt += 1) {
      try {
        await db
          .prepare(
            `INSERT INTO crm_sarah_handoff_links (
              id,
              handoff_token,
              tenant_ref,
              contact_id,
              opportunity_id,
              source_ref,
              reply_event_id,
              click_count,
              last_clicked_at,
              created_at,
              updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, 0, NULL, ?, ?)`,
          )
          .bind(
            compactRandomId('crm_sarah_handoff'),
            handoffToken,
            input.tenantRef,
            input.contactId,
            input.opportunityId ?? null,
            sourceRef,
            input.replyEventId ?? null,
            nowIso,
            nowIso,
          )
          .run()

        return {
          handoffToken,
          url: buildSarahHandoffUrl(baseUrl, handoffToken),
          receiptRef: `crm_sarah_handoff:${handoffToken}`,
          sourceRef,
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        if (!message.toLowerCase().includes('unique')) {
          throw new CrmSarahHandoffValidationError(
            `crm_sarah_handoff_links insert failed: ${message}`,
          )
        }
        // Token collision (astronomically unlikely) — mint a fresh token and
        // retry rather than ever reusing another prospect's URL.
        handoffToken = runtime.makeToken()
        assertHandoffToken(handoffToken)
      }
    }

    throw new CrmSarahHandoffValidationError(
      'could not mint a unique handoff token',
    )
  }

  const readHandoffLinkByToken = async (
    handoffToken: string,
  ): Promise<CrmSarahHandoffLink | null> => {
    if (!HANDOFF_TOKEN_PATTERN.test(handoffToken)) return null
    const row = await db
      .prepare('SELECT * FROM crm_sarah_handoff_links WHERE handoff_token = ?')
      .bind(handoffToken)
      .first<CrmSarahHandoffD1Row>()

    return row === null ? null : linkFromRow(row)
  }

  const recordHandoffClick = async (
    handoffToken: string,
    runtime: CrmSarahHandoffRuntime = systemCrmSarahHandoffRuntime,
  ): Promise<CrmSarahHandoffClickResult | null> => {
    if (!HANDOFF_TOKEN_PATTERN.test(handoffToken)) return null
    const nowIso = runtime.nowIso()
    const result = await db
      .prepare(
        `UPDATE crm_sarah_handoff_links
            SET click_count = click_count + 1,
                last_clicked_at = ?,
                updated_at = ?
          WHERE handoff_token = ?`,
      )
      .bind(nowIso, nowIso, handoffToken)
      .run()

    if ((result.meta?.changes ?? 0) === 0) return null

    const row = await db
      .prepare(
        `SELECT source_ref, contact_id, click_count
           FROM crm_sarah_handoff_links
          WHERE handoff_token = ?`,
      )
      .bind(handoffToken)
      .first<Readonly<{ source_ref: string; contact_id: string; click_count: number }>>()

    return row === null
      ? null
      : {
          sourceRef: row.source_ref,
          contactId: row.contact_id,
          clickCount: Number(row.click_count),
        }
  }

  return { issueHandoffLink, readHandoffLinkByToken, recordHandoffClick }
}
