import { Effect } from 'effect'
import { describe, expect, test } from 'vitest'

import {
  ImageGenerationService,
  buildGeminiGenerateContentBody,
  buildImagenPredictBody,
  extractGeminiImages,
  extractImagenImages,
  normalizeGenerateImageRequest,
  systemImageGenerationRuntime,
} from './image-generation'

const onePixelPngBase64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII='

class MemoryR2Bucket {
  readonly objects = new Map<
    string,
    Readonly<{ body: Uint8Array; type: string }>
  >()

  put(
    key: string,
    value: string | ArrayBuffer | ArrayBufferView | ReadableStream | Blob,
    options?: R2PutOptions,
  ): Promise<R2Object> {
    const bytes =
      value instanceof Uint8Array
        ? value
        : typeof value === 'string'
          ? new TextEncoder().encode(value)
          : new Uint8Array(0)

    this.objects.set(key, {
      body: bytes,
      type:
        options?.httpMetadata instanceof Headers
          ? (options.httpMetadata.get('content-type') ??
            'application/octet-stream')
          : (options?.httpMetadata?.contentType ?? 'application/octet-stream'),
    })

    return Promise.resolve({ key } as R2Object)
  }
}

const successfulGeminiFetch: typeof fetch = async (request, init) => {
  expect(String(request)).toBe(
    'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent',
  )
  expect(init?.method).toBe('POST')
  expect((init?.headers as Record<string, string>)['x-goog-api-key']).toBe(
    'test-key',
  )

  return Response.json({
    candidates: [
      {
        content: {
          parts: [
            {
              inlineData: {
                data: onePixelPngBase64,
                mimeType: 'image/png',
              },
            },
          ],
        },
      },
    ],
  })
}

describe('image generation provider helpers', () => {
  test('wraps the Worker global fetch instead of storing the raw method', () => {
    expect(systemImageGenerationRuntime.fetch).not.toBe(fetch)
  })

  test('builds Gemini generateContent requests with prompt and references', async () => {
    const input = await Effect.runPromise(
      normalizeGenerateImageRequest({
        prompt: 'Create a dark command center.',
        referenceImages: [{ data: onePixelPngBase64, mimeType: 'image/png' }],
      }),
    )

    expect(buildGeminiGenerateContentBody(input)).toEqual({
      contents: [
        {
          parts: [
            { text: 'Create a dark command center.' },
            {
              inline_data: {
                data: onePixelPngBase64,
                mime_type: 'image/png',
              },
            },
          ],
        },
      ],
      generationConfig: {
        responseModalities: ['Image'],
      },
    })
  })

  test('builds Imagen predict requests with explicit count and shape', async () => {
    const input = await Effect.runPromise(
      normalizeGenerateImageRequest({
        aspectRatio: '16:9',
        count: 4,
        imageSize: '2K',
        model: 'imagen-4.0-generate-001',
        prompt: 'Robot holding a red skateboard',
        provider: 'google-imagen',
      }),
    )

    expect(buildImagenPredictBody(input)).toEqual({
      instances: [{ prompt: 'Robot holding a red skateboard' }],
      parameters: {
        aspectRatio: '16:9',
        imageSize: '2K',
        sampleCount: 4,
      },
    })
  })

  test('extracts Gemini and Imagen base64 image payloads defensively', () => {
    expect(
      extractGeminiImages({
        candidates: [
          {
            content: {
              parts: [
                { text: 'ok' },
                {
                  inlineData: {
                    data: onePixelPngBase64,
                    mimeType: 'image/png',
                  },
                },
              ],
            },
          },
        ],
      }),
    ).toEqual([{ data: onePixelPngBase64, mimeType: 'image/png' }])

    expect(
      extractImagenImages({
        predictions: [
          {
            image: {
              imageBytes: onePixelPngBase64,
              mimeType: 'image/png',
            },
          },
        ],
      }),
    ).toEqual([{ data: onePixelPngBase64, mimeType: 'image/png' }])
  })
})

describe('ImageGenerationService', () => {
  test('stores generated bytes and returns stable image metadata', async () => {
    const bucket = new MemoryR2Bucket()

    const result = await Effect.runPromise(
      Effect.gen(function* () {
        const service = yield* ImageGenerationService
        return yield* service.generate({
          prompt: 'Create a dark OpenAgents briefing room.',
        })
      }).pipe(
        Effect.provide(
          ImageGenerationService.layer(
            {
              ARTIFACTS: bucket as unknown as R2Bucket,
              GEMINI_API_KEY: 'test-key',
              appUrl: 'https://openagents.test',
            },
            {
              fetch: successfulGeminiFetch,
              makeImageId: () => 'generated_image_test',
              nowIso: () => '2026-06-04T12:00:00.000Z',
            },
          ),
        ),
      ),
    )

    expect(result.images).toHaveLength(1)
    expect(result.images[0]).toMatchObject({
      byteLength: 68,
      key: 'generated-images/users/2026-06-04/generated_image_test-0-gemini-2.5-flash-image.png',
      mimeType: 'image/png',
      model: 'gemini-2.5-flash-image',
      provider: 'google-gemini',
      url: 'https://openagents.test/api/images/generated-images%2Fusers%2F2026-06-04%2Fgenerated_image_test-0-gemini-2.5-flash-image.png',
    })
    expect(bucket.objects.size).toBe(1)
  })

  test('normalizes provider rate limits', async () => {
    const exit = await Effect.runPromiseExit(
      Effect.gen(function* () {
        const service = yield* ImageGenerationService
        return yield* service.generate({
          prompt: 'Create a dark OpenAgents briefing room.',
        })
      }).pipe(
        Effect.provide(
          ImageGenerationService.layer(
            {
              ARTIFACTS: new MemoryR2Bucket() as unknown as R2Bucket,
              GEMINI_API_KEY: 'test-key',
            },
            {
              fetch: async () =>
                Response.json({ error: 'limit' }, { status: 429 }),
              makeImageId: () => 'generated_image_test',
              nowIso: () => '2026-06-04T12:00:00.000Z',
            },
          ),
        ),
      ),
    )

    expect(exit._tag).toBe('Failure')
    if (exit._tag === 'Failure') {
      expect(String(exit.cause)).toContain('ProviderRateLimited')
    }
  })
})
