import { describe, expect, test } from 'vitest'

import { exactRoutePathManifest } from './index'

const approvedExactRoutePaths = [
  '/',
  '/api/public/home',
  '/api/khala/feedback',
  '/api/khala/tokens',
  '/api/operator/khala/feedback',
  '/api/operator/khala/trace-review',
  '/api/operator/rlm/traces',
  '/api/operator/khala/unsupported-requests',
  '/api/public/business-signup',
  '/api/public/business/funnel-dashboard',
  '/api/operator/business/affiliate-codes',
  '/api/operator/business/affiliate-attribution',
  '/api/public/business-intake-chat',
  '/api/public/tassadar-run-summary',
  '/api/public/training/public-distributed-run-scale',
  '/api/public/pylon/largest-decentralized-training-claim',
  '/api/public/activity-timeline',
  '/api/public/activity-timeline/stream',
  '/api/public/forum-activity',
  '/api/public/tassadar/compiled-module-marketplace',
  '/api/public/tassadar-replays/first-real-settlement',
  '/api/public/proof-replays',
  '/api/public/product-promises',
  '/api/public/free-tier-data-sharing',
  '/api/public/khala-code/plans',
  '/api/public/khala-code/download-counts',
  '/api/public/khala-code/outside-user-runs',
  '/api/public/khala-code/outside-user-runs/:receiptRef',
  '/api/operator/khala-code/trace-plugin-revenue-share-precedents',
  '/api/public/khala-code/trace-plugin-revenue-share-precedents/:receiptRef',
  '/api/operator/qa-swarm/first-engagements',
  '/api/public/qa-swarm/first-engagements/:receiptRef',
  '/api/public/revenue-loop/first-dollar-evidence/:bundleRef',
  '/api/public/product-promises/transitions',
  '/api/public/product-promises/api.hosted_gemini.v1/readiness',
  '/api/public/product-promises/audit',
  '/api/public/metrics/accepted-outcomes-per-kwh',
  '/api/public/energy/flexible-load-proof',
  '/api/public/reputation/verified-outcomes',
  '/api/public/gym/run-progress',
  '/api/public/gym/mutalisk-khala-delegation/runs',
  '/api/public/gym/leaderboard',
  '/api/public/khala/head-to-head',
  '/api/public/payments/contributor-accrual-bundle',
  '/api/public/training/full-pipeline-program',
  '/api/public/training/marathon-operations',
  '/api/public/training/model-ladder-rungs',
  '/api/public/training/public-gradient-windows',
  '/api/public/training/ablation-derisking-ledger',
  '/api/public/training/post-training-arc/instruct-sft-lane',
  '/api/public/training/post-training-arc/dpo-preference-workload',
  '/api/public/training/post-training-arc/vibe-test-rubric',
  '/api/public/models/tassadar-percepta-executor/architecture-receipts',
  '/api/public/models/tassadar-percepta-executor/cpu-transform-training-receipts',
  '/api/public/demand-provenance',
  '/api/public/markets/open-markets',
  '/api/public/markets/liquidity/skeleton',
  '/api/public/markets/risk/skeleton',
  '/api/public/marketplace/composed-products',
  '/api/public/marketplace/wasm-plugins',
  '/api/public/markets/signature-monetization/metering',
  '/api/public/pylon/multi-earning-node',
  '/api/mobile/workroom-approval-projection',
  '/api/public/omni/client-delivery-projection',
  '/api/mobile/voice-sessions/ingest',
  '/api/public/autopilot/composed-runs',
  '/api/public/autopilot/labor-products',
  '/api/public/business/coding-quick-win-pipeline',
  '/api/public/autopilot/self-serve-fanout',
  '/api/public/autopilot/marketplace-work-classes',
  '/api/public/customer-one-cohort',
  '/api/operator/gym/run-progress',
  '/api/operator/gym/mutalisk-khala-delegation/runs',
  '/api/operator/gym/mutalisk-khala-delegation/progress',
  '/api/operator/gym/mutalisk-khala-delegation/summary',
  '/api/operator/gym/leaderboard',
  '/api/operator/khala/head-to-head',
  '/api/gym/mirrorcode/runs',
  '/api/gym/mirrorcode/token-burn',
  '/api/gym/mirrorcode/backstop-burn',
  '/api/operator/gym/full-trace-archives',
  '/api/operator/customer-one-cohort/rows',
  '/api/operator/product-promises/transitions',
  '/api/operator/artanis/mind/smoke',
  '/api/operator/tassadar/replay',
  '/api/operator/buy-mode',
  '/api/operator/buy-mode/start',
  '/api/operator/buy-mode/stop',
  '/api/operator/buy-mode/dispatch',
  '/api/operator/buy-mode/eval',
  '/api/operator/buy-mode/results/settle',
  '/chat',
  '/discord',
  '/login/email',
  '/login/github',
  '/auth/github/write/start',
  '/auth/callback',
  '/auth/logout',
  '/logout',
  '/api/auth/session',
  '/api/auth/totals',
  '/api/mdk',
  '/api/admin/overview',
  '/api/admin/cf-browser-smoke',
  '/api/internal/khala-sync/db-smoke',
  // Khala Sync public tokens-served reconcile/repair (KS-6.3, #8304):
  // admin bearer only; proves projection == SUM(exact token_usage_events
  // rows) (invariant 8) and hosts the explicit audited repair/backfill.
  '/api/internal/khala-sync/public-counters/tokens-served/reconcile',
  // Khala Sync fleet-intent consumption (KS-3.2, #8292): admin bearer only;
  // bounded oldest-first pages of durable operator fleet intents for the
  // Pylon supervisor enforcement loop. (Approved here as a rebase-hygiene
  // fix: the route landed in the manifest without its approved-list entry.)
  '/api/internal/khala-sync/fleet-intents',
  // Khala Sync runtime control-intent dispatch-consumer seam (#8388): admin
  // bearer only; the Pylon-side runtime dispatch consumer polls durable
  // runtime.* control intents and resolves chat_message bodies through
  // these two routes.
  '/api/internal/khala-sync/runtime-intents',
  '/api/internal/khala-sync/chat-message',
  // Khala Sync hub internal surface (KS-4.2, #8295): admin bearer only;
  // per-scope KhalaSyncHubDO append / log / connect. Public /api/sync/*
  // catch-up/connect arrives with KS-4.3/4.4.
  '/api/internal/khala-sync/hub/append',
  '/api/internal/khala-sync/hub/log',
  '/api/internal/khala-sync/hub/connect',
  // Khala Sync access-changed revocation trigger (KS-7.1, #8305): admin
  // bearer only; broadcasts MustRefetch(access_changed) to a scope's hub.
  // (Approved here as a rebase-hygiene fix: the route landed in the
  // manifest without its approved-list entry.)
  '/api/internal/khala-sync/hub/access-changed',
  // Khala Sync push (KS-3.1, #8291): authenticated transactional mutator
  // execution.
  '/api/sync/push',
  // Khala Sync catch-up log (KS-4.3, #8296): authenticated offset-resumable
  // LogPage reads, hub-first with authoritative Postgres fallthrough.
  '/api/sync/log',
  // Khala Sync bootstrap (KS-4.4, #8297): authenticated consistent snapshot
  // pages + final stitch cursor.
  '/api/sync/bootstrap',
  // Khala Sync CVR diff pull (KS-7.2, #8306): authenticated recovery-path
  // read-set diff, flag-gated behind KHALA_SYNC_CVR=1 (404 when unset).
  // (Approved here as a rebase-hygiene fix: the route landed in the
  // manifest without its approved-list entry.)
  '/api/sync/cvr-pull',
  // Khala Sync live tail (KS-4.4, #8297): authenticated WebSocket upgrade
  // proxied to the per-scope KhalaSyncHubDO.
  '/api/sync/connect',
  '/api/stats/token-usage/events',
  '/api/stats/token-usage/aggregate',
  '/api/admin/inference-analytics',
  '/api/operator/fleet/status',
  '/api/operator/fleet/state',
  '/api/operator/pro/status',
  '/api/stats/token-usage/leaderboards',
  '/api/stats/token-usage/leaderboard-preference',
  '/api/auth/teams',
  '/api/autopilot/continuation-policy',
  '/api/autopilot/morning-report',
  '/api/public/pylon-stats',
  '/api/public/khala-tokens-served',
  '/api/public/khala-tokens-served/history',
  '/api/public/khala-tokens-served/model-mix',
  '/api/public/khala-tokens-served/demand-mix',
  '/api/public/khala-tokens-served/channel-mix',
  '/api/pylon/codex/turns',
  '/api/pylon/codex/local-usage',
  '/api/pylon/claude/turns',
  '/api/pylon/codex/event-chunks',
  '/api/pylon/codex/proof',
  '/api/pylon/codex/trace-status',
  '/api/public/pylon-capacity-funnel',
  '/api/public/pylon-capacity-funnel/history',
  '/api/public/site-referral-payouts',
  '/api/public/partner-payouts',
  '/api/public/relay-health',
  '/api/public/launch-dashboard',
  '/api/public/treasury/launch-status',
  '/api/operator/treasury/status',
  '/api/operator/treasury/funding-destination',
  '/api/operator/treasury/spark-funding-destination',
  '/api/operator/treasury/spark-funding-invoice',
  '/api/operator/treasury/transactions/reconcile',
  '/api/operator/treasury/recipient-report',
  '/api/operator/treasury/recipient-confirmations',
  '/api/operator/tips-buffer/status',
  '/api/operator/tips-buffer/funding-destination',
  '/api/operator/artanis/spend-decision',
  '/api/operator/treasury/payout',
  '/api/operator/tips-buffer/payout',
  '/api/public/artanis/report',
  '/api/public/artanis/activity',
  '/api/public/labor-earnings',
  '/api/public/labor-earnings/payout',
  '/api/public/artanis/labor-receipts',
  '/api/public/artanis/labor-green-readiness',
  '/api/public/artanis/admin-ticks',
  '/api/public/artanis/tick-streak',
  '/api/public/artanis/tassadar-distillation-dataset',
  '/api/public/artanis/responder-support',
  '/api/blueprint/program-registry',
  '/api/blueprint/program-runs',
  '/api/blueprint/action-submissions',
  '/api/blueprint/contributions',
  '/api/blueprint/contracts',
  '/api/blueprint/tassadar-modules',
  '/.well-known/openagents.json',
  '/AGENTS-CORE.md',
  '/AGENTS.md',
  '/HEARTBEAT.md',
  '/RULES.md',
  '/skill.json',
  '/lander2',
  '/lander3',
  '/lander4',
  '/lander5',
  '/business',
  '/business/agents.md',
  '/business-new',
  '/install.md',
  '/surfaces.md',
  '/pylon.md',
  '/sites.md',
  '/rules.md',
  '/heartbeat.md',
  '/agents-core.md',
  '/qa-runner.md',
  '/llms.txt',
  '/agents.md',
  '/ai.md',
  '/skill.md',
  '/openapi.json',
  '/api/openapi.json',
  '/api/omni/sdk-seed',
  '/api/developer/signature-packages/validate',
  '/api/public/adjutant/activity',
  '/api/public/proof/otec',
  '/api/github-write/connections',
  '/api/github-write/grants/resolve',
  '/api/admin/sync/notify',
  '/api/agents/register',
  '/api/admin/agents/reissue-token',
  '/api/keys/free',
  '/api/agents/me',
  '/v1/agent-definitions',
  '/v1/agent-definitions/webhooks/github',
  '/v1/agent-definitions/webhooks/github/completions',
  '/v1/agent-definitions/webhooks/slack',
  '/v1/agent-definitions/webhooks/forum',
  '/v1/agent-definitions/webhooks/forum/completions',
  '/api/agents/me/balance',
  '/api/agents/me/balance/preferences',
  '/api/agents/home',
  '/api/public/inference/privacy-receipts/:receiptRef',
  '/v1/inference/privacy/paid-privacy/purchases',
  '/v1/khala-code/plan',
  '/v1/khala-code/plans/purchases',
  '/v1/inference/privacy/confidential-compute/executions',
  '/v1/chat/completions',
  '/mpp/v1/chat/completions',
  '/v1/inference/acceptance-verdicts',
  '/v1/inference/acceptance-jobs/lease',
  '/v1/inference/acceptance-jobs/ack',
  '/v1/models',
  '/v1/quote',
  '/v1/gateway/readiness',
  '/v1/gateway/glm-fleet/readiness',
  '/v1/gateway/dispatch-failures',
  '/api/operator/inference/pylon-fabric/smoke',
  '/v1/fine_tuning/jobs',
  '/v1/sandboxes',
] as const

describe('Worker exact route manifest', () => {
  test('matches the approved exact route table order', () => {
    expect(exactRoutePathManifest).toEqual(approvedExactRoutePaths)
  })

  test('does not contain duplicate exact paths', () => {
    expect(new Set(exactRoutePathManifest).size).toBe(
      exactRoutePathManifest.length,
    )
  })
})
