included:
  - ios

excluded:
  - ios/build
  - ios/OpenAgentsCore/.build
  - ios/OpenAgentsTests
  - ios/OpenAgentsCore/Tests
  - packages/tricoder
  - docs

disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - todo

opt_in_rules: []

custom_rules:
  ban_print:
    name: "No print() in sources"
    regex: "\\bprint\\s*\\("
    message: "Use OpenAgentsLog or os.Logger instead of print()"
    severity: error
    excluded:
      - ios/OpenAgentsTests
      - ios/OpenAgentsCore/Tests

  acp_ban_jsonserialization_in_wire:
    name: "No JSONSerialization in ACP wire types"
    included:
      - ios/OpenAgentsCore/Sources/OpenAgentsCore/AgentClientProtocol
    regex: "\\bJSONSerialization\\b"
    message: "Avoid JSONSerialization in ACP wire types. Use Codable encoders/decoders."
    severity: error

  acp_codingkeys_hint:
    name: "ACP wire Codable should declare CodingKeys or custom encode/decode"
    included:
      - ios/OpenAgentsCore/Sources/OpenAgentsCore/AgentClientProtocol
    regex: "^\\s*(struct|enum)\\s+\\w+\\s*:\\s*[^\n]*\\bCodable\\b"
    message: "Wire types should declare CodingKeys or custom encode/decode (disable on line if intentionally omitted)."
    severity: warning

reporter: xcode
