[workspace]
members = [
    "crates/coderbench","crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
publish = false
edition = "2024"
rust-version = "1.97.1"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
