<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Services.Extism.Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message returned in response to a `AuditModulesRequest`.
 *
 * Generated from protobuf message <code>AuditModulesResponse</code>
 */
class AuditModulesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * each record contains the ID of the invalid Module which failed the audit, as well as the failure
     * report produced by the validation check (encoded in JSON)
     *
     * Generated from protobuf field <code>map<int64, bytes> invalid_module_report = 1;</code>
     */
    private $invalid_module_report;
    /**
     * Generated from protobuf field <code>.Pagination pagination = 2;</code>
     */
    protected $pagination = null;
    /**
     * the full count of results in the database (not the count of this message's
     * `modules`).
     *
     * Generated from protobuf field <code>uint64 total = 3;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>optional .Error error = 4;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $invalid_module_report
     *           each record contains the ID of the invalid Module which failed the audit, as well as the failure
     *           report produced by the validation check (encoded in JSON)
     *     @type \Services.Extism.Proto\Pagination $pagination
     *     @type int|string $total
     *           the full count of results in the database (not the count of this message's
     *           `modules`).
     *     @type \Services.Extism.Proto\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * each record contains the ID of the invalid Module which failed the audit, as well as the failure
     * report produced by the validation check (encoded in JSON)
     *
     * Generated from protobuf field <code>map<int64, bytes> invalid_module_report = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getInvalidModuleReport()
    {
        return $this->invalid_module_report;
    }

    /**
     * each record contains the ID of the invalid Module which failed the audit, as well as the failure
     * report produced by the validation check (encoded in JSON)
     *
     * Generated from protobuf field <code>map<int64, bytes> invalid_module_report = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setInvalidModuleReport($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT64, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->invalid_module_report = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Pagination pagination = 2;</code>
     * @return \Services.Extism.Proto\Pagination|null
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    public function hasPagination()
    {
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        unset($this->pagination);
    }

    /**
     * Generated from protobuf field <code>.Pagination pagination = 2;</code>
     * @param \Services.Extism.Proto\Pagination $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Services.Extism.Proto\Pagination::class);
        $this->pagination = $var;

        return $this;
    }

    /**
     * the full count of results in the database (not the count of this message's
     * `modules`).
     *
     * Generated from protobuf field <code>uint64 total = 3;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * the full count of results in the database (not the count of this message's
     * `modules`).
     *
     * Generated from protobuf field <code>uint64 total = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Error error = 4;</code>
     * @return \Services.Extism.Proto\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>optional .Error error = 4;</code>
     * @param \Services.Extism.Proto\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Services.Extism.Proto\Error::class);
        $this->error = $var;

        return $this;
    }

}

