/// <reference types="@cloudflare/workers-types" />

export {};

declare global {
  interface Env {
    Chat: DurableObjectNamespace;
    Sandbox?: DurableObjectNamespace;
    AI: Ai;
    AUTOPILOT_SKY_MODE?: string;
    AUTOPILOT_TOOL_POLICY?: string;
    AUTOPILOT_TOOL_CHOICE?: string;
    AUTOPILOT_TOOL_MAX_CALLS?: string;
    AUTOPILOT_TOOL_MAX_OUTBOUND_BYTES?: string;
    AUTOPILOT_TOOL_ADMIN_SECRET?: string;
    AUTOPILOT_EXECUTOR_KIND?: string;
    AUTOPILOT_TUNNEL_URL?: string;
    AUTOPILOT_TUNNEL_TOKEN?: string;
    AUTOPILOT_TUNNEL_TIMEOUT_MS?: string;
    AUTOPILOT_TUNNEL_ACCESS_CLIENT_ID?: string;
    AUTOPILOT_TUNNEL_ACCESS_CLIENT_SECRET?: string;
    CF_ACCESS_CLIENT_ID?: string;
    CF_ACCESS_CLIENT_SECRET?: string;
    AUTOPILOT_HTTP_ALLOWLIST?: string;
    AUTOPILOT_HTTP_MAX_BYTES?: string;
    AUTOPILOT_HTTP_TIMEOUT_MS?: string;
    AUTOPILOT_CODEX_SECRET?: string;
    AUTOPILOT_CODEX_CALLBACK_TIMEOUT_MS?: string;
    AUTOPILOT_CODEX_CORS_ORIGIN?: string;
    AUTOPILOT_EXTENSION_ALLOWLIST?: string;
    AUTOPILOT_EXTENSION_DEFAULTS?: string;
    AUTOPILOT_EXTENSION_CATALOG_URL?: string;
    AUTOPILOT_EXTENSION_CATALOG_JSON?: string;
    AUTOPILOT_EXTENSION_CATALOG_KEY?: string;
    AUTOPILOT_EXTENSION_ADMIN_SECRET?: string;
    AUTOPILOT_EXTENSION_KV?: KVNamespace;
    AUTOPILOT_EXTENSION_BUCKET?: R2Bucket;
  }
}
