import {
  BehaviorContractSchemaVersion,
  type BehaviorContractRegistryDocument,
} from "@openagentsinc/behavior-contracts"

export const openAgentsDesktopUxContractRegistry: BehaviorContractRegistryDocument = {
  schemaVersion: BehaviorContractSchemaVersion,
  version: "2026-07-10.7",
  contracts: [
    {
      contractId: "openagents_desktop.seam.codex_recent_history_projection.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "local Codex history",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "When local Codex history is available, opening OpenAgents Desktop shows every top-level Codex chat updated in the last 24 hours in newest-first order while excluding known child, sub-agent, and side sessions. Selecting a chat shows its basic metadata and bounded recent user and assistant messages; unavailable history stays an honest empty state.",
      authorityBoundary: "The local history adapter is read-only and only projects bounded metadata and conversational display text through the fixed Electron bridge. It grants no session resume, send, filesystem browsing, cloud sync, worker dispatch, or provider authority.",
      seam: { client: "apps/openagents-desktop/src/renderer/boot.ts", server: "apps/openagents-desktop/src/codex-history-worker.ts" },
      evidenceRefs: ["apps/openagents-desktop/src/codex-history.ts", "apps/openagents-desktop/src/codex-history-worker.ts"],
      oracles: [{ id: "codex_recent_history_projection.e2e", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/codex-history.e2e.test.ts", description: "Exercises the bounded rollout projection and oversized-thread first-content path." }],
      verification: "bun test apps/openagents-desktop/tests/codex-history.e2e.test.ts; runs in the normal desktop test sweep.",
    },
    {
      contractId: "openagents_desktop.chat.thread_first_content_under_50ms.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "thread loading performance",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Threads must always show their first bounded message content in less than 50 milliseconds, regardless of total rollout size. Large threads must be chunked; full-rollout parsing is forbidden on the selection path.",
      authorityBoundary: "The 50-millisecond budget covers local first-content projection after selection. It does not authorize loading unbounded history, exposing raw events, or moving filesystem work onto Electron's main process.",
      evidenceRefs: ["apps/openagents-desktop/src/codex-history.ts", "apps/openagents-desktop/src/codex-history-worker.ts"],
      oracles: [{ id: "oversized_rollout_first_content.performance", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/codex-history.e2e.test.ts", description: "Creates a 256 MiB sparse rollout and requires bounded first-content projection to finish under 50 ms." }],
      verification: "bun test apps/openagents-desktop/tests/codex-history.e2e.test.ts enforces the 50 ms wall-clock budget in the normal desktop test sweep.",
    },
    {
      contractId: "openagents_desktop.seam.runtime_gateway_closed_protocol.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "Desktop Runtime Gateway",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "The signed Desktop renderer reaches host runtime state through one versioned closed query/command/event protocol. Unknown requests fail schema decoding, unavailable commands never appear completed, lifecycle events are ordered and disposable, and the renderer never receives runtime credentials or a generic transport.",
      authorityBoundary: "Electron main owns the Runtime Gateway and validates the invoking top-level bundled renderer. The renderer receives bounded capability/lifecycle projections only; this contract grants no OpenAgents authentication, Khala Sync authority, provider credential, loopback URL, raw IPC channel, MessagePort, filesystem handle, process handle, or raw runtime event.",
      seam: { client: "apps/openagents-desktop/src/preload.cts", server: "apps/openagents-desktop/src/runtime-gateway.ts" },
      evidenceRefs: ["apps/openagents-desktop/src/runtime-gateway-contract.ts", "apps/openagents-desktop/tests/electron-boundary.test.ts"],
      oracles: [{ id: "runtime_gateway_closed_protocol.e2e", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/runtime-gateway.e2e.test.ts", description: "Round-trips schema-decoded renderer requests and proves truthful capability, unavailable command, lifecycle ordering, disposal, and rejection behavior." }],
      verification: "bun run --cwd apps/openagents-desktop verify runs the seam suite, mechanical boundary oracle, bundle, and real Electron bootstrap smoke.",
    },
    {
      contractId: "openagents_desktop.sync.host_owned_sqlite.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "Khala Sync local persistence",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop opens the shared Khala Sync SQLite store inside Electron main, persists one installation identity across restart, and closes it deterministically. Until OpenAgents sign-in lands, the gateway reports local persistence ready but network Sync unavailable.",
      authorityBoundary: "The renderer receives only bounded readiness. Database path and handle, installation identity refs, rows, mutation queue, and credentials remain host-only. The local database is a reconstructible cache/offline queue and never server authority.",
      evidenceRefs: ["apps/openagents-desktop/src/desktop-sync-host.ts", "apps/openagents-desktop/src/desktop-sync-store.ts", "packages/khala-sync-client/src/store-core.ts"],
      oracles: [{ id: "desktop_sync_host.lifecycle", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/tests/desktop-sync-host.test.ts", description: "Proves restart-stable identity, private permissions, idempotent close, bounded readiness projection, and reuse of the shared SQLite store." }],
      verification: "bun run --cwd apps/openagents-desktop verify runs the host lifecycle suite and real Electron gateway bootstrap.",
    },
    {
      contractId: "openagents_desktop.session.os_encrypted_custody.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "native OpenAgents session custody",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop keeps the native OpenAgents access token, refresh token, and server-derived owner ref in one versioned Electron safeStorage-encrypted record under its private userData root; recovered credentials remain unverified until the server accepts them.",
      authorityBoundary: "OS encryption and private disk custody do not verify the credential, authorize Khala Sync rows or commands, create a device_session, or expose any credential field to preload, renderer, Runtime Gateway, logs, receipts, or public errors.",
      evidenceRefs: ["apps/openagents-desktop/src/desktop-session-vault.ts", "docs/sol/issues/desktop-session-vault.md", "github:OpenAgentsInc/openagents#8661"],
      oracles: [{ id: "desktop_session_vault.os_encrypted_custody", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/tests/desktop-session-vault.test.ts", description: "Proves safeStorage encryption, private atomic persistence, encryption/backend refusal, malformed-record purge, bounded recovery, idempotent clear, and public-safe failures." }],
      verification: "The desktop-session-vault and Electron-boundary suites prove custody and renderer isolation; Desktop typecheck/build and behavior-contract validation gate the integration.",
    },
    {
      contractId: "openagents_desktop.session.recovered_validation_rotation.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "native OpenAgents session recovery",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop validates recovered native credentials through the existing OpenAgents native-session boundary, persists bounded OpenAuth rotation before readiness, purges denial or owner mismatch, and never equates verified session readiness with live Sync.",
      authorityBoundary: "Server verification establishes only a native OpenAgents session. It does not make Khala Sync live, authorize cached rows or commands, create a device_session, or expose owner or replacement token fields through the Runtime Gateway.",
      evidenceRefs: ["apps/openagents-desktop/src/desktop-session-recovery.ts", "docs/sol/issues/desktop-session-recovery.md", "github:OpenAgentsInc/openagents#8662"],
      oracles: [
        { id: "desktop_session_recovery.validation_rotation", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/tests/desktop-session-recovery.test.ts", description: "Proves exact native-session verification, rotation-before-ready, denial/owner-mismatch purge, transient retention, and tokenless results." },
        { id: "desktop_session_recovery.gateway_projection", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/runtime-gateway.e2e.test.ts", description: "Proves the renderer-facing Runtime Gateway projects only bounded verified readiness without owner or credential fields." },
      ],
      verification: "Desktop recovery, Runtime Gateway, and Electron-boundary suites plus typecheck/build enforce both sides of the host-only validation seam.",
    },
  ],
}
