import {
  BehaviorContractSchemaVersion,
  type BehaviorContractRegistryDocument,
} from "@openagentsinc/behavior-contracts"

export const openAgentsDesktopUxContractRegistry: BehaviorContractRegistryDocument = {
  schemaVersion: BehaviorContractSchemaVersion,
  version: "2026-07-10.11",
  contracts: [
    {
      contractId: "openagents_desktop.seam.codex_recent_history_projection.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "local Codex history",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "When local Codex history is available, opening OpenAgents Desktop shows every top-level Codex chat updated in the last 24 hours in newest-first order while excluding known child, sub-agent, and side sessions. Selecting a chat shows its basic metadata and bounded recent user and assistant messages; unavailable history stays an honest empty state.",
      authorityBoundary: "The local history adapter is read-only and only projects bounded metadata and conversational display text through the fixed Electron bridge. It grants no session resume, send, filesystem browsing, cloud sync, worker dispatch, or provider authority.",
      seam: { client: "apps/openagents-desktop/src/renderer/boot.ts", server: "apps/openagents-desktop/src/codex-history-worker.ts" },
      evidenceRefs: ["apps/openagents-desktop/src/codex-history.ts", "apps/openagents-desktop/src/codex-history-worker.ts"],
      oracles: [{ id: "codex_recent_history_projection.e2e", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/codex-history.e2e.test.ts", description: "Exercises the bounded rollout projection and oversized-thread first-content path." }],
      verification: "bun test apps/openagents-desktop/tests/codex-history.e2e.test.ts; runs in the normal desktop test sweep.",
    },
    {
      contractId: "openagents_desktop.chat.thread_first_content_under_50ms.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "thread loading performance",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Threads must always show their first bounded message content in less than 50 milliseconds, regardless of total rollout size. Large threads must be chunked; full-rollout parsing is forbidden on the selection path.",
      authorityBoundary: "The 50-millisecond budget covers local first-content projection after selection. It does not authorize loading unbounded history, exposing raw events, or moving filesystem work onto Electron's main process.",
      evidenceRefs: ["apps/openagents-desktop/src/codex-history.ts", "apps/openagents-desktop/src/codex-history-worker.ts"],
      oracles: [{ id: "oversized_rollout_first_content.performance", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/codex-history.e2e.test.ts", description: "Creates a 256 MiB sparse rollout and requires bounded first-content projection to finish under 50 ms." }],
      verification: "bun test apps/openagents-desktop/tests/codex-history.e2e.test.ts enforces the 50 ms wall-clock budget in the normal desktop test sweep.",
    },
    {
      contractId: "openagents_desktop.seam.runtime_gateway_closed_protocol.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "Desktop Runtime Gateway",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "The signed Desktop renderer reaches host runtime state through one versioned closed query/command/event protocol. Unknown requests fail schema decoding, unavailable commands never appear completed, lifecycle events are ordered and disposable, and the renderer never receives runtime credentials or a generic transport.",
      authorityBoundary: "Electron main owns the Runtime Gateway and validates the invoking top-level bundled renderer. The renderer may request bounded OpenAgents session entry/exit commands but receives only their typed outcome; it gets no credential, callback/authorize URL, Khala Sync authority, provider credential, raw IPC channel, MessagePort, filesystem handle, process handle, or raw runtime event.",
      seam: { client: "apps/openagents-desktop/src/preload.cts", server: "apps/openagents-desktop/src/runtime-gateway.ts" },
      evidenceRefs: ["apps/openagents-desktop/src/runtime-gateway-contract.ts", "apps/openagents-desktop/tests/electron-boundary.test.ts"],
      oracles: [{ id: "runtime_gateway_closed_protocol.e2e", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/runtime-gateway.e2e.test.ts", description: "Round-trips schema-decoded renderer requests and proves truthful capability, unavailable command, lifecycle ordering, disposal, and rejection behavior." }],
      verification: "bun run --cwd apps/openagents-desktop verify runs the seam suite, mechanical boundary oracle, bundle, and real Electron bootstrap smoke.",
    },
    {
      contractId: "openagents_desktop.sync.host_owned_sqlite.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "Khala Sync local persistence",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop opens the shared Khala Sync SQLite store inside Electron main, persists one installation identity across restart, and after native-session verification composes the shared HTTP/WebSocket session on exactly the server-derived owner's personal scope. Rotation is re-read host-side and the session closes before the store.",
      authorityBoundary: "The renderer receives only bounded phase and freshness. Owner refs, credentials, database path and handle, installation identity refs, rows, mutation queue, transport, and session remain host-only. The local database is a reconstructible cache/offline queue and never server authority; authenticated substrate is not an authoritative conversation projection.",
      evidenceRefs: ["apps/openagents-desktop/src/desktop-sync-host.ts", "apps/openagents-desktop/src/desktop-sync-store.ts", "packages/khala-sync-client/src/store-core.ts"],
      oracles: [{ id: "desktop_sync_host.lifecycle", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/tests/desktop-sync-host.test.ts", description: "Proves restart-stable identity, private permissions, personal-scope selection, dynamic token lookup, live/freshness transition, session-before-store close, and reuse of the shared SQLite store." }],
      verification: "bun run --cwd apps/openagents-desktop verify runs the host lifecycle suite and real Electron gateway bootstrap.",
    },
    {
      contractId: "openagents_desktop.sync.native_conversation_continuity.v1",
      state: "enforced",
      surface: "openagents-desktop-and-mobile-hosts",
      productArea: "authoritative cross-device conversation continuity",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "A Desktop-created canonical chat_thread and first chat_message can be confirmed on mobile, mobile can append one canonical follow-up, and both native hosts converge on identical public-safe refs, confirmed entity versions, thread cursor, and live phase, then reconstruct the same state after restart without duplicates.",
      authorityBoundary: "Only server-confirmed chat_thread/chat_message rows enter the bounded conversation projection. Owner identity, credentials, store/session/overlay/transport objects, optimistic bodies, provider runtime events, and assistant-role inference remain host-only or explicitly outside this contract; denial and sign-out remove the conversation capability.",
      evidenceRefs: ["packages/khala-sync-client/src/chat.ts", "packages/khala-sync-client/src/conversation.ts", "apps/openagents-desktop/src/desktop-sync-host.ts", "apps/openagents-mobile/src/sync/mobile-sync-host-core.ts", "docs/sol/issues/native-conversation-continuation.md", "github:OpenAgentsInc/openagents#8668"],
      oracles: [{ id: "native_conversation_continuation.e2e", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/native-conversation-continuation.e2e.test.ts", description: "Runs the real Desktop node:sqlite host and mobile Expo-SQLite host over the shared session/overlay protocol against a server-authoritative chat fake, then proves Desktop-to-mobile-to-Desktop convergence, exact versions/cursor, and restart reconstruction." }],
      verification: "The native conversation continuation e2e runs in the normal Desktop sweep; shared chat mutator/projection tests run in the khala-sync-client sweep and the collection package regression proves existing consumers use the same centralized mutators.",
    },
    {
      contractId: "openagents_desktop.session.os_encrypted_custody.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "native OpenAgents session custody",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop keeps the native OpenAgents access token, refresh token, and server-derived owner ref in one versioned Electron safeStorage-encrypted record under its private userData root; recovered credentials remain unverified until the server accepts them.",
      authorityBoundary: "OS encryption and private disk custody do not verify the credential, authorize Khala Sync rows or commands, create a device_session, or expose any credential field to preload, renderer, Runtime Gateway, logs, receipts, or public errors.",
      evidenceRefs: ["apps/openagents-desktop/src/desktop-session-vault.ts", "docs/sol/issues/desktop-session-vault.md", "github:OpenAgentsInc/openagents#8661"],
      oracles: [{ id: "desktop_session_vault.os_encrypted_custody", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/tests/desktop-session-vault.test.ts", description: "Proves safeStorage encryption, private atomic persistence, encryption/backend refusal, malformed-record purge, bounded recovery, idempotent clear, and public-safe failures." }],
      verification: "The desktop-session-vault and Electron-boundary suites prove custody and renderer isolation; Desktop typecheck/build and behavior-contract validation gate the integration.",
    },
    {
      contractId: "openagents_desktop.session.recovered_validation_rotation.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "native OpenAgents session recovery",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop validates recovered native credentials through the existing OpenAgents native-session boundary, persists bounded OpenAuth rotation before readiness, purges denial or owner mismatch, and never equates verified session readiness with live Sync.",
      authorityBoundary: "Server verification establishes only a native OpenAgents session. It does not make Khala Sync live, authorize cached rows or commands, create a device_session, or expose owner or replacement token fields through the Runtime Gateway.",
      evidenceRefs: ["apps/openagents-desktop/src/desktop-session-recovery.ts", "docs/sol/issues/desktop-session-recovery.md", "github:OpenAgentsInc/openagents#8662"],
      oracles: [
        { id: "desktop_session_recovery.validation_rotation", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/tests/desktop-session-recovery.test.ts", description: "Proves exact native-session verification, rotation-before-ready, denial/owner-mismatch purge, transient retention, and tokenless results." },
        { id: "desktop_session_recovery.gateway_projection", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/runtime-gateway.e2e.test.ts", description: "Proves the renderer-facing Runtime Gateway projects only bounded verified readiness without owner or credential fields." },
      ],
      verification: "Desktop recovery, Runtime Gateway, and Electron-boundary suites plus typecheck/build enforce both sides of the host-only validation seam.",
    },
    {
      contractId: "openagents_desktop.session.loopback_pkce_entry_exit.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "native OpenAgents session entry and exit",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop main binds a temporary literal-loopback listener, launches the exact public-client GitHub code + S256 request, validates callback state, verifies the server owner before encrypted custody, and revokes both credential classes before local sign-out.",
      authorityBoundary: "The Runtime Gateway accepts only argument-free session entry/exit commands and returns bounded completed/cancelled/unavailable phase. No callback, authorize URL, state, code, verifier, owner, access token, or refresh token enters preload, renderer, logs, receipts, or public errors; verified session is not live Sync.",
      evidenceRefs: ["apps/openagents-desktop/src/desktop-session-pkce.ts", "docs/sol/issues/desktop-session-pkce.md", "github:OpenAgentsInc/openagents#8664"],
      oracles: [
        { id: "desktop_session_pkce.loopback_entry_exit", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/tests/desktop-session-pkce.test.ts", description: "Proves literal-loopback lifecycle, callback state, public-safe response, exact authorize/exchange tuples, server owner verification, immediate rotation, timeout/cancel, and dual revocation before clear." },
        { id: "desktop_session_pkce.gateway_commands", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/runtime-gateway.e2e.test.ts", description: "Proves argument-free session commands round-trip through the closed Runtime Gateway and return only bounded phase outcomes." },
      ],
      verification: "Desktop PKCE, Runtime Gateway, and Electron-boundary suites plus typecheck/build enforce host composition without a live browser or GUI in tests.",
    },
    {
      contractId: "openagents_desktop.session.effect_native_controls.v1",
      state: "enforced",
      surface: "openagents-desktop",
      productArea: "native OpenAgents session UI",
      enforcementTier: "test-sweep",
      blockerRefs: [],
      source: { channel: "owner-codex-session", statedBy: "owner", statedOn: "2026-07-10" },
      statement: "Desktop Settings renders the exact bounded OpenAgents session phase and routes visible sign-in/sign-out controls through typed Effect Native intents to argument-free Runtime Gateway commands, with honest in-flight and unavailable states.",
      authorityBoundary: "The renderer sees only signed-out, unverified, session-ready, denied, unavailable, or local authenticating presentation state. It receives no callback/authorize URL, state, code, verifier, owner, token, storage handle, or live Sync authority.",
      evidenceRefs: ["apps/openagents-desktop/src/renderer/settings.ts", "docs/sol/issues/desktop-session-controls.md", "github:OpenAgentsInc/openagents#8665"],
      oracles: [
        { id: "desktop_session_controls.effect_native_intents", kind: "bun-test", mode: "unit", ref: "apps/openagents-desktop/src/renderer/settings.test.ts", description: "Drives the real Effect Native Settings view and intent registry through signed-out, authenticating, session-ready, sign-in, and sign-out states with a tokenless fake bridge." },
        { id: "desktop_session_controls.gateway_phase", kind: "bun-test", mode: "e2e", ref: "apps/openagents-desktop/tests/runtime-gateway.e2e.test.ts", description: "Proves bootstrap carries an explicit bounded session phase and session commands remain argument-free and single-flight." },
      ],
      verification: "Settings view/intent, Runtime Gateway, and Electron-boundary suites plus Desktop typecheck/build enforce the visible tokenless path without GUI automation.",
    },
  ],
}
