apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 556.0.0
    run.googleapis.com/creator: chris@openagents.com
    run.googleapis.com/lastModifier: chris@openagents.com
    run.googleapis.com/operation-id: 278047a2-904b-444c-9475-b514e9e8e0ba
  creationTimestamp: '2026-02-20T02:40:01.386533Z'
  generation: 8
  labels:
    cloud.googleapis.com/location: us-central1
    run.googleapis.com/lastUpdatedTime: '2026-02-20T20:43:14.361349Z'
  name: openagents-runtime-migrate
  namespace: '157437760789'
  resourceVersion: AAZLR39NK+8
  selfLink: /apis/run.googleapis.com/v1/namespaces/157437760789/jobs/openagents-runtime-migrate
  uid: 98481483-c4ba-405b-971a-5ff871c1f7cb
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 556.0.0
        run.googleapis.com/cloudsql-instances: openagentsgemini:us-central1:l402-aperture-db
        run.googleapis.com/execution-environment: gen2
      labels:
        client.knative.dev/nonce: leb_paj_fiw
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - args:
            - eval
            - OpenAgentsRuntime.Release.migrate_and_verify!()
            command:
            - bin/openagents_runtime
            env:
            - name: PHX_SERVER
              value: 'true'
            - name: PHX_HOST
              value: openagents-runtime
            - name: RELEASE_DISTRIBUTION
              value: none
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-runtime-database-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-runtime-secret-key-base
            - name: RUNTIME_SIGNATURE_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-runtime-signing-key
            image: us-central1-docker.pkg.dev/openagentsgemini/openagents-runtime/runtime:fix-khala-checkpoint-20260220144018
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
          maxRetries: 3
          serviceAccountName: 157437760789-compute@developer.gserviceaccount.com
          timeoutSeconds: '600'
status:
  conditions:
  - status: 'True'
    type: Ready
  executionCount: 9
  latestCreatedExecution:
    completionStatus: EXECUTION_SUCCEEDED
    completionTimestamp: '2026-02-20T20:45:10.184948Z'
    creationTimestamp: '2026-02-20T20:43:17.580813Z'
    name: openagents-runtime-migrate-7w9ww
  observedGeneration: 8
