apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 556.0.0
    run.googleapis.com/creator: chris@openagents.com
    run.googleapis.com/lastModifier: chris@openagents.com
    run.googleapis.com/operation-id: 9212a93c-0007-433a-88b2-99476403da5e
  creationTimestamp: '2026-02-16T20:48:19.993339Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1
    run.googleapis.com/lastUpdatedTime: '2026-02-16T20:48:19.993339Z'
  name: openagents-maintenance-down
  namespace: '157437760789'
  resourceVersion: AAZK9xjquqg
  selfLink: /apis/run.googleapis.com/v1/namespaces/157437760789/jobs/openagents-maintenance-down
  uid: 1430baf5-3bb6-4421-8d53-5567c7e129ac
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 556.0.0
        run.googleapis.com/cloudsql-instances: openagentsgemini:us-central1:l402-aperture-db
        run.googleapis.com/execution-environment: gen2
      labels:
        client.knative.dev/nonce: don_zeh_gik
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - args:
            - artisan
            - down
            - --secret=<redacted>
            - --retry=60
            - --render=errors.503
            command:
            - php
            env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: 'false'
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: /cloudsql/openagentsgemini:us-central1:l402-aperture-db
            - name: DB_DATABASE
              value: openagents_web
            - name: DB_USERNAME
              value: openagents_web
            - name: APP_MAINTENANCE_DRIVER
              value: cache
            - name: APP_MAINTENANCE_STORE
              value: database
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-web-app-key
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-web-db-password
            image: us-central1-docker.pkg.dev/openagentsgemini/openagents-web/laravel:72cae86ae
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
          maxRetries: 3
          serviceAccountName: 157437760789-compute@developer.gserviceaccount.com
          timeoutSeconds: '600'
status:
  conditions:
  - status: 'True'
    type: Ready
  executionCount: 1
  latestCreatedExecution:
    completionStatus: EXECUTION_SUCCEEDED
    completionTimestamp: '2026-02-16T20:49:54.877413Z'
    creationTimestamp: '2026-02-16T20:48:22.506264Z'
    name: openagents-maintenance-down-5l6kl
  observedGeneration: 1
