apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 556.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '100'
    run.googleapis.com/operation-id: aa87893f-3aa9-4f6d-9f19-0826d3c7d765
    run.googleapis.com/urls: '["https://openagents-web-157437760789.us-central1.run.app","https://openagents-web-ezxz4mgdsq-uc.a.run.app"]'
    serving.knative.dev/creator: chris@openagents.com
    serving.knative.dev/lastModifier: chris@openagents.com
  creationTimestamp: '2026-02-15T22:14:20.523383Z'
  generation: 97
  labels:
    cloud.googleapis.com/location: us-central1
  name: openagents-web
  namespace: '157437760789'
  resourceVersion: AAZLRpmh4GM
  selfLink: /apis/serving.knative.dev/v1/namespaces/157437760789/services/openagents-web
  uid: 1579b373-a2b9-49ee-b0c0-1b5f2acb7b0b
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 556.0.0
        run.googleapis.com/cloudsql-instances: openagentsgemini:us-central1:l402-aperture-db
        run.googleapis.com/network-interfaces: '[{"network":"oa-lightning","subnetwork":"oa-lightning-us-central1"}]'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/vpc-access-egress: private-ranges-only
      labels:
        client.knative.dev/nonce: dgqtzdcgvm
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 20
      containers:
      - env:
        - name: APP_ENV
          value: production
        - name: APP_DEBUG
          value: '0'
        - name: LOG_CHANNEL
          value: stderr
        - name: AI_DEFAULT
          value: ai_gateway
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: /cloudsql/openagentsgemini:us-central1:l402-aperture-db
        - name: DB_DATABASE
          value: openagents_web
        - name: DB_USERNAME
          value: openagents_web
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-app-key
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-db-password
        - name: WORKOS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-workos-client-id
        - name: WORKOS_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-workos-api-key
        - name: WORKOS_REDIRECT_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-workos-redirect-url
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-openrouter-api-key
        - name: CACHE_STORE
          value: redis
        - name: QUEUE_CONNECTION
          value: redis
        - name: SESSION_DRIVER
          value: redis
        - name: REDIS_HOST
          value: 10.163.121.75
        - name: REDIS_PORT
          value: '6379'
        - name: OA_SMOKE_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-smoke-secret
        - name: APP_MAINTENANCE_DRIVER
          value: cache
        - name: APP_MAINTENANCE_STORE
          value: database
        - name: APP_URL
          value: https://openagents.com
        - name: OA_ALLOW_LOCAL_TEST_AUTH
          value: 'true'
        - name: OA_LOCAL_TEST_AUTH_EMAILS
          value: maintenance-test@openagents.com
        - name: POSTHOG_DISABLED
          value: 'false'
        - name: ASSET_URL
          value: https://openagents.com
        - name: SESSION_DOMAIN
          value: .openagents.com
        - name: L402_ALLOWLIST_HOSTS
          value: sats4ai.com,l402.openagents.com
        - name: L402_CREDENTIAL_TTL_SECONDS
          value: '600'
        - name: L402_RESPONSE_MAX_BYTES
          value: '65536'
        - name: L402_RESPONSE_PREVIEW_BYTES
          value: '1024'
        - name: L402_PAYMENT_TIMEOUT_MS
          value: '12000'
        - name: L402_INVOICE_PAYER
          value: spark_wallet
        - name: L402_DEMO_SATS4AI_URL
          value: https://sats4ai.com/api/l402/text-generation
        - name: LND_REST_BASE_URL
        - name: LND_REST_TLS_VERIFY
          value: 'true'
        - name: AI_GATEWAY_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-ai-gateway-api-key
        - name: L402_ENFORCE_HOST_ALLOWLIST
          value: 'false'
        - name: SPARK_EXECUTOR_BASE_URL
          value: https://l402-wallet-executor-ezxz4mgdsq-uc.a.run.app
        - name: SPARK_EXECUTOR_TIMEOUT_MS
          value: '20000'
        - name: SPARK_EXECUTOR_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: l402-wallet-executor-auth-token
        - name: POSTHOG_HOST
          value: https://us.i.posthog.com
        - name: POSTHOG_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-web-posthog-api-key
        - name: OA_RUNTIME_ELIXIR_BASE_URL
          value: https://openagents-runtime-157437760789.us-central1.run.app
        - name: OA_RUNTIME_SIGNING_KEY_ID
          value: runtime-v1
        - name: OA_RUNTIME_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-runtime-signing-key
        - name: OA_SYNC_TOKEN_ISSUER
          value: https://openagents.com
        - name: OA_SYNC_TOKEN_AUDIENCE
          value: openagents-sync
        - name: OA_SYNC_TOKEN_KEY_ID
          value: sync-auth-v1
        - name: OA_SYNC_TOKEN_CLAIMS_VERSION
          value: oa_sync_claims_v1
        - name: OA_SYNC_TOKEN_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-runtime-signing-key
        - name: OA_KHALA_TOKEN_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openagents-runtime-signing-key
        image: us-central1-docker.pkg.dev/openagentsgemini/openagents-web/laravel:436a8deba
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 157437760789-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://openagents-web-ezxz4mgdsq-uc.a.run.app
  conditions:
  - lastTransitionTime: '2026-02-20T19:40:57.580643Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-02-20T19:40:49.910888Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-02-20T19:40:57.524944Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: openagents-web-00097-jr6
  latestReadyRevisionName: openagents-web-00097-jr6
  observedGeneration: 97
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: openagents-web-00097-jr6
  url: https://openagents-web-ezxz4mgdsq-uc.a.run.app
