apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: livekit-cert-manager
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: controller
  endpoints:
    - port: http-metrics
      interval: 30s
