apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: livekit-server
  namespace: livekit-system
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      app.kubernetes.io/name: livekit-server
      app.kubernetes.io/instance: livekit-server
