apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-server-keys
  namespace: livekit-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager
    kind: SecretStore
  target:
    name: livekit-server-keys
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: keys.yaml
      remoteRef:
        key: oa-livekit-prod-server-keys
        property: keys_yaml
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-redis-auth
  namespace: livekit-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager
    kind: SecretStore
  target:
    name: livekit-redis-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: host
      remoteRef:
        key: oa-livekit-prod-redis-auth
        property: host
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ca.crt
      remoteRef:
        key: oa-livekit-prod-redis-auth
        property: ca_cert
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
