apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - priority-class.yaml
  - secret-identity.yaml
  - sarah-agent-identity.yaml
  - external-secrets.yaml
  - sarah-agent-runtime.yaml
  - turn-certificate.yaml
  - signaling-certificate.yaml
  - disruption-budget.yaml
  - pod-monitoring.yaml
  - cert-manager-monitoring.yaml
  - certificate-issuer.yaml
