apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: livekit-server
  namespace: livekit-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: livekit-server
      app.kubernetes.io/instance: livekit-server
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      timeout: 10s
  targetLabels:
    metadata:
      - pod
      - node
