#!/bin/sh
# Print the commands a Coder release has, read from the commit it was built
# from: the `coder SUBCOMMAND` lines of `coder --help` (crates/coder-new/src/main.rs)
# and the in-app slash commands (crates/coder-new/src/slash.rs).
#
# The website names the published release in CODER_VERSION
# (crates/openagents-web/src/pages/download.rs) and keeps this list beside it
# in crates/openagents-web/src/coder_release_commands.txt. A test there fails
# when the site, its docs, or the chat answer bank tells people to run a Coder
# command the published release lacks. After publishing a release:
#
#   scripts/release/coder-commands.sh VERSION COMMIT \
#     > crates/openagents-web/src/coder_release_commands.txt
#
# and set CODER_VERSION to VERSION in the same change.
set -eu

[ $# -eq 2 ] || { echo "usage: $0 VERSION COMMIT" >&2; exit 2; }
version=$1
commit=$2
repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)
sha=$(git -C "$repo_root" rev-parse --verify "$commit^{commit}")
crate=$(git -C "$repo_root" show "$sha:crates/coder-new/Cargo.toml" | sed -n 's/^version = "\(.*\)"$/\1/p' | head -1)
[ "$crate" = "$version" ] || { echo "$sha builds coder $crate, not $version" >&2; exit 1; }

main=$(mktemp)
slash=$(mktemp)
trap 'rm -f "$main" "$slash"' EXIT
git -C "$repo_root" show "$sha:crates/coder-new/src/main.rs" >"$main"
git -C "$repo_root" show "$sha:crates/coder-new/src/slash.rs" >"$slash"

echo "# The commands in Coder $version, the release CODER_VERSION names."
echo "# Generated by scripts/release/coder-commands.sh; do not edit by hand."
echo "version $version"
echo "commit $sha"
python3 -I - "$main" "$slash" <<'EOF'
import re, sys
main = open(sys.argv[1]).read()
slash = open(sys.argv[2]).read()
subs = set()
# The help's usage lines: "  coder login            Sign in ...".
start = main.index("fn help()")
for line in main[start:].split("\n"):
    m = re.match(r"^\s*coder ([a-z][a-z-]*)\b", line)
    if m:
        subs.add(m.group(1))
    if line.startswith("Options:"):
        break
words = set()
start = slash.index("pub fn help()")
body = slash[start:slash.index("\n}\n", start)]
for m in re.finditer(r'(?:"|\\n)/([a-z][a-z-]*)', body):
    if m.group(1) != "demo":  # local development builds only
        words.add(m.group(1))
if not words:
    sys.exit("could not read the commands from this commit")
for sub in sorted(subs):
    print(f"coder {sub}")
for word in sorted(words):
    print(f"/{word}")
EOF
