#!/usr/bin/env python3
"""Write per-operation contract fixtures and their decode tests.

    python3 crates/boat/schema/fixtures.py

Rewrites `fixtures/spec/` (one file per operation in `operations.json`, from
the pinned `boat-v1.yaml`) and `tests/fixtures.rs`, which sends each fixture's
request through the SDK against a loopback server and decodes every success
body (the schema sample, each `oneOf` variant, each published example), every
failure body, and every redacted capture in `fixtures/observed/` for that
operation. It reads no credentials and makes no network call.

Ported from the private Coder repository's `crates/coder-box/schema/fixtures.py`
(c8821c72eb), with Box renamed to Boat.
"""
import hashlib
import json
import re
import subprocess
from pathlib import Path
from urllib.parse import urlencode

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "schema/boat-v1.yaml"
SPEC = yaml.safe_load(SPEC_PATH.read_text())
OUT = ROOT / "fixtures/spec"
OUT.mkdir(parents=True, exist_ok=True)
OPS = {o["operation_id"]: o for o in json.loads((ROOT / "schema/operations.json").read_text())}

# The SDK commit is the last commit that changed the generated client or the
# pinned schema, so regenerating the fixtures does not move it.
SDK_COMMIT = subprocess.run(
    ["git", "log", "-1", "--format=%H", "--", "src/api", "src/models",
     "schema/boat-v1.yaml", "schema/operations.json"],
    capture_output=True, text=True, check=True, cwd=ROOT,
).stdout.strip()
SOURCE = {
    "sdk_commit": SDK_COMMIT,
    "spec_path": "crates/boat/schema/boat-v1.yaml",
    "spec_version": SPEC["info"]["title"] + ", info.version " + str(SPEC["info"]["version"]),
    "spec_sha256": hashlib.sha256(SPEC_PATH.read_bytes()).hexdigest(),
    "operation_inventory": "crates/boat/schema/operations.json",
    "generator": "crates/boat/schema/fixtures.py",
    "note": "Derived from the pinned specification. No value here is a vendor response.",
}


def resolve(v):
    if "$ref" in v:
        parts = v["$ref"].split("/")
        return SPEC["components"][parts[-2]][parts[-1]]
    return v


def merged(schema):
    if "allOf" not in schema:
        return schema
    result = {"type": "object", "properties": {}, "required": []}
    for part in schema["allOf"]:
        part = merged(resolve(part))
        result["properties"].update(part.get("properties", {}))
        result["required"] += part.get("required", [])
    return result


def sample(schema, include_optional=False):
    schema = merged(resolve(schema))
    if "oneOf" in schema or "anyOf" in schema:
        return sample(schema.get("oneOf", schema.get("anyOf"))[0], include_optional)
    if "const" in schema:
        return schema["const"]
    if "enum" in schema:
        return next(v for v in schema["enum"] if v is not None)
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next(t for t in kind if t != "null")
    if kind == "object" or "properties" in schema:
        return {k: sample(v) for k, v in schema.get("properties", {}).items()
                if include_optional or k in schema.get("required", [])}
    if kind == "array":
        return []
    return {"string": "sample", "integer": 1, "boolean": True, "number": 1.0}.get(kind)


def ref_name(v):
    return v["$ref"].split("/")[-1] if "$ref" in v else None


def snake(name):
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    return re.sub(r"[^a-zA-Z0-9]+", "_", name).lower()


def pascal(name):
    return "".join(x[:1].upper() + x[1:] for x in re.split(r"[^a-zA-Z0-9]", name))


def error_body(status):
    body = sample(SPEC["components"]["schemas"]["ErrorEnvelope"], True)
    body.update({"ok": False, "type": "sandbox.error", "status": status, "code": "sample_error",
                 "message": "sample", "requestId": "req_sample"})
    body["error"] = {"code": "sample_error", "message": "sample", "status": status}
    return body


tests = [
    "// Generated by `schema/fixtures.py`: every operation's fixture request goes",
    "// through the SDK, and every success, failure and captured body decodes.",
    "mod support;",
    "use boat::models::*;",
]
index = []
for path, item in SPEC["paths"].items():
    for method, op in item.items():
        if method not in {"get", "post", "put", "patch", "delete"}:
            continue
        oid = op["operationId"]
        record = OPS[oid]
        params = []
        values, query, headers = {}, [], []
        target = "/api/v1" + path
        for p in item.get("parameters", []) + op.get("parameters", []):
            p = resolve(p)
            value = sample(p["schema"])
            values[p["name"]] = value
            text = str(value).lower() if isinstance(value, bool) else str(value)
            params.append({
                "name": p["name"], "in": p["in"], "required": bool(p.get("required")),
                "description": p.get("description"), "example_value": value,
            })
            if p["in"] == "path":
                target = target.replace("{" + p["name"] + "}", text)
            elif p["in"] == "query":
                query.append((p["name"], text))
            else:
                headers.append((p["name"], text))
        if query:
            target += "?" + urlencode(query)
        body_schema = None
        if "requestBody" in op:
            body_schema = op["requestBody"]["content"]["application/json"]["schema"]
            values["body"] = sample(body_schema, True)
        responses = {}
        failures = []
        success = None
        for status, response in op["responses"].items():
            response_ref = ref_name(response)
            response = resolve(response)
            content = response.get("content", {}).get("application/json", {})
            entry = {
                "description": response.get("description"),
                "schema": ref_name(content.get("schema", {})) if content else None,
                "binary": bool(response.get("content")) and "application/json" not in response.get("content", {}),
                "published_examples": {n: e["value"] for n, e in content.get("examples", {}).items()},
            }
            if response_ref:
                entry["shared_response"] = response_ref
            responses[str(status)] = entry
            if str(status).startswith("2") and success is None:
                schema = content.get("schema")
                variants = None
                variant_samples = []
                if schema is not None:
                    resolved = merged(resolve(schema))
                    if "oneOf" in resolved or "anyOf" in resolved:
                        choices = resolved.get("oneOf", resolved.get("anyOf"))
                        variants = [ref_name(v) for v in choices]
                        variant_samples = [sample(v, True) for v in choices[1:]]
                success = {
                    "status": str(status),
                    "schema": entry["schema"],
                    "schema_variants": variants,
                    "binary": entry["binary"],
                    "published_examples": entry["published_examples"],
                    "schema_sample": None if schema is None else sample(schema, True),
                    "variant_samples": variant_samples,
                    "schema_sample_note": "Derived from the pinned schema with every field present. Not a vendor response.",
                }
            if not str(status).startswith("2") and str(status).isdigit():
                examples = list(entry["published_examples"].values())
                failures.append({
                    "status": str(status), "shared_response": response_ref,
                    "description": response.get("description"),
                    "body": examples[0] if examples else error_body(int(status)),
                    "body_source": "published example" if examples else "ErrorEnvelope sample",
                })
        fixture = {
            "operation_id": oid,
            "method": method.upper(),
            "path": path,
            "source": SOURCE,
            "sdk_method": record["rust_method"],
            "sdk_response_type": record["response"],
            "summary": op.get("summary"),
            "description": op.get("description"),
            "parameters": params,
            "request": {
                "target": target,
                "headers": {k: v for k, v in headers},
                "body_schema": ref_name(body_schema) if body_schema else None,
                "body": values.get("body"),
                "sdk_params_json": values or None,
            },
            "success": success,
            "responses": responses,
            "failure_cases": failures,
        }
        (OUT / f"{oid}.json").write_text(json.dumps(fixture, indent=2) + "\n")
        index.append({"operation_id": oid, "method": method.upper(), "path": path,
                      "published_response_examples": sum(len(r["published_examples"]) for r in responses.values())})

        name = record["rust_method"]
        args = "&params" if values else ""
        binary = record["response"] == "crate::Download"
        tests += ["#[tokio::test]", f"async fn {name}_fixture() {{", f'    let fixture = support::fixture("{oid}");']
        if values:
            tests.append(f"    let params: {pascal(oid)}Params = support::params(&fixture);")
        tests += ["    for case in support::bodies(&fixture) {",
                  "        let (client, job) = support::serve_fixture(case.status, &case.body).await;",
                  f"        let result = client.{name}({args}).await;",
                  "        support::check(&fixture, &case, result.map(|_| ()), job.await.expect(\"request\"));",
                  "    }", "}"]
(OUT / "index.json").write_text(json.dumps({"source": SOURCE, "operations": index}, indent=2) + "\n")
(ROOT / "tests/fixtures.rs").write_text("\n".join(tests) + "\n")
print(len(index), "operations")
