/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CodexTokenRouteImport } from './routes/codex-token'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as AppKbRouteImport } from './routes/_app/kb'
import { Route as AppHatcheryRouteImport } from './routes/_app/hatchery'
import { Route as AppAutopilotRouteImport } from './routes/_app/autopilot'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppKbIndexRouteImport } from './routes/_app/kb/index'
import { Route as AppKbSlugRouteImport } from './routes/_app/kb/$slug'
import { Route as AppChatChatIdRouteImport } from './routes/_app/chat.$chatId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexTokenRoute = CodexTokenRouteImport.update({
  id: '/codex-token',
  path: '/codex-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AppKbRoute = AppKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => AppRoute,
} as any)
const AppHatcheryRoute = AppHatcheryRouteImport.update({
  id: '/hatchery',
  path: '/hatchery',
  getParentRoute: () => AppRoute,
} as any)
const AppAutopilotRoute = AppAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppKbIndexRoute = AppKbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKbRoute,
} as any)
const AppKbSlugRoute = AppKbSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppKbRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/approvals': typeof ApprovalsRoute
  '/callback': typeof CallbackRoute
  '/chat': typeof ChatRoute
  '/codex-token': typeof CodexTokenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/assistant': typeof AppAssistantRoute
  '/autopilot': typeof AppAutopilotRoute
  '/hatchery': typeof AppHatcheryRoute
  '/kb': typeof AppKbRouteWithChildren
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/kb/$slug': typeof AppKbSlugRoute
  '/kb/': typeof AppKbIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/approvals': typeof ApprovalsRoute
  '/callback': typeof CallbackRoute
  '/chat': typeof ChatRoute
  '/codex-token': typeof CodexTokenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/assistant': typeof AppAssistantRoute
  '/autopilot': typeof AppAutopilotRoute
  '/hatchery': typeof AppHatcheryRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/kb/$slug': typeof AppKbSlugRoute
  '/kb': typeof AppKbIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/callback': typeof CallbackRoute
  '/chat': typeof ChatRoute
  '/codex-token': typeof CodexTokenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/autopilot': typeof AppAutopilotRoute
  '/_app/hatchery': typeof AppHatcheryRoute
  '/_app/kb': typeof AppKbRouteWithChildren
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/kb/$slug': typeof AppKbSlugRoute
  '/_app/kb/': typeof AppKbIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/callback'
    | '/chat'
    | '/codex-token'
    | '/login'
    | '/setup'
    | '/signup'
    | '/admin'
    | '/assistant'
    | '/autopilot'
    | '/hatchery'
    | '/kb'
    | '/authenticated'
    | '/chat/$chatId'
    | '/kb/$slug'
    | '/kb/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/callback'
    | '/chat'
    | '/codex-token'
    | '/login'
    | '/setup'
    | '/signup'
    | '/admin'
    | '/assistant'
    | '/autopilot'
    | '/hatchery'
    | '/authenticated'
    | '/chat/$chatId'
    | '/kb/$slug'
    | '/kb'
  id:
    | '__root__'
    | '/_app'
    | '/_authenticated'
    | '/approvals'
    | '/callback'
    | '/chat'
    | '/codex-token'
    | '/login'
    | '/setup'
    | '/signup'
    | '/_app/admin'
    | '/_app/assistant'
    | '/_app/autopilot'
    | '/_app/hatchery'
    | '/_app/kb'
    | '/_authenticated/authenticated'
    | '/_app/'
    | '/_app/chat/$chatId'
    | '/_app/kb/$slug'
    | '/_app/kb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  CallbackRoute: typeof CallbackRoute
  ChatRoute: typeof ChatRoute
  CodexTokenRoute: typeof CodexTokenRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex-token': {
      id: '/codex-token'
      path: '/codex-token'
      fullPath: '/codex-token'
      preLoaderRoute: typeof CodexTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_app/kb': {
      id: '/_app/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof AppKbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hatchery': {
      id: '/_app/hatchery'
      path: '/hatchery'
      fullPath: '/hatchery'
      preLoaderRoute: typeof AppHatcheryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/autopilot': {
      id: '/_app/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AppAutopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kb/': {
      id: '/_app/kb/'
      path: '/'
      fullPath: '/kb/'
      preLoaderRoute: typeof AppKbIndexRouteImport
      parentRoute: typeof AppKbRoute
    }
    '/_app/kb/$slug': {
      id: '/_app/kb/$slug'
      path: '/$slug'
      fullPath: '/kb/$slug'
      preLoaderRoute: typeof AppKbSlugRouteImport
      parentRoute: typeof AppKbRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppKbRouteChildren {
  AppKbSlugRoute: typeof AppKbSlugRoute
  AppKbIndexRoute: typeof AppKbIndexRoute
}

const AppKbRouteChildren: AppKbRouteChildren = {
  AppKbSlugRoute: AppKbSlugRoute,
  AppKbIndexRoute: AppKbIndexRoute,
}

const AppKbRouteWithChildren = AppKbRoute._addFileChildren(AppKbRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAutopilotRoute: typeof AppAutopilotRoute
  AppHatcheryRoute: typeof AppHatcheryRoute
  AppKbRoute: typeof AppKbRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChatChatIdRoute: typeof AppChatChatIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAutopilotRoute: AppAutopilotRoute,
  AppHatcheryRoute: AppHatcheryRoute,
  AppKbRoute: AppKbRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChatChatIdRoute: AppChatChatIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  CallbackRoute: CallbackRoute,
  ChatRoute: ChatRoute,
  CodexTokenRoute: CodexTokenRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
