import {
  IdeLanguageProviderStartSchema,
  IdeLanguageRequestRefSchema,
  IdeLanguageRequestSchema,
  IdeLanguageResultRefSchema,
  IdeLanguageResultSchema,
  type IdeLanguageCapability,
  type IdeLanguageItem,
  type IdeLanguageRequest,
  type IdeLanguageResult,
  type IdeLanguageResultState,
} from "./language-contract.ts";
import {
  IdeAttachmentGenerationSchema,
  IdeAttachmentRefSchema,
  IdeFileRefSchema,
  IdeLanguageGenerationSchema,
  IdeLanguageServiceRefSchema,
  IdePlacementRefSchema,
  IdeProjectRefSchema,
  IdeRootRefSchema,
  IdeServiceGenerationSchema,
  IdeWorktreeRefSchema,
} from "./project-contract.ts";
import { IdeLanguageStartRefSchema } from "./language-contract.ts";
import {
  IdeDocumentGeneration,
  IdeMonacoModelVersion,
  makeIdeDocumentRef,
} from "./monaco-document-contract.ts";

export const ideLanguageProviderFixture = () => IdeLanguageProviderStartSchema.make({
  executable: "typescript/lib/tsserverlibrary",
  providerVersion: "6.0.3",
  capabilities: [
    "diagnostics", "completion", "completion_resolve", "hover", "definition",
    "declaration", "type_definition", "references", "document_symbols",
    "workspace_symbols", "rename_preview", "format_document", "format_range",
    "code_actions", "semantic_tokens", "inlay_hints", "folding_ranges",
  ].map(capability => ({ capability: capability as IdeLanguageCapability, available: true, reason: null })),
});

export const makeIdeLanguageRequestFixture = (
  suffix = "fixture",
  capability: IdeLanguageCapability = "diagnostics",
): IdeLanguageRequest => IdeLanguageRequestSchema.make({
  schemaVersion: "openagents.desktop.ide-language-request.v1",
  grantRef: `workspace.grant.${suffix}`,
  requestRef: IdeLanguageRequestRefSchema.make(`ide.language-request.${suffix}.${capability}`),
  capability,
  projectRef: IdeProjectRefSchema.make(`ide.project.${suffix}`),
  rootRef: IdeRootRefSchema.make(`ide.root.${suffix}`),
  worktreeRef: IdeWorktreeRefSchema.make(`ide.worktree.${suffix}`),
  attachmentRef: IdeAttachmentRefSchema.make(`ide.attachment.${suffix}`),
  attachmentGeneration: IdeAttachmentGenerationSchema.make(1),
  languageGeneration: IdeLanguageGenerationSchema.make(1),
  documentRef: makeIdeDocumentRef(`workspace.grant.${suffix}`, 1),
  fileRef: IdeFileRefSchema.make(`ide.file.${suffix}`),
  pathRef: "src/index.ts",
  documentGeneration: IdeDocumentGeneration.make(1),
  documentVersion: IdeMonacoModelVersion.make(1),
  expectedServiceGeneration: null,
  requestedAt: "2026-07-19T00:00:00.000Z",
  language: "typescript",
  content: "export const answer: number = 42;\n",
  position: { line: 1, column: 14, offset: 13 },
  range: { start: { line: 1, column: 14, offset: 13 }, end: { line: 1, column: 20, offset: 19 } },
  query: null,
  limit: 1_000,
  timeoutMs: 1_000,
});

export const makeIdeLanguageResultFixture = (
  request: IdeLanguageRequest = makeIdeLanguageRequestFixture(),
  items: ReadonlyArray<IdeLanguageItem> = [],
  state: IdeLanguageResultState = { _tag: "Complete" },
): IdeLanguageResult => IdeLanguageResultSchema.make({
  schemaVersion: "openagents.desktop.ide-language-result.v1",
  resultRef: IdeLanguageResultRefSchema.make(`ide.language-result.${String(request.requestRef).replace("ide.language-request.", "")}`),
  requestRef: request.requestRef,
  capability: request.capability,
  projectRef: request.projectRef,
  rootRef: request.rootRef,
  worktreeRef: request.worktreeRef,
  attachmentRef: request.attachmentRef,
  attachmentGeneration: request.attachmentGeneration,
  languageGeneration: request.languageGeneration,
  documentRef: request.documentRef,
  fileRef: request.fileRef,
  pathRef: request.pathRef,
  documentGeneration: request.documentGeneration,
  documentVersion: request.documentVersion,
  serviceRef: IdeLanguageServiceRefSchema.make("ide.language-service.typescript"),
  serviceGeneration: IdeServiceGenerationSchema.make(1),
  startRef: IdeLanguageStartRefSchema.make("ide.language-start.1.0"),
  placementRef: IdePlacementRefSchema.make("ide.placement.project-local"),
  evidenceTier: "project_local",
  executable: "typescript/lib/tsserverlibrary",
  providerVersion: "6.0.3",
  requestedAt: request.requestedAt,
  observedAt: "2026-07-19T00:00:00.010Z",
  freshnessMs: 10,
  state,
  items,
  excerpt: request.content,
  capabilities: ideLanguageProviderFixture().capabilities,
});
