import {
  IdeRepositoryGenerationSchema,
  IdeRepositoryRefSchema,
  IdeSourceControlBindingSchema,
  IdeSourceControlConfigGenerationSchema,
  IdeSourceControlCredentialHelperGenerationSchema,
  IdeSourceControlDiffRefSchema,
  IdeSourceControlRefGenerationSchema,
  IdeSourceControlRemoteGenerationSchema,
  IdeSourceControlSnapshotSchema,
  type IdeSourceControlSnapshot,
} from "./source-control-contract.ts";
import {
  IdeAttachmentGenerationSchema,
  IdeProjectRefSchema,
  IdeRootRefSchema,
  IdeWorktreeRefSchema,
} from "./project-contract.ts";

export const ideSourceControlFixtureBinding = () => IdeSourceControlBindingSchema.make({
  projectRef: IdeProjectRefSchema.make("ide.project.fixture"),
  rootRef: IdeRootRefSchema.make("ide.root.fixture"),
  worktreeRef: IdeWorktreeRefSchema.make("ide.worktree.fixture"),
  attachmentGeneration: IdeAttachmentGenerationSchema.make(1),
  repositoryRef: IdeRepositoryRefSchema.make("ide.repository.fixture"),
});

export const ideSourceControlFixtureSnapshot = (
  repositoryGeneration = 1,
): IdeSourceControlSnapshot => IdeSourceControlSnapshotSchema.make({
  schemaVersion: "openagents.desktop.ide-source-control.v1",
  binding: ideSourceControlFixtureBinding(),
  version: {
    repositoryGeneration: IdeRepositoryGenerationSchema.make(repositoryGeneration),
    statusRef: `status-${repositoryGeneration}`,
    headOid: "1111111111111111111111111111111111111111",
    indexOid: `index-${repositoryGeneration}`,
    worktreeOid: `worktree-${repositoryGeneration}`,
    refGeneration: IdeSourceControlRefGenerationSchema.make(1),
    configGeneration: IdeSourceControlConfigGenerationSchema.make(1),
    remoteGeneration: IdeSourceControlRemoteGenerationSchema.make(1),
    credentialHelperGeneration: IdeSourceControlCredentialHelperGenerationSchema.make(1),
  },
  branch: "main",
  upstream: "origin/main",
  detached: false,
  ahead: 0,
  behind: 0,
  operation: { _tag: "Idle" },
  paths: [{
    path: "src/a.ts",
    priorPath: null,
    indexState: "unmodified",
    worktreeState: "modified",
    baseOid: "1111111111111111111111111111111111111111",
    indexOid: "1111111111111111111111111111111111111111",
    worktreeOid: `content-${repositoryGeneration}`,
    modeBefore: "100644",
    modeAfter: "100644",
    conflict: null,
    secretWithheld: false,
    ignored: false,
    binary: false,
    truncated: false,
    stagedDiffRef: null,
    unstagedDiffRef: IdeSourceControlDiffRefSchema.make(`ide.scm-diff.fixture-${repositoryGeneration}`),
  }],
  worktrees: [{
    worktreeRef: IdeWorktreeRefSchema.make("ide.worktree.fixture"),
    branch: "main",
    headOid: "1111111111111111111111111111111111111111",
    detached: false,
    locked: false,
    prunable: false,
    ownerRef: "owner.fixture",
    activeSessionRef: "session.fixture",
    removalPreviewRef: null,
    managed: false,
    dirty: false,
    changed: false,
    unpushed: false,
  }],
  delivery: [{
    phase: "changed",
    proven: true,
    evidenceRefs: [`status-${repositoryGeneration}`],
    observedAt: "2026-07-20T05:40:00.000Z",
    freshness: "current",
  }],
  omittedPathCount: 0,
  truncated: false,
  observedAt: "2026-07-20T05:40:00.000Z",
  stopped: false,
});
