//! Design tokens: the table in `oa-tokens` (shared with the native GUI
//! themes) generates the checked-in token stylesheets
//! `static/tokens-primitive.css`, `static/tokens-semantic.css` and
//! `static/tokens-components.css`.
//!
//! - [`apps_sdk`] holds Apps SDK UI's three token layers as written upstream.
//!   Their light values are **Coder Light**, unchanged.
//! - [`noir`] holds **Coder Noir**: the roles whose dark value it replaces.
//!   Every other dark value is Apps SDK UI's.
//! - [`product`] holds our own roles in the same naming scheme.
//!
//! Every theme-dependent value is `light-dark(<Coder Light>, <Coder Noir>)`,
//! resolved by `color-scheme`, which `data-theme="light|dark"` sets (see
//! `static/base.css`). With no `data-theme`, the system setting decides.
//!
//! Regenerate the CSS after editing a table:
//!
//! ```sh
//! OPENAGENTS_UI_BLESS=1 cargo test -p openagents-ui
//! ```
//!
//! Without the variable, a test fails when the checked-in files differ from
//! the table.

pub use oa_tokens::{
    Resolver, Rgba, Scheme, Section, ThemeChoice, all_tokens, apps_sdk, noir, product, themed_value,
};

pub use crate::css_lower::css_value;
use std::fmt::Write as _;

/// One generated token stylesheet.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TokenFile {
    Primitive,
    Semantic,
    Components,
}

impl TokenFile {
    pub const ALL: [TokenFile; 3] = [
        TokenFile::Primitive,
        TokenFile::Semantic,
        TokenFile::Components,
    ];

    /// Path relative to the crate root.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            TokenFile::Primitive => "static/tokens-primitive.css",
            TokenFile::Semantic => "static/tokens-semantic.css",
            TokenFile::Components => "static/tokens-components.css",
        }
    }

    fn sections(self) -> Vec<Section> {
        match self {
            TokenFile::Primitive => apps_sdk::PRIMITIVE.to_vec(),
            TokenFile::Semantic => apps_sdk::SEMANTIC.to_vec(),
            TokenFile::Components => {
                let mut all = apps_sdk::COMPONENTS.to_vec();
                all.extend_from_slice(product::COMPONENTS);
                all
            }
        }
    }

    /// The generated stylesheet text.
    #[must_use]
    pub fn css(self) -> String {
        let mut out = String::from(HEADER);
        out.push_str("@layer theme {\n  :root,\n  :where([data-theme]) {\n");
        let mut first = true;
        for section in self.sections() {
            if !first {
                out.push('\n');
            }
            first = false;
            let _ = writeln!(out, "    /* {} */", section.title);
            for (name, value) in section.tokens {
                let _ = writeln!(
                    out,
                    "    {name}: {};",
                    css_value(&themed_value(name, value))
                );
            }
        }
        out.push_str("  }\n");
        if self == TokenFile::Primitive {
            out.push_str(PRIMITIVE_THEME_SCALARS);
        }
        out.push_str("}\n");
        out
    }
}

const HEADER: &str = "/* Generated by openagents-ui from src/tokens (OPENAGENTS_UI_BLESS=1 cargo test -p openagents-ui). Do not edit.\n   Token values ported from Apps SDK UI (MIT, see crates/openagents-ui/NOTICE). */\n";

/// Primitive values that are not colors, so `light-dark()` cannot carry them:
/// shadow strength and the hairline. Upstream keys them off `data-theme`;
/// here the system setting also selects the dark set when no theme is chosen.
const PRIMITIVE_THEME_SCALARS: &str = r#"
  @media (resolution >= 150dpi), (resolution >= 1.5dppx) {
    :root,
    :where([data-theme]) {
      --hairline: 0.5px;
    }
  }

  :where(:root),
  :where([data-theme="light"]) {
    --shadow-alpha-100: 0.08;
    --shadow-alpha-200: 0.08;
    --shadow-alpha-300: 0.1;
    --shadow-alpha-400: 0.12;
    --shadow-hairline-width: 1px;
    --shadow-hairline-color: rgb(0 0 0 / 8%);
  }

  @media (resolution >= 150dpi), (resolution >= 1.5dppx) {
    :where(:root),
    :where([data-theme="light"]) {
      --shadow-hairline-width: 0.5px;
      --shadow-hairline-color: rgb(0 0 0 / 10%);
    }
  }

  @media (prefers-color-scheme: dark) {
    :where(:root:not([data-theme])) {
      --shadow-alpha-100: 0.2;
      --shadow-alpha-200: 0.2;
      --shadow-alpha-300: 0.36;
      --shadow-alpha-400: 0.3;
      --shadow-hairline-width: 1px;
      --shadow-hairline-color: rgb(255 255 255 / 10%);
    }
  }

  @media (prefers-color-scheme: dark) and ((resolution >= 150dpi) or (resolution >= 1.5dppx)) {
    :where(:root:not([data-theme])) {
      --shadow-hairline-width: 0.5px;
      --shadow-hairline-color: rgb(255 255 255 / 12%);
    }
  }

  :where([data-theme="dark"]) {
    --shadow-alpha-100: 0.2;
    --shadow-alpha-200: 0.2;
    --shadow-alpha-300: 0.36;
    --shadow-alpha-400: 0.3;
    --shadow-hairline-width: 1px;
    --shadow-hairline-color: rgb(255 255 255 / 10%);
  }

  @media (resolution >= 150dpi), (resolution >= 1.5dppx) {
    :where([data-theme="dark"]) {
      --shadow-hairline-width: 0.5px;
      --shadow-hairline-color: rgb(255 255 255 / 12%);
    }
  }

  :where([data-theme="dark"]) [data-surface="elevated"] {
    --shadow-hairline: 0 0 rgb(0 0 0 / 0%);
  }
"#;

#[cfg(test)]
mod tests;
