//! Design tokens: one Rust table that generates the checked-in token
//! stylesheets `static/tokens-primitive.css`, `static/tokens-semantic.css`
//! and `static/tokens-components.css`.
//!
//! - [`apps_sdk`] holds Apps SDK UI's three token layers as written upstream.
//!   Their light values are **Coder Light**, unchanged.
//! - [`noir`] holds **Coder Noir**: the roles whose dark value it replaces.
//!   Every other dark value is Apps SDK UI's.
//! - [`product`] holds our own roles in the same naming scheme.
//!
//! Every theme-dependent value is `light-dark(<Coder Light>, <Coder Noir>)`,
//! resolved by `color-scheme`, which `data-theme="light|dark"` sets (see
//! `static/base.css`). With no `data-theme`, the system setting decides.
//!
//! Regenerate the CSS after editing a table:
//!
//! ```sh
//! OPENAGENTS_UI_BLESS=1 cargo test -p openagents-ui
//! ```
//!
//! Without the variable, a test fails when the checked-in files differ from
//! the table.

pub mod apps_sdk;
pub mod noir;
pub mod product;

use std::collections::HashMap;

pub use crate::css_lower::css_value;
use crate::css_lower::{matching_paren, split_args};
use std::fmt::Write as _;

/// A titled group of `(name, value)` custom properties.
#[derive(Clone, Copy, Debug)]
pub struct Section {
    pub title: &'static str,
    pub tokens: &'static [(&'static str, &'static str)],
}

/// The two themes. `Light` is Coder Light, `Dark` is Coder Noir.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Scheme {
    Light,
    Dark,
}

/// One generated token stylesheet.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TokenFile {
    Primitive,
    Semantic,
    Components,
}

impl TokenFile {
    pub const ALL: [TokenFile; 3] = [
        TokenFile::Primitive,
        TokenFile::Semantic,
        TokenFile::Components,
    ];

    /// Path relative to the crate root.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            TokenFile::Primitive => "static/tokens-primitive.css",
            TokenFile::Semantic => "static/tokens-semantic.css",
            TokenFile::Components => "static/tokens-components.css",
        }
    }

    fn sections(self) -> Vec<Section> {
        match self {
            TokenFile::Primitive => apps_sdk::PRIMITIVE.to_vec(),
            TokenFile::Semantic => apps_sdk::SEMANTIC.to_vec(),
            TokenFile::Components => {
                let mut all = apps_sdk::COMPONENTS.to_vec();
                all.extend_from_slice(product::COMPONENTS);
                all
            }
        }
    }

    /// The generated stylesheet text.
    #[must_use]
    pub fn css(self) -> String {
        let mut out = String::from(HEADER);
        out.push_str("@layer theme {\n  :root,\n  :where([data-theme]) {\n");
        let mut first = true;
        for section in self.sections() {
            if !first {
                out.push('\n');
            }
            first = false;
            let _ = writeln!(out, "    /* {} */", section.title);
            for (name, value) in section.tokens {
                let _ = writeln!(
                    out,
                    "    {name}: {};",
                    css_value(&themed_value(name, value))
                );
            }
        }
        out.push_str("  }\n");
        if self == TokenFile::Primitive {
            out.push_str(PRIMITIVE_THEME_SCALARS);
        }
        out.push_str("}\n");
        out
    }
}

const HEADER: &str = "/* Generated by openagents-ui from src/tokens (OPENAGENTS_UI_BLESS=1 cargo test -p openagents-ui). Do not edit.\n   Token values ported from Apps SDK UI (MIT, see crates/openagents-ui/NOTICE). */\n";

/// Primitive values that are not colors, so `light-dark()` cannot carry them:
/// shadow strength and the hairline. Upstream keys them off `data-theme`;
/// here the system setting also selects the dark set when no theme is chosen.
const PRIMITIVE_THEME_SCALARS: &str = r#"
  @media (resolution >= 150dpi), (resolution >= 1.5dppx) {
    :root,
    :where([data-theme]) {
      --hairline: 0.5px;
    }
  }

  :where(:root),
  :where([data-theme="light"]) {
    --shadow-alpha-100: 0.08;
    --shadow-alpha-200: 0.08;
    --shadow-alpha-300: 0.1;
    --shadow-alpha-400: 0.12;
    --shadow-hairline-width: 1px;
    --shadow-hairline-color: rgb(0 0 0 / 8%);
  }

  @media (resolution >= 150dpi), (resolution >= 1.5dppx) {
    :where(:root),
    :where([data-theme="light"]) {
      --shadow-hairline-width: 0.5px;
      --shadow-hairline-color: rgb(0 0 0 / 10%);
    }
  }

  @media (prefers-color-scheme: dark) {
    :where(:root:not([data-theme])) {
      --shadow-alpha-100: 0.2;
      --shadow-alpha-200: 0.2;
      --shadow-alpha-300: 0.36;
      --shadow-alpha-400: 0.3;
      --shadow-hairline-width: 1px;
      --shadow-hairline-color: rgb(255 255 255 / 10%);
    }
  }

  @media (prefers-color-scheme: dark) and ((resolution >= 150dpi) or (resolution >= 1.5dppx)) {
    :where(:root:not([data-theme])) {
      --shadow-hairline-width: 0.5px;
      --shadow-hairline-color: rgb(255 255 255 / 12%);
    }
  }

  :where([data-theme="dark"]) {
    --shadow-alpha-100: 0.2;
    --shadow-alpha-200: 0.2;
    --shadow-alpha-300: 0.36;
    --shadow-alpha-400: 0.3;
    --shadow-hairline-width: 1px;
    --shadow-hairline-color: rgb(255 255 255 / 10%);
  }

  @media (resolution >= 150dpi), (resolution >= 1.5dppx) {
    :where([data-theme="dark"]) {
      --shadow-hairline-width: 0.5px;
      --shadow-hairline-color: rgb(255 255 255 / 12%);
    }
  }

  :where([data-theme="dark"]) [data-surface="elevated"] {
    --shadow-hairline: 0 0 rgb(0 0 0 / 0%);
  }
"#;

/// The token's value with Coder Noir's dark value applied, still in source
/// form (`alpha()`/`spacing()` not yet lowered).
#[must_use]
pub fn themed_value(name: &str, value: &str) -> String {
    let Some((_, noir)) = noir::OVERRIDES.iter().find(|(token, _)| *token == name) else {
        return value.to_string();
    };
    let light = match split_function(value, "light-dark") {
        Some(args) if args.len() == 2 => args[0].clone(),
        _ => value.to_string(),
    };
    format!("light-dark({light}, #{noir:06x})")
}

/// If `value` is exactly `name(...)`, its top-level arguments.
fn split_function(value: &str, name: &str) -> Option<Vec<String>> {
    let value = value.trim();
    let inner = value.strip_prefix(name)?.strip_prefix('(')?;
    if matching_paren(value, name.len())? != value.len() - 1 {
        return None;
    }
    Some(split_args(&inner[..inner.len() - 1]))
}

/// Every token name and its (Noir-applied, source-form) value, across all
/// three layers and the product roles.
#[must_use]
pub fn all_tokens() -> Vec<(&'static str, String)> {
    let mut out = Vec::new();
    for file in TokenFile::ALL {
        for section in file.sections() {
            for (name, value) in section.tokens {
                out.push((*name, themed_value(name, value)));
            }
        }
    }
    // Theme scalars defined outside the main block (light values).
    for (name, value) in [
        ("--shadow-hairline-width", "1px"),
        ("--shadow-hairline-color", "rgb(0 0 0 / 8%)"),
        ("--shadow-alpha-100", "0.08"),
        ("--shadow-alpha-200", "0.08"),
        ("--shadow-alpha-300", "0.1"),
        ("--shadow-alpha-400", "0.12"),
    ] {
        out.push((name, value.to_string()));
    }
    out
}

/// An sRGB color with alpha, channels in `0.0..=1.0`.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Rgba {
    pub r: f64,
    pub g: f64,
    pub b: f64,
    pub a: f64,
}

impl Rgba {
    #[must_use]
    pub fn opaque(rgb: u32) -> Self {
        Rgba {
            r: f64::from((rgb >> 16) & 0xff) / 255.0,
            g: f64::from((rgb >> 8) & 0xff) / 255.0,
            b: f64::from(rgb & 0xff) / 255.0,
            a: 1.0,
        }
    }

    /// This color drawn over `below`.
    #[must_use]
    pub fn over(self, below: Rgba) -> Rgba {
        let a = self.a + below.a * (1.0 - self.a);
        if a == 0.0 {
            return Rgba {
                r: 0.0,
                g: 0.0,
                b: 0.0,
                a: 0.0,
            };
        }
        let mix = |top: f64, bottom: f64| (top * self.a + bottom * below.a * (1.0 - self.a)) / a;
        Rgba {
            r: mix(self.r, below.r),
            g: mix(self.g, below.g),
            b: mix(self.b, below.b),
            a,
        }
    }

    /// WCAG relative luminance (alpha ignored).
    #[must_use]
    pub fn luminance(self) -> f64 {
        let channel = |value: f64| {
            if value <= 0.039_28 {
                value / 12.92
            } else {
                ((value + 0.055) / 1.055).powf(2.4)
            }
        };
        0.2126 * channel(self.r) + 0.7152 * channel(self.g) + 0.0722 * channel(self.b)
    }

    /// WCAG contrast ratio between two opaque colors.
    #[must_use]
    pub fn contrast(self, other: Rgba) -> f64 {
        let (a, b) = (self.luminance(), other.luminance());
        let (light, dark) = if a > b { (a, b) } else { (b, a) };
        (light + 0.05) / (dark + 0.05)
    }
}

/// Resolves token colors per theme, the way a browser would.
pub struct Resolver {
    tokens: HashMap<&'static str, String>,
}

impl Default for Resolver {
    fn default() -> Self {
        Self::new()
    }
}

impl Resolver {
    #[must_use]
    pub fn new() -> Self {
        Resolver {
            tokens: all_tokens().into_iter().collect(),
        }
    }

    /// Whether a token is defined.
    #[must_use]
    pub fn defines(&self, name: &str) -> bool {
        self.tokens.contains_key(name)
    }

    /// The color a token resolves to in `scheme`, if it is a color.
    #[must_use]
    pub fn color(&self, name: &str, scheme: Scheme) -> Option<Rgba> {
        self.eval(self.tokens.get(name)?, scheme, 0)
    }

    fn eval(&self, expr: &str, scheme: Scheme, depth: usize) -> Option<Rgba> {
        if depth > 32 {
            return None;
        }
        let expr = expr.trim();
        if let Some(hex) = expr.strip_prefix('#') {
            let hex = if hex.len() == 3 {
                hex.chars().flat_map(|c| [c, c]).collect()
            } else {
                hex.to_string()
            };
            return u32::from_str_radix(&hex, 16).ok().map(Rgba::opaque);
        }
        if expr == "transparent" {
            return Some(Rgba {
                r: 0.0,
                g: 0.0,
                b: 0.0,
                a: 0.0,
            });
        }
        if let Some(args) = split_function(expr, "light-dark") {
            let pick = if scheme == Scheme::Light { 0 } else { 1 };
            return self.eval(args.get(pick)?, scheme, depth + 1);
        }
        if let Some(args) = split_function(expr, "var") {
            let value = self.tokens.get(args[0].as_str())?;
            return self.eval(value, scheme, depth + 1);
        }
        if let Some(args) = split_function(expr, "alpha") {
            let base = self.eval(&args[0], scheme, depth + 1)?;
            let amount = args
                .get(1)?
                .trim()
                .trim_end_matches('%')
                .parse::<f64>()
                .ok()?
                / 100.0;
            return Some(Rgba {
                a: base.a * amount,
                ..base
            });
        }
        for name in ["rgb", "rgba"] {
            if let Some(args) = split_function(expr, name) {
                let inner = args.join(" ");
                let (channels, alpha) = match inner.split_once('/') {
                    Some((c, a)) => (c.to_string(), Some(a.trim().to_string())),
                    None => (inner.clone(), None),
                };
                let parts: Vec<f64> = channels
                    .split_whitespace()
                    .map(|p| p.parse::<f64>().ok())
                    .collect::<Option<_>>()?;
                if parts.len() != 3 {
                    return None;
                }
                let a = match alpha {
                    Some(a) if a.ends_with('%') => {
                        a.trim_end_matches('%').parse::<f64>().ok()? / 100.0
                    }
                    Some(a) => a.parse::<f64>().ok()?,
                    None => 1.0,
                };
                return Some(Rgba {
                    r: parts[0] / 255.0,
                    g: parts[1] / 255.0,
                    b: parts[2] / 255.0,
                    a,
                });
            }
        }
        None
    }
}

#[cfg(test)]
mod tests;
