#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;

use nip05_registrar::config::RESERVED_NAMES;
use nip05_registrar::routes::{AppState, router};
use nip05_registrar::store::{NostrJson, Store};
use serde_json::Value;
use tempfile::TempDir;
use tokio::net::TcpListener;
use tokio::task::JoinHandle;

const TOKEN: &str = "test-token-aaaa-bbbb-cccc-dddd";
const NPUB_FIATJAF: &str = "npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6";
const HEX_FIATJAF: &str = "3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d";
// Different valid npub (random-looking but well-formed). Generated by
// taking the example pubkey and flipping bytes to a known new value, then
// re-encoded by the test using the bech32 crate.
const HEX_OTHER: &str = "0000000000000000000000000000000000000000000000000000000000000001";

struct Harness {
    addr: SocketAddr,
    _tempdir: TempDir,
    data_file: PathBuf,
    handle: JoinHandle<()>,
}

impl Harness {
    fn url(&self, path: &str) -> String {
        format!("http://{}{}", self.addr, path)
    }
}

impl Drop for Harness {
    fn drop(&mut self) {
        self.handle.abort();
    }
}

async fn boot() -> Harness {
    let tempdir = TempDir::new().expect("tempdir");
    let data_file = tempdir.path().join("nostr.json");
    let reserved: BTreeSet<String> =
        RESERVED_NAMES.iter().map(|s| (*s).to_string()).collect();
    let store = Store::load(data_file.clone(), reserved).expect("store");
    let state = AppState {
        store: Arc::new(store),
        admin_token: Arc::new(TOKEN.to_string()),
    };
    let app = router(state);
    let listener = TcpListener::bind("127.0.0.1:0").await.expect("bind");
    let addr = listener.local_addr().expect("addr");
    let handle = tokio::spawn(async move {
        let _ = axum::serve(listener, app).await;
    });
    // Tiny yield so the server is ready when the first client request hits.
    tokio::task::yield_now().await;
    Harness {
        addr,
        _tempdir: tempdir,
        data_file,
        handle,
    }
}

fn other_npub() -> String {
    let bytes = hex::decode(HEX_OTHER).expect("hex");
    let arr: [u8; 32] = bytes.try_into().expect("32 bytes");
    let hrp = bech32::Hrp::parse("npub").expect("hrp");
    bech32::encode::<bech32::Bech32>(hrp, &arr).expect("encode")
}

#[tokio::test]
async fn get_nostr_json_returns_empty_initially() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .get(h.url("/.well-known/nostr.json"))
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let body: Value = resp.json().await.expect("json");
    assert!(body.get("names").unwrap().as_object().unwrap().is_empty());
}

#[tokio::test]
async fn cors_header_present_on_well_known() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .get(h.url("/.well-known/nostr.json"))
        .header("origin", "https://some-other-app.example")
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let cors = resp
        .headers()
        .get("access-control-allow-origin")
        .expect("cors header")
        .to_str()
        .unwrap()
        .to_string();
    assert_eq!(cors, "*");
}

#[tokio::test]
async fn post_claim_requires_bearer_token() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 401);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["error"], "unauthorized");
}

#[tokio::test]
async fn post_claim_rejects_wrong_bearer_token() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth("not-the-token")
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 401);
}

#[tokio::test]
async fn post_claim_succeeds_and_persists_to_disk() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 201);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["name"], "alice");
    assert_eq!(body["pubkey"], HEX_FIATJAF);

    // GET reflects the new claim
    let get_resp: Value = client
        .get(h.url("/.well-known/nostr.json"))
        .send()
        .await
        .expect("get")
        .json()
        .await
        .expect("json");
    assert_eq!(get_resp["names"]["alice"], HEX_FIATJAF);

    // Disk reflects the new claim too
    let disk = std::fs::read_to_string(&h.data_file).expect("read");
    let parsed: NostrJson = serde_json::from_str(&disk).expect("parse");
    assert_eq!(
        parsed.names.get("alice").map(String::as_str),
        Some(HEX_FIATJAF)
    );
}

#[tokio::test]
async fn post_claim_rejects_invalid_handle() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "Alice!", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 400);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["error"], "invalid_handle");
}

#[tokio::test]
async fn post_claim_rejects_reserved_handle() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "admin", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 400);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["error"], "reserved_handle");
}

#[tokio::test]
async fn post_claim_rejects_invalid_npub() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": "npub1totallyinvalid"}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 400);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["error"], "invalid_npub");
}

#[tokio::test]
async fn post_claim_rejects_duplicate_handle() {
    let h = boot().await;
    let client = reqwest::Client::new();
    // First claim succeeds.
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 201);
    // Second claim of the same name with a different valid pubkey conflicts.
    let other = other_npub();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": other}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 409);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["error"], "handle_taken");
}

#[tokio::test]
async fn post_claim_rejects_duplicate_pubkey() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 201);
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "bob", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 409);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["error"], "pubkey_taken");
}

#[tokio::test]
async fn post_claim_accepts_hex_pubkey_form() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "pubkey": HEX_FIATJAF}))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 201);
    let body: Value = resp.json().await.expect("json");
    assert_eq!(body["pubkey"], HEX_FIATJAF);
}

#[tokio::test]
async fn delete_claim_removes_entry_and_requires_auth() {
    let h = boot().await;
    let client = reqwest::Client::new();
    client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");

    // DELETE without auth is rejected.
    let resp = client
        .delete(h.url("/admin/claim/alice"))
        .send()
        .await
        .expect("delete");
    assert_eq!(resp.status(), 401);

    // DELETE with auth succeeds.
    let resp = client
        .delete(h.url("/admin/claim/alice"))
        .bearer_auth(TOKEN)
        .send()
        .await
        .expect("delete");
    assert_eq!(resp.status(), 204);

    // GET reflects the removal.
    let get_resp: Value = client
        .get(h.url("/.well-known/nostr.json"))
        .send()
        .await
        .expect("get")
        .json()
        .await
        .expect("json");
    assert!(get_resp["names"].as_object().unwrap().is_empty());

    // Disk reflects the removal.
    let disk = std::fs::read_to_string(&h.data_file).expect("read");
    let parsed: NostrJson = serde_json::from_str(&disk).expect("parse");
    assert!(parsed.names.is_empty());
}

#[tokio::test]
async fn delete_claim_returns_404_when_missing() {
    let h = boot().await;
    let client = reqwest::Client::new();
    let resp = client
        .delete(h.url("/admin/claim/ghost"))
        .bearer_auth(TOKEN)
        .send()
        .await
        .expect("delete");
    assert_eq!(resp.status(), 404);
}

#[tokio::test]
async fn get_nostr_json_filters_by_name_query() {
    let h = boot().await;
    let client = reqwest::Client::new();
    client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");

    let other = other_npub();
    client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "bob", "npub": other}))
        .send()
        .await
        .expect("post");

    let body: Value = client
        .get(h.url("/.well-known/nostr.json?name=alice"))
        .send()
        .await
        .expect("get")
        .json()
        .await
        .expect("json");
    let names = body["names"].as_object().unwrap();
    assert_eq!(names.len(), 1);
    assert_eq!(names["alice"], HEX_FIATJAF);
}

#[tokio::test]
async fn atomic_write_does_not_leave_tmp_file() {
    let h = boot().await;
    let client = reqwest::Client::new();
    client
        .post(h.url("/admin/claim"))
        .bearer_auth(TOKEN)
        .json(&serde_json::json!({"name": "alice", "npub": NPUB_FIATJAF}))
        .send()
        .await
        .expect("post");

    let parent = h.data_file.parent().unwrap();
    let entries: Vec<_> = std::fs::read_dir(parent)
        .unwrap()
        .filter_map(Result::ok)
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    assert!(
        entries.iter().any(|e| e == "nostr.json"),
        "expected nostr.json present, got {entries:?}"
    );
    assert!(
        !entries.iter().any(|e| e.ends_with(".tmp")),
        "tmp file leaked: {entries:?}"
    );
}
