//! The physics layer SRD spells act through.
//!
//! [`SpellWorld`] holds a `physics::World` of dynamic props beside the
//! chamber's kinematic characters, stepped on the chamber's 120 Hz clock and
//! saved with every checkpoint. It also holds the seeded [`dice::Dice`],
//! active [`fields::SpellField`] areas, spell-owned bodies and joints,
//! concentration, and a momentum [`physics::Ledger`] with one named term per
//! source of external momentum.
//!
//! To add a spell, write `spells/<name>.rs` with its cast function and its
//! playground scenario, then add one line to [`CATALOG`] (its action-bar
//! slot) and one line to `crate::playground::scenarios`.
pub mod black_tentacles;
pub mod command;
pub mod dice;
pub mod feather_fall;
pub mod fields;
pub mod gust;
#[cfg(test)]
mod integration_tests;
pub mod levitate;
pub mod meteor_swarm;
pub mod props;
pub mod proxies;
pub mod reverse_gravity;
pub mod scenarios;
pub mod telekinesis;
pub mod thunderwave;
mod validation;
pub mod wall_of_stone;
pub mod wind_wall;

use glam::{DQuat, DVec3};
use physics::{BodyId, Ledger, Momentum};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub use dice::{Dice, Save, fall_dice};
pub use fields::{Area, Fields, SpellField};
pub use props::{Material, Prop, PropKind, PropSpec, Size};

/// One foot, m. Spell distances are written in feet times this constant.
pub const FEET: f64 = 0.3048;
/// One round, s. "Until the end of your next turn" is one round after the cast.
pub const ROUND: f32 = 6.;
/// Gravity on props and spell bodies, m/s².
pub const GRAVITY: f64 = 9.81;
/// The player wizard's spell save DC.
pub const SPELL_SAVE_DC: i32 = 15;
/// Characters closer than their radius plus this gap exchange momentum, m.
pub const CONTACT_GAP: f64 = 0.05;
/// Restitution of character contacts.
pub const CONTACT_RESTITUTION: f64 = 0.1;
/// Upright capsule of every chamber character, m.
pub const CHARACTER_RADIUS: f64 = 0.35;
pub const CHARACTER_HEIGHT: f64 = 1.8;
/// Relative ledger residual the tests and evidence accept.
pub const LEDGER_TOLERANCE: f64 = 1e-9;
/// Prop collision identities start here, far above any scene actor ID.
pub const PROP_ENTITY_BASE: u64 = 1 << 32;
pub const MAX_PROPS: usize = 192;

/// A spell on the second action-bar row (hotkeys Shift+1 to Shift+0).
pub struct SpellDef {
    /// Row-two slot, 0 through 9; slot 0 is Shift+1 and slot 9 is Shift+0.
    pub slot: u8,
    /// Lowercase name, as on the `--spell-playground` command line.
    pub key: &'static str,
    pub label: &'static str,
    /// Atlas sprite, generated by the original UI atlas.
    pub icon: &'static str,
    pub description: &'static str,
    /// Chamber mana and cooldown: MMO tuning, not tabletop rules.
    pub cost: i32,
    pub cooldown: f32,
    /// Runs an admitted cast. The caster's facing is `game.yaw`.
    pub cast: fn(&mut crate::play::Game) -> Result<(), String>,
}

/// Row-two spells. Reserved slots, in issue order: 0 Telekinesis (#10452),
/// 1 Wall of Stone (#10453), 2 Levitate (#10454), 3 Feather Fall (#10455),
/// 4 Gust of Wind (#10456), 5 Wind Wall (#10457), 6 Black Tentacles
/// (#10458), 7 Meteor Swarm (#10459), 8 Reverse Gravity (#10460).
pub const CATALOG: &[SpellDef] = &[
    SpellDef {
        slot: 6,
        key: "black-tentacles",
        label: "Black Tentacles",
        icon: "black-tentacles-icon",
        description: "Articulated tentacles restrain creatures and grab props",
        cost: 5,
        cooldown: ROUND,
        cast: black_tentacles::cast,
    },
    SpellDef {
        slot: 8,
        key: "reverse-gravity",
        label: "Reverse Gravity",
        icon: "reverse-gravity-icon",
        description: "Invert gravity in a 100-foot-high cylinder",
        cost: 5,
        cooldown: ROUND,
        cast: reverse_gravity::cast,
    },
    SpellDef {
        slot: 7,
        key: "meteor-swarm",
        label: "Meteor Swarm",
        icon: "meteor-swarm-icon",
        description: "Four swept impacts with blast, fire, and object damage",
        cost: 10,
        cooldown: ROUND,
        cast: meteor_swarm::cast,
    },
    SpellDef {
        slot: 5,
        key: "wind-wall",
        label: "Wind Wall",
        icon: "wind-wall-icon",
        description: "Raise an updraft wall that deflects ordinary ammunition",
        cost: 5,
        cooldown: ROUND,
        cast: wind_wall::cast,
    },
    SpellDef {
        slot: 1,
        key: "wall-of-stone",
        label: "Wall of Stone",
        icon: "wall-of-stone-icon",
        description: "Raise supported breakable granite panels",
        cost: 5,
        cooldown: ROUND,
        cast: wall_of_stone::cast,
    },
    SpellDef {
        slot: 4,
        key: "gust-of-wind",
        label: "Gust of Wind",
        icon: "gust-of-wind-icon",
        description: "Blow a steerable Line of wind",
        cost: 5,
        cooldown: ROUND,
        cast: gust::cast,
    },
    SpellDef {
        slot: 0,
        key: "telekinesis",
        label: "Telekinesis",
        icon: "telekinesis-icon",
        description: "Grip a creature or prop; steer and release with momentum",
        cost: 5,
        cooldown: ROUND,
        cast: telekinesis::cast,
    },
    SpellDef {
        slot: 2,
        key: "levitate",
        label: "Levitate",
        icon: "levitate-icon",
        description: "Lift a creature or loose object; push off surfaces to move",
        cost: 5,
        cooldown: ROUND,
        cast: levitate::cast,
    },
    SpellDef {
        slot: 3,
        key: "feather-fall",
        label: "Feather Fall",
        icon: "feather-fall-icon",
        description: "Protect up to five visible falling creatures",
        cost: 5,
        cooldown: ROUND,
        cast: feather_fall::cast,
    },
];

pub fn spell_in_slot(slot: u8) -> Option<&'static SpellDef> {
    CATALOG.iter().find(|s| s.slot == slot)
}

/// Constitution modifiers from SRD stat blocks; the Cultist has CON 10.
pub fn constitution_modifier(model: &str) -> i32 {
    match model {
        m if m.starts_with("cultist") => 0,
        // Not an SRD creature: a straw training dummy is as hardy as a commoner.
        "dummy" => 0,
        // The ritual's boss has no SRD stat block; this is encounter tuning.
        "claude" => 5,
        _ => 0,
    }
}

/// Size category of a chamber model, for its reference mass.
pub fn model_size(model: &str) -> Size {
    if model == "claude" {
        Size::Large
    } else {
        Size::Medium
    }
}

/// A target whose displacement the overlay and the evidence report.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Track {
    pub label: String,
    pub target: Target,
    pub spell: String,
    pub at: f32,
    pub start: DVec3,
    /// The distance the spell asked for, m; zero when it did not move it.
    pub requested: f64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Target {
    /// Scene actor ID.
    Actor(u64),
    /// Index into [`SpellWorld::props`].
    Prop(usize),
}

/// One line of the spell log the overlay prints.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Record {
    pub at: f32,
    pub spell: String,
    pub text: String,
    pub save: Option<Save>,
}

/// A spell's bodies and joints, removed when the spell ends.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Owned {
    pub cast: u64,
    pub spell: String,
    pub caster: u64,
    pub joints: Vec<physics::JointId>,
    pub expires: Option<f32>,
}

/// A character the spell world can push: a scene actor's controller.
pub struct Mover<'a> {
    pub actor: u64,
    pub mass: f64,
    pub character: &'a mut physics::character::Character,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SpellWorld {
    pub world: physics::World,
    pub props: Vec<Prop>,
    pub ledger: Ledger,
    pub dice: Dice,
    pub fields: Vec<SpellField>,
    pub owned: Vec<Owned>,
    /// Caster actor to the cast that holds their concentration.
    pub concentration: BTreeMap<u64, u64>,
    pub casts: u64,
    #[serde(default)]
    pub time: f64,
    pub log: Vec<Record>,
    pub tracks: Vec<Track>,
    /// Row-two cooldowns: slot to the scene time it is ready.
    pub ready: BTreeMap<u8, f32>,
    #[serde(default)]
    pub feather_falls: Vec<crate::feather_fall::FeatherFall>,
    #[serde(default)]
    pub levitations: Vec<levitate::Effect>,
    #[serde(default)]
    pub telekinesis: Vec<telekinesis::Effect>,
    #[serde(default)]
    pub gusts: Vec<gust::Effect>,
    #[serde(default)]
    pub flames: Vec<crate::gust::Flame>,
    #[serde(default)]
    pub escape_ready: BTreeMap<u64, f64>,
    #[serde(default)]
    pub walls: Vec<wall_of_stone::Effect>,
    #[serde(default)]
    pub wind_walls: Vec<wind_wall::Effect>,
    #[serde(default)]
    pub meteors: Vec<meteor_swarm::Effect>,
    #[serde(default)]
    pub creatures: Vec<crate::meteor_swarm::Creature>,
    #[serde(default)]
    pub damage: Vec<(u64, i32, String)>,
    #[serde(default)]
    pub proxies: Vec<proxies::Proxy>,
    #[serde(default)]
    pub tentacles: Vec<black_tentacles::Effect>,
    #[serde(default)]
    pub reversed: Vec<reverse_gravity::Effect>,
    /// Prop poses at the start of the last tick, for presentation.
    previous: Vec<(DVec3, DQuat)>,
    /// Momentum lost as dynamic bodies are removed.
    #[serde(default)]
    pub removed: u64,
}

impl Default for SpellWorld {
    fn default() -> Self {
        Self::new(&[], 0)
    }
}

impl SpellWorld {
    /// A world whose static bodies are the scene's collision boxes.
    pub fn new(statics: &[physics::kinematic::Aabb], seed: u64) -> Self {
        let mut world = physics::World::new(1. / 120.);
        for aabb in statics {
            let center = (aabb.min + aabb.max) * 0.5;
            let body = world.add(
                physics::Body::new(1., DVec3::ONE, center).with_kind(physics::BodyKind::Static),
            );
            world.add_collider(
                physics::Collider::new(
                    body,
                    physics::Shape::Cuboid {
                        half: (aabb.max - aabb.min) * 0.5,
                    },
                )
                .with_material(Material::Stone.physics()),
            );
        }
        Self {
            ledger: Ledger::new(DVec3::ZERO, world.momentum(DVec3::ZERO)),
            world,
            props: vec![],
            dice: Dice::new(seed),
            fields: vec![],
            owned: vec![],
            concentration: BTreeMap::new(),
            casts: 0,
            time: 0.,
            log: vec![],
            tracks: vec![],
            ready: BTreeMap::new(),
            feather_falls: vec![],
            levitations: vec![],
            telekinesis: vec![],
            gusts: vec![],
            flames: vec![],
            escape_ready: BTreeMap::new(),
            walls: vec![],
            wind_walls: vec![],
            meteors: vec![],
            creatures: vec![],
            damage: vec![],
            proxies: vec![],
            tentacles: vec![],
            reversed: vec![],
            previous: vec![],
            removed: 0,
        }
    }

    pub fn validate(&self, instance: u64) -> Result<(), String> {
        self.world.check_version()?;
        self.dice.validate()?;
        self.validate_effects()?;
        if self.feather_falls.len() > 64 {
            return Err("Too many Feather Fall effects".into());
        }
        for effect in &self.feather_falls {
            effect.validate()?;
        }
        let bodies = self.world.bodies().len();
        let mut lives = std::collections::BTreeSet::new();
        if self.props.len() > MAX_PROPS
            || self.log.len() > 256
            || self.tracks.len() > 256
            || self.fields.len() > 64
            || self.owned.len() > 64
            || self.previous.len() > self.props.len()
            || self.props.iter().any(|p| {
                p.body.0 as usize >= bodies
                    || p.collider.0 as usize >= self.world.colliders().len()
                    || self.world.colliders()[p.collider.0 as usize].body != p.body
                    || p.life.instance != instance
                    || p.life.entity < PROP_ENTITY_BASE
                    || !lives.insert(p.life)
                    || p.spec.validate().is_err()
                    || p.removed != self.world[p.body].removed
                    || p.owner.is_some_and(|cast| cast > self.casts)
            })
            || self.fields.iter().any(|f| {
                f.area.validate().is_err() || !f.acceleration.is_finite() || !f.expires.is_finite()
            })
            || self
                .world
                .bodies()
                .iter()
                .any(|b| !b.pos.is_finite() || !b.vel.is_finite() || !b.omega.is_finite())
            || self.concentration.values().any(|cast| *cast > self.casts)
        {
            return Err("Invalid spell world checkpoint".into());
        }
        Ok(())
    }

    /// Starts a cast: a new cast ID. A concentration spell first ends the
    /// caster's previous concentration.
    pub fn begin_cast(&mut self, caster: u64, concentration: bool) -> Result<u64, String> {
        self.casts = self.casts.checked_add(1).ok_or("Spell casts exhausted")?;
        if concentration {
            if let Some(previous) = self.concentration.insert(caster, self.casts) {
                self.end_cast(previous)?;
            }
        }
        Ok(self.casts)
    }

    /// Adds a joint that the cast owns; it leaves when the cast ends.
    pub fn add_owned_joint(
        &mut self,
        cast: u64,
        spell: &str,
        caster: u64,
        joint: physics::Joint,
    ) -> physics::JointId {
        let id = self.world.add_joint(joint);
        match self.owned.iter_mut().find(|o| o.cast == cast) {
            Some(owned) => owned.joints.push(id),
            None => self.owned.push(Owned {
                cast,
                spell: spell.into(),
                caster,
                joints: vec![id],
                expires: None,
            }),
        }
        id
    }

    /// Adds an area that pushes on bodies and characters inside it.
    pub fn add_field(&mut self, field: SpellField) -> Result<(), String> {
        field.area.validate()?;
        if self.fields.len() >= 64 || !field.acceleration.is_finite() {
            return Err("Invalid spell field".into());
        }
        self.fields.push(field);
        Ok(())
    }

    /// Ends a cast: its fields, joints, and bodies leave the world.
    pub fn end_cast(&mut self, cast: u64) -> Result<(), String> {
        let before = self.boundary_snapshot();
        for effect in &mut self.levitations {
            if effect.cast == cast {
                effect.state.end(crate::levitate::End::Concentration);
            }
        }
        for effect in &mut self.telekinesis {
            if effect.cast == cast {
                effect.grip.end(&mut self.world);
            }
        }
        for effect in &mut self.walls {
            if effect.cast == cast {
                effect.wall.end(&mut self.world, self.time);
            }
        }
        for effect in &mut self.wind_walls {
            if effect.cast == cast {
                effect.wall.end(&mut self.world, &[]);
            }
        }
        for effect in &mut self.tentacles {
            if effect.cast == cast {
                effect.spell.end(&mut self.world);
            }
        }
        for effect in &mut self.reversed {
            if effect.cast == cast {
                effect.spell.end(&mut self.world);
            }
        }
        for proxy in &mut self.proxies {
            if proxy.cast == cast {
                proxy.ended = true;
            }
        }
        self.record_boundary(&before, "spell:removed");
        for effect in &self.walls {
            if effect.wall.permanent {
                for prop in &mut self.props {
                    if prop.owner == Some(effect.cast) {
                        prop.owner = None;
                    }
                }
            }
        }
        for prop in &mut self.props {
            prop.removed = self.world[prop.body].removed;
        }
        for effect in &mut self.gusts {
            if effect.cast == cast {
                effect.gust.end();
            }
        }
        self.fields.retain(|f| f.cast != cast);
        self.concentration.retain(|_, held| *held != cast);
        let owned: Vec<_> = self
            .owned
            .iter()
            .filter(|o| o.cast == cast)
            .cloned()
            .collect();
        self.owned.retain(|o| o.cast != cast);
        for joint in owned.iter().flat_map(|o| o.joints.iter()) {
            self.world.remove_joint(*joint);
        }
        let props: Vec<_> = (0..self.props.len())
            .filter(|i| self.props[*i].owner == Some(cast) && !self.props[*i].removed)
            .collect();
        for index in props {
            self.remove_prop(index)?;
        }
        Ok(())
    }

    /// Ends the concentration a caster holds, as on death.
    pub fn end_concentration(&mut self, caster: u64) -> Result<(), String> {
        if let Some(cast) = self.concentration.remove(&caster) {
            self.end_cast(cast)?;
        }
        Ok(())
    }

    /// Adds a prop whose box is centered on `center`, turned `yaw` about
    /// the vertical. A secured prop is a static body.
    pub fn add_prop(
        &mut self,
        life: physics::queries::Life,
        name: &str,
        spec: PropSpec,
        center: DVec3,
        yaw: f64,
        owner: Option<u64>,
    ) -> Result<usize, String> {
        spec.validate()?;
        if self.props.len() >= MAX_PROPS {
            return Err("Spell prop budget exceeded".into());
        }
        if life.entity < PROP_ENTITY_BASE || self.props.iter().any(|p| p.life == life) {
            return Err("Prop life collides with another identity".into());
        }
        if !center.is_finite() || !yaw.is_finite() || name.len() > 64 {
            return Err("Invalid prop placement".into());
        }
        let rotation = DQuat::from_rotation_y(yaw);
        let mut body = physics::Body::new(
            spec.mass,
            physics::Body::box_inertia(spec.mass, spec.dimensions),
            center + rotation * spec.center_of_mass,
        );
        body.orientation = rotation;
        body.prev_orientation = rotation;
        if spec.secured {
            body = body.with_kind(physics::BodyKind::Static);
        }
        let id = self.world.add(body);
        let collider = self.world.add_collider(
            physics::Collider::new(
                id,
                physics::Shape::Cuboid {
                    half: spec.dimensions * 0.5,
                },
            )
            .at(-spec.center_of_mass, DQuat::IDENTITY)
            .with_material(spec.material.physics()),
        );
        self.props.push(Prop {
            life,
            name: name.into(),
            hit_points: spec.hit_points,
            spec,
            body: id,
            collider,
            owner,
            removed: false,
        });
        self.previous.clear();
        Ok(self.props.len() - 1)
    }

    /// Removes a prop: its body leaves the world and its momentum leaves
    /// the ledger under the "removed" term.
    pub fn remove_prop(&mut self, index: usize) -> Result<(), String> {
        let prop = self.props.get_mut(index).ok_or("Unknown prop")?;
        if prop.removed {
            return Ok(());
        }
        prop.removed = true;
        let body = prop.body;
        let lost = Momentum::of(&self.world[body], self.ledger.origin);
        if self.world[body].moves() {
            self.ledger.add(
                "removed",
                Momentum {
                    linear: -lost.linear,
                    angular: -lost.angular,
                },
            );
        }
        self.world.remove_body(body);
        self.removed += 1;
        Ok(())
    }

    /// Momentum at the creation/removal boundary, separate from forces and contacts.
    pub fn boundary_snapshot(&self) -> Vec<Option<Momentum>> {
        self.world
            .bodies()
            .iter()
            .map(|b| {
                (b.kind == physics::BodyKind::Dynamic && !b.removed)
                    .then(|| Momentum::of(b, self.ledger.origin))
            })
            .collect()
    }
    pub fn record_boundary(&mut self, before: &[Option<Momentum>], term: &str) {
        let mut delta = Momentum::ZERO;
        for (i, b) in self.world.bodies().iter().enumerate() {
            let active = b.kind == physics::BodyKind::Dynamic && !b.removed;
            match (before.get(i).copied().flatten(), active) {
                (Some(old), false) => {
                    delta.linear -= old.linear;
                    delta.angular -= old.angular;
                }
                (None, true) => {
                    delta = delta + Momentum::of(b, self.ledger.origin);
                }
                _ => {}
            }
        }
        self.ledger.add(term, delta);
    }

    /// Registers a spell-created cuboid for collision queries and native presentation.
    pub fn adopt_body(
        &mut self,
        body: physics::BodyId,
        name: &str,
        kind: PropKind,
        owner: Option<u64>,
        instance: u64,
    ) -> Result<usize, String> {
        if let Some(index) = self.props.iter().position(|p| p.body == body) {
            return Ok(index);
        }
        let (index, collider) = self
            .world
            .colliders()
            .iter()
            .enumerate()
            .find(|(_, c)| c.body == body)
            .ok_or("Spell body has no collider")?;
        let dimensions = match collider.shape {
            physics::Shape::Cuboid { half } => half * 2.,
            physics::Shape::Sphere { radius } => DVec3::splat(radius * 2.),
            physics::Shape::Capsule {
                radius,
                half_length,
            } => DVec3::new(radius * 2., radius * 2., (radius + half_length) * 2.),
        };
        let mut spec = PropSpec::reference(kind);
        spec.dimensions = dimensions;
        spec.mass = self.world[body].mass.max(0.1);
        spec.center_of_mass = DVec3::ZERO;
        spec.material = Material::Stone;
        spec.secured = self.world[body].kind == physics::BodyKind::Static;
        spec.hit_points = Some(180);
        spec.validate()?;
        if self.props.len() >= MAX_PROPS {
            return Err("Spell prop budget exceeded".into());
        }
        self.props.push(Prop {
            life: physics::queries::Life {
                instance,
                entity: PROP_ENTITY_BASE + self.props.len() as u64,
                generation: 0,
            },
            name: name.into(),
            spec,
            body,
            collider: physics::ColliderId(index as u32),
            hit_points: Some(180),
            owner,
            removed: self.world[body].removed,
        });
        self.previous.clear();
        Ok(self.props.len() - 1)
    }

    /// Center of a prop's collision box, m.
    pub fn prop_center(&self, index: usize) -> DVec3 {
        let prop = &self.props[index];
        self.world.colliders()[prop.collider.0 as usize]
            .pose(&self.world)
            .0
    }

    /// The pose of a prop's box between the last tick's start and now.
    pub fn prop_pose(&self, index: usize, alpha: f64) -> (DVec3, DQuat) {
        let prop = &self.props[index];
        let body = &self.world[prop.body];
        let offset = -prop.spec.center_of_mass;
        let (pos, rotation) = self
            .previous
            .get(index)
            .map(|(p, q)| {
                (
                    p.lerp(body.pos, alpha.clamp(0., 1.)),
                    q.slerp(body.orientation, alpha.clamp(0., 1.)),
                )
            })
            .unwrap_or((body.pos, body.orientation));
        (pos + rotation * offset, rotation)
    }

    /// The eight corners of a prop's collision box, world frame.
    pub fn prop_corners(&self, index: usize) -> [DVec3; 8] {
        let prop = &self.props[index];
        let (center, rotation) = self.world.colliders()[prop.collider.0 as usize].pose(&self.world);
        let half = prop.spec.dimensions * 0.5;
        std::array::from_fn(|i| {
            let sign = DVec3::new(
                if i & 1 == 0 { -1. } else { 1. },
                if i & 2 == 0 { -1. } else { 1. },
                if i & 4 == 0 { -1. } else { 1. },
            );
            center + rotation * (half * sign)
        })
    }

    /// Initial speed that slides a resting prop exactly `distance` on the
    /// stone floor: v₀ = √(2 μ g d), μ being the pair's friction.
    pub fn prop_push_speed(&self, index: usize, distance: f64) -> f64 {
        let floor = Material::Stone.physics().friction;
        let friction = (self.props[index].spec.material.physics().friction * floor).sqrt();
        (2. * friction * GRAVITY * distance.max(0.)).sqrt()
    }

    /// Calibrated SRD push of a prop: the initial horizontal speed that
    /// stops at `distance` on flat ground, recorded under `spell` in the
    /// ledger. Secured and removed props do not move.
    pub fn push_prop(
        &mut self,
        index: usize,
        direction: DVec3,
        distance: f64,
        spell: &str,
    ) -> Result<bool, String> {
        let direction = DVec3::new(direction.x, 0., direction.z).normalize_or_zero();
        let prop = self.props.get(index).ok_or("Unknown prop")?;
        if prop.spec.secured || prop.removed || direction == DVec3::ZERO {
            return Ok(false);
        }
        let body = prop.body;
        let speed = self.prop_push_speed(index, distance);
        self.world.wake(body);
        let mass = self.world[body].mass;
        let at = self.world[body].pos;
        let impulse = direction * speed * mass;
        self.world[body].apply_impulse_at(impulse, at);
        self.ledger
            .add_impulse(&format!("spell:{spell}"), impulse, at);
        Ok(true)
    }

    /// Applies an impulse to a prop at a point, recorded under `term`.
    pub fn impulse_prop(
        &mut self,
        index: usize,
        impulse: DVec3,
        at: DVec3,
        term: &str,
    ) -> Result<(), String> {
        let prop = self.props.get(index).ok_or("Unknown prop")?;
        if prop.spec.secured || prop.removed || !impulse.is_finite() || !at.is_finite() {
            return Ok(());
        }
        let body = prop.body;
        self.world.wake(body);
        self.world[body].apply_impulse_at(impulse, at);
        self.ledger.add_impulse(term, impulse, at);
        Ok(())
    }

    /// Records the prop poses presentation interpolates from.
    pub fn begin_tick(&mut self) {
        self.previous = self
            .props
            .iter()
            .map(|p| (self.world[p.body].pos, self.world[p.body].orientation))
            .collect();
    }

    /// Advances the rigid world `steps` fixed steps, recording every
    /// external impulse in the ledger, and expires fields that end by `time`.
    pub fn step(&mut self, steps: u32, time: f32) -> Result<(), String> {
        self.time = f64::from(time);
        let expired_effects: Vec<_> = self
            .concentration
            .values()
            .copied()
            .filter(|cast| {
                self.levitations.iter().any(|e| {
                    e.cast == *cast
                        && (self.time - e.state.cast_at >= crate::levitate::DURATION
                            || !e.state.holding())
                }) || self
                    .telekinesis
                    .iter()
                    .any(|e| e.cast == *cast && self.world.tick >= e.grip.ends)
                    || self.walls.iter().any(|e| {
                        e.cast == *cast
                            && self.time - e.wall.cast_at >= crate::wall_of_stone::DURATION
                    })
                    || self
                        .gusts
                        .iter()
                        .any(|e| e.cast == *cast && !e.gust.active(self.time))
                    || self
                        .wind_walls
                        .iter()
                        .any(|e| e.cast == *cast && !e.wall.active(self.time))
                    || self.tentacles.iter().any(|e| {
                        e.cast == *cast && (e.spell.ended || self.world.tick >= e.spell.ends)
                    })
                    || self.reversed.iter().any(|e| {
                        e.cast == *cast && (self.world.tick >= e.spell.ends || !e.spell.active())
                    })
            })
            .collect();
        for cast in expired_effects {
            self.end_cast(cast)?;
        }
        let expired: Vec<u64> = self
            .fields
            .iter()
            .filter(|f| f.expires <= time)
            .map(|f| f.cast)
            .chain(
                self.owned
                    .iter()
                    .filter(|o| o.expires.is_some_and(|at| at <= time))
                    .map(|o| o.cast),
            )
            .collect();
        for cast in expired {
            self.end_cast(cast)?;
        }
        if !self
            .world
            .bodies()
            .iter()
            .any(|b| b.kind == physics::BodyKind::Dynamic && !b.removed)
        {
            self.world.tick += u64::from(steps);
            return Ok(());
        }
        let gravity = DVec3::new(0., -GRAVITY, 0.);
        for _ in 0..steps {
            let dt = self.world.dt;
            let targets: Vec<_> = self
                .proxies
                .iter()
                .filter(|p| !p.ended)
                .map(|p| crate::black_tentacles::Target {
                    body: p.body,
                    kind: crate::black_tentacles::Kind::Creature {
                        strength: 0,
                        athletics: 0,
                    },
                })
                .chain(
                    self.props
                        .iter()
                        .filter(|p| !p.removed && p.spec.kind != PropKind::Tentacle)
                        .map(|p| crate::black_tentacles::Target {
                            body: p.body,
                            kind: crate::black_tentacles::Kind::Prop {
                                secured: p.spec.secured,
                            },
                        }),
                )
                .collect();
            let identities: BTreeMap<_, _> =
                self.proxies.iter().map(|p| (p.body, p.actor)).collect();
            let mut tentacle_events = vec![];
            for effect in &mut self.tentacles {
                tentacle_events.extend(effect.spell.before_step_with(
                    &mut self.world,
                    &targets,
                    &mut |body, sides| {
                        if let Some(actor) = body.and_then(|b| identities.get(&b)) {
                            self.dice.save(*actor, "Strength", 0, SPELL_SAVE_DC).roll
                        } else {
                            self.dice.roll(sides)
                        }
                    },
                    Some(&mut self.ledger),
                ));
            }
            for event in tentacle_events {
                black_tentacles::record(self, event);
            }
            for effect in &mut self.wind_walls {
                let props: Vec<_> = self
                    .props
                    .iter()
                    .filter(|p| !p.removed)
                    .map(|p| crate::wind_wall::Prop {
                        body: p.body,
                        size: match p.spec.size {
                            Size::Tiny => crate::wind_wall::Size::Tiny,
                            Size::Small => crate::wind_wall::Size::Small,
                            _ => crate::wind_wall::Size::Medium,
                        },
                        radius: p.spec.dimensions.max_element() * 0.5,
                    })
                    .collect();
                effect
                    .wall
                    .before_step(&mut self.world, &props, &mut self.ledger);
            }
            for effect in &self.gusts {
                let profiles: Vec<_> = self
                    .props
                    .iter()
                    .filter(|p| !p.removed && !p.spec.secured)
                    .map(|p| {
                        (
                            p.body,
                            crate::gust::Profile {
                                mass: p.spec.mass,
                                half: p.spec.dimensions * 0.5,
                                drag_coefficient: 1.2,
                                friction: p.spec.material.physics().friction,
                            },
                        )
                    })
                    .collect();
                for blow in effect.gust.blow(time as f64, &mut self.world, &profiles) {
                    self.ledger.add_impulse("gust:drag", blow.impulse, blow.at);
                }
            }
            for effect in &mut self.telekinesis {
                if let Some(grip) = effect.grip.grip {
                    self.world.wake(grip.body);
                }
                effect
                    .grip
                    .steer(&mut self.world, effect.caster_position, effect.aim);
            }
            for effect in &mut self.levitations {
                if let Target::Prop(index) = effect.target {
                    let body = self.props[index].body;
                    effect.state.update(
                        time as f64,
                        self.world[body].pos.distance(effect.caster_position),
                    );
                    effect
                        .state
                        .drive(&mut self.world, body, GRAVITY, &mut self.ledger);
                }
            }
            // What the field adds: only bodies that respond this step.
            let mut field_terms: Vec<(String, DVec3, DVec3)> = vec![];
            for body in self.world.bodies() {
                let responds = body.kind == physics::BodyKind::Dynamic
                    && !body.removed
                    && (!body.sleeping || body.vel != DVec3::ZERO || body.omega != DVec3::ZERO);
                if !responds {
                    continue;
                }
                field_terms.push(("gravity".into(), gravity * body.mass * dt, body.pos));
                for field in self.fields.iter().filter(|f| f.area.contains(body.pos)) {
                    field_terms.push((
                        format!("spell:{}", field.spell),
                        field.acceleration * body.mass * dt,
                        body.pos,
                    ));
                }
            }
            let fields = Fields {
                gravity,
                fields: &self.fields,
            };
            for effect in &self.reversed {
                if !effect.spell.active() {
                    continue;
                }
                for i in 0..self.world.bodies().len() {
                    let id = physics::BodyId(i as u32);
                    let body = self.world[id];
                    if body.kind != physics::BodyKind::Dynamic || body.removed {
                        continue;
                    }
                    let reference = if self
                        .proxies
                        .iter()
                        .any(|p| p.body == id && p.cast == effect.cast)
                    {
                        body.pos - DVec3::Y * 0.9
                    } else {
                        body.pos
                    };
                    let acceleration = effect.spell.gravity.at(reference, body.vel) - gravity;
                    self.world.wake(id);
                    self.world[id].apply_force(acceleration * body.mass);
                    self.ledger.add_impulse(
                        "reverse-gravity",
                        acceleration * body.mass * dt,
                        body.pos,
                    );
                }
            }
            let reversed_velocities: Vec<Vec<f64>> = self
                .reversed
                .iter()
                .map(|e| {
                    e.spell
                        .falls
                        .iter()
                        .map(|(id, _)| self.world[*id].vel.y)
                        .collect()
                })
                .collect();
            self.world.step(&fields);
            let mut gravity_broken = Vec::new();
            for (effect, before) in self.reversed.iter_mut().zip(&reversed_velocities) {
                for impact in effect.spell.observe(&mut self.world, before) {
                    if impact.strike.dice == 0 {
                        continue;
                    }
                    let damage = (0..impact.strike.dice)
                        .map(|_| self.dice.roll(6) as i32)
                        .sum::<i32>();
                    if let Some(proxy) = self.proxies.iter().find(|p| p.body == impact.body) {
                        self.damage
                            .push((proxy.actor, damage, "Reverse Gravity impact".into()));
                    } else if let Some(prop) = self
                        .props
                        .iter_mut()
                        .find(|p| p.body == impact.body && !p.removed)
                    {
                        if let Some(hp) = &mut prop.hit_points {
                            *hp = (*hp - damage).max(0);
                            if *hp == 0 {
                                gravity_broken.push(prop.body);
                            }
                        }
                        self.log.push(Record {
                            at: time,
                            spell: "Reverse Gravity impact".into(),
                            text: format!(
                                "{} strikes a surface: {}d6 = {damage}; HP {:?}",
                                prop.name, impact.strike.dice, prop.hit_points
                            ),
                            save: None,
                        });
                    }
                }
            }
            for effect in &mut self.levitations {
                if let Target::Prop(index) = effect.target {
                    let id = self.props[index].body;
                    if effect.state.gentle()
                        && self.world.contacts.iter().any(|c| {
                            (c.body_b == id && c.impulse.y > 0.)
                                || (c.body_a == id && c.impulse.y < 0.)
                        })
                    {
                        effect.state.land();
                    }
                }
            }
            for effect in &self.walls {
                for bond in &effect.wall.bonds {
                    if let Some(joint) = self.world.joint(bond.joint) {
                        let a = self.world[joint.a].responds()
                            || self.world.slept.iter().any(|(id, _)| *id == joint.a);
                        let b = self.world[joint.b].responds()
                            || self.world.slept.iter().any(|(id, _)| *id == joint.b);
                        let sign = match (a, b) {
                            (false, true) => 1.,
                            (true, false) => -1.,
                            _ => 0.,
                        };
                        self.ledger.add(
                            "wall-of-stone:weld",
                            Momentum::impulse(
                                joint.impulse * sign,
                                joint.point,
                                self.ledger.origin,
                            ) + Momentum {
                                linear: DVec3::ZERO,
                                angular: joint.angular_impulse * sign,
                            },
                        );
                    }
                }
            }
            for effect in &self.reversed {
                for hold in &effect.spell.holds {
                    if let Some(joint) = hold.joint.and_then(|id| self.world.joint(id)) {
                        let sign = if self.world[joint.b].responds()
                            || self.world.slept.iter().any(|(body, _)| *body == joint.b)
                        {
                            1.
                        } else {
                            0.
                        };
                        self.ledger.add(
                            "reverse-gravity:fixed-grab",
                            Momentum::impulse(
                                joint.impulse * sign,
                                joint.point,
                                self.ledger.origin,
                            ) + Momentum {
                                linear: DVec3::ZERO,
                                angular: joint.angular_impulse * sign,
                            },
                        );
                    }
                }
            }
            for effect in &self.tentacles {
                for tentacle in &effect.spell.tentacles {
                    if let crate::black_tentacles::Mode::Hold { joint, .. } = tentacle.mode {
                        if let Some(joint) = self.world.joint(joint) {
                            let awake = |id| {
                                self.world[id].responds()
                                    || self.world.slept.iter().any(|(body, _)| *body == id)
                            };
                            let sign = match (awake(joint.a), awake(joint.b)) {
                                (true, false) => -1.,
                                (false, true) => 1.,
                                _ => 0.,
                            };
                            self.ledger.add(
                                "tentacles:controller",
                                Momentum::impulse(
                                    joint.impulse * sign,
                                    joint.point,
                                    self.ledger.origin,
                                ),
                            );
                        }
                    }
                }
            }
            let before = self.boundary_snapshot();
            let mut tentacle_events = vec![];
            for effect in &mut self.tentacles {
                tentacle_events.extend(
                    effect
                        .spell
                        .after_step(&mut self.world, Some(&mut self.ledger)),
                );
            }
            for event in tentacle_events {
                black_tentacles::record(self, event);
            }
            for effect in &mut self.reversed {
                if self.world.tick >= effect.spell.ends {
                    effect.spell.end(&mut self.world);
                }
            }
            for proxy in &mut self.proxies {
                proxy.held = self.tentacles.iter().any(|e| {
                    e.cast == proxy.cast && !e.spell.ended && e.spell.restrained(proxy.body)
                }) || self
                    .reversed
                    .iter()
                    .any(|e| e.cast == proxy.cast && e.spell.active());
                if !proxy.held
                    && !self
                        .tentacles
                        .iter()
                        .any(|e| e.cast == proxy.cast && !e.spell.ended)
                {
                    proxy.ended = true;
                }
            }
            let mut meteor_bodies = vec![];
            let mut meteor_events = vec![];
            for effect in &mut self.meteors {
                for impact in effect.swarm.after_step(
                    &mut self.world,
                    &self.creatures,
                    &mut effect.objects,
                    &mut |s| self.dice.roll(s),
                ) {
                    meteor_events.push((
                        format!(
                            "Meteor {}: impact at ({:.1}, {:.1}, {:.1}) m{}",
                            impact.meteor + 1,
                            impact.center.x,
                            impact.center.y,
                            impact.center.z,
                            if impact.obstructed {
                                "; intercepted above the target"
                            } else {
                                ""
                            }
                        ),
                        None,
                    ));
                    for hit in impact.creatures {
                        let save = Save {
                            target: u64::from(hit.id),
                            ability: "DEX".into(),
                            roll: hit.save.d20 as u32,
                            modifier: hit.save.modifier,
                            total: hit.save.d20 + hit.save.modifier,
                            dc: hit.save.dc,
                            success: hit.save.success,
                            forced: false,
                        };
                        meteor_events.push((
                            format!(
                                "Creature {}: DEX {} vs DC {} {}; {} fire + {} bludgeoning",
                                hit.id,
                                save.total,
                                save.dc,
                                if save.success { "succeeds" } else { "fails" },
                                hit.damage.fire,
                                hit.damage.bludgeoning,
                            ),
                            Some(save),
                        ));
                        self.damage.push((
                            u64::from(hit.id),
                            hit.damage.total(),
                            "Meteor Swarm".into(),
                        ));
                    }
                    for hit in impact.objects {
                        meteor_bodies.extend(hit.debris.iter().copied());
                        if !self.world[hit.body].removed {
                            self.ledger.add_impulse(
                                "meteor:blast",
                                hit.impulse,
                                self.world[hit.body].pos,
                            );
                        }
                    }
                }
                meteor_bodies.extend(effect.swarm.meteors.iter().filter_map(|m| m.body));
                crate::meteor_swarm::burn(&mut self.world, &mut effect.objects);
                for prop in &mut self.props {
                    if let Some(object) = effect.objects.iter().find(|o| o.body == prop.body) {
                        prop.hit_points = object.hp;
                    }
                }
            }
            for body in meteor_bodies {
                if !self.world[body].removed {
                    let instance = self.props.first().map_or(1, |p| p.life.instance);
                    let meteor = self
                        .meteors
                        .iter()
                        .any(|e| e.swarm.meteors.iter().any(|m| m.body == Some(body)));
                    self.adopt_body(
                        body,
                        "Meteor or impact debris",
                        if meteor {
                            PropKind::Meteor
                        } else {
                            PropKind::SpellBody
                        },
                        None,
                        instance,
                    )?;
                }
            }
            for (event, save) in meteor_events {
                self.record(time, "Meteor Swarm", event, save);
            }
            self.record_boundary(&before, "meteor:spawn/remove");
            for effect in &mut self.walls {
                effect.wall.after_step(&mut self.world, time as f64);
            }
            for prop in &mut self.props {
                prop.removed = self.world[prop.body].removed;
            }
            for effect in &mut self.telekinesis {
                effect.grip.after_step(
                    &mut self.world,
                    effect.caster_position,
                    Some(&mut self.ledger),
                );
            }
            for (term, impulse, at) in field_terms {
                self.ledger.add_impulse(&term, impulse, at);
            }
            let slept: Vec<usize> = self
                .world
                .slept
                .iter()
                .map(|(id, _)| id.0 as usize)
                .collect();
            let awake = |world: &physics::World, i: usize| {
                world.bodies()[i].responds() || slept.contains(&i)
            };
            let mut contact_terms = vec![];
            for c in &self.world.contacts {
                let (a, b) = (c.body_a.0 as usize, c.body_b.0 as usize);
                let sign = match (awake(&self.world, a), awake(&self.world, b)) {
                    (false, true) => 1.,
                    (true, false) => -1.,
                    _ => continue,
                };
                contact_terms.push((c.impulse * sign, c.point, c.twist * sign));
            }
            for (impulse, point, twist) in contact_terms {
                self.ledger.add_impulse("static contact", impulse, point);
                self.ledger.add(
                    "static contact",
                    Momentum {
                        linear: DVec3::ZERO,
                        angular: twist,
                    },
                );
            }
            for (_, removed) in std::mem::take(&mut self.world.slept) {
                self.ledger.add(
                    "sleep",
                    Momentum {
                        linear: -removed.linear,
                        angular: -removed.angular,
                    },
                );
            }
            reverse_gravity::break_props(self, &gravity_broken)?;
        }
        Ok(())
    }

    /// Relative momentum residual: what the props' momentum has that the
    /// start and the recorded terms do not explain.
    pub fn ledger_error(&self) -> physics::LedgerError {
        self.ledger.error(self.world.momentum(self.ledger.origin))
    }

    /// Exchanges momentum between characters and the dynamic props they
    /// touch: a knocked character shoves a prop, and a moving prop shoves a
    /// character, each through one contact impulse using the character's
    /// reference mass. Walking alone does not shove; the sweep stops it.
    pub fn couple(&mut self, movers: &mut [Mover<'_>]) -> Result<(), String> {
        for mover in movers.iter_mut() {
            if self
                .proxies
                .iter()
                .any(|p| p.actor == mover.actor && p.held && !p.ended)
                || self
                    .telekinesis
                    .iter()
                    .any(|e| e.target == Target::Actor(mover.actor) && e.proxy.is_some())
            {
                continue;
            }
            let c = &mut *mover.character;
            let (a, b) = (
                c.feet + DVec3::Y * CHARACTER_RADIUS,
                c.feet + DVec3::Y * (CHARACTER_HEIGHT - CHARACTER_RADIUS),
            );
            for index in 0..self.props.len() {
                let prop = &self.props[index];
                if prop.removed
                    || prop.spec.secured
                    || prop.spec.kind == PropKind::Tentacle
                    || self.world.colliders()[prop.collider.0 as usize].filter
                        == physics::Filter::NONE
                {
                    continue;
                }
                let body = self.world[prop.body];
                let collider = self.world.colliders()[prop.collider.0 as usize];
                if collider
                    .pose(&self.world)
                    .0
                    .distance(c.feet + DVec3::Y * 0.9)
                    > collider.shape.bound() + CHARACTER_HEIGHT
                {
                    continue;
                }
                let segment = |q: DVec3| {
                    let ab = b - a;
                    a + ab * ((q - a).dot(ab) / ab.length_squared()).clamp(0., 1.)
                };
                let mut p = segment(body.pos);
                let mut q = collider.closest_point(&self.world, p);
                for _ in 0..3 {
                    p = segment(q);
                    q = collider.closest_point(&self.world, p);
                }
                let gap = p.distance(q);
                if gap > CHARACTER_RADIUS + CONTACT_GAP {
                    continue;
                }
                let normal = if gap > 1e-6 {
                    (q - p) / gap
                } else {
                    (body.pos - p).normalize_or_zero()
                };
                let normal = DVec3::new(normal.x, 0., normal.z).normalize_or_zero();
                if normal == DVec3::ZERO {
                    continue;
                }
                let own = c.external;
                let r = q - body.pos;
                let closing = (own - (body.vel + body.omega_world().cross(r))).dot(normal);
                if closing <= 1e-4 || (!c.knocked() && body.vel.length() < 0.05) {
                    continue;
                }
                self.world.wake(prop.body);
                let body = &self.world[prop.body];
                let angular = r.cross(normal);
                let k = 1. / mover.mass
                    + body.inverse_mass()
                    + angular.dot(body.inverse_inertia_world(angular));
                let j = (1. + CONTACT_RESTITUTION) * closing / k;
                let impulse = normal * j;
                self.impulse_prop(index, impulse, q, "character contact")?;
                c.external = (c.external - impulse / mover.mass).clamp_length_max(100.);
                c.external.y = 0.;
            }
        }
        Ok(())
    }

    /// Adds every live prop to a character query scene at its pose.
    pub fn insert_query_colliders(
        &self,
        scene: &mut physics::queries::Scene,
    ) -> Result<(), String> {
        use physics::queries::{Mesh, MeshCollider, Usage};
        for prop in self.props.iter().filter(|p| !p.removed) {
            if scene.pose(prop.query_key()).is_some() {
                continue;
            }
            let half = prop.spec.dimensions * 0.5;
            let offset = -prop.spec.center_of_mass;
            scene.insert(MeshCollider {
                key: prop.query_key(),
                layers: 1,
                usage: if prop.spec.kind == PropKind::Tentacle
                    || self.world.colliders()[prop.collider.0 as usize].filter
                        == physics::Filter::NONE
                {
                    Usage::Selection
                } else {
                    Usage::Blocking
                },
                mesh: Mesh::from_box(offset - half, offset + half)?,
            })?;
        }
        self.sync_query_poses(scene)
    }

    /// Moves props' query colliders to their bodies and drops removed ones.
    pub fn sync_query_poses(&self, scene: &mut physics::queries::Scene) -> Result<(), String> {
        for prop in &self.props {
            if prop.removed {
                scene.remove(prop.query_key());
                continue;
            }
            let body = &self.world[prop.body];
            scene.set_pose(
                prop.query_key(),
                physics::queries::Pose {
                    position: body.pos,
                    rotation: body.orientation.normalize(),
                },
            )?;
        }
        Ok(())
    }

    /// Appends one log line, keeping the most recent 256.
    pub fn record(&mut self, at: f32, spell: &str, text: String, save: Option<Save>) {
        if self.log.len() >= 256 {
            self.log.remove(0);
        }
        self.log.push(Record {
            at,
            spell: spell.into(),
            text,
            save,
        });
    }

    /// Starts measuring a target's displacement.
    pub fn track(&mut self, track: Track) {
        if self.tracks.len() >= 256 {
            self.tracks.remove(0);
        }
        self.tracks.push(track);
    }

    pub fn body(&self, id: BodyId) -> &physics::Body {
        &self.world[id]
    }
}

#[cfg(test)]
mod tests;
