//! The physics layer SRD spells act through.
//!
//! [`SpellWorld`] holds a `physics::World` of dynamic props beside the
//! chamber's kinematic characters, stepped on the chamber's 120 Hz clock and
//! saved with every checkpoint. It also holds the seeded [`dice::Dice`],
//! active [`fields::SpellField`] areas, spell-owned bodies and joints,
//! concentration, and a momentum [`physics::Ledger`] with one named term per
//! source of external momentum.
//!
//! To add a spell, write `spells/<name>.rs` with its cast function and its
//! playground scenario, then add one line to [`CATALOG`] (its action-bar
//! slot) and one line to `crate::playground::scenarios`.
pub mod black_tentacles;
pub mod dice;
pub mod feather_fall;
pub mod fields;
pub mod gust_of_wind;
pub mod levitate;
pub mod props;
pub mod thunderwave;
pub mod wall_of_stone;
pub mod wind_wall;

use glam::{DQuat, DVec3};
use physics::{BodyId, Ledger, Momentum};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub use dice::{Dice, Save, fall_dice};
pub use fields::{Area, Fields, SpellField};
pub use props::{Material, Prop, PropKind, PropSpec, Size};

/// One foot, m. Spell distances are written in feet times this constant.
pub const FEET: f64 = 0.3048;
/// One round, s. "Until the end of your next turn" is one round after the cast.
pub const ROUND: f32 = 6.;
/// Gravity on props and spell bodies, m/s².
pub const GRAVITY: f64 = 9.81;
/// The player wizard's spell save DC.
pub const SPELL_SAVE_DC: i32 = 15;
/// Characters closer than their radius plus this gap exchange momentum, m.
pub const CONTACT_GAP: f64 = 0.05;
/// Restitution of character contacts.
pub const CONTACT_RESTITUTION: f64 = 0.1;
/// Upright capsule of every chamber character, m.
pub const CHARACTER_RADIUS: f64 = 0.35;
pub const CHARACTER_HEIGHT: f64 = 1.8;
/// Relative ledger residual the tests and evidence accept.
pub const LEDGER_TOLERANCE: f64 = 1e-9;
/// Prop collision identities start here, far above any scene actor ID.
pub const PROP_ENTITY_BASE: u64 = 1 << 32;
pub const MAX_PROPS: usize = 192;

/// A spell on the second action-bar row (hotkeys Shift+1 to Shift+0).
pub struct SpellDef {
    /// Row-two slot, 0 through 9; slot 0 is Shift+1 and slot 9 is Shift+0.
    pub slot: u8,
    /// Lowercase name, as on the `--spell-playground` command line.
    pub key: &'static str,
    pub label: &'static str,
    /// Atlas sprite, generated by the original UI atlas.
    pub icon: &'static str,
    pub description: &'static str,
    /// Chamber mana and cooldown: MMO tuning, not tabletop rules.
    pub cost: i32,
    pub cooldown: f32,
    /// Runs an admitted cast. The caster's facing is `game.yaw`.
    pub cast: fn(&mut crate::play::Game) -> Result<(), String>,
}

/// Row-two spells. Reserved slots, in issue order: 0 Telekinesis (#10452),
/// 1 Wall of Stone (#10453), 2 Levitate (#10454), 3 Feather Fall (#10455),
/// 4 Gust of Wind (#10456), 5 Wind Wall (#10457), 6 Black Tentacles
/// (#10458), 7 Meteor Swarm (#10459), 8 Reverse Gravity (#10460).
pub const CATALOG: &[SpellDef] = &[
    gust_of_wind::DEF,
    wind_wall::DEF,
    levitate::DEF,
    crate::reverse_gravity::game::SPELL,
    crate::telekinesis::DEF,
    feather_fall::SPELL,
    wall_of_stone::DEF,
    black_tentacles::DEF,
];

pub fn spell_in_slot(slot: u8) -> Option<&'static SpellDef> {
    CATALOG.iter().find(|s| s.slot == slot)
}

/// Constitution modifiers from SRD stat blocks; the Cultist has CON 10.
pub fn constitution_modifier(model: &str) -> i32 {
    match model {
        m if m.starts_with("cultist") => 0,
        // Not an SRD creature: a straw training dummy is as hardy as a commoner.
        "dummy" => 0,
        // The ritual's boss has no SRD stat block; this is encounter tuning.
        "claude" => 5,
        _ => 0,
    }
}

/// Size category of a chamber model, for its reference mass.
pub fn model_size(model: &str) -> Size {
    if model == "claude" {
        Size::Large
    } else {
        Size::Medium
    }
}

/// A target whose displacement the overlay and the evidence report.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Track {
    pub label: String,
    pub target: Target,
    pub spell: String,
    pub at: f32,
    pub start: DVec3,
    /// The distance the spell asked for, m; zero when it did not move it.
    pub requested: f64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Target {
    /// Scene actor ID.
    Actor(u64),
    /// Index into [`SpellWorld::props`].
    Prop(usize),
}

/// One line of the spell log the overlay prints.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Record {
    pub at: f32,
    pub spell: String,
    pub text: String,
    pub save: Option<Save>,
}

/// A spell's bodies and joints, removed when the spell ends.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Owned {
    pub cast: u64,
    pub spell: String,
    pub caster: u64,
    pub joints: Vec<physics::JointId>,
    pub expires: Option<f32>,
}

/// A character the spell world can push: a scene actor's controller.
pub struct Mover<'a> {
    pub actor: u64,
    pub mass: f64,
    pub character: &'a mut physics::character::Character,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SpellWorld {
    pub world: physics::World,
    pub props: Vec<Prop>,
    pub ledger: Ledger,
    pub dice: Dice,
    pub fields: Vec<SpellField>,
    pub owned: Vec<Owned>,
    /// Caster actor to the cast that holds their concentration.
    pub concentration: BTreeMap<u64, u64>,
    pub casts: u64,
    pub log: Vec<Record>,
    pub tracks: Vec<Track>,
    /// Row-two cooldowns: slot to the scene time it is ready.
    pub ready: BTreeMap<u8, f32>,
    /// Prop poses at the start of the last tick, for presentation.
    previous: Vec<(DVec3, DQuat)>,
    /// Momentum lost as dynamic bodies are removed.
    #[serde(default)]
    pub removed: u64,
    /// Standing wind walls and what they track.
    #[serde(default)]
    pub wind: wind_wall::Wind,
    #[serde(default)]
    pub levitations: levitate::Levitations,
    /// Reverse Gravity's casts, creatures, and falls.
    #[serde(default)]
    pub reverse_gravity: crate::reverse_gravity::game::State,
    /// Each caster's Telekinesis hand and grip.
    #[serde(default)]
    pub telekinesis: BTreeMap<u64, crate::telekinesis::Telekinesis>,
    /// Feather Fall's wards, reaction picks, and followed falls.
    #[serde(default)]
    pub feather_fall: feather_fall::State,
    /// Gust of Wind Lines, the scene flames they put out, and archers.
    #[serde(default)]
    pub gust: gust_of_wind::State,
    /// Raised Wall of Stone panels, their joints, and debris.
    #[serde(default)]
    pub wall_of_stone: wall_of_stone::State,
    /// Active Black Tentacles casts.
    #[serde(default)]
    pub tentacles: Vec<black_tentacles::Active>,
    /// Black Tentacles damage the game has yet to apply: actor and amount.
    #[serde(default)]
    pub tentacle_damage: Vec<(u64, i32)>,
    /// Scene time of the last step, s, for log lines written between steps.
    #[serde(default)]
    pub time: f32,
    /// Whether the agent controller may cast Black Tentacles. Off by
    /// default, so encounters recorded before the spell replay unchanged;
    /// the live chamber turns it on.
    #[serde(default)]
    pub agent_tentacles: bool,
}

impl Default for SpellWorld {
    fn default() -> Self {
        Self::new(&[], 0)
    }
}

impl SpellWorld {
    /// A world whose static bodies are the scene's collision boxes.
    pub fn new(statics: &[physics::kinematic::Aabb], seed: u64) -> Self {
        let mut world = physics::World::new(1. / 120.);
        for aabb in statics {
            let center = (aabb.min + aabb.max) * 0.5;
            let body = world.add(
                physics::Body::new(1., DVec3::ONE, center).with_kind(physics::BodyKind::Static),
            );
            world.add_collider(
                physics::Collider::new(
                    body,
                    physics::Shape::Cuboid {
                        half: (aabb.max - aabb.min) * 0.5,
                    },
                )
                .with_material(Material::Stone.physics()),
            );
        }
        Self {
            ledger: Ledger::new(DVec3::ZERO, world.momentum(DVec3::ZERO)),
            world,
            props: vec![],
            dice: Dice::new(seed),
            fields: vec![],
            owned: vec![],
            concentration: BTreeMap::new(),
            casts: 0,
            log: vec![],
            tracks: vec![],
            ready: BTreeMap::new(),
            previous: vec![],
            removed: 0,
            wind: wind_wall::Wind::default(),
            levitations: Default::default(),
            reverse_gravity: Default::default(),
            telekinesis: BTreeMap::new(),
            feather_fall: feather_fall::State::default(),
            gust: gust_of_wind::State::default(),
            wall_of_stone: Default::default(),
            tentacles: vec![],
            tentacle_damage: vec![],
            time: 0.,
            agent_tentacles: false,
        }
    }

    pub fn validate(&self, instance: u64) -> Result<(), String> {
        self.world.check_version()?;
        self.dice.validate()?;
        self.levitations.validate(self.props.len(), self.casts)?;
        self.wall_of_stone.validate(self)?;
        let bodies = self.world.bodies().len();
        let mut lives = std::collections::BTreeSet::new();
        if self.props.len() > MAX_PROPS
            || self.log.len() > 256
            || self.tracks.len() > 256
            || self.fields.len() > 64
            || self.owned.len() > 64
            || self.previous.len() > self.props.len()
            || self.props.iter().any(|p| {
                p.body.0 as usize >= bodies
                    || p.collider.0 as usize >= self.world.colliders().len()
                    || self.world.colliders()[p.collider.0 as usize].body != p.body
                    || p.life.instance != instance
                    || p.life.entity < PROP_ENTITY_BASE
                    || !lives.insert(p.life)
                    || p.spec.validate().is_err()
                    || p.removed != self.world[p.body].removed
                    || p.owner.is_some_and(|cast| cast > self.casts)
            })
            || self.fields.iter().any(|f| {
                f.area.validate().is_err() || !f.acceleration.is_finite() || !f.expires.is_finite()
            })
            || self
                .world
                .bodies()
                .iter()
                .any(|b| !b.pos.is_finite() || !b.vel.is_finite() || !b.omega.is_finite())
            || self.concentration.values().any(|cast| *cast > self.casts)
            || self.wind.validate(self.casts).is_err()
            || self.reverse_gravity.validate(self.props.len()).is_err()
            || self.telekinesis.len() > 16
            || self
                .telekinesis
                .values()
                .any(|t| t.hand.0 as usize >= bodies || t.cast > self.casts)
            || self.feather_fall.validate().is_err()
            || self.gust.validate(self.casts).is_err()
            || !self.time.is_finite()
            || self.tentacles.len() > 8
            || self.tentacle_damage.len() > 256
            || self.tentacles.iter().any(|t| {
                t.cast > self.casts
                    || t.proxies.len() > 64
                    || t.proxies
                        .iter()
                        .map(|p| p.body)
                        .chain(t.spell.owned().0)
                        .any(|b| b.0 as usize >= bodies)
            })
        {
            return Err("Invalid spell world checkpoint".into());
        }
        Ok(())
    }

    /// Starts a cast: a new cast ID. A concentration spell first ends the
    /// caster's previous concentration.
    pub fn begin_cast(&mut self, caster: u64, concentration: bool) -> Result<u64, String> {
        self.casts = self.casts.checked_add(1).ok_or("Spell casts exhausted")?;
        if concentration {
            if let Some(previous) = self.concentration.insert(caster, self.casts) {
                self.end_cast(previous)?;
            }
        }
        Ok(self.casts)
    }

    /// Adds a joint that the cast owns; it leaves when the cast ends.
    pub fn add_owned_joint(
        &mut self,
        cast: u64,
        spell: &str,
        caster: u64,
        joint: physics::Joint,
    ) -> physics::JointId {
        let id = self.world.add_joint(joint);
        match self.owned.iter_mut().find(|o| o.cast == cast) {
            Some(owned) => owned.joints.push(id),
            None => self.owned.push(Owned {
                cast,
                spell: spell.into(),
                caster,
                joints: vec![id],
                expires: None,
            }),
        }
        id
    }

    /// Adds an area that pushes on bodies and characters inside it.
    pub fn add_field(&mut self, field: SpellField) -> Result<(), String> {
        field.area.validate()?;
        if self.fields.len() >= 64 || !field.acceleration.is_finite() {
            return Err("Invalid spell field".into());
        }
        self.fields.push(field);
        Ok(())
    }

    /// Ends a cast: its fields, joints, and bodies leave the world.
    pub fn end_cast(&mut self, cast: u64) -> Result<(), String> {
        self.wind.end_cast(cast, &mut self.world, &self.props);
        black_tentacles::end(self, cast, self.time);
        self.fields.retain(|f| f.cast != cast);
        self.gust.end(cast);
        self.concentration.retain(|_, held| *held != cast);
        self.levitations.end_cast(cast);
        let owned: Vec<_> = self
            .owned
            .iter()
            .filter(|o| o.cast == cast)
            .cloned()
            .collect();
        self.owned.retain(|o| o.cast != cast);
        for joint in owned.iter().flat_map(|o| o.joints.iter()) {
            self.world.remove_joint(*joint);
        }
        let props: Vec<_> = (0..self.props.len())
            .filter(|i| self.props[*i].owner == Some(cast) && !self.props[*i].removed)
            .collect();
        for index in props {
            self.remove_prop(index)?;
        }
        Ok(())
    }

    /// Ends the concentration a caster holds, as on death.
    pub fn end_concentration(&mut self, caster: u64) -> Result<(), String> {
        if let Some(cast) = self.concentration.remove(&caster) {
            self.end_cast(cast)?;
        }
        Ok(())
    }

    /// Adds a prop whose box is centered on `center`, turned `yaw` about
    /// the vertical. A secured prop is a static body.
    pub fn add_prop(
        &mut self,
        life: physics::queries::Life,
        name: &str,
        spec: PropSpec,
        center: DVec3,
        yaw: f64,
        owner: Option<u64>,
    ) -> Result<usize, String> {
        spec.validate()?;
        if self.props.len() >= MAX_PROPS {
            return Err("Spell prop budget exceeded".into());
        }
        if life.entity < PROP_ENTITY_BASE || self.props.iter().any(|p| p.life == life) {
            return Err("Prop life collides with another identity".into());
        }
        if !center.is_finite() || !yaw.is_finite() || name.len() > 64 {
            return Err("Invalid prop placement".into());
        }
        let rotation = DQuat::from_rotation_y(yaw);
        let mut body = physics::Body::new(
            spec.mass,
            physics::Body::box_inertia(spec.mass, spec.dimensions),
            center + rotation * spec.center_of_mass,
        );
        body.orientation = rotation;
        body.prev_orientation = rotation;
        if spec.secured {
            body = body.with_kind(physics::BodyKind::Static);
        }
        let id = self.world.add(body);
        let collider = self.world.add_collider(
            physics::Collider::new(
                id,
                physics::Shape::Cuboid {
                    half: spec.dimensions * 0.5,
                },
            )
            .at(-spec.center_of_mass, DQuat::IDENTITY)
            .with_material(spec.material.physics()),
        );
        self.props.push(Prop {
            life,
            name: name.into(),
            hit_points: spec.hit_points,
            spec,
            body: id,
            collider,
            owner,
            removed: false,
        });
        self.previous.clear();
        Ok(self.props.len() - 1)
    }

    /// Removes a prop: its body leaves the world and its momentum leaves
    /// the ledger under the "removed" term.
    pub fn remove_prop(&mut self, index: usize) -> Result<(), String> {
        let prop = self.props.get_mut(index).ok_or("Unknown prop")?;
        if prop.removed {
            return Ok(());
        }
        prop.removed = true;
        let body = prop.body;
        let lost = Momentum::of(&self.world[body], self.ledger.origin);
        if self.world[body].moves() {
            self.ledger.add(
                "removed",
                Momentum {
                    linear: -lost.linear,
                    angular: -lost.angular,
                },
            );
        }
        self.world.remove_body(body);
        self.removed += 1;
        Ok(())
    }

    /// Center of a prop's collision box, m.
    pub fn prop_center(&self, index: usize) -> DVec3 {
        let prop = &self.props[index];
        self.world.colliders()[prop.collider.0 as usize]
            .pose(&self.world)
            .0
    }

    /// The pose of a prop's box between the last tick's start and now.
    pub fn prop_pose(&self, index: usize, alpha: f64) -> (DVec3, DQuat) {
        let prop = &self.props[index];
        let body = &self.world[prop.body];
        let offset = -prop.spec.center_of_mass;
        let (pos, rotation) = self
            .previous
            .get(index)
            .map(|(p, q)| {
                (
                    p.lerp(body.pos, alpha.clamp(0., 1.)),
                    q.slerp(body.orientation, alpha.clamp(0., 1.)),
                )
            })
            .unwrap_or((body.pos, body.orientation));
        (pos + rotation * offset, rotation)
    }

    /// The eight corners of a prop's collision box, world frame.
    pub fn prop_corners(&self, index: usize) -> [DVec3; 8] {
        let prop = &self.props[index];
        let (center, rotation) = self.world.colliders()[prop.collider.0 as usize].pose(&self.world);
        let half = prop.spec.dimensions * 0.5;
        std::array::from_fn(|i| {
            let sign = DVec3::new(
                if i & 1 == 0 { -1. } else { 1. },
                if i & 2 == 0 { -1. } else { 1. },
                if i & 4 == 0 { -1. } else { 1. },
            );
            center + rotation * (half * sign)
        })
    }

    /// Initial speed that slides a resting prop exactly `distance` on the
    /// stone floor: v₀ = √(2 μ g d), μ being the pair's friction.
    pub fn prop_push_speed(&self, index: usize, distance: f64) -> f64 {
        let floor = Material::Stone.physics().friction;
        let friction = (self.props[index].spec.material.physics().friction * floor).sqrt();
        (2. * friction * GRAVITY * distance.max(0.)).sqrt()
    }

    /// Calibrated SRD push of a prop: the initial horizontal speed that
    /// stops at `distance` on flat ground, recorded under `spell` in the
    /// ledger. Secured and removed props do not move.
    pub fn push_prop(
        &mut self,
        index: usize,
        direction: DVec3,
        distance: f64,
        spell: &str,
    ) -> Result<bool, String> {
        let direction = DVec3::new(direction.x, 0., direction.z).normalize_or_zero();
        let prop = self.props.get(index).ok_or("Unknown prop")?;
        if prop.spec.secured || prop.removed || direction == DVec3::ZERO {
            return Ok(false);
        }
        let body = prop.body;
        let speed = self.prop_push_speed(index, distance);
        self.world.wake(body);
        let mass = self.world[body].mass;
        let at = self.world[body].pos;
        let impulse = direction * speed * mass;
        self.world[body].apply_impulse_at(impulse, at);
        self.ledger
            .add_impulse(&format!("spell:{spell}"), impulse, at);
        Ok(true)
    }

    /// Applies an impulse to a prop at a point, recorded under `term`.
    pub fn impulse_prop(
        &mut self,
        index: usize,
        impulse: DVec3,
        at: DVec3,
        term: &str,
    ) -> Result<(), String> {
        let prop = self.props.get(index).ok_or("Unknown prop")?;
        if prop.spec.secured || prop.removed || !impulse.is_finite() || !at.is_finite() {
            return Ok(());
        }
        let body = prop.body;
        self.world.wake(body);
        self.world[body].apply_impulse_at(impulse, at);
        self.ledger.add_impulse(term, impulse, at);
        Ok(())
    }

    /// Records the prop poses presentation interpolates from.
    pub fn begin_tick(&mut self) {
        self.previous = self
            .props
            .iter()
            .map(|p| (self.world[p.body].pos, self.world[p.body].orientation))
            .collect();
    }

    /// Advances the rigid world `steps` fixed steps, recording every
    /// external impulse in the ledger, and expires fields that end by `time`.
    pub fn step(&mut self, steps: u32, time: f32) -> Result<(), String> {
        self.time = time;
        let expired: Vec<u64> = self
            .fields
            .iter()
            .filter(|f| f.expires <= time)
            .map(|f| f.cast)
            .chain(
                self.owned
                    .iter()
                    .filter(|o| o.expires.is_some_and(|at| at <= time))
                    .map(|o| o.cast),
            )
            .collect();
        for cast in expired {
            self.end_cast(cast)?;
        }
        wall_of_stone::after_tick(self, time)?;
        if self.props.iter().all(|p| p.removed || p.spec.secured)
            && self.telekinesis.is_empty()
            && self.tentacles.is_empty()
        {
            self.world.tick += u64::from(steps);
            return Ok(());
        }
        let gravity = DVec3::new(0., -GRAVITY, 0.);
        for _ in 0..steps {
            let dt = self.world.dt;
            self.wind
                .before_step(&mut self.world, &self.props, &mut self.ledger);
            self.levitations
                .drive(&mut self.world, &mut self.ledger, &self.props);
            // Tentacle forces wake their segments, so they come first.
            black_tentacles::before_step(self, time);
            // What the field adds: only bodies that respond this step.
            for tk in self.telekinesis.values_mut() {
                tk.substep_before(&mut self.world);
            }
            let mut field_terms: Vec<(String, DVec3, DVec3)> = vec![];
            for body in self.world.bodies() {
                let responds = body.kind == physics::BodyKind::Dynamic
                    && !body.removed
                    && (!body.sleeping || body.vel != DVec3::ZERO || body.omega != DVec3::ZERO);
                if !responds {
                    continue;
                }
                field_terms.push(("gravity".into(), gravity * body.mass * dt, body.pos));
                for field in self.fields.iter().filter(|f| f.area.contains(body.pos)) {
                    field_terms.push((
                        format!("spell:{}", field.spell),
                        field.accel_at(body.pos, body.vel, gravity) * body.mass * dt,
                        body.pos,
                    ));
                }
            }
            let fields = Fields {
                gravity,
                fields: &self.fields,
            };
            self.world.step(&fields);
            wall_of_stone::after_world_step(self);
            for (term, impulse, at) in field_terms {
                self.ledger.add_impulse(&term, impulse, at);
            }
            black_tentacles::after_step(self, time);
            let slept: Vec<usize> = self
                .world
                .slept
                .iter()
                .map(|(id, _)| id.0 as usize)
                .collect();
            let awake = |world: &physics::World, i: usize| {
                world.bodies()[i].responds() || slept.contains(&i)
            };
            let mut contact_terms = vec![];
            for c in &self.world.contacts {
                let (a, b) = (c.body_a.0 as usize, c.body_b.0 as usize);
                let sign = match (awake(&self.world, a), awake(&self.world, b)) {
                    (false, true) => 1.,
                    (true, false) => -1.,
                    _ => continue,
                };
                contact_terms.push((c.impulse * sign, c.point, c.twist * sign));
            }
            for (impulse, point, twist) in contact_terms {
                self.ledger.add_impulse("static contact", impulse, point);
                self.ledger.add(
                    "static contact",
                    Momentum {
                        linear: DVec3::ZERO,
                        angular: twist,
                    },
                );
            }
            for tk in self.telekinesis.values_mut() {
                tk.substep_after(&mut self.world, &mut self.ledger);
            }
            for (_, removed) in std::mem::take(&mut self.world.slept) {
                self.ledger.add(
                    "sleep",
                    Momentum {
                        linear: -removed.linear,
                        angular: -removed.angular,
                    },
                );
            }
        }
        Ok(())
    }

    /// Relative momentum residual: what the props' momentum has that the
    /// start and the recorded terms do not explain.
    pub fn ledger_error(&self) -> physics::LedgerError {
        self.ledger.error(self.world.momentum(self.ledger.origin))
    }

    /// Exchanges momentum between characters and the dynamic props they
    /// touch: a knocked character shoves a prop, and a moving prop shoves a
    /// character, each through one contact impulse using the character's
    /// reference mass. Walking alone does not shove; the sweep stops it.
    pub fn couple(&mut self, movers: &mut [Mover<'_>]) -> Result<(), String> {
        for mover in movers.iter_mut() {
            let c = &mut *mover.character;
            let (a, b) = (
                c.feet + DVec3::Y * CHARACTER_RADIUS,
                c.feet + DVec3::Y * (CHARACTER_HEIGHT - CHARACTER_RADIUS),
            );
            for index in 0..self.props.len() {
                let prop = &self.props[index];
                if prop.removed || prop.spec.secured {
                    continue;
                }
                let body = self.world[prop.body];
                let collider = self.world.colliders()[prop.collider.0 as usize];
                if collider
                    .pose(&self.world)
                    .0
                    .distance(c.feet + DVec3::Y * 0.9)
                    > collider.shape.bound() + CHARACTER_HEIGHT
                {
                    continue;
                }
                let segment = |q: DVec3| {
                    let ab = b - a;
                    a + ab * ((q - a).dot(ab) / ab.length_squared()).clamp(0., 1.)
                };
                let mut p = segment(body.pos);
                let mut q = collider.closest_point(&self.world, p);
                for _ in 0..3 {
                    p = segment(q);
                    q = collider.closest_point(&self.world, p);
                }
                let gap = p.distance(q);
                if gap > CHARACTER_RADIUS + CONTACT_GAP {
                    continue;
                }
                let normal = if gap > 1e-6 {
                    (q - p) / gap
                } else {
                    (body.pos - p).normalize_or_zero()
                };
                let normal = DVec3::new(normal.x, 0., normal.z).normalize_or_zero();
                if normal == DVec3::ZERO {
                    continue;
                }
                let own = c.external;
                let r = q - body.pos;
                let closing = (own - (body.vel + body.omega_world().cross(r))).dot(normal);
                if closing <= 1e-4 || (!c.knocked() && body.vel.length() < 0.05) {
                    continue;
                }
                self.world.wake(prop.body);
                let body = &self.world[prop.body];
                let angular = r.cross(normal);
                let k = 1. / mover.mass
                    + body.inverse_mass()
                    + angular.dot(body.inverse_inertia_world(angular));
                let j = (1. + CONTACT_RESTITUTION) * closing / k;
                let impulse = normal * j;
                self.impulse_prop(index, impulse, q, "character contact")?;
                c.external = (c.external - impulse / mover.mass).clamp_length_max(100.);
                c.external.y = 0.;
            }
        }
        Ok(())
    }

    /// Adds every live prop to a character query scene at its pose.
    pub fn insert_query_colliders(
        &self,
        scene: &mut physics::queries::Scene,
    ) -> Result<(), String> {
        use physics::queries::{Mesh, MeshCollider, Usage};
        for prop in self.props.iter().filter(|p| !p.removed) {
            let half = prop.spec.dimensions * 0.5;
            let offset = -prop.spec.center_of_mass;
            scene.insert(MeshCollider {
                key: prop.query_key(),
                layers: 1,
                usage: Usage::Blocking,
                mesh: Mesh::from_box(offset - half, offset + half)?,
            })?;
        }
        self.sync_query_poses(scene)
    }

    /// Moves props' query colliders to their bodies and drops removed ones.
    pub fn sync_query_poses(&self, scene: &mut physics::queries::Scene) -> Result<(), String> {
        for prop in &self.props {
            if prop.removed {
                scene.remove(prop.query_key());
                continue;
            }
            let body = &self.world[prop.body];
            scene.set_pose(
                prop.query_key(),
                physics::queries::Pose {
                    position: body.pos,
                    rotation: body.orientation.normalize(),
                },
            )?;
        }
        Ok(())
    }

    /// Appends one log line, keeping the most recent 256.
    pub fn record(&mut self, at: f32, spell: &str, text: String, save: Option<Save>) {
        if self.log.len() >= 256 {
            self.log.remove(0);
        }
        self.log.push(Record {
            at,
            spell: spell.into(),
            text,
            save,
        });
    }

    /// Starts measuring a target's displacement.
    pub fn track(&mut self, track: Track) {
        if self.tracks.len() >= 256 {
            self.tracks.remove(0);
        }
        self.tracks.push(track);
    }

    pub fn body(&self, id: BodyId) -> &physics::Body {
        &self.world[id]
    }
}

#[cfg(test)]
mod tests;
