//! Regenerate the original coast pack without loading its generated bytes.

#[test]
#[ignore = "Explicit coast artifact queue compiler"]
fn compile_coast_pack() {
    use std::path::PathBuf;
    use verse_zone_everglade::zones::everglade_pack::{
        compile,
        format::{self, Limits},
    };
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets/verse/coast/source");
    let out = root.parent().unwrap();
    let limits = Limits {
        pack_bytes: 48 * 1024 * 1024,
        decoded_texture_bytes: 32 * 1024 * 1024,
        texture_edge: 512,
        triangles: 120_000,
        model_triangles: 12_000,
        committed_bytes: 64 * 1024 * 1024,
        character_triangles: 800,
        body_bytes: 64 * 1024 * 1024,
    };
    let sets = [
        "rocks",
        "beach",
        "harbor",
        "lighthouse",
        "boats",
        "reef",
        "beasts",
        "lod",
    ];
    let compiled = compile::compile(&root, &sets, None, &limits).unwrap();
    let decoded = format::decode(&compiled.bytes, &limits).unwrap();
    std::fs::write(
        out.join(format!("{}.vtp", compiled.sha256)),
        &compiled.bytes,
    )
    .unwrap();
    let record = serde_json::json!({"sha256":compiled.sha256,"bytes":compiled.bytes.len(),"models":compiled.models,"triangles":compiled.triangles,"decoded_texture_bytes":compiled.decoded_texture_bytes,"source_bytes":compiled.source_bytes,"forms":decoded.forms.iter().map(|f|(&f.name,f.triangles())).collect::<Vec<_>>()});
    std::fs::write(
        out.join("pack.json"),
        serde_json::to_vec_pretty(&record).unwrap(),
    )
    .unwrap();
    println!("pub const SHA256: &str = \"{}\";", compiled.sha256);
    println!("pub const BYTES: u64 = {};", compiled.bytes.len());
    println!(
        "const BUNDLED: &[u8] = include_bytes!(\"../../../assets/verse/coast/{}.vtp\");",
        compiled.sha256
    );
}
fn main() {}
