/**
 * OpenAgents Desktop — Electron main process (#8574).
 *
 * Scaffolded from the pinned MIT-licensed LuanRoger/electron-shadcn template
 * (see UPSTREAM.md) and hardened per the issue's mandatory first-commit
 * boundary: contextIsolation on, nodeIntegration OFF, sandbox ON, no webview,
 * deny-by-default permissions/navigation/window-open, and a minimal
 * contextBridge preload (no ipcRenderer, no MessagePort/oRPC bridge, no
 * updater, no devtools installer).
 *
 * Plain TypeScript, bundled by `scripts/build.ts` (Bun) into `dist/`.
 */
import path from "node:path"
import { randomUUID } from "node:crypto"
import { BrowserWindow, app, dialog, ipcMain, safeStorage, session, shell, type IpcMainInvokeEvent } from "electron"
import { Effect } from "effect"
import {
  buildInterruptTurnIntent,
  buildStartTurnIntent,
} from "@openagentsinc/khala-sync-client"

// macOS derives the running application/menu identity before `ready`; set
// both Electron's application name and the process title at module startup so
// development (`electron .`) and packaged launches agree on "OpenAgents".
app.setName("OpenAgents")
process.title = "OpenAgents"

import {
  CodexAccountsChannel,
  CodexConnectOpenChannel,
  CodexConnectStartChannel,
  CodexConnectStatusChannel,
} from "./codex-connect-contract.ts"
import { makeCodexConnectService, makeFixtureSpawnPylon } from "./codex-connect.ts"
import {
  ProviderAccountsListChannel,
  ProviderAccountsUsageChannel,
  decodeProviderAccountUsageRequest,
  unavailableProviderAccountUsageResult,
} from "./provider-accounts-contract.ts"
import { makeFixtureProviderAccountsSpawn, makeProviderAccountsService } from "./provider-accounts.ts"
import { FleetStageChannel, decodeFleetStageRequest, unavailableFleetStageResult } from "./fleet-contract.ts"
import { submitFleetBrief } from "./fleet-control.ts"
import { completeChatTurn } from "./chat-service.ts"
import { DesktopChatTurnChannel, DesktopHydrateThreadChannel, DesktopNewThreadChannel, DesktopOpenThreadChannel, DesktopThreadsChannel, decode, DesktopThreadRequestSchema, DesktopTurnRequestSchema, type DesktopMessage } from "./chat-contract.ts"
import {
  FABLE_LOCAL_FINAL_TEXT_LIMIT,
  FableLocalAvailabilityChannel,
  FableLocalEventChannel,
  FableLocalInterruptChannel,
  FableLocalStartChannel,
  decodeFableLocalInterruptRequest,
  decodeFableLocalStartRequest,
  fableLocalFailureMessage,
  fableLocalModelNoteText,
  fableLocalTraceNoteText,
} from "./fable-local-contract.ts"
import {
  FABLE_LOCAL_FIXTURE_ACCOUNT,
  makeFableLocalRuntime,
  makeFixtureFableLocalQuery,
} from "./fable-local-runtime.ts"
import { makeThreadStore } from "./thread-store.ts"
import { makeCodexHistoryHost } from "./codex-history-host.ts"
import { makeDesktopHostLifecycle } from "./desktop-host-lifecycle.ts"
import {
  DesktopWorkspaceChooseChannel,
  DesktopWorkspaceFilesChannel,
  DesktopWorkspaceGitDiffChannel,
  DesktopWorkspaceGitStatusChannel,
  DesktopWorkspaceReadChannel,
  DesktopWorkspaceSaveChannel,
  DesktopWorkspaceSummaryChannel,
  decodeWorkspaceFileRequest,
  decodeWorkspaceGitDiffRequest,
  decodeWorkspaceSaveRequest,
} from "./workspace-contract.ts"
import { openWorkspaceService } from "./workspace-service.ts"
import {
  DesktopRuntimeGatewayEventChannel,
  DesktopRuntimeGatewayInvokeChannel,
  decodeDesktopRuntimeGatewayRequest,
  invalidDesktopRuntimeGatewayResponse,
  type DesktopRuntimeGatewayRequest,
} from "./runtime-gateway-contract.ts"
import { createDesktopRuntimeGateway } from "./runtime-gateway.ts"
import { desktopRuntimeCapabilities } from "./runtime-gateway.ts"
import {
  desktopOperationRef,
  decodeDesktopOperationContext,
  makeDesktopCorrelationJournal,
  type DesktopOperationContext,
} from "./desktop-operation-context.ts"
import { openDesktopSyncHost } from "./desktop-sync-host.ts"
import {
  openDesktopSessionVault,
  type DesktopSessionVault,
} from "./desktop-session-vault.ts"
import { recoverVerifiedDesktopSession } from "./desktop-session-recovery.ts"
import { traceAcceptanceJourney, traceAcceptanceReload } from "./electron-trace-acceptance.ts"
import { resolveLiveProofConfig, runLiveProof } from "./live-proof.ts"
import {
  signInDesktopSession,
  signOutDesktopSession,
} from "./desktop-session-pkce.ts"

const here = import.meta.dirname
const smokeMode = process.env.OPENAGENTS_DESKTOP_SMOKE === "1"
// Generated by the desktop build from the exact checked-in OpenAgents mobile
// icon. Keep it inside the packaged runtime directory: no renderer or
// user-controlled path has filesystem authority through this asset.
const desktopIconPath = path.join(here, "assets", "openagents-icon.png")

// Smoke runs headless and can never complete a real browser device-auth, so
// it uses a scripted fixture child (clearly logged; never in normal runs).
if (smokeMode) {
  console.log("[openagents-desktop] codex-connect running in SMOKE FIXTURE mode (no real pylon spawn)")
}
const codexConnect = makeCodexConnectService(here, {
  ...(smokeMode ? { spawnPylon: makeFixtureSpawnPylon() } : {}),
  openExternal: (url) => shell.openExternal(url),
})
if (smokeMode) {
  console.log("[openagents-desktop] provider-accounts running in SMOKE FIXTURE mode (no real pylon spawn)")
}
const providerAccounts = makeProviderAccountsService(
  here,
  smokeMode ? { spawnPylon: makeFixtureProviderAccountsSpawn() } : {},
)
let desktopSessionVault: DesktopSessionVault | null = null
let desktopSessionState: "signed_out" | "credential_present_unverified" | "session_ready" | "denied" | "unavailable" = "unavailable"
const desktopOperationSessionRef = `session.desktop.${randomUUID()}`
let desktopCorrelationSequence = 0
const desktopCorrelationJournal = makeDesktopCorrelationJournal()
const operationContextFor = (request: DesktopRuntimeGatewayRequest): DesktopOperationContext | null => {
  const operationRef = desktopOperationRef(request)
  const runRef = request.kind === "command" && "runRef" in request.command
    ? request.command.runRef
    : undefined
  if (request.context !== undefined) {
    return request.context.operationRef === operationRef &&
      request.context.sessionRef === desktopOperationSessionRef &&
      request.context.runRef === runRef
      ? request.context
      : null
  }
  return decodeDesktopOperationContext({
    operationRef,
    sessionRef: desktopOperationSessionRef,
    correlationRef: `correlation.desktop.${++desktopCorrelationSequence}`,
    ...(runRef === undefined ? {} : { runRef }),
  })
}
const connectVerifiedDesktopSync = (): boolean => {
  const syncHost = hostLifecycle.sync()
  if (syncHost === null || desktopSessionVault === null) return false
  try {
    const credential = desktopSessionVault.load()
    if (credential === null) {
      syncHost.disconnectAuthenticated()
      return false
    }
    syncHost.connectAuthenticated({
      verification:"server_verified",
      baseUrl: process.env.OPENAGENTS_COM_BASE_URL ?? "https://openagents.com",
      ownerUserId: credential.ownerUserId,
      authToken: () => desktopSessionVault?.load()?.accessToken ?? "",
    })
    return true
  } catch {
    syncHost.disconnectAuthenticated()
    return false
  }
}
const runtimeGateway = createDesktopRuntimeGateway(() => desktopRuntimeCapabilities({
  sessionLocalState: desktopSessionState,
  syncLocalState: hostLifecycle.sync()?.status().state === "local_ready" ? "ready" : "unavailable",
  syncNetworkPhase: hostLifecycle.sync()?.status().syncPhase ?? "closed",
}), {
  signIn: async signal => {
    if (desktopSessionVault === null) return { state: "unavailable" }
    const previous = desktopSessionState
    const result = await signInDesktopSession({
      vault: desktopSessionVault,
      openExternal: url => shell.openExternal(url),
      signal,
    })
    desktopSessionState = result.state === "verified"
      ? connectVerifiedDesktopSync() ? "session_ready" : "unavailable"
      : result.state === "cancelled"
        ? previous
        : "unavailable"
    return result
  },
  signOut: async signal => {
    if (desktopSessionVault === null) return { state: "unavailable" }
    // Close and purge the account-linked Sync session before the renderer can
    // race another command against remote token revocation.
    try { hostLifecycle.sync()?.unlinkAccount() } catch { /* remote revocation still runs */ }
    const result = await signOutDesktopSession({ vault: desktopSessionVault, signal })
    desktopSessionState = result.state
    return result
  },
}, () => desktopSessionState === "credential_present_unverified" ? "unverified" : desktopSessionState, () => {
  const service = hostLifecycle.sync()?.conversation() ?? null
  if (service === null) return null
  return {
    catalog: () => ({
      status: service.personalStatus(),
      threads: Effect.runSync(service.listConfirmedThreads()),
    }),
    thread: threadRef => {
      Effect.runSync(service.openThread(threadRef))
      return {
        status: service.threadStatus(threadRef),
        messages: Effect.runSync(service.listConfirmedMessages(threadRef)),
      }
    },
    create: (threadRef, title) => Number(Effect.runSync(service.createThread({
      threadId: threadRef,
      title,
    }))),
    append: (threadRef, messageRef, body) => Number(Effect.runSync(service.appendMessage({
      threadId: threadRef,
      messageId: messageRef,
      body,
    }))),
  }
}, () => {
  const service = hostLifecycle.sync()?.timeline() ?? null
  if (service === null) return null
  return {
    snapshot: runRef => {
      Effect.runSync(service.open(runRef))
      return Effect.runSync(service.snapshot(runRef))
    },
    snapshotForThread: threadRef =>
      Effect.runSync(service.snapshotForThread(threadRef)),
  }
}, () => ({
  catalog: () => hostLifecycle.history()!.run({ kind: "history_catalog", sessionsRoot: codexSessionsRoot() }) as Promise<import("./codex-history-contract.ts").CodexHistoryCatalog>,
  page: (threadRef, offset, limit) => hostLifecycle.history()!.run({ kind: "history_page", sessionsRoot: codexSessionsRoot(), threadRef, offset, limit }) as Promise<import("./codex-history-contract.ts").CodexHistoryPage | null>,
}),()=>hostLifecycle.sync()===null?"local_unavailable":hostLifecycle.sync()!.status().identityTier, () => {
  const service = hostLifecycle.sync()?.runtime() ?? null
  if (service === null && smokeMode) {
    return {
      start: (_input, operationContext) => {
        if (operationContext !== undefined) desktopCorrelationJournal.record("sync.intent", operationContext)
        return 1
      },
      interrupt: (_input, operationContext) => {
        if (operationContext !== undefined) desktopCorrelationJournal.record("sync.intent", operationContext)
        return 1
      },
      outcome: () => null,
    }
  }
  if (service === null) return null
  const context = (lane: "codex_app_server" | "claude_pylon" = "codex_app_server") => {
    const createdAt = new Date()
    return {
      expiresAtIso: new Date(createdAt.getTime() + 5 * 60_000).toISOString(),
      nowIso: createdAt.toISOString(),
      surface: "desktop" as const,
      target: { lane },
    }
  }
  return {
    outcome: input => Effect.runSync(service.outcome(input)),
    start: (input, operationContext) => {
      if (operationContext !== undefined) desktopCorrelationJournal.record("sync.intent", operationContext)
      return Number(Effect.runSync(service.startTurn(buildStartTurnIntent({
        context: context(input.lane),
        correlationRefs: operationContext === undefined ? [] : [
          operationContext.operationRef,
          operationContext.sessionRef,
          operationContext.correlationRef,
        ],
        messageRef: input.messageRef,
        threadRef: input.threadRef,
        turnRef: input.runRef,
      }))))
    },
    interrupt: (input, operationContext) => {
      if (operationContext !== undefined) desktopCorrelationJournal.record("sync.intent", operationContext)
      return Number(Effect.runSync(service.interruptTurn(buildInterruptTurnIntent({
        commandRef: input.commandRef,
        context: context(),
        correlationRefs: operationContext === undefined ? [] : [
          operationContext.operationRef,
          operationContext.sessionRef,
          operationContext.correlationRef,
        ],
        threadRef: input.threadRef,
        turnRef: input.runRef,
      }))))
    },
  }
}, (stage, context) => desktopCorrelationJournal.record(stage, context))

const isTrustedRuntimeGatewaySender = (event: IpcMainInvokeEvent): boolean => {
  const frame = event.senderFrame
  if (frame === null || frame !== event.sender.mainFrame) return false
  try {
    const url = new URL(frame.url)
    return url.protocol === "file:" && path.basename(url.pathname) === "index.html"
  } catch {
    return false
  }
}

ipcMain.handle(DesktopRuntimeGatewayInvokeChannel, (event, value: unknown) => {
  if (!isTrustedRuntimeGatewaySender(event)) {
    return { kind: "request_rejected", reason: "untrusted_renderer" } as const
  }
  const request = decodeDesktopRuntimeGatewayRequest(value)
  if (request === null) return invalidDesktopRuntimeGatewayResponse()
  const context = operationContextFor(request)
  if (context === null) return invalidDesktopRuntimeGatewayResponse()
  desktopCorrelationJournal.record("ipc.received", context)
  const gateway = hostLifecycle.runtime()
  if (gateway === null) return { kind: "request_rejected", reason: "gateway_disposed", context } as const
  const outcome = gateway.request(request, context)
  const recordReturned = <Value>(response: Value): Value => {
    desktopCorrelationJournal.record("ipc.returned", context)
    return response
  }
  return outcome instanceof Promise ? outcome.then(recordReturned) : recordReturned(outcome)
})

// Interim development identity ONLY. The frozen macOS bundle ID / Windows
// AppUserModelId / deep-link scheme / userData path / update channel are an
// owner decision (issue #8574 scope 1, NEEDS_OWNER) before the first packaged
// build. Never reuse com.openagents.khala.code.desktop or khala-code://.
app.setPath("userData", path.join(app.getPath("appData"), "OpenAgentsDesktopDev"))

const hardenSession = (): void => {
  // Deny-by-default: this shell requests no runtime permissions.
  session.defaultSession.setPermissionRequestHandler((_webContents, _permission, callback) => {
    callback(false)
  })
}

/**
 * A deliberately single-purpose IPC boundary. The preload validates first and
 * main validates again; the renderer never gets filesystem, token, arbitrary
 * command, or loopback request authority.
 */
ipcMain.handle(FleetStageChannel, async (_event, value: unknown) => {
  const request = decodeFleetStageRequest(value)
  return request === null ? unavailableFleetStageResult() : submitFleetBrief(request)
})

const threads = () => makeThreadStore(path.join(app.getPath("userData"), "threads.json"))
const codexSessionsRoot = () => path.resolve(
  process.env.OPENAGENTS_DESKTOP_CODEX_SESSIONS ?? (
    smokeMode
      ? path.join(here, "..", "tests", "fixtures", "codex-smoke", "sessions")
      : path.join(app.getPath("home"), ".codex", "sessions")
  ),
)
const codexHistoryHost = makeCodexHistoryHost(new URL("./codex-history-worker.js", import.meta.url))
const hostLifecycle = makeDesktopHostLifecycle({
  runtime: runtimeGateway,
  account: codexConnect,
  history: codexHistoryHost,
})
// Local file authority begins only after an explicit directory-picker choice.
// A process working directory or environment default is not user selection.
const workspaceSnapshot = () => {
  const workspace = hostLifecycle.workspace()
  if (workspace === null) return null
  try { return workspace.summary() } catch { return null }
}
ipcMain.handle(DesktopWorkspaceSummaryChannel, () => workspaceSnapshot())
ipcMain.handle(DesktopWorkspaceFilesChannel, () => workspaceSnapshot())
ipcMain.handle(DesktopWorkspaceChooseChannel, async () => {
  const result = await dialog.showOpenDialog({ properties: ["openDirectory", "createDirectory"] })
  if (result.canceled || result.filePaths[0] === undefined) return workspaceSnapshot()
  hostLifecycle.replaceWorkspace(openWorkspaceService(result.filePaths[0]))
  return workspaceSnapshot()
})
ipcMain.handle(DesktopWorkspaceReadChannel, (_event, value: unknown) => {
  const workspace = hostLifecycle.workspace()
  const request = decodeWorkspaceFileRequest(value)
  return request === null || workspace === null ? null : workspace.read(request.path)
})
ipcMain.handle(DesktopWorkspaceSaveChannel, (_event, value: unknown) => {
  const workspace = hostLifecycle.workspace()
  const request = decodeWorkspaceSaveRequest(value)
  if (request === null) return { state: "unavailable", message: "The file save request is invalid." }
  if (workspace === null) return { state: "unavailable", message: "Choose a workspace folder before saving." }
  return workspace.save(request)
})
ipcMain.handle(DesktopWorkspaceGitStatusChannel, () =>
  hostLifecycle.workspace()?.gitStatus() ?? { state: "unavailable" },
)
ipcMain.handle(DesktopWorkspaceGitDiffChannel, (_event, value: unknown) => {
  const workspace = hostLifecycle.workspace()
  const request = decodeWorkspaceGitDiffRequest(value)
  if (request === null) return { state: "unavailable", message: "The diff request is invalid." }
  if (workspace === null) return { state: "unavailable", message: "Choose a workspace folder before reviewing changes." }
  return workspace.gitDiff(request.path)
})
// List is intentionally metadata-only: a large local history must not
// serialize every transcript into the renderer merely to draw the sidebar.
ipcMain.handle(DesktopThreadsChannel, () => hostLifecycle.history()?.run({ kind: "list", sessionsRoot: codexSessionsRoot(), ...(smokeMode ? { limit: 1 } : {}) }) ?? Promise.resolve(null))
ipcMain.handle(DesktopNewThreadChannel, () => threads().newThread())
ipcMain.handle(DesktopOpenThreadChannel, (_event, value: unknown) => {
  const request = decode(DesktopThreadRequestSchema, value) as { id: string } | null
  return request === null ? null : hostLifecycle.history()?.run({ kind: "detail", sessionsRoot: codexSessionsRoot(), id: request.id }) ?? null
})
ipcMain.handle(DesktopHydrateThreadChannel, (_event, value: unknown) => {
  const request = decode(DesktopThreadRequestSchema, value) as { id: string } | null
  return request === null ? null : hostLifecycle.history()?.run({ kind: "detail", sessionsRoot: codexSessionsRoot(), id: request.id, messageLimit: 40 }) ?? null
})
ipcMain.handle(DesktopChatTurnChannel, async (_event, value: unknown) => {
  const request = decode(DesktopTurnRequestSchema, value) as { id: string; message: string } | null
  if (request === null || request.message.trim() === "" || request.message.length > 8_000) {
    return { ok: false, error: "That message could not be sent." }
  }
  const store = threads()
  const user: DesktopMessage = { key: randomUUID(), role: "user", text: request.message.trim(), timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }
  const saved = store.append(request.id, user)
  if (saved === null) return { ok: false, error: "That conversation no longer exists." }
  try {
    const text = await completeChatTurn(saved.notes)
    const thread = store.append(saved.id, { key: randomUUID(), role: "assistant", text, timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) })
    return { ok: true, thread }
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : "The model request failed." }
  }
})

// Fable local lane (#8712): a REAL streaming Claude turn on this machine in
// local (not-signed-in) mode, on an isolated `~/.claude-pylon-*` account home
// — never the default `~/.claude`, never a login flow, never the cloud
// gateway. Smoke runs a scripted fixture (clearly logged; never normal runs).
if (smokeMode) {
  console.log("[openagents-desktop] fable-local running in SMOKE FIXTURE mode (no real Claude SDK session)")
}
const fableLocal = makeFableLocalRuntime({
  scratchRoot: () => path.join(app.getPath("userData"), "fable-local"),
  ...(smokeMode
    ? {
        queryImpl: async () => makeFixtureFableLocalQuery(),
        discoverImpl: async () => [FABLE_LOCAL_FIXTURE_ACCOUNT],
      }
    : {}),
})
ipcMain.handle(FableLocalAvailabilityChannel, () => fableLocal.availability())
ipcMain.handle(FableLocalInterruptChannel, (_event, value: unknown) => {
  const request = decodeFableLocalInterruptRequest(value)
  return request === null ? false : fableLocal.interrupt(request.turnRef)
})
ipcMain.handle(FableLocalStartChannel, async (event, value: unknown) => {
  const request = decodeFableLocalStartRequest(value)
  if (request === null || request.message.trim() === "") {
    return { ok: false, error: "That message could not be sent." }
  }
  const store = threads()
  const user: DesktopMessage = {
    key: randomUUID(),
    role: "user",
    text: request.message.trim(),
    timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
  }
  const saved = store.append(request.threadRef, user)
  if (saved === null) return { ok: false, error: "That conversation no longer exists." }
  // History authority is main's own thread store — the renderer supplies only
  // the new message. The just-appended user note is the prompt, not history.
  const history = saved.notes.slice(0, -1).map(note => ({ role: note.role, text: note.text }))
  const sender = event.sender
  const result = await fableLocal.runTurn({
    turnRef: request.turnRef,
    threadRef: request.threadRef,
    history,
    message: request.message.trim(),
    emit: turnEvent => {
      // Persist tool trace and effective-model lines so the finalized
      // transcript keeps the same evidence the live stream showed (bounded by
      // the store's note cap).
      if (turnEvent.kind === "tool_use" || turnEvent.kind === "tool_result" ||
        turnEvent.kind === "model_effective") {
        store.append(request.threadRef, {
          key: randomUUID(),
          role: "system",
          text: turnEvent.kind === "model_effective"
            ? fableLocalModelNoteText(turnEvent.model)
            : fableLocalTraceNoteText(turnEvent),
          timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        })
      }
      if (sender.isDestroyed()) return
      // Attach the persisted thread snapshot (user message included) to the
      // start event so the renderer can stream onto real thread state.
      const event = turnEvent.kind === "turn_started" ? { ...turnEvent, thread: saved } : turnEvent
      sender.send(FableLocalEventChannel, { turnRef: request.turnRef, event })
    },
  })
  if (!result.ok) return { ok: false, error: fableLocalFailureMessage(result.reason, result.detail) }
  const thread = store.append(request.threadRef, {
    key: randomUUID(),
    role: "assistant",
    text: result.text.slice(0, FABLE_LOCAL_FINAL_TEXT_LIMIT),
    timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
  })
  return thread === null
    ? { ok: false, error: "That conversation no longer exists." }
    : { ok: true, thread }
})

// Codex account reconnect (#8640 unblock): renderer-argument-free channels
// only. Main owns the pylon child processes and the verification URL; the
// renderer polls typed status and never sees tokens, emails, or raw output.
ipcMain.handle(CodexAccountsChannel, () => hostLifecycle.account()?.listAccounts() ?? Promise.resolve({ state: "unavailable" }))
ipcMain.handle(CodexConnectStartChannel, () => hostLifecycle.account()?.start() ?? { state: "failed", reason: "pylon_runtime_unavailable" })
ipcMain.handle(CodexConnectStatusChannel, () => hostLifecycle.account()?.status() ?? { state: "failed", reason: "pylon_runtime_unavailable" })
ipcMain.handle(CodexConnectOpenChannel, () => hostLifecycle.account()?.openVerification() ?? Promise.resolve(false))

// Provider-neutral fleet accounts (#8712): read-only projections. List takes
// no renderer arguments; usage validates the account ref on both sides of the
// boundary. Failures stay typed `{ ok: false, reason }` — never a throw.
ipcMain.handle(ProviderAccountsListChannel, () => providerAccounts.listProviderAccounts())
ipcMain.handle(ProviderAccountsUsageChannel, (_event, value: unknown) => {
  const request = decodeProviderAccountUsageRequest(value)
  return request === null
    ? unavailableProviderAccountUsageResult("unknown", "invalid_request")
    : providerAccounts.fetchProviderAccountUsage(request.ref)
})

// Deny-by-default for every WebContents: no navigation away from the bundled
// renderer, no window.open, no <webview> attachment.
app.on("web-contents-created", (_event, contents) => {
  contents.on("will-navigate", (event) => {
    event.preventDefault()
  })
  contents.on("will-attach-webview", (event) => {
    event.preventDefault()
  })
  contents.setWindowOpenHandler(() => ({ action: "deny" }))
})

const createWindow = (): BrowserWindow => {
  const window = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 720,
    minHeight: 480,
    backgroundColor: "#03060b",
    show: false,
    title: "OpenAgents",
    icon: desktopIconPath,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      nodeIntegrationInSubFrames: false,
      sandbox: true,
      webviewTag: false,
      webSecurity: true,
      devTools: !app.isPackaged,
      spellcheck: false,
      backgroundThrottling: false,
      preload: path.join(here, "preload.cjs"),
    },
  })
  const closeWindowScope = hostLifecycle.registerWindow(`window.${window.id}`, runtimeGateway.subscribe(event => {
    if (!window.isDestroyed()) window.webContents.send(DesktopRuntimeGatewayEventChannel, event)
  }))
  window.once("closed", closeWindowScope)
  window.once("ready-to-show", () => {
    window.show()
  })
  void window.loadFile(path.join(here, "renderer/index.html"))
  return window
}

/**
 * Smoke mode (`bun run smoke`): proves the Effect Native intent loop runs
 * inside the real Electron renderer — types into the catalog-rendered
 * composer, submits, and asserts the message row appended AND the composer
 * cleared (the v29 clear-on-submit contract, effect-native#72). When
 * `OPENAGENTS_DESKTOP_SMOKE_SHOTS` names a directory, it captures pixel
 * receipts (shell / composer-typed / composer-cleared). Exits 0/1.
 */
const smokeShotsDir = process.env.OPENAGENTS_DESKTOP_SMOKE_SHOTS

const smokeWaitForShell = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const deadline = Date.now() + 15000
  while (Date.now() < deadline && document.querySelector('[data-en-key="shell-root"]') === null) {
    await wait(100)
  }
  return document.querySelector('[data-en-key="shell-root"]') !== null
})()`

const smokeRuntimeGatewayBootstrap = `(async () => {
  const bridge = globalThis.openagentsDesktop
  if (typeof bridge?.runtimeRequest !== "function") return { ok: false, reason: "Runtime Gateway bridge missing" }
  const result = await bridge.runtimeRequest({
    kind: "query",
    requestId: "smoke-runtime-bootstrap",
    query: { id: "runtime.bootstrap" },
  })
  return {
    ok: result?.kind === "query_result" &&
      result.requestId === "smoke-runtime-bootstrap" &&
      result.result?.protocolVersion === 7 &&
      result.result?.lifecycle === "ready" &&
      result.result?.capabilities?.some((capability) => capability.id === "codex-history" && capability.state === "available"),
    protocolVersion: result?.result?.protocolVersion,
    lifecycle: result?.result?.lifecycle,
    capabilityCount: result?.result?.capabilities?.length ?? 0,
  }
})()`

const smokeLifecycleCorrelation = `(async () => {
  const bridge = globalThis.openagentsDesktop
  if (typeof bridge?.runtimeRequest !== "function") return { ok: false, reason: "Runtime Gateway bridge missing" }
  const bootstrap = await bridge.runtimeRequest({
    kind: "query",
    requestId: "smoke-correlation-bootstrap",
    query: { id: "runtime.bootstrap" },
  })
  const sessionRef = bootstrap?.context?.sessionRef
  if (typeof sessionRef !== "string") return { ok: false, reason: "Session correlation missing" }
  const context = {
    operationRef: "operation.desktop.smoke.start",
    sessionRef,
    correlationRef: "correlation.desktop.smoke",
    runRef: "run.desktop.smoke",
  }
  const response = await bridge.runtimeRequest({
    kind: "command",
    commandId: context.operationRef,
    context,
    command: {
      id: "conversation.start",
      threadRef: "thread.desktop.smoke",
      messageRef: "message.desktop.smoke",
      runRef: context.runRef,
    },
  })
  return {
    ok: response?.kind === "runtime_command_outcome" &&
      response.status === "unknown_pending_reconcile" &&
      response.context?.operationRef === context.operationRef &&
      response.context?.sessionRef === context.sessionRef &&
      response.context?.correlationRef === context.correlationRef &&
      response.context?.runRef === context.runRef,
  }
})()`

const smokeTypeIntoComposer = `(() => {
  const input = document.querySelector('[data-en-key="shell-input"] input')
  if (input === null) return { ok: false, reason: "composer input never mounted" }
  input.focus()
  input.value = "Pixel-proof: real chat rows on the shared catalog"
  input.dispatchEvent(new Event("input", { bubbles: true }))
  return { ok: true, typed: input.value }
})()`

const smokeCodexHistoryDetails = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const first = document.querySelector('[data-en-key^="sidebar-thread-"]')
  if (first === null) return { ok: false, reason: "history row never mounted" }
  first.click()
  const deadline = Date.now() + 15000
  while (Date.now() < deadline && document.querySelector('[data-en-key="history-workspace-split"]') === null) {
    await wait(100)
  }
  const sidebar = document.querySelector('[data-en-key="sidebar-history-list"] > [data-en-role="section-label"]')
  const detail = document.querySelector('[data-en-key="history-workspace-split"]')
  return { ok: sidebar?.textContent === "Codex history · all time" && detail !== null }
})()`

const smokeOpenCommandPalette = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-command-palette-toggle"]')
  if (button === null) return { ok: false, reason: "Command palette button never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && document.querySelector('[data-en-key="desktop-command-palette"]') === null) {
    await wait(50)
  }
  const palette = document.querySelector('[data-en-key="desktop-command-palette"]')
  const files = document.querySelector('[data-en-key="desktop-command-workspace.files"]')
  return { ok: palette !== null && files !== null }
})()`

const smokeCloseCommandPalette = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="desktop-command-palette-close"]')
  if (button === null) return { ok: false, reason: "Command palette close button never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && document.querySelector('[data-en-key="desktop-command-palette"]') !== null) {
    await wait(50)
  }
  return { ok: document.querySelector('[data-en-key="desktop-command-palette"]') === null }
})()`

const smokeOpenFleetDesk = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-fleet-toggle"]')
  if (button === null) return { ok: false, reason: "Fleet toggle never mounted" }
  button.click()
  const deadline = Date.now() + 20_000
  while (Date.now() < deadline && document.querySelector('[data-en-key="fleet-desk"]') === null) {
    await wait(50)
  }
  const objective = document.querySelector('[data-en-key="fleet-objective"] input')
  const dispatch = document.querySelector('[data-en-key="fleet-stage-request"]')
  const status = document.querySelector('[data-en-key="fleet-authority-status"]')
  return {
    ok: objective !== null && dispatch !== null && status !== null && status.textContent === "Draft",
    status: status === null ? null : status.textContent,
  }
})()`

const smokeSubmitComposer = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const input = document.querySelector('[data-en-key="shell-input"] input')
  if (input === null) return { ok: false, reason: "composer input never mounted" }
  const messageCount = () =>
    document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message]').length
  const messagesBefore = messageCount()
  input.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true }))
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && (messageCount() < messagesBefore + 2 || input.value !== "")) {
    await wait(50)
  }
  const userRow = document.querySelector(
    '[data-en-key="shell-transcript"] [data-en-message][data-en-role="user"]'
  )
  const responseRow = Array.from(
    document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message][data-en-role="assistant"], [data-en-key="shell-transcript"] [data-en-message][data-en-role="system"]')
  ).at(-1)
  const sender = userRow === null ? null : userRow.querySelector('[data-en-role="sender"]')
  const body = userRow === null ? null : userRow.querySelector('[data-en-role="body"]')
  const responseSender = responseRow === undefined ? null : responseRow.querySelector('[data-en-role="sender"]')
  return {
    ok:
      messageCount() === messagesBefore + 2 &&
      input.value === "" &&
      sender !== null && sender.textContent === "YOU" &&
      body !== null && body.textContent.includes("Pixel-proof") &&
      !body.textContent.includes("YOU") &&
      responseSender !== null && (responseSender.textContent === "ASSISTANT" || responseSender.textContent === "SYSTEM"),
    messagesBefore,
    messagesAfter: messageCount(),
    inputAfterSubmit: input.value,
    senderChip: sender === null ? null : sender.textContent,
    responseSenderChip: responseSender === null ? null : responseSender.textContent,
  }
})()`

const smokePingLoop = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-ping"]')
  if (button === null) return { ok: false, reason: "ping button never mounted" }
  const badgeText = () => {
    const badge = document.querySelector('[data-en-key="shell-ping-count"]')
    return badge === null ? null : badge.textContent
  }
  const before = badgeText()
  const messageCount = () =>
    document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message]').length
  const notesBefore = messageCount()
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && badgeText() === before) {
    await wait(50)
  }
  const after = badgeText()
  return {
    ok: after !== before && after !== null && after.includes("1") && messageCount() === notesBefore + 1,
    before,
    after,
    notesBefore,
    notesAfter: messageCount(),
  }
})()`

const smokeOpenSettings = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-settings-toggle"]')
  if (button === null) return { ok: false, reason: "Settings toggle never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (
    Date.now() < deadline &&
    document.querySelector('[data-en-key="settings-account-codex-2-readiness"]') === null
  ) {
    await wait(50)
  }
  const revoked = document.querySelector('[data-en-key="settings-account-codex-2-readiness"]')
  const connect = document.querySelector('[data-en-key="settings-connect-codex"]')
  return {
    ok: revoked !== null && revoked.textContent === "credentials_revoked" &&
      connect !== null && connect.textContent === "Connect Codex account",
    revokedChip: revoked === null ? null : revoked.textContent,
    connectLabel: connect === null ? null : connect.textContent,
  }
})()`

const smokeConnectCodex = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="settings-connect-codex"]')
  if (button === null) return { ok: false, reason: "Connect button never mounted" }
  button.click()
  const deadline = Date.now() + 10000
  while (
    Date.now() < deadline &&
    document.querySelector('[data-en-key="settings-connect-code"]') === null
  ) {
    await wait(100)
  }
  const code = document.querySelector('[data-en-key="settings-connect-code"]')
  const link = document.querySelector('[data-en-key="settings-connect-link"]')
  return {
    ok: code !== null && code.textContent === "1234-ABCDE" &&
      link !== null && link.textContent === "https://auth.openai.com/codex/device",
  }
})()`

const smokeCloseSettings = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="settings-back"]')
  if (button === null) return { ok: false, reason: "Settings back button never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && document.querySelector('[data-en-key="shell-main"]') === null) {
    await wait(50)
  }
  return { ok: document.querySelector('[data-en-key="shell-main"]') !== null }
})()`

// Regression guard (#8712 polish): New chat from a LOADED Codex history page
// must land in a fresh empty transcript, never the historical conversation.
const smokeNewChatFromHistory = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  if (document.querySelector('[data-en-key="history-workspace-split"]') === null) {
    return { ok: false, reason: "history detail was not loaded before New chat" }
  }
  const button = document.querySelector('[data-en-key="workspace-new-chat"]')
  if (button === null) return { ok: false, reason: "New chat dock button never mounted" }
  button.click()
  const deadline = Date.now() + 15000
  while (Date.now() < deadline && (
    document.querySelector('[data-en-key="shell-transcript"]') === null ||
    document.querySelector('[data-en-key="history-workspace-split"]') !== null
  )) {
    await wait(50)
  }
  const transcript = document.querySelector('[data-en-key="shell-transcript"]')
  const split = document.querySelector('[data-en-key="history-workspace-split"]')
  const messages = document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message]').length
  const composer = document.querySelector('[data-en-key="shell-input"] input')
  return {
    ok: transcript !== null && split === null && messages === 0 &&
      composer !== null && composer.disabled === false,
    historyStillLoaded: split !== null,
    messages,
    composerMounted: composer !== null,
  }
})()`

// Fable local streaming journey (#8712): from the fresh chat, the Fable chip
// must be enabled (fixture account), Codex must be visibly disabled with its
// caption, and a send must stream PROGRESSIVE text (a partial snapshot is
// observed before the final), render the read-only tool trace line, then
// finalize with the composer re-enabled. Fixture-driven; the event mapping,
// IPC bridge, thread persistence, and renderer streaming path are all real.
const smokeFableLocalStreaming = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const fable = document.querySelector('[data-en-key="shell-harness-fable"]')
  const codex = document.querySelector('[data-en-key="shell-harness-codex"]')
  const caption = document.querySelector('[data-en-key="shell-harness-caption"]')
  if (fable === null || codex === null) return { ok: false, reason: "harness chips never mounted" }
  if (fable.disabled !== false) return { ok: false, reason: "fable chip disabled despite fixture account" }
  if (codex.disabled !== true) return { ok: false, reason: "codex chip enabled without a session" }
  if (caption === null || !caption.textContent.includes("Codex — requires OpenAgents session")) {
    return { ok: false, reason: "codex unavailable caption missing" }
  }
  fable.click()
  const input = document.querySelector('[data-en-key="shell-input"] input')
  if (input === null) return { ok: false, reason: "composer input never mounted" }
  input.focus()
  input.value = "Stream a fable-local proof"
  input.dispatchEvent(new Event("input", { bubbles: true }))
  const assistantText = () => {
    const rows = document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message][data-en-role="assistant"]')
    const last = rows[rows.length - 1]
    return last === undefined ? "" : (last.querySelector('[data-en-role="body"]')?.textContent ?? "")
  }
  input.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true }))
  const finalText = "Fable local streaming proof."
  let sawPartial = false
  const deadline = Date.now() + 20000
  while (Date.now() < deadline) {
    const text = assistantText()
    if (text.length > 0 && text !== finalText) sawPartial = true
    if (text === finalText && input.disabled === false) break
    await wait(25)
  }
  const trace = Array.from(
    document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message][data-en-role="system"]'),
  ).some((row) => (row.textContent ?? "").includes("Read"))
  return {
    ok: sawPartial && assistantText() === finalText && input.disabled === false && trace,
    sawPartial,
    finalized: assistantText() === finalText,
    trace,
    text: assistantText(),
  }
})()`

// Fleet workspace journey (#8712): the dock's Fleet button must open the
// read-only fleet panel with the fixture provider accounts rendered.
const smokeOpenFleetWorkspace = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="workspace-fleet"]')
  if (button === null) return { ok: false, reason: "Fleet dock button never mounted" }
  button.click()
  const deadline = Date.now() + 15000
  while (Date.now() < deadline && document.querySelector('[data-en-key="fleet-accounts-table"]') === null) {
    await wait(50)
  }
  const panel = document.querySelector('[data-en-key="workspace-fleet-panel"]')
  const expected = ["codex", "codex-2", "claude-pylon-3"]
  const refs = expected.map((ref) =>
    document.querySelector('[data-en-key="fleet-ref-' + ref + '"]')?.textContent ?? null)
  const revoked = document.querySelector('[data-en-key="fleet-readiness-codex-2"]')
  const dots = document.querySelector('[data-en-key="fleet-status-dots"]')
  return {
    ok: panel !== null && dots !== null &&
      refs.every((value, index) => value === expected[index]) &&
      revoked !== null && revoked.textContent === "credentials-missing",
    refs,
    revokedReadiness: revoked === null ? null : revoked.textContent,
  }
})()`

const captureShot = async (window: BrowserWindow, name: string): Promise<void> => {
  if (smokeShotsDir === undefined || smokeShotsDir === "") return
  const image = await window.webContents.capturePage()
  const { mkdirSync, writeFileSync } = await import("node:fs")
  mkdirSync(smokeShotsDir, { recursive: true })
  writeFileSync(path.join(smokeShotsDir, `${name}.png`), image.toPNG())
  console.log(`[openagents-desktop smoke] shot ${name}.png`)
}

const runSmoke = (window: BrowserWindow): void => {
  const finish = (code: 0 | 1): void => {
    hostLifecycle.dispose()
    const snapshot = hostLifecycle.snapshot()
    const active = Number(snapshot.runtime) + Number(snapshot.workspace) + Number(snapshot.sync) +
      Number(snapshot.account) + Number(snapshot.history) + snapshot.windowCount
    const ok = snapshot.disposed && active === 0
    console.log("[openagents-desktop smoke] lifecycle-teardown", JSON.stringify({ ok, active }))
    desktopCorrelationJournal.dispose()
    app.exit(ok ? code : 1)
  }
  const timeout = setTimeout(() => {
    console.error("[openagents-desktop smoke] TIMEOUT waiting for renderer")
    finish(1)
  }, 45_000)
  let tracePass = 0
  window.webContents.on("did-finish-load", () => {
    void (async () => {
      const step = async (name: string, script: string): Promise<void> => {
        const result: unknown = await window.webContents.executeJavaScript(script, true)
        const ok =
          result === true ||
          (typeof result === "object" && result !== null && (result as { ok?: unknown }).ok === true)
        if (!ok) {
          throw new Error(`${name} failed: ${JSON.stringify(result)}`)
        }
        console.log(`[openagents-desktop smoke] ${name} OK`, JSON.stringify(result))
      }
      try {
        if (tracePass === 1) {
          await step("codex-trace-reload-restoration", traceAcceptanceReload)
          clearTimeout(timeout)
          console.log("[openagents-desktop smoke] OK")
          finish(0)
          return
        }
        await step("shell-mounted", smokeWaitForShell)
        await step("runtime-gateway-bootstrap", smokeRuntimeGatewayBootstrap)
        await step("lifecycle-correlation", smokeLifecycleCorrelation)
        if (!desktopCorrelationJournal.complete("correlation.desktop.smoke")) {
          throw new Error(`lifecycle-correlation journal incomplete: ${desktopCorrelationJournal.stages("correlation.desktop.smoke").join(",")}`)
        }
        console.log("[openagents-desktop smoke] lifecycle-correlation-journal OK", JSON.stringify({ ok: true, stageCount: 4 }))
        await captureShot(window, "01-shell")
        await step("command-palette-open", smokeOpenCommandPalette)
        await captureShot(window, "02-command-palette")
        await step("command-palette-close", smokeCloseCommandPalette)
        await step("recent-codex-history-selected-detail", smokeCodexHistoryDetails)
        await step("codex-trace-acceptance", traceAcceptanceJourney)
        await captureShot(window, "03-codex-history-detail")
        // Settings / Codex reconnect (#8640 unblock). Headless smoke cannot
        // complete a real browser device-auth, so main runs a FIXTURE spawn:
        // the awaiting_browser receipt below shows scripted fixture data.
        await step("settings-open-accounts", smokeOpenSettings)
        await captureShot(window, "04-settings-accounts")
        await step("settings-connect-awaiting-browser-FIXTURE", smokeConnectCodex)
        await captureShot(window, "05-settings-awaiting-browser-fixture")
        await step("settings-back-to-chat", smokeCloseSettings)
        // With the historical page still loaded, New chat must yield a fresh
        // empty transcript (the on-camera regression), then the Fleet dock
        // button must render the fixture accounts panel.
        await step("new-chat-from-history-empty-transcript", smokeNewChatFromHistory)
        await captureShot(window, "06-new-chat-empty")
        // Fable local turn is FIXTURE-driven in smoke (no real Claude SDK
        // session; a scripted delta sequence flows through the real mapping).
        await step("fable-local-streamed-turn-FIXTURE", smokeFableLocalStreaming)
        await captureShot(window, "07-fable-local-streamed")
        await step("fleet-workspace-fixture-accounts", smokeOpenFleetWorkspace)
        await captureShot(window, "08-fleet-workspace")
        tracePass = 1
        window.webContents.reload()
      } catch (error) {
        clearTimeout(timeout)
        console.error("[openagents-desktop smoke] ERROR", error instanceof Error ? error.message : "unknown smoke failure")
        finish(1)
      }
    })()
  })
}

void app.whenReady().then(async () => {
  // macOS does not use BrowserWindow's icon for the active Dock tile in a
  // development Electron process. Set both native surfaces to the same mobile
  // PNG so the running desktop application has one product identity.
  if (process.platform === "darwin") app.dock?.setIcon(desktopIconPath)
  hardenSession()
  try {
    const syncHost = openDesktopSyncHost({
      databasePath: path.join(app.getPath("userData"), "sync", "khala-sync.sqlite"),
      randomId: randomUUID,
    })
    hostLifecycle.replaceSync(syncHost)
  } catch {
    console.error("[openagents-desktop] local Sync persistence unavailable")
  }
  try {
    desktopSessionVault = openDesktopSessionVault({
      filePath: path.join(app.getPath("userData"), "session", "native-session.enc"),
      safeStorage,
    })
    desktopSessionState = desktopSessionVault.recover().state
    if (desktopSessionState === "credential_present_unverified") {
      const recovery = await recoverVerifiedDesktopSession({
        vault: desktopSessionVault,
      })
      desktopSessionState = recovery.state === "verified"
        ? connectVerifiedDesktopSync() ? "session_ready" : "unavailable"
        : recovery.state
      if(recovery.state==="denied")hostLifecycle.sync()?.unlinkAccount()
    }
  } catch {
    desktopSessionVault = null
    desktopSessionState = "unavailable"
    console.error("[openagents-desktop] OS-encrypted session custody unavailable")
  }
  runtimeGateway.start()
  const window = createWindow()
  // Episode 250 live-proof driver (#8712): REAL adapters (no smoke fixtures),
  // mutually exclusive with smoke. See ./live-proof.ts — additive only.
  const liveProof = resolveLiveProofConfig(process.env, app.getPath("userData"))
  if (liveProof.enabled && liveProof.conflict) {
    console.error("[openagents-desktop live-proof] OPENAGENTS_DESKTOP_LIVE_PROOF and OPENAGENTS_DESKTOP_SMOKE are mutually exclusive; refusing to run either")
    app.exit(1)
    return
  }
  if (smokeMode) runSmoke(window)
  else if (liveProof.enabled) {
    runLiveProof(window, {
      outDir: liveProof.outDir,
      exit: (code) => {
        hostLifecycle.dispose()
        providerAccounts.dispose()
        desktopCorrelationJournal.dispose()
        app.exit(code)
      },
    })
  }
})

app.on("window-all-closed", () => {
  if (process.platform !== "darwin" || smokeMode) {
    app.quit()
  }
})

app.on("before-quit", () => {
  hostLifecycle.dispose()
  providerAccounts.dispose()
  fableLocal.dispose()
  desktopCorrelationJournal.dispose()
})

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})
