/**
 * OpenAgents Desktop — Electron main process (#8574).
 *
 * Scaffolded from the pinned MIT-licensed LuanRoger/electron-shadcn template
 * (see UPSTREAM.md) and hardened per the issue's mandatory first-commit
 * boundary: contextIsolation on, nodeIntegration OFF, sandbox ON, no webview,
 * deny-by-default permissions/navigation/window-open, and a minimal
 * contextBridge preload (no ipcRenderer, no MessagePort/oRPC bridge, no
 * updater, no devtools installer).
 *
 * Plain TypeScript, bundled by `scripts/build.ts` (Bun) into `dist/`.
 */
import path from "node:path"
import { randomUUID } from "node:crypto"
import { Worker } from "node:worker_threads"
import { BrowserWindow, app, dialog, ipcMain, safeStorage, session, shell, type IpcMainInvokeEvent } from "electron"
import { Effect } from "effect"

// macOS derives the running application/menu identity before `ready`; set
// both Electron's application name and the process title at module startup so
// development (`electron .`) and packaged launches agree on "OpenAgents".
app.setName("OpenAgents")
process.title = "OpenAgents"

import {
  CodexAccountsChannel,
  CodexConnectOpenChannel,
  CodexConnectStartChannel,
  CodexConnectStatusChannel,
} from "./codex-connect-contract.ts"
import { makeCodexConnectService, makeFixtureSpawnPylon } from "./codex-connect.ts"
import { FleetStageChannel, decodeFleetStageRequest, unavailableFleetStageResult } from "./fleet-contract.ts"
import { submitFleetBrief } from "./fleet-control.ts"
import { completeChatTurn } from "./chat-service.ts"
import { DesktopChatTurnChannel, DesktopHydrateThreadChannel, DesktopNewThreadChannel, DesktopOpenThreadChannel, DesktopThreadsChannel, decode, DesktopThreadRequestSchema, DesktopTurnRequestSchema, type DesktopMessage } from "./chat-contract.ts"
import { makeThreadStore } from "./thread-store.ts"
import {
  DesktopWorkspaceChooseChannel,
  DesktopWorkspaceFilesChannel,
  DesktopWorkspaceGitDiffChannel,
  DesktopWorkspaceGitStatusChannel,
  DesktopWorkspaceReadChannel,
  DesktopWorkspaceSaveChannel,
  DesktopWorkspaceSummaryChannel,
  decodeWorkspaceFileRequest,
  decodeWorkspaceGitDiffRequest,
  decodeWorkspaceSaveRequest,
} from "./workspace-contract.ts"
import { inspectWorkspace, readWorkspaceFile, saveWorkspaceFile, workspaceGitDiff, workspaceGitStatus } from "./workspace-service.ts"
import {
  DesktopRuntimeGatewayEventChannel,
  DesktopRuntimeGatewayInvokeChannel,
  decodeDesktopRuntimeGatewayRequest,
  invalidDesktopRuntimeGatewayResponse,
} from "./runtime-gateway-contract.ts"
import { createDesktopRuntimeGateway } from "./runtime-gateway.ts"
import { desktopRuntimeCapabilities } from "./runtime-gateway.ts"
import { openDesktopSyncHost, type DesktopSyncHost } from "./desktop-sync-host.ts"
import {
  openDesktopSessionVault,
  type DesktopSessionVault,
} from "./desktop-session-vault.ts"
import { recoverVerifiedDesktopSession } from "./desktop-session-recovery.ts"
import { traceAcceptanceJourney, traceAcceptanceReload } from "./electron-trace-acceptance.ts"
import {
  signInDesktopSession,
  signOutDesktopSession,
} from "./desktop-session-pkce.ts"

const here = import.meta.dirname
const smokeMode = process.env.OPENAGENTS_DESKTOP_SMOKE === "1"
// Generated by the desktop build from the exact checked-in OpenAgents mobile
// icon. Keep it inside the packaged runtime directory: no renderer or
// user-controlled path has filesystem authority through this asset.
const desktopIconPath = path.join(here, "assets", "openagents-icon.png")

// Smoke runs headless and can never complete a real browser device-auth, so
// it uses a scripted fixture child (clearly logged; never in normal runs).
if (smokeMode) {
  console.log("[openagents-desktop] codex-connect running in SMOKE FIXTURE mode (no real pylon spawn)")
}
const codexConnect = makeCodexConnectService(here, {
  ...(smokeMode ? { spawnPylon: makeFixtureSpawnPylon() } : {}),
  openExternal: (url) => shell.openExternal(url),
})
let desktopSyncHost: DesktopSyncHost | null = null
let desktopSessionVault: DesktopSessionVault | null = null
let desktopSessionState: "signed_out" | "credential_present_unverified" | "session_ready" | "denied" | "unavailable" = "unavailable"
const connectVerifiedDesktopSync = (): boolean => {
  if (desktopSyncHost === null || desktopSessionVault === null) return false
  try {
    const credential = desktopSessionVault.load()
    if (credential === null) {
      desktopSyncHost.disconnectAuthenticated()
      return false
    }
    desktopSyncHost.connectAuthenticated({
      verification:"server_verified",
      baseUrl: process.env.OPENAGENTS_COM_BASE_URL ?? "https://openagents.com",
      ownerUserId: credential.ownerUserId,
      authToken: () => desktopSessionVault?.load()?.accessToken ?? "",
    })
    return true
  } catch {
    desktopSyncHost.disconnectAuthenticated()
    return false
  }
}
const runtimeGateway = createDesktopRuntimeGateway(() => desktopRuntimeCapabilities({
  sessionLocalState: desktopSessionState,
  syncLocalState: desktopSyncHost?.status().state === "local_ready" ? "ready" : "unavailable",
  syncNetworkPhase: desktopSyncHost?.status().syncPhase ?? "closed",
}), {
  signIn: async () => {
    if (desktopSessionVault === null) return { state: "unavailable" }
    const previous = desktopSessionState
    const result = await signInDesktopSession({
      vault: desktopSessionVault,
      openExternal: url => shell.openExternal(url),
    })
    desktopSessionState = result.state === "verified"
      ? connectVerifiedDesktopSync() ? "session_ready" : "unavailable"
      : result.state === "cancelled"
        ? previous
        : "unavailable"
    return result
  },
  signOut: async () => {
    if (desktopSessionVault === null) return { state: "unavailable" }
    const result = await signOutDesktopSession({ vault: desktopSessionVault })
    if (result.state === "signed_out") desktopSyncHost?.unlinkAccount()
    desktopSessionState = result.state
    return result
  },
}, () => desktopSessionState === "credential_present_unverified" ? "unverified" : desktopSessionState, () => {
  const service = desktopSyncHost?.conversation() ?? null
  if (service === null) return null
  return {
    catalog: () => ({
      status: service.personalStatus(),
      threads: Effect.runSync(service.listConfirmedThreads()),
    }),
    thread: threadRef => {
      Effect.runSync(service.openThread(threadRef))
      return {
        status: service.threadStatus(threadRef),
        messages: Effect.runSync(service.listConfirmedMessages(threadRef)),
      }
    },
    create: (threadRef, title) => Number(Effect.runSync(service.createThread({
      threadId: threadRef,
      title,
    }))),
    append: (threadRef, messageRef, body) => Number(Effect.runSync(service.appendMessage({
      threadId: threadRef,
      messageId: messageRef,
      body,
    }))),
  }
}, () => {
  const service = desktopSyncHost?.timeline() ?? null
  if (service === null) return null
  return {
    snapshot: runRef => {
      Effect.runSync(service.open(runRef))
      return Effect.runSync(service.snapshot(runRef))
    },
  }
}, () => ({
  catalog: () => runCodexHistoryWorker({ kind: "history_catalog", sessionsRoot: codexSessionsRoot() }) as Promise<import("./codex-history-contract.ts").CodexHistoryCatalog>,
  page: (threadRef, offset, limit) => runCodexHistoryWorker({ kind: "history_page", sessionsRoot: codexSessionsRoot(), threadRef, offset, limit }) as Promise<import("./codex-history-contract.ts").CodexHistoryPage | null>,
}),()=>desktopSyncHost===null?"local_unavailable":desktopSyncHost.status().identityTier)

const isTrustedRuntimeGatewaySender = (event: IpcMainInvokeEvent): boolean => {
  const frame = event.senderFrame
  if (frame === null || frame !== event.sender.mainFrame) return false
  try {
    const url = new URL(frame.url)
    return url.protocol === "file:" && path.basename(url.pathname) === "index.html"
  } catch {
    return false
  }
}

ipcMain.handle(DesktopRuntimeGatewayInvokeChannel, (event, value: unknown) => {
  if (!isTrustedRuntimeGatewaySender(event)) {
    return { kind: "request_rejected", reason: "untrusted_renderer" } as const
  }
  const request = decodeDesktopRuntimeGatewayRequest(value)
  return request === null ? invalidDesktopRuntimeGatewayResponse() : runtimeGateway.request(request)
})

runtimeGateway.subscribe(event => {
  for (const window of BrowserWindow.getAllWindows()) {
    if (!window.isDestroyed()) window.webContents.send(DesktopRuntimeGatewayEventChannel, event)
  }
})

// Interim development identity ONLY. The frozen macOS bundle ID / Windows
// AppUserModelId / deep-link scheme / userData path / update channel are an
// owner decision (issue #8574 scope 1, NEEDS_OWNER) before the first packaged
// build. Never reuse com.openagents.khala.code.desktop or khala-code://.
app.setPath("userData", path.join(app.getPath("appData"), "OpenAgentsDesktopDev"))

const hardenSession = (): void => {
  // Deny-by-default: this shell requests no runtime permissions.
  session.defaultSession.setPermissionRequestHandler((_webContents, _permission, callback) => {
    callback(false)
  })
}

/**
 * A deliberately single-purpose IPC boundary. The preload validates first and
 * main validates again; the renderer never gets filesystem, token, arbitrary
 * command, or loopback request authority.
 */
ipcMain.handle(FleetStageChannel, async (_event, value: unknown) => {
  const request = decodeFleetStageRequest(value)
  return request === null ? unavailableFleetStageResult() : submitFleetBrief(request)
})

const threads = () => makeThreadStore(path.join(app.getPath("userData"), "threads.json"))
const codexSessionsRoot = () => path.resolve(process.env.OPENAGENTS_DESKTOP_CODEX_SESSIONS ?? path.join(app.getPath("home"), ".codex", "sessions"))
type CodexHistoryRequest =
  | Readonly<{ kind: "list"; sessionsRoot: string; limit?: number }>
  | Readonly<{ kind: "detail"; sessionsRoot: string; id: string; messageLimit?: number }>
  | Readonly<{ kind: "history_catalog"; sessionsRoot: string }>
  | Readonly<{ kind: "history_page"; sessionsRoot: string; threadRef: string; offset?: number; limit?: number }>
let historyWorker: Worker | null = null
let historyRequestId = 0
const historyPending = new Map<number, (value: unknown) => void>()
const runCodexHistoryWorker = (request: CodexHistoryRequest): Promise<unknown> => new Promise((resolve) => {
  if (historyWorker === null) {
    historyWorker = new Worker(new URL("./codex-history-worker.js", import.meta.url))
    historyWorker.on("message", (message: { id?: unknown; ok?: unknown; result?: unknown }) => {
      if (typeof message.id !== "number") return
      const pending = historyPending.get(message.id); if (pending === undefined) return
      historyPending.delete(message.id); pending(message.ok === true ? message.result : null)
    })
    historyWorker.on("error", () => { for (const pending of historyPending.values()) pending(null); historyPending.clear(); historyWorker = null })
  }
  const id = ++historyRequestId
  historyPending.set(id, resolve)
  historyWorker.postMessage({ id, request })
})
// Local file authority begins only after an explicit directory-picker choice.
// A process working directory or environment default is not user selection.
let workspaceRoot: string | null = null
const workspaceSnapshot = () => {
  if (workspaceRoot === null) return null
  try { return inspectWorkspace(workspaceRoot) } catch { return null }
}
ipcMain.handle(DesktopWorkspaceSummaryChannel, () => workspaceSnapshot())
ipcMain.handle(DesktopWorkspaceFilesChannel, () => workspaceSnapshot())
ipcMain.handle(DesktopWorkspaceChooseChannel, async () => {
  const result = await dialog.showOpenDialog({ properties: ["openDirectory", "createDirectory"] })
  if (result.canceled || result.filePaths[0] === undefined) return workspaceSnapshot()
  workspaceRoot = path.resolve(result.filePaths[0])
  return workspaceSnapshot()
})
ipcMain.handle(DesktopWorkspaceReadChannel, (_event, value: unknown) => {
  const request = decodeWorkspaceFileRequest(value)
  return request === null || workspaceRoot === null ? null : readWorkspaceFile(workspaceRoot, request.path)
})
ipcMain.handle(DesktopWorkspaceSaveChannel, (_event, value: unknown) => {
  const request = decodeWorkspaceSaveRequest(value)
  if (request === null) return { state: "unavailable", message: "The file save request is invalid." }
  if (workspaceRoot === null) return { state: "unavailable", message: "Choose a workspace folder before saving." }
  return saveWorkspaceFile(workspaceRoot, request)
})
ipcMain.handle(DesktopWorkspaceGitStatusChannel, () =>
  workspaceRoot === null ? { state: "unavailable" } : workspaceGitStatus(workspaceRoot),
)
ipcMain.handle(DesktopWorkspaceGitDiffChannel, (_event, value: unknown) => {
  const request = decodeWorkspaceGitDiffRequest(value)
  if (request === null) return { state: "unavailable", message: "The diff request is invalid." }
  if (workspaceRoot === null) return { state: "unavailable", message: "Choose a workspace folder before reviewing changes." }
  return workspaceGitDiff(workspaceRoot, request.path)
})
// List is intentionally metadata-only: a large local history must not
// serialize every transcript into the renderer merely to draw the sidebar.
ipcMain.handle(DesktopThreadsChannel, () => runCodexHistoryWorker({ kind: "list", sessionsRoot: codexSessionsRoot(), ...(smokeMode ? { limit: 1 } : {}) }))
ipcMain.handle(DesktopNewThreadChannel, () => threads().newThread())
ipcMain.handle(DesktopOpenThreadChannel, (_event, value: unknown) => {
  const request = decode(DesktopThreadRequestSchema, value) as { id: string } | null
  return request === null ? null : runCodexHistoryWorker({ kind: "detail", sessionsRoot: codexSessionsRoot(), id: request.id })
})
ipcMain.handle(DesktopHydrateThreadChannel, (_event, value: unknown) => {
  const request = decode(DesktopThreadRequestSchema, value) as { id: string } | null
  return request === null ? null : runCodexHistoryWorker({ kind: "detail", sessionsRoot: codexSessionsRoot(), id: request.id, messageLimit: 40 })
})
ipcMain.handle(DesktopChatTurnChannel, async (_event, value: unknown) => {
  const request = decode(DesktopTurnRequestSchema, value) as { id: string; message: string } | null
  if (request === null || request.message.trim() === "" || request.message.length > 8_000) {
    return { ok: false, error: "That message could not be sent." }
  }
  const store = threads()
  const user: DesktopMessage = { key: randomUUID(), role: "user", text: request.message.trim(), timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }
  const saved = store.append(request.id, user)
  if (saved === null) return { ok: false, error: "That conversation no longer exists." }
  try {
    const text = await completeChatTurn(saved.notes)
    const thread = store.append(saved.id, { key: randomUUID(), role: "assistant", text, timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) })
    return { ok: true, thread }
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : "The model request failed." }
  }
})

// Codex account reconnect (#8640 unblock): renderer-argument-free channels
// only. Main owns the pylon child processes and the verification URL; the
// renderer polls typed status and never sees tokens, emails, or raw output.
ipcMain.handle(CodexAccountsChannel, () => codexConnect.listAccounts())
ipcMain.handle(CodexConnectStartChannel, () => codexConnect.start())
ipcMain.handle(CodexConnectStatusChannel, () => codexConnect.status())
ipcMain.handle(CodexConnectOpenChannel, () => codexConnect.openVerification())

// Deny-by-default for every WebContents: no navigation away from the bundled
// renderer, no window.open, no <webview> attachment.
app.on("web-contents-created", (_event, contents) => {
  contents.on("will-navigate", (event) => {
    event.preventDefault()
  })
  contents.on("will-attach-webview", (event) => {
    event.preventDefault()
  })
  contents.setWindowOpenHandler(() => ({ action: "deny" }))
})

const createWindow = (): BrowserWindow => {
  const window = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 720,
    minHeight: 480,
    backgroundColor: "#03060b",
    show: false,
    title: "OpenAgents",
    icon: desktopIconPath,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      nodeIntegrationInSubFrames: false,
      sandbox: true,
      webviewTag: false,
      webSecurity: true,
      devTools: !app.isPackaged,
      spellcheck: false,
      backgroundThrottling: false,
      preload: path.join(here, "preload.cjs"),
    },
  })
  window.once("ready-to-show", () => {
    window.show()
  })
  void window.loadFile(path.join(here, "renderer/index.html"))
  return window
}

/**
 * Smoke mode (`bun run smoke`): proves the Effect Native intent loop runs
 * inside the real Electron renderer — types into the catalog-rendered
 * composer, submits, and asserts the message row appended AND the composer
 * cleared (the v29 clear-on-submit contract, effect-native#72). When
 * `OPENAGENTS_DESKTOP_SMOKE_SHOTS` names a directory, it captures pixel
 * receipts (shell / composer-typed / composer-cleared). Exits 0/1.
 */
const smokeShotsDir = process.env.OPENAGENTS_DESKTOP_SMOKE_SHOTS

const smokeWaitForShell = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const deadline = Date.now() + 15000
  while (Date.now() < deadline && document.querySelector('[data-en-key="shell-root"]') === null) {
    await wait(100)
  }
  return document.querySelector('[data-en-key="shell-root"]') !== null
})()`

const smokeRuntimeGatewayBootstrap = `(async () => {
  const bridge = globalThis.openagentsDesktop
  if (typeof bridge?.runtimeRequest !== "function") return { ok: false, reason: "Runtime Gateway bridge missing" }
  const result = await bridge.runtimeRequest({
    kind: "query",
    requestId: "smoke-runtime-bootstrap",
    query: { id: "runtime.bootstrap" },
  })
  return {
    ok: result?.kind === "query_result" &&
      result.requestId === "smoke-runtime-bootstrap" &&
      result.result?.protocolVersion === 5 &&
      result.result?.lifecycle === "ready" &&
      result.result?.capabilities?.some((capability) => capability.id === "codex-history" && capability.state === "available"),
    result,
  }
})()`

const smokeTypeIntoComposer = `(() => {
  const input = document.querySelector('[data-en-key="shell-input"] input')
  if (input === null) return { ok: false, reason: "composer input never mounted" }
  input.focus()
  input.value = "Pixel-proof: real chat rows on the shared catalog"
  input.dispatchEvent(new Event("input", { bubbles: true }))
  return { ok: true, typed: input.value }
})()`

const smokeCodexHistoryDetails = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const first = document.querySelector('[data-en-key^="sidebar-thread-"]')
  if (first === null) return { ok: false, reason: "history row never mounted" }
  first.click()
  const deadline = Date.now() + 15000
  while (Date.now() < deadline && document.querySelector('[data-en-key="history-workspace-split"]') === null) {
    await wait(100)
  }
  const sidebar = document.querySelector('[data-en-key="sidebar-chats-label"]')
  const detail = document.querySelector('[data-en-key="history-workspace-split"]')
  return { ok: sidebar?.textContent === "Codex history · all time" && detail !== null }
})()`

const smokeOpenCommandPalette = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-command-palette-toggle"]')
  if (button === null) return { ok: false, reason: "Command palette button never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && document.querySelector('[data-en-key="desktop-command-palette"]') === null) {
    await wait(50)
  }
  const palette = document.querySelector('[data-en-key="desktop-command-palette"]')
  const files = document.querySelector('[data-en-key="desktop-command-workspace.files"]')
  return { ok: palette !== null && files !== null }
})()`

const smokeCloseCommandPalette = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="desktop-command-palette-close"]')
  if (button === null) return { ok: false, reason: "Command palette close button never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && document.querySelector('[data-en-key="desktop-command-palette"]') !== null) {
    await wait(50)
  }
  return { ok: document.querySelector('[data-en-key="desktop-command-palette"]') === null }
})()`

const smokeOpenFleetDesk = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-fleet-toggle"]')
  if (button === null) return { ok: false, reason: "Fleet toggle never mounted" }
  button.click()
  const deadline = Date.now() + 20_000
  while (Date.now() < deadline && document.querySelector('[data-en-key="fleet-desk"]') === null) {
    await wait(50)
  }
  const objective = document.querySelector('[data-en-key="fleet-objective"] input')
  const dispatch = document.querySelector('[data-en-key="fleet-stage-request"]')
  const status = document.querySelector('[data-en-key="fleet-authority-status"]')
  return {
    ok: objective !== null && dispatch !== null && status !== null && status.textContent === "Draft",
    status: status === null ? null : status.textContent,
  }
})()`

const smokeSubmitComposer = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const input = document.querySelector('[data-en-key="shell-input"] input')
  if (input === null) return { ok: false, reason: "composer input never mounted" }
  const messageCount = () =>
    document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message]').length
  const messagesBefore = messageCount()
  input.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true }))
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && (messageCount() < messagesBefore + 2 || input.value !== "")) {
    await wait(50)
  }
  const userRow = document.querySelector(
    '[data-en-key="shell-transcript"] [data-en-message][data-en-role="user"]'
  )
  const responseRow = Array.from(
    document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message][data-en-role="assistant"], [data-en-key="shell-transcript"] [data-en-message][data-en-role="system"]')
  ).at(-1)
  const sender = userRow === null ? null : userRow.querySelector('[data-en-role="sender"]')
  const body = userRow === null ? null : userRow.querySelector('[data-en-role="body"]')
  const responseSender = responseRow === undefined ? null : responseRow.querySelector('[data-en-role="sender"]')
  return {
    ok:
      messageCount() === messagesBefore + 2 &&
      input.value === "" &&
      sender !== null && sender.textContent === "YOU" &&
      body !== null && body.textContent.includes("Pixel-proof") &&
      !body.textContent.includes("YOU") &&
      responseSender !== null && (responseSender.textContent === "ASSISTANT" || responseSender.textContent === "SYSTEM"),
    messagesBefore,
    messagesAfter: messageCount(),
    inputAfterSubmit: input.value,
    senderChip: sender === null ? null : sender.textContent,
    responseSenderChip: responseSender === null ? null : responseSender.textContent,
  }
})()`

const smokePingLoop = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-ping"]')
  if (button === null) return { ok: false, reason: "ping button never mounted" }
  const badgeText = () => {
    const badge = document.querySelector('[data-en-key="shell-ping-count"]')
    return badge === null ? null : badge.textContent
  }
  const before = badgeText()
  const messageCount = () =>
    document.querySelectorAll('[data-en-key="shell-transcript"] [data-en-message]').length
  const notesBefore = messageCount()
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && badgeText() === before) {
    await wait(50)
  }
  const after = badgeText()
  return {
    ok: after !== before && after !== null && after.includes("1") && messageCount() === notesBefore + 1,
    before,
    after,
    notesBefore,
    notesAfter: messageCount(),
  }
})()`

const smokeOpenSettings = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="shell-settings-toggle"]')
  if (button === null) return { ok: false, reason: "Settings toggle never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (
    Date.now() < deadline &&
    document.querySelector('[data-en-key="settings-account-codex-2-readiness"]') === null
  ) {
    await wait(50)
  }
  const revoked = document.querySelector('[data-en-key="settings-account-codex-2-readiness"]')
  const connect = document.querySelector('[data-en-key="settings-connect-codex"]')
  return {
    ok: revoked !== null && revoked.textContent === "credentials_revoked" &&
      connect !== null && connect.textContent === "Connect Codex account",
    revokedChip: revoked === null ? null : revoked.textContent,
    connectLabel: connect === null ? null : connect.textContent,
  }
})()`

const smokeConnectCodex = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="settings-connect-codex"]')
  if (button === null) return { ok: false, reason: "Connect button never mounted" }
  button.click()
  const deadline = Date.now() + 10000
  while (
    Date.now() < deadline &&
    document.querySelector('[data-en-key="settings-connect-code"]') === null
  ) {
    await wait(100)
  }
  const code = document.querySelector('[data-en-key="settings-connect-code"]')
  const link = document.querySelector('[data-en-key="settings-connect-link"]')
  return {
    ok: code !== null && code.textContent === "1234-ABCDE" &&
      link !== null && link.textContent === "https://auth.openai.com/codex/device",
    code: code === null ? null : code.textContent,
    link: link === null ? null : link.textContent,
  }
})()`

const smokeCloseSettings = `(async () => {
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  const button = document.querySelector('[data-en-key="settings-back"]')
  if (button === null) return { ok: false, reason: "Settings back button never mounted" }
  button.click()
  const deadline = Date.now() + 5000
  while (Date.now() < deadline && document.querySelector('[data-en-key="shell-main"]') === null) {
    await wait(50)
  }
  return { ok: document.querySelector('[data-en-key="shell-main"]') !== null }
})()`

const captureShot = async (window: BrowserWindow, name: string): Promise<void> => {
  if (smokeShotsDir === undefined || smokeShotsDir === "") return
  const image = await window.webContents.capturePage()
  const { mkdirSync, writeFileSync } = await import("node:fs")
  mkdirSync(smokeShotsDir, { recursive: true })
  writeFileSync(path.join(smokeShotsDir, `${name}.png`), image.toPNG())
  console.log(`[openagents-desktop smoke] shot ${name}.png`)
}

const runSmoke = (window: BrowserWindow): void => {
  const timeout = setTimeout(() => {
    console.error("[openagents-desktop smoke] TIMEOUT waiting for renderer")
    app.exit(1)
  }, 45_000)
  let tracePass = 0
  window.webContents.on("did-finish-load", () => {
    void (async () => {
      const step = async (name: string, script: string): Promise<void> => {
        const result: unknown = await window.webContents.executeJavaScript(script, true)
        const ok =
          result === true ||
          (typeof result === "object" && result !== null && (result as { ok?: unknown }).ok === true)
        if (!ok) {
          throw new Error(`${name} failed: ${JSON.stringify(result)}`)
        }
        console.log(`[openagents-desktop smoke] ${name} OK`, JSON.stringify(result))
      }
      try {
        if (tracePass === 1) {
          await step("codex-trace-reload-restoration", traceAcceptanceReload)
          clearTimeout(timeout)
          console.log("[openagents-desktop smoke] OK")
          app.exit(0)
          return
        }
        await step("shell-mounted", smokeWaitForShell)
        await step("runtime-gateway-bootstrap", smokeRuntimeGatewayBootstrap)
        await captureShot(window, "01-shell")
        await step("command-palette-open", smokeOpenCommandPalette)
        await captureShot(window, "02-command-palette")
        await step("command-palette-close", smokeCloseCommandPalette)
        await step("recent-codex-history-selected-detail", smokeCodexHistoryDetails)
        await step("codex-trace-acceptance", traceAcceptanceJourney)
        await captureShot(window, "03-codex-history-detail")
        // Settings / Codex reconnect (#8640 unblock). Headless smoke cannot
        // complete a real browser device-auth, so main runs a FIXTURE spawn:
        // the awaiting_browser receipt below shows scripted fixture data.
        await step("settings-open-accounts", smokeOpenSettings)
        await captureShot(window, "04-settings-accounts")
        await step("settings-connect-awaiting-browser-FIXTURE", smokeConnectCodex)
        await captureShot(window, "05-settings-awaiting-browser-fixture")
        await step("settings-back-to-chat", smokeCloseSettings)
        tracePass = 1
        window.webContents.reload()
      } catch (error) {
        clearTimeout(timeout)
        console.error("[openagents-desktop smoke] ERROR", error)
        app.exit(1)
      }
    })()
  })
}

void app.whenReady().then(async () => {
  // macOS does not use BrowserWindow's icon for the active Dock tile in a
  // development Electron process. Set both native surfaces to the same mobile
  // PNG so the running desktop application has one product identity.
  if (process.platform === "darwin") app.dock?.setIcon(desktopIconPath)
  hardenSession()
  try {
    desktopSyncHost = openDesktopSyncHost({
      databasePath: path.join(app.getPath("userData"), "sync", "khala-sync.sqlite"),
      randomId: randomUUID,
    })
  } catch {
    desktopSyncHost = null
    console.error("[openagents-desktop] local Sync persistence unavailable")
  }
  try {
    desktopSessionVault = openDesktopSessionVault({
      filePath: path.join(app.getPath("userData"), "session", "native-session.enc"),
      safeStorage,
    })
    desktopSessionState = desktopSessionVault.recover().state
    if (desktopSessionState === "credential_present_unverified") {
      const recovery = await recoverVerifiedDesktopSession({
        vault: desktopSessionVault,
      })
      desktopSessionState = recovery.state === "verified"
        ? connectVerifiedDesktopSync() ? "session_ready" : "unavailable"
        : recovery.state
      if(recovery.state==="denied")desktopSyncHost?.unlinkAccount()
    }
  } catch {
    desktopSessionVault = null
    desktopSessionState = "unavailable"
    console.error("[openagents-desktop] OS-encrypted session custody unavailable")
  }
  runtimeGateway.start()
  const window = createWindow()
  if (smokeMode) runSmoke(window)
})

app.on("window-all-closed", () => {
  // Kill any in-flight pylon device-auth child with the window.
  codexConnect.dispose()
  if (process.platform !== "darwin" || smokeMode) {
    app.quit()
  }
})

app.on("before-quit", () => {
  codexConnect.dispose()
  runtimeGateway.dispose()
  desktopSyncHost?.close()
  desktopSyncHost = null
})

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})
