// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendWorldEventReducer from "../append_world_event_reducer";
import AuthorizeServiceIdentityReducer from "../authorize_service_identity_reducer";
import RecordBridgeFailureReducer from "../record_bridge_failure_reducer";
import RecordBridgeHealthReducer from "../record_bridge_health_reducer";
import RecordBridgeSuccessReducer from "../record_bridge_success_reducer";
import RecordProjectionCursorReducer from "../record_projection_cursor_reducer";
import RevokeServiceIdentityReducer from "../revoke_service_identity_reducer";
import UpsertProofRefReducer from "../upsert_proof_ref_reducer";
import UpsertRunEntityReducer from "../upsert_run_entity_reducer";
import UpsertSettlementRefReducer from "../upsert_settlement_ref_reducer";
import UpsertTrainingRunReducer from "../upsert_training_run_reducer";
import UpsertWorldEdgeReducer from "../upsert_world_edge_reducer";

export type AppendWorldEventParams = __Infer<typeof AppendWorldEventReducer>;
export type AuthorizeServiceIdentityParams = __Infer<typeof AuthorizeServiceIdentityReducer>;
export type RecordBridgeFailureParams = __Infer<typeof RecordBridgeFailureReducer>;
export type RecordBridgeHealthParams = __Infer<typeof RecordBridgeHealthReducer>;
export type RecordBridgeSuccessParams = __Infer<typeof RecordBridgeSuccessReducer>;
export type RecordProjectionCursorParams = __Infer<typeof RecordProjectionCursorReducer>;
export type RevokeServiceIdentityParams = __Infer<typeof RevokeServiceIdentityReducer>;
export type UpsertProofRefParams = __Infer<typeof UpsertProofRefReducer>;
export type UpsertRunEntityParams = __Infer<typeof UpsertRunEntityReducer>;
export type UpsertSettlementRefParams = __Infer<typeof UpsertSettlementRefReducer>;
export type UpsertTrainingRunParams = __Infer<typeof UpsertTrainingRunReducer>;
export type UpsertWorldEdgeParams = __Infer<typeof UpsertWorldEdgeReducer>;

