/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SignaturesRouteImport } from './routes/signatures'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as ApiRpcRouteImport } from './routes/api.rpc'
import { Route as MarketingLoginRouteImport } from './routes/_marketing.login'
import { Route as ApiAuthVerifyRouteImport } from './routes/api.auth.verify'
import { Route as ApiAuthStartRouteImport } from './routes/api.auth.start'
import { Route as ApiAuthSignoutRouteImport } from './routes/api.auth.signout'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturesRoute = SignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingLoginRoute = MarketingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStartRoute = ApiAuthStartRouteImport.update({
  id: '/api/auth/start',
  path: '/api/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/assistant': typeof AssistantRoute
  '/autopilot': typeof AutopilotRoute
  '/callback': typeof CallbackRoute
  '/modules': typeof ModulesRoute
  '/signatures': typeof SignaturesRoute
  '/tools': typeof ToolsRoute
  '/login': typeof MarketingLoginRoute
  '/api/rpc': typeof ApiRpcRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRoutesByTo {
  '/assistant': typeof AssistantRoute
  '/autopilot': typeof AutopilotRoute
  '/callback': typeof CallbackRoute
  '/modules': typeof ModulesRoute
  '/signatures': typeof SignaturesRoute
  '/tools': typeof ToolsRoute
  '/login': typeof MarketingLoginRoute
  '/api/rpc': typeof ApiRpcRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/': typeof MarketingIndexRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/autopilot': typeof AutopilotRoute
  '/callback': typeof CallbackRoute
  '/modules': typeof ModulesRoute
  '/signatures': typeof SignaturesRoute
  '/tools': typeof ToolsRoute
  '/_marketing/login': typeof MarketingLoginRoute
  '/api/rpc': typeof ApiRpcRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/autopilot'
    | '/callback'
    | '/modules'
    | '/signatures'
    | '/tools'
    | '/login'
    | '/api/rpc'
    | '/chat/$chatId'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assistant'
    | '/autopilot'
    | '/callback'
    | '/modules'
    | '/signatures'
    | '/tools'
    | '/login'
    | '/api/rpc'
    | '/chat/$chatId'
    | '/'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/auth/verify'
  id:
    | '__root__'
    | '/_marketing'
    | '/assistant'
    | '/autopilot'
    | '/callback'
    | '/modules'
    | '/signatures'
    | '/tools'
    | '/_marketing/login'
    | '/api/rpc'
    | '/chat/$chatId'
    | '/_marketing/'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AutopilotRoute: typeof AutopilotRoute
  CallbackRoute: typeof CallbackRoute
  ModulesRoute: typeof ModulesRoute
  SignaturesRoute: typeof SignaturesRoute
  ToolsRoute: typeof ToolsRoute
  ApiRpcRoute: typeof ApiRpcRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthStartRoute: typeof ApiAuthStartRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signatures': {
      id: '/signatures'
      path: '/signatures'
      fullPath: '/signatures'
      preLoaderRoute: typeof SignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/login': {
      id: '/_marketing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MarketingLoginRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/start': {
      id: '/api/auth/start'
      path: '/api/auth/start'
      fullPath: '/api/auth/start'
      preLoaderRoute: typeof ApiAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingRouteChildren {
  MarketingLoginRoute: typeof MarketingLoginRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingLoginRoute: MarketingLoginRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AutopilotRoute: AutopilotRoute,
  CallbackRoute: CallbackRoute,
  ModulesRoute: ModulesRoute,
  SignaturesRoute: SignaturesRoute,
  ToolsRoute: ToolsRoute,
  ApiRpcRoute: ApiRpcRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthStartRoute: ApiAuthStartRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
