#!/usr/bin/env bun
// #5166: prepare the Breez Spark WASM for a Bun-compiled standalone binary.
//
// (1) Base64-embed the SDK's nodejs WASM into src/generated/spark-wasm-b64.ts so
//     `bun build --compile` bundles the bytes INTO the binary, and the runtime
//     (src/spark-wasm-runtime.ts) can extract them on any machine.
// (2) Patch the SDK's wasm loader so it honors PYLON_SPARK_WASM_PATH (the path the
//     runtime extracts to) instead of only the build-machine `${__dirname}` path
//     that does not exist on a user's machine.
//
// Idempotent. Run BEFORE `bun build --compile`. Not needed for source/npm runs
// (the SDK resolves its own WASM from node_modules there).

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"

const pylonRoot = join(import.meta.dir, "..")

// Resolve the SDK's nodejs entry (.../nodejs/index.js) -> its directory.
const sdkNodejsDir = dirname(require.resolve("@breeztech/breez-sdk-spark"))
const wasmFile = join(sdkNodejsDir, "breez_sdk_spark_wasm_bg.wasm")
const loaderFile = join(sdkNodejsDir, "breez_sdk_spark_wasm.js")

if (!existsSync(wasmFile)) {
  throw new Error(`embed-spark-wasm: WASM not found at ${wasmFile}`)
}

// (1) Embed the WASM as base64 into a generated module.
const b64 = readFileSync(wasmFile).toString("base64")
const genDir = join(pylonRoot, "src/generated")
mkdirSync(genDir, { recursive: true })
writeFileSync(
  join(genDir, "spark-wasm-b64.ts"),
  `// AUTO-GENERATED by scripts/embed-spark-wasm.ts (#5166). Do not edit; do not commit.\nexport const WASM_B64 = ${JSON.stringify(b64)}\n`,
)

// (2) Patch the SDK loader to honor PYLON_SPARK_WASM_PATH (idempotent).
let loader = readFileSync(loaderFile, "utf8")
if (!loader.includes("PYLON_SPARK_WASM_PATH")) {
  const original = "const wasmPath = `${__dirname}/breez_sdk_spark_wasm_bg.wasm`;"
  if (!loader.includes(original)) {
    throw new Error("embed-spark-wasm: could not find the wasmPath line to patch in the SDK loader")
  }
  const patched =
    "const wasmPath = (process.env.PYLON_SPARK_WASM_PATH && require('fs').existsSync(process.env.PYLON_SPARK_WASM_PATH)) ? process.env.PYLON_SPARK_WASM_PATH : `${__dirname}/breez_sdk_spark_wasm_bg.wasm`;"
  loader = loader.replace(original, patched)
  writeFileSync(loaderFile, loader)
}

console.log(`embed-spark-wasm: embedded ${b64.length} b64 chars + patched SDK loader (${sdkNodejsDir})`)
