#!/usr/bin/env bash
# Run a headless Pylon node that self-registers with the discovery broker so the
# mobile app can auto-connect from anywhere on the tailnet.
#
# Intended for a launchd LaunchAgent (KeepAlive) so the node stays up — see
# docs/autopilot-coder/2026-06-13-afk-autonomous-loop.md. Pair with a
# `tailscale serve --bg --https=443 http://127.0.0.1:<port>` HTTPS front and set
# OA_DISCOVERY_PUBLIC_URL to that MagicDNS endpoint (HTTPS satisfies iOS ATS and
# routes over the tailnet tunnel, so it works on cellular too).
#
# All config is env-driven with sane defaults. The control token is generated by
# the node itself and is never placed in this script.
set -euo pipefail

# repo root = three levels up from apps/pylon/scripts
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

export PYLON_CONTROL_HOST="${PYLON_CONTROL_HOST:-127.0.0.1}"
export PYLON_CONTROL_PORT="${PYLON_CONTROL_PORT:-4716}"
export OA_DISCOVERY_BROKER="${OA_DISCOVERY_BROKER:-https://oa-updates-ezxz4mgdsq-uc.a.run.app}"
export OA_DISCOVERY_OWNER="${OA_DISCOVERY_OWNER:-chris}"
export PYLON_NODE_REF="${PYLON_NODE_REF:-$(hostname -s)}"
# OA_DISCOVERY_PUBLIC_URL should be the tailscale-serve HTTPS endpoint, e.g.
# https://<host>.<tailnet>.ts.net — required for remote (cellular) phone connect.

exec bun apps/pylon/src/index.ts node
