import { componentClass } from "@openagentsinc/ui/class-foldkit"

export const domainStyles = {
      list: componentClass("oa-autopilot-domain-list"),
      panel: componentClass("oa-autopilot-domain-panel"),
      inlinePanel: componentClass("oa-autopilot-domain-inline-panel"),
      subPanel: componentClass("oa-autopilot-domain-sub-panel"),
      header: componentClass("oa-autopilot-domain-header"),
      wrap: componentClass("oa-autopilot-domain-wrap"),
      stack: componentClass("oa-autopilot-domain-stack"),
      stackSmall: componentClass("oa-autopilot-domain-stack-small"),
      metadataGrid: componentClass("oa-autopilot-domain-metadata-grid"),
      title: componentClass("oa-autopilot-domain-title"),
      label: componentClass("oa-autopilot-domain-label"),
      muted: componentClass("oa-autopilot-domain-muted"),
      empty: componentClass("oa-autopilot-domain-empty"),
      codePrimary: componentClass("oa-autopilot-domain-code-primary"),
      codeMuted: componentClass("oa-autopilot-domain-code-muted"),
      value: componentClass("oa-autopilot-domain-value"),
      successValue: componentClass("oa-autopilot-domain-success-value"),
      actionButton: componentClass("oa-autopilot-domain-action-button"),
      providerRow: componentClass("oa-autopilot-domain-provider-row"),
      earningsRow: componentClass("oa-autopilot-domain-earnings-row"),
      assignmentRow: componentClass("oa-autopilot-domain-assignment-row"),
      artifactRow: componentClass("oa-autopilot-domain-artifact-row"),
      receiptRow: componentClass("oa-autopilot-domain-receipt-row"),
      twoColumnRow: componentClass("oa-autopilot-domain-two-column-row"),
      eventRow: componentClass("oa-autopilot-domain-event-row"),
      progressStack: componentClass("oa-autopilot-domain-progress-stack"),
      progressTrack: componentClass("oa-autopilot-domain-progress-track"),
      progressBar: componentClass("oa-autopilot-domain-progress-bar"),
      commandBlock: componentClass("oa-autopilot-domain-command-block"),
      chip: componentClass("oa-autopilot-domain-chip"),
      chipNeutral: componentClass("oa-autopilot-domain-chip-neutral"),
      chipSuccess: componentClass("oa-autopilot-domain-chip-success"),
      chipWarning: componentClass("oa-autopilot-domain-chip-warning"),
      chipDanger: componentClass("oa-autopilot-domain-chip-danger"),
      chipInfo: componentClass("oa-autopilot-domain-chip-info"),
} as const
