import {
  stylexFallback,
  stylexRuntimeFallbackEnabled,
} from "@openagentsinc/ui/stylex-foldkit"
import type { AutopilotCoreDarkCssVar } from "@openagentsinc/ui/tokens"
import * as stylex from "@stylexjs/stylex"

const mono =
  'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace'

const cssVar = (name: AutopilotCoreDarkCssVar): `var(${AutopilotCoreDarkCssVar})` =>
  `var(${name})`

const colors = {
  "--bg": cssVar("--bg"),
  "--bg-secondary": cssVar("--bg-secondary"),
  "--text": cssVar("--text"),
  "--text-secondary": cssVar("--text-secondary"),
  "--outline": cssVar("--outline"),
  "--primary": cssVar("--primary"),
  "--success": cssVar("--success"),
  "--warning": cssVar("--warning"),
  "--danger": cssVar("--danger"),
  "--info": cssVar("--info"),
} as const satisfies Record<AutopilotCoreDarkCssVar, `var(${AutopilotCoreDarkCssVar})`>

export const domainStyles = stylexRuntimeFallbackEnabled()
  ? {
      list: stylexFallback("oa-autopilot-domain-list"),
      panel: stylexFallback("oa-autopilot-domain-panel"),
      inlinePanel: stylexFallback("oa-autopilot-domain-inline-panel"),
      subPanel: stylexFallback("oa-autopilot-domain-sub-panel"),
      header: stylexFallback("oa-autopilot-domain-header"),
      wrap: stylexFallback("oa-autopilot-domain-wrap"),
      stack: stylexFallback("oa-autopilot-domain-stack"),
      stackSmall: stylexFallback("oa-autopilot-domain-stack-small"),
      metadataGrid: stylexFallback("oa-autopilot-domain-metadata-grid"),
      title: stylexFallback("oa-autopilot-domain-title"),
      label: stylexFallback("oa-autopilot-domain-label"),
      muted: stylexFallback("oa-autopilot-domain-muted"),
      empty: stylexFallback("oa-autopilot-domain-empty"),
      codePrimary: stylexFallback("oa-autopilot-domain-code-primary"),
      codeMuted: stylexFallback("oa-autopilot-domain-code-muted"),
      value: stylexFallback("oa-autopilot-domain-value"),
      successValue: stylexFallback("oa-autopilot-domain-success-value"),
      actionButton: stylexFallback("oa-autopilot-domain-action-button"),
      providerRow: stylexFallback("oa-autopilot-domain-provider-row"),
      earningsRow: stylexFallback("oa-autopilot-domain-earnings-row"),
      assignmentRow: stylexFallback("oa-autopilot-domain-assignment-row"),
      artifactRow: stylexFallback("oa-autopilot-domain-artifact-row"),
      receiptRow: stylexFallback("oa-autopilot-domain-receipt-row"),
      twoColumnRow: stylexFallback("oa-autopilot-domain-two-column-row"),
      eventRow: stylexFallback("oa-autopilot-domain-event-row"),
      progressStack: stylexFallback("oa-autopilot-domain-progress-stack"),
      progressTrack: stylexFallback("oa-autopilot-domain-progress-track"),
      progressBar: stylexFallback("oa-autopilot-domain-progress-bar"),
      commandBlock: stylexFallback("oa-autopilot-domain-command-block"),
      chip: stylexFallback("oa-autopilot-domain-chip"),
      chipNeutral: stylexFallback("oa-autopilot-domain-chip-neutral"),
      chipSuccess: stylexFallback("oa-autopilot-domain-chip-success"),
      chipWarning: stylexFallback("oa-autopilot-domain-chip-warning"),
      chipDanger: stylexFallback("oa-autopilot-domain-chip-danger"),
      chipInfo: stylexFallback("oa-autopilot-domain-chip-info"),
    }
  : stylex.create({
      list: {
        display: "grid",
        gap: 8,
      },
      panel: {
        display: "grid",
        gap: 12,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg-secondary"],
        padding: 16,
        color: colors["--text"],
      },
      inlinePanel: {
        display: "inline-flex",
        minWidth: 0,
        alignItems: "center",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg-secondary"],
        paddingBlock: 8,
        paddingInline: 12,
        color: colors["--text"],
      },
      subPanel: {
        display: "grid",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: "transparent",
        padding: 12,
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "minmax(0,1fr) minmax(0,1.4fr)",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      header: {
        display: "flex",
        flexWrap: "wrap",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 12,
      },
      wrap: {
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        gap: 8,
      },
      stack: {
        display: "grid",
        minWidth: 0,
        gap: 4,
      },
      stackSmall: {
        display: "grid",
        gap: 4,
      },
      metadataGrid: {
        display: "grid",
        gap: 8,
        fontSize: 12,
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
        },
      },
      title: {
        margin: 0,
        fontFamily: mono,
        fontSize: 14,
        fontWeight: 700,
        color: colors["--primary"],
      },
      label: {
        fontFamily: mono,
        fontSize: 12,
        textTransform: "uppercase",
        color: colors["--text-secondary"],
      },
      muted: {
        margin: 0,
        fontFamily: mono,
        fontSize: 12,
        color: colors["--text-secondary"],
      },
      empty: {
        margin: 0,
        fontSize: 14,
        color: colors["--text-secondary"],
      },
      codePrimary: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        fontFamily: mono,
        fontSize: 14,
        color: colors["--primary"],
      },
      codeMuted: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        fontFamily: mono,
        fontSize: 12,
        color: colors["--text-secondary"],
      },
      value: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        fontFamily: mono,
        fontSize: 18,
        fontWeight: 700,
        color: colors["--primary"],
      },
      successValue: {
        fontFamily: mono,
        fontSize: 12,
        fontWeight: 700,
        color: colors["--success"],
      },
      actionButton: {
        display: "inline-flex",
        height: 32,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 4,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        paddingInline: 12,
        fontFamily: mono,
        fontSize: 12,
        fontWeight: 700,
        color: colors["--primary"],
        opacity: {
          default: null,
          ":disabled": 0.45,
        },
      },
      providerRow: {
        display: "grid",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg-secondary"],
        padding: 12,
        color: colors["--text"],
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "minmax(0,1fr) 7rem minmax(0,1fr)",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      earningsRow: {
        display: "grid",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg"],
        padding: 12,
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "minmax(0,1fr) 8rem 12rem",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      assignmentRow: {
        display: "grid",
        gap: 12,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg-secondary"],
        padding: 12,
        color: colors["--text"],
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)":
            "minmax(0,1fr) 8rem minmax(8rem,12rem) auto",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      artifactRow: {
        display: "grid",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg-secondary"],
        padding: 12,
        color: colors["--text"],
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "minmax(0,1.5fr) minmax(0,1fr) 12rem",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      receiptRow: {
        display: "grid",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg-secondary"],
        padding: 12,
        color: colors["--text"],
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "minmax(0,1fr) minmax(0,1fr) 7rem",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      twoColumnRow: {
        display: "grid",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: "transparent",
        padding: 12,
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "minmax(0,1fr) 7rem",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      eventRow: {
        display: "grid",
        gap: 8,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg-secondary"],
        padding: 12,
        gridTemplateColumns: {
          default: null,
          "@media (min-width: 640px)": "4rem 10rem minmax(0,1fr) minmax(0,1fr)",
        },
        alignItems: {
          default: null,
          "@media (min-width: 640px)": "center",
        },
      },
      progressStack: {
        display: "grid",
        gap: 4,
      },
      progressTrack: {
        height: 8,
        overflow: "hidden",
        borderRadius: 4,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg"],
      },
      progressBar: {
        height: "100%",
        backgroundColor: colors["--info"],
      },
      commandBlock: {
        display: "block",
        minWidth: 0,
        overflowX: "auto",
        whiteSpace: "pre",
        borderRadius: 4,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors["--outline"],
        backgroundColor: colors["--bg"],
        paddingBlock: 8,
        paddingInline: 12,
        fontFamily: mono,
        fontSize: 12,
        color: colors["--primary"],
      },
      chip: {
        display: "inline-flex",
        height: 24,
        alignItems: "center",
        whiteSpace: "nowrap",
        borderRadius: 4,
        borderWidth: 1,
        borderStyle: "solid",
        paddingInline: 8,
        fontFamily: mono,
        fontSize: 12,
        fontWeight: 700,
        lineHeight: 1,
      },
      chipNeutral: {
        borderColor: colors["--outline"],
        backgroundColor: "transparent",
        color: colors["--text-secondary"],
      },
      chipSuccess: {
        borderColor: colors["--success"],
        backgroundColor: "color-mix(in srgb, var(--success) 12%, transparent)",
        color: colors["--success"],
      },
      chipWarning: {
        borderColor: colors["--warning"],
        backgroundColor: "color-mix(in srgb, var(--warning) 12%, transparent)",
        color: colors["--warning"],
      },
      chipDanger: {
        borderColor: colors["--danger"],
        backgroundColor: "color-mix(in srgb, var(--danger) 12%, transparent)",
        color: colors["--danger"],
      },
      chipInfo: {
        borderColor: colors["--info"],
        backgroundColor: "color-mix(in srgb, var(--info) 12%, transparent)",
        color: colors["--info"],
      },
    })
