import { stylexFallback } from "@openagentsinc/ui/stylex-foldkit"

export const domainStyles = {
      list: stylexFallback("oa-autopilot-domain-list"),
      panel: stylexFallback("oa-autopilot-domain-panel"),
      inlinePanel: stylexFallback("oa-autopilot-domain-inline-panel"),
      subPanel: stylexFallback("oa-autopilot-domain-sub-panel"),
      header: stylexFallback("oa-autopilot-domain-header"),
      wrap: stylexFallback("oa-autopilot-domain-wrap"),
      stack: stylexFallback("oa-autopilot-domain-stack"),
      stackSmall: stylexFallback("oa-autopilot-domain-stack-small"),
      metadataGrid: stylexFallback("oa-autopilot-domain-metadata-grid"),
      title: stylexFallback("oa-autopilot-domain-title"),
      label: stylexFallback("oa-autopilot-domain-label"),
      muted: stylexFallback("oa-autopilot-domain-muted"),
      empty: stylexFallback("oa-autopilot-domain-empty"),
      codePrimary: stylexFallback("oa-autopilot-domain-code-primary"),
      codeMuted: stylexFallback("oa-autopilot-domain-code-muted"),
      value: stylexFallback("oa-autopilot-domain-value"),
      successValue: stylexFallback("oa-autopilot-domain-success-value"),
      actionButton: stylexFallback("oa-autopilot-domain-action-button"),
      providerRow: stylexFallback("oa-autopilot-domain-provider-row"),
      earningsRow: stylexFallback("oa-autopilot-domain-earnings-row"),
      assignmentRow: stylexFallback("oa-autopilot-domain-assignment-row"),
      artifactRow: stylexFallback("oa-autopilot-domain-artifact-row"),
      receiptRow: stylexFallback("oa-autopilot-domain-receipt-row"),
      twoColumnRow: stylexFallback("oa-autopilot-domain-two-column-row"),
      eventRow: stylexFallback("oa-autopilot-domain-event-row"),
      progressStack: stylexFallback("oa-autopilot-domain-progress-stack"),
      progressTrack: stylexFallback("oa-autopilot-domain-progress-track"),
      progressBar: stylexFallback("oa-autopilot-domain-progress-bar"),
      commandBlock: stylexFallback("oa-autopilot-domain-command-block"),
      chip: stylexFallback("oa-autopilot-domain-chip"),
      chipNeutral: stylexFallback("oa-autopilot-domain-chip-neutral"),
      chipSuccess: stylexFallback("oa-autopilot-domain-chip-success"),
      chipWarning: stylexFallback("oa-autopilot-domain-chip-warning"),
      chipDanger: stylexFallback("oa-autopilot-domain-chip-danger"),
      chipInfo: stylexFallback("oa-autopilot-domain-chip-info"),
} as const
