import { describe, expect, test } from "bun:test"
import type { View } from "@effect-native/core"
import { historyWorkspaceView } from "./history-workspace.ts"
import type { CodexHistoryPage } from "../codex-history-contract.ts"

const page: CodexHistoryPage = { rootThreadRef:"root",selectedThreadRef:"child",offset:0,limit:200,totalItems:1,hasPrevious:false,hasNext:false,completeness:{source:1,rendered:1,redactions:0,gaps:0,complete:true},agents:[{threadRef:"root",parentThreadRef:null,title:"Root",status:"completed",createdAt:"2026-07-10T00:00:00Z",updatedAt:"2026-07-10T00:00:00Z",depth:0,descendantCount:1,model:null,role:null,nickname:null,agentPath:null,sourceVersion:null,reasoning:null},{threadRef:"child",parentThreadRef:"root",title:"Worker",status:"running",createdAt:"2026-07-10T00:00:00Z",updatedAt:"2026-07-10T00:00:00Z",depth:1,descendantCount:0,model:"gpt",role:"worker",nickname:"worker",agentPath:"root/worker",sourceVersion:"v2",reasoning:null}],items:[{itemRef:"child:0",threadRef:"child",sequence:0,timestamp:"2026-07-10T00:00:00Z",kind:"tool_call",label:"exec",summary:"bun test",status:"running",fields:[{label:"input",value:"bun test"}],redacted:false,sourceType:"response_item/function_call"}] }
const nodes=(view:View):View[]=>{const value=view as any; return [view,...(Array.isArray(value.children)?value.children.flatMap(nodes):[]),...(Array.isArray(value.items)?value.items.flatMap(nodes):[]),...(Array.isArray(value.panes)?value.panes.flatMap((p:any)=>nodes(p.content)):[])]}
describe("history workspace",()=>{
  test("renders a bounded split view with semantic agent tree and completeness",()=>{const view=historyWorkspaceView({catalog:{roots:[],agents:[]},page,selectedItemRef:null,railCollapsed:false,expandedThreadRefs:["root"]});const all=nodes(view) as any[];expect(all.find(n=>n.key==="history-workspace-split")?._tag).toBe("SplitPane");expect(all.find(n=>n.key==="history-agent-child")?.a11y).toMatchObject({role:"treeitem",level:2,selected:true});expect(all.find(n=>n.key==="history-completeness")?.message).toContain("1 source = 1 rendered")})
  test("selected item opens structured detail with back action",()=>{const all=nodes(historyWorkspaceView({catalog:{roots:[],agents:[]},page,selectedItemRef:"child:0",railCollapsed:false,expandedThreadRefs:["root"]})) as any[];expect(all.find(n=>n.key==="history-item-inspector")).toBeDefined();expect(all.find(n=>n.key==="history-item-back")?.onPress.name).toBe("HistoryItemSelected")})
  test("bounded timeline uses native variable-height scrolling and compact row previews",()=>{const long={...page,items:[{...page.items[0]!,summary:"x".repeat(2_000)}]};const all=nodes(historyWorkspaceView({catalog:{roots:[],agents:[]},page:long,selectedItemRef:null,railCollapsed:false,expandedThreadRefs:["root"]})) as any[];expect(all.find(n=>n.key==="history-timeline-page")?.virtualize).toBe(false);const row=all.find(n=>String(n.key).startsWith("history-item-"));expect(row.label.length).toBeLessThan(500);expect(row.label.endsWith("…")).toBe(true)})
})
