import type { ReactElement } from "react"
import { AlertTriangle, GitBranch, RefreshCw, ShieldCheck } from "lucide-react"
import { ComponentValueBinding, IntentRef, type IntentError, type IntentReporter, type JsonPayload } from "@effect-native/core"
import { Effect } from "@effect-native/core/effect"

import { Button } from "#components/ui/button"
import { Badge } from "#components/ui/badge"
import { Input } from "#components/ui/input"
import type { DesktopShellState } from "./shell.ts"
import { RedactedSensitiveText } from "./react-sensitive-text.tsx"
import { ReactConnectSurface } from "./react-connect-surface.tsx"

export type ReactSettingsSectionId = "settings-general" | "settings-codex" | "settings-extensions" | "settings-source-control" | "settings-keybindings" | "settings-diagnostics" | "settings-connections" | "settings-account"

const dispatch = (report: IntentReporter, name: string, payload: JsonPayload = null): void => {
  void Effect.runPromise(report(payload === null ? IntentRef(name) : IntentRef(name, ComponentValueBinding()), payload) as Effect.Effect<void, IntentError>).catch(() => undefined)
}

const Maintenance = ({ state, report }: { readonly state: DesktopShellState; readonly report: IntentReporter }): ReactElement => <section className="oa-react-settings-section" aria-labelledby="react-runtime-maintenance-title">
  <h2 id="react-runtime-maintenance-title">Codex CLI</h2><p>Installed Codex version, channel, and update truth from this Mac.</p>
  {state.settings.harnessMaintenance.lastOutcome === null ? null : <p role="status">{state.settings.harnessMaintenance.lastOutcome}</p>}
  {state.settings.harnessMaintenance.view.state === "loading" ? <div className="oa-react-settings-skeleton" aria-label="Checking harnesses"><span /><span /></div>
    : state.settings.harnessMaintenance.view.state === "unavailable" ? <p role="alert">{state.settings.harnessMaintenance.view.message}</p>
    : state.settings.harnessMaintenance.view.harnesses.filter(item => item.harness === "codex").map(item => <article className="oa-react-settings-status-article" key={item.harness} data-harness={item.harness} data-status={item.advisory}><div><strong>Codex</strong><span>{item.installedVersion ?? "Not installed"} · {item.channel}</span>{item.recoveryMessage == null ? null : <small>{item.recoveryMessage}</small>}</div><span className="oa-react-settings-status-label">{item.advisory === "current" ? "Up to date" : item.advisory === "behind_latest" ? "Update available" : "Version unknown"}</span>{item.updateSupported ? <Button size="sm" disabled={state.settings.harnessMaintenance.updating !== null} onClick={() => dispatch(report, "DesktopHarnessUpdateRequested", item.harness)}>Update</Button> : null}</article>)}
</section>

const Account = ({ state, codexOnly = false }: { readonly state: DesktopShellState; readonly codexOnly?: boolean }): ReactElement => <section className="oa-react-settings-section" aria-labelledby="react-provider-accounts-title">
  <h2 id="react-provider-accounts-title">{codexOnly ? "Codex account" : "Provider accounts"}</h2><p>Account identity is blurred until you explicitly reveal it.</p>
  {state.fleet.phase === "loading" || state.fleet.phase === "idle" ? <div className="oa-react-settings-skeleton" aria-label="Loading accounts"><span /><span /></div>
    : state.fleet.accounts.filter(account => !codexOnly || account.provider === "codex").length === 0 ? <p>No {codexOnly ? "Codex " : ""}account connected.</p>
    : state.fleet.accounts.filter(account => !codexOnly || account.provider === "codex").map(account => <article className="oa-react-settings-status-article" key={account.ref} data-provider-account={account.ref} data-status={account.readiness}><div><strong>{account.provider === "codex" ? "Codex" : account.provider}</strong><span>{account.ref}</span></div><span>{account.readiness.replaceAll("-", " ")}</span>{account.email === null ? null : <RedactedSensitiveText value={account.email} ariaLabel={`Toggle ${account.provider} account email visibility`} revealTooltip="Click to reveal email" hideTooltip="Click to hide email" />}</article>)}
</section>

const General = ({ state, report }: { readonly state: DesktopShellState; readonly report: IntentReporter }): ReactElement => <>
  <Maintenance state={state} report={report} />
  <section className="oa-react-settings-section" aria-labelledby="react-editor-input-title">
    <h2 id="react-editor-input-title">Editor input</h2>
    <p>Built-in Vim uses the same Monaco document, save, conflict, and recovery authority. It is off by default and works offline.</p>
    <Button variant={state.workspaceEditor.vimEnabled ? "default" : "outline"} aria-pressed={state.workspaceEditor.vimEnabled} onClick={() => dispatch(report, "WorkspaceEditorVimToggled")}>{state.workspaceEditor.vimEnabled ? "Vim enabled" : "Vim disabled"}</Button>
  </section>
  {state.settings.localCodexUsageControlAvailable ? <section className="oa-react-settings-section" aria-labelledby="react-local-usage-title"><h2 id="react-local-usage-title">Share local Codex usage</h2><p>When on, OpenAgents reports how many tokens each turn used — the input, cached-input, output, reasoning, and total token counts — plus the model name and a one-time turn reference. Only those numbers are sent: never your prompts, responses, files, paths, account names, or credentials. This updates the aggregate public tokens-served counter. Turn it off any time; queued reports are deleted.</p><Button variant={state.settings.shareLocalCodexUsage ? "default" : "outline"} aria-pressed={state.settings.shareLocalCodexUsage} onClick={() => dispatch(report, "DesktopLocalCodexUsageSharingToggled", !state.settings.shareLocalCodexUsage)}>{state.settings.shareLocalCodexUsage ? "Sharing on" : "Sharing off"}</Button></section> : null}
  <section className="oa-react-settings-section" aria-labelledby="react-graph-memory-title">
    <h2 id="react-graph-memory-title">Graph memory</h2>
    <p>Extraction can use a semantic model and cause spend. Recall is a separate control that reads only the authorized graph. Both controls are off by default.</p>
    <Button variant={state.settings.graphExtractionEnabled ? "default" : "outline"} aria-pressed={state.settings.graphExtractionEnabled} onClick={() => dispatch(report, "DesktopGraphExtractionToggled", !state.settings.graphExtractionEnabled)}>{state.settings.graphExtractionEnabled ? "Extraction on" : "Extraction off"}</Button>
    <Button variant={state.settings.graphRecallEnabled ? "default" : "outline"} aria-pressed={state.settings.graphRecallEnabled} onClick={() => dispatch(report, "DesktopGraphRecallToggled", !state.settings.graphRecallEnabled)}>{state.settings.graphRecallEnabled ? "Recall on" : "Recall off"}</Button>
  </section>
  <Account state={state} codexOnly />
</>

const Extensions = ({ state, report }: { readonly state: DesktopShellState; readonly report: IntentReporter }): ReactElement => <section className="oa-react-settings-card" aria-labelledby="settings-extensions-heading"><header><div><p>Tools</p><h2 id="settings-extensions-heading">Extensions</h2></div></header>
  <div className="oa-react-settings-rows">{state.settings.mcp.servers.state === "loading" ? <div className="oa-react-settings-skeleton" aria-label="Loading MCP servers"><span /><span /></div> : state.settings.mcp.servers.state === "unavailable" ? <p role="alert">{state.settings.mcp.servers.message}</p> : state.settings.mcp.servers.servers.map(server => <article key={server.name}><div><strong>{server.name}</strong><small>{server.transport} · {server.command ?? server.url ?? "configured"}</small></div><Badge variant="outline">{server.enabled ? "enabled" : "disabled"}</Badge><div><Button size="sm" variant="outline" onClick={() => dispatch(report, "DesktopMcpToggleRequested", server.name)}>{server.enabled ? "Disable" : "Enable"}</Button><Button size="sm" variant="ghost" onClick={() => dispatch(report, "DesktopMcpRemoveRequested", server.name)}>Remove</Button></div></article>)}</div>
  <h3>Local Claude plugins</h3><div className="oa-react-settings-rows">{state.settings.plugins.state === "loading" ? <div className="oa-react-settings-skeleton" aria-label="Loading plugins"><span /></div> : state.settings.plugins.state === "unavailable" ? <p role="alert">{state.settings.plugins.message}</p> : state.settings.plugins.plugins.map(plugin => <article key={plugin.ref}><div><strong>{plugin.name}</strong><small>{plugin.skills.length} skills · next turn</small></div><Badge variant="outline">{plugin.readiness}</Badge><div><Button size="sm" variant="outline" onClick={() => dispatch(report, "DesktopPluginToggleRequested", plugin.ref)}>{plugin.enabled ? "Disable" : "Enable"}</Button><Button size="sm" variant="ghost" onClick={() => dispatch(report, "DesktopPluginRemoveRequested", plugin.ref)}>Remove</Button></div></article>)}</div><Button onClick={() => dispatch(report, "DesktopPluginChooseRequested")}>Add local plugin</Button>
</section>

const Keybindings = ({ state, report }: { readonly state: DesktopShellState; readonly report: IntentReporter }): ReactElement => <section className="oa-react-settings-card" aria-labelledby="settings-keybindings-heading"><header><div><p>Input</p><h2 id="settings-keybindings-heading">Keyboard shortcuts</h2></div><Button size="sm" variant="ghost" onClick={() => dispatch(report, "DesktopCommandBindingsReset")}>Reset all</Button></header>
  {state.commandBindings === null ? <div className="oa-react-settings-empty"><AlertTriangle aria-hidden="true" /><h3>Shortcuts unavailable</h3><p>The platform command-binding host did not return a projection.</p></div> : <div className="oa-react-settings-table" role="table" aria-label="Keyboard shortcuts">{state.commandBindings.rows.map(row => <button key={row.commandId} role="row" data-conflict={row.conflict ? "true" : "false"} onClick={() => dispatch(report, "DesktopCommandBindingSelected", row.commandId)}><span role="cell"><strong>{row.label}</strong><small>{row.commandId} · {row.context ?? "global"} · {row.platform ?? "platform"}</small></span><span role="cell">{row.overrideBinding ?? (row.effectiveBindings.join(" / ") || "Unassigned")}<small>{row.source ?? (row.overrideBinding === null ? "default" : "user")} · {row.vimPrecedence ?? "app before Vim"}{(row.conflictKinds ?? []).length === 0 ? "" : ` · ${(row.conflictKinds ?? []).join("/")} conflict`}</small></span></button>)}</div>}
  {state.commandBindingSelectedId === null ? null : <div className="oa-react-settings-inline-editor"><Input aria-label="Shortcut chord" placeholder="Meta+Shift+K" value={state.commandBindingDraft} onChange={event => dispatch(report, "DesktopCommandBindingDraftChanged", event.currentTarget.value)} /><Button disabled={state.commandBindingDraft.trim() === ""} onClick={() => dispatch(report, "DesktopCommandBindingSaved")}>Save</Button><Button variant="outline" onClick={() => dispatch(report, "DesktopCommandBindingRemoved")}>Use defaults</Button></div>}
  {state.commandBindings?.conflicts.map(conflict => <p role="alert" key={conflict.chord}>{conflict.chord} conflicts across {conflict.commandIds.length} commands and is disabled.</p>)}
</section>

const Diagnostics = ({ state, report }: { readonly state: DesktopShellState; readonly report: IntentReporter }): ReactElement => <section className="oa-react-settings-card" aria-labelledby="settings-diagnostics-heading"><header><div><p>Health</p><h2 id="settings-diagnostics-heading">Diagnostics</h2></div><div><Button size="sm" variant="outline" onClick={() => dispatch(report, "DesktopDiagnosticsRefreshRequested")}>Refresh</Button><Button size="sm" variant="ghost" onClick={() => dispatch(report, "DesktopDiagnosticsExportRequested")}>Export redacted</Button></div></header>
  {state.diagnostics.report.state === "loading" ? <div className="oa-react-settings-skeleton" aria-label="Loading diagnostics"><span /><span /><span /></div> : state.diagnostics.report.state === "unavailable" ? <p role="alert">{state.diagnostics.report.message}</p> : <div className="oa-react-settings-rows">{state.diagnostics.report.report.rows.map(row => <article key={row.domain}><div><strong>{row.domain}</strong><small>{row.summary}</small></div><Badge variant="outline">{row.level}</Badge><span>{row.refs.join(" · ") || "No public refs"}</span></article>)}</div>}{state.diagnostics.notice === null ? null : <p role="status">{state.diagnostics.notice}</p>}
</section>

const SourceControl = ({ state, report }: { readonly state: DesktopShellState; readonly report: IntentReporter }): ReactElement => { const status = state.git.status; return <section className="oa-react-settings-card" aria-labelledby="settings-source-control-heading"><header><div><p>Repository</p><h2 id="settings-source-control-heading">Source control</h2></div><Button size="sm" variant="outline" onClick={() => dispatch(report, "GitPanelRefreshRequested")}><RefreshCw aria-hidden="true" />Refresh</Button></header>{state.git.phase === "loading" ? <div className="oa-react-settings-skeleton" aria-label="Loading source control settings"><span /><span /><span /></div> : status === null ? <div className="oa-react-settings-empty"><GitBranch aria-hidden="true" /><h3>No repository status</h3><p>Select an admitted project/worktree to load its exact Git projection.</p></div> : <div className="oa-react-settings-table" role="table" aria-label="Source control status"><div role="row"><span role="columnheader">Branch</span><strong role="cell">{status.branch ?? "Detached HEAD"}</strong></div><div role="row"><span role="columnheader">Upstream</span><span role="cell">{status.upstream ?? "Not configured"}</span></div><div role="row"><span role="columnheader">Ahead / behind</span><span role="cell">{status.ahead} / {status.behind}</span></div><div role="row"><span role="columnheader">Changes</span><span role="cell">{status.staged.length} staged · {status.unstaged.length} unstaged · {status.untracked.length} untracked</span></div></div>}<p className="oa-react-settings-boundary"><ShieldCheck aria-hidden="true" />Stage, discard, commit, branch, and push use the exact visible status snapshot. Credential mutation remains outside this surface.</p></section> }

export const ReactSettingsSurface = ({ state, report, sectionId }: { readonly state: DesktopShellState; readonly report: IntentReporter; readonly sectionId: ReactSettingsSectionId }): ReactElement => sectionId === "settings-general" ? <General state={state} report={report} /> : sectionId === "settings-codex" ? <Maintenance state={state} report={report} /> : sectionId === "settings-extensions" ? <Extensions state={state} report={report} /> : sectionId === "settings-source-control" ? <SourceControl state={state} report={report} /> : sectionId === "settings-keybindings" ? <Keybindings state={state} report={report} /> : sectionId === "settings-diagnostics" ? <Diagnostics state={state} report={report} /> : sectionId === "settings-connections" ? <ReactConnectSurface connections={state.connections} report={report} /> : <Account state={state} />
