//! The route result (plan section 5 with 13.2, 13.3, 13.4, 13.5, 13.9).
//!
//! What the router decided a message calls for. It is an observation and a
//! proposal, never permission: the host admits and starts work; an engine
//! never starts other engines.

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::digest::{Digest, digest_of};
use crate::snapshot::CapabilityPin;

/// The most runs one dispatch plan starts: every engine a computer names
/// (`coder::router::MAX_ENGINES`).
pub const MAX_RUNS: usize = 8;

/// The route families. Labels for evaluation and the admission snapshot;
/// the route policy routes on typed Jev readings, never on these words.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RouteFamily {
    /// A prepared, knowledge, or model answer: no computer execution.
    Answer,
    /// A command from this computer's own command tree, or a screen of the
    /// app (13.4).
    LocalCommand,
    /// A pinned plugin or program with validated typed arguments, or the
    /// plugin-creation flow (#10177).
    Plugin,
    /// Coder: a dispatch plan of one or more runs, or a continuation.
    Coder,
    /// A background rule the host runs with no model in the loop (13.9).
    StandingRule,
    /// Offer to build or install a capability; never install implicitly.
    MissingCapability,
    Clarification,
    Refusal,
}

impl RouteFamily {
    pub const ALL: [RouteFamily; 8] = [
        RouteFamily::Answer,
        RouteFamily::LocalCommand,
        RouteFamily::Plugin,
        RouteFamily::Coder,
        RouteFamily::StandingRule,
        RouteFamily::MissingCapability,
        RouteFamily::Clarification,
        RouteFamily::Refusal,
    ];
}

/// The route result.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "route", rename_all = "snake_case", deny_unknown_fields)]
pub enum RouteResult {
    Answer {
        source: AnswerSource,
    },
    LocalCommand {
        action: LocalAction,
    },
    Plugin {
        plugin: PluginRoute,
    },
    Coder {
        plan: DispatchPlan,
    },
    StandingRule {
        rule: RuleProposal,
    },
    MissingCapability {
        /// What the person asked for, in plain words.
        need: String,
        remedy: Remedy,
    },
    Clarification {
        question: String,
        reason: ClarifyReason,
    },
    Refusal {
        reason: RefusalReason,
    },
}

impl RouteResult {
    #[must_use]
    pub fn family(&self) -> RouteFamily {
        match self {
            RouteResult::Answer { .. } => RouteFamily::Answer,
            RouteResult::LocalCommand { .. } => RouteFamily::LocalCommand,
            RouteResult::Plugin { .. } => RouteFamily::Plugin,
            RouteResult::Coder { .. } => RouteFamily::Coder,
            RouteResult::StandingRule { .. } => RouteFamily::StandingRule,
            RouteResult::MissingCapability { .. } => RouteFamily::MissingCapability,
            RouteResult::Clarification { .. } => RouteFamily::Clarification,
            RouteResult::Refusal { .. } => RouteFamily::Refusal,
        }
    }

    /// The digest an admission snapshot and an offer bind.
    #[must_use]
    pub fn digest(&self) -> Digest {
        digest_of(&(crate::ROUTE_SCHEMA, self))
    }

    /// Checks the bounds code enforces before anything is offered.
    ///
    /// # Errors
    ///
    /// The first bound the result breaks.
    pub fn validate(&self) -> Result<(), Invalid> {
        match self {
            RouteResult::Coder { plan } => plan.validate(),
            RouteResult::LocalCommand {
                action: LocalAction::Command { argv, .. },
            } if argv.is_empty() => Err(Invalid::EmptyCommand),
            _ => Ok(()),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum AnswerSource {
    /// A reviewed prepared answer.
    Prepared { entry: String },
    /// Grounded in a corpus, with checked citations.
    Knowledge {
        corpus: String,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        citations: Vec<String>,
    },
    /// Generated by an admitted model under the disclosure policy.
    Model,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum LocalAction {
    /// A command from the computer's own tree, checked against that tree
    /// rather than the proposer's claim.
    Command { argv: Vec<String>, effect: Effect },
    /// A screen of the app (wallet, computers, a deck).
    Screen {
        screen: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        target: Option<String>,
    },
}

/// A command's effect class, the words `coder::router::Effect` carries.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Effect {
    ReadOnly,
    LocalWrite,
    Publishes,
    Grants,
    Spends,
    Secret,
    LongRunning,
}

impl Effect {
    /// How a command with this effect runs from chat (13.4): read-only at
    /// once, a state change after the person confirms the exact command,
    /// money movement and secrets never. A surface may be stricter (the
    /// phone), never looser.
    #[must_use]
    pub fn run_policy(self) -> RunPolicy {
        match self {
            Effect::ReadOnly => RunPolicy::AtOnce,
            Effect::Spends | Effect::Secret => RunPolicy::NeverFromChat,
            Effect::LocalWrite | Effect::Publishes | Effect::Grants | Effect::LongRunning => {
                RunPolicy::Confirm
            }
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RunPolicy {
    AtOnce,
    Confirm,
    NeverFromChat,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum PluginRoute {
    /// Run a pinned, admitted plugin or program (a Gym test set is a
    /// program) with arguments validated in code.
    Run {
        capability: CapabilityPin,
        arguments: Value,
    },
    /// The plugin-creation flow (#10177): what it should and should not
    /// do, a drafted package and tests, a test run, then register.
    Create { brief: String },
}

/// A dispatch plan (13.2): N runs the host starts, the flat first case of
/// section 11's graph.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DispatchPlan {
    pub class: TaskClass,
    pub fan_out: FanOut,
    pub runs: Vec<PlannedRun>,
    /// A requested summary is composed from the runs' results, never by a
    /// further run.
    pub summary: Summary,
}

impl DispatchPlan {
    /// # Errors
    ///
    /// No runs, more than [`MAX_RUNS`], a one-per-engine plan that repeats
    /// an engine, or a single plan with more than one run.
    pub fn validate(&self) -> Result<(), Invalid> {
        if self.runs.is_empty() {
            return Err(Invalid::NoRuns);
        }
        if self.runs.len() > MAX_RUNS {
            return Err(Invalid::TooManyRuns(self.runs.len()));
        }
        match self.fan_out {
            FanOut::Single if self.runs.len() != 1 => Err(Invalid::SingleWithMany),
            FanOut::OnePerEngine => {
                let mut seen: Vec<&str> = Vec::new();
                for run in &self.runs {
                    if seen.contains(&run.engine.as_str()) {
                        return Err(Invalid::RepeatedEngine(run.engine.clone()));
                    }
                    seen.push(&run.engine);
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum TaskClass {
    RepositoryChange,
    /// Look through a repository and report; read-only.
    Exploration,
    Review,
    /// Work an issue through the issue flow (13.5); `issue` absent means
    /// pick an open one nobody is working on.
    IssueWork {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        issue: Option<u64>,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FanOut {
    Single,
    /// One run per engine ("one per agent").
    OnePerEngine,
    /// The engines the person named.
    Named,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Summary {
    None,
    Compose,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlannedRun {
    /// `codex`, `claude`, `grok`, `opencode`, `devin`, `microcoder`, ...
    pub engine: String,
    pub chosen: Chosen,
    /// Read-only is enforced by the executor's policy (no worktree
    /// writes, Git sealed), not by the prompt.
    pub mode: RunMode,
    /// The run's input, by digest; the text lives in the task intent.
    pub input: Digest,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub continuation: Option<Continuation>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Chosen {
    /// The person named it.
    Named,
    /// The signed-in, enabled set (13.1).
    Default,
    /// The router's engine reading.
    Router,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RunMode {
    ReadOnly,
    Write,
}

/// A follow-up that continues an existing task (13.3, #10171). Its
/// admission inherits the original grant and disclosure; anything wider is
/// a new offer.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Continuation {
    pub task: String,
    /// The task revision the router read.
    pub based_on: u64,
    pub how: ContinueHow,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContinueHow {
    /// The ended turn's next turn, in the same engine session and worktree
    /// (the task owner's `continue`).
    NextTurn,
    /// Delivered to the running run at its next step (the device `steer`).
    Steer,
}

/// A standing rule compiled once from the conversation (13.9, #10157).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuleProposal {
    pub change: RuleChange,
    /// The rule document's schema, such as `openagents.background.rule.v1`;
    /// the background crate validates it.
    pub rule_schema: String,
    pub rule: Value,
    pub rule_digest: Digest,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum RuleChange {
    Define,
    Edit { rule: String },
    Pause { rule: String, until: u64 },
    Remove { rule: String },
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Remedy {
    /// Install a published plugin by name.
    Install {
        plugin: String,
    },
    /// Build it as a plugin ([`PluginRoute::Create`]).
    Build,
    None,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ClarifyReason {
    AmbiguousIntent,
    /// No product default applies (13.1).
    NoDefault,
    /// A default would cross an authority line.
    CrossesAuthority,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RefusalReason {
    Harmful,
    SecretShared,
    AsksForSecret,
    /// Money movement never runs from chat; the wallet does it.
    MoneyMovement,
    MissingGrant,
    DeniedDisclosure,
    HostUnavailable,
    StaleOffer,
    RouteNotAllowed,
    LimitReached,
    /// The caller's own key refused under `mine`; nothing runs on ours.
    ProviderKeyRefused,
    UnverifiableEvidence,
    RecoveryInProgress,
}

impl RefusalReason {
    /// The API error `(type, code)` this maps to, from the API design's
    /// error table (section 3.2), where one exists. The rest are proposed
    /// subreasons awaiting review (plan section 7).
    #[must_use]
    pub fn api_error(self) -> Option<(&'static str, &'static str)> {
        Some(match self {
            RefusalReason::MissingGrant => ("permission", "computer_not_granted"),
            RefusalReason::RouteNotAllowed => ("unprocessable", "route_not_allowed"),
            RefusalReason::HostUnavailable => ("unavailable", "computer_offline"),
            RefusalReason::LimitReached => ("limit_reached", "limit_reached"),
            RefusalReason::ProviderKeyRefused => ("unavailable", "upstream_unavailable"),
            _ => return None,
        })
    }
}

/// A bound a route result breaks.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Invalid {
    NoRuns,
    TooManyRuns(usize),
    SingleWithMany,
    RepeatedEngine(String),
    EmptyCommand,
}
