//! Foundations: color swatches, the type scale, radius and shadow, icons.
//!
//! The site CSP forbids inline styles, so each swatch and specimen is a class
//! plus a `data-token`, and `static/components/catalog-tokens.css` carries
//! one rule per token. That file is generated from the tables here by
//! [`tokens_css`]; a test fails when it is stale.

use maud::{Markup, PreEscaped, Render, html};

use super::{Pane, caption, row, specimen, stack};
use crate::icons::{Icon, IconSize};
use crate::tokens::{Resolver, Rgba};

/// Path of the generated swatch stylesheet, relative to the crate root.
pub const TOKENS_CSS_PATH: &str = "static/components/catalog-tokens.css";

/// Color swatch groups: a title and token names without the leading `--`.
pub const COLOR_GROUPS: &[(&str, &[&str])] = &[
    (
        "Surfaces",
        &[
            "color-surface",
            "color-surface-secondary",
            "color-surface-tertiary",
            "color-surface-elevated",
            "color-surface-elevated-secondary",
        ],
    ),
    (
        "Text",
        &[
            "color-text",
            "color-text-secondary",
            "color-text-tertiary",
            "color-text-inverse",
        ],
    ),
    (
        "Borders and ring",
        &[
            "color-border-subtle",
            "color-border",
            "color-border-strong",
            "color-ring",
        ],
    ),
    (
        "Disabled",
        &[
            "color-background-disabled",
            "color-border-disabled",
            "color-text-disabled",
        ],
    ),
    (
        "Primary",
        &[
            "color-background-primary-solid",
            "color-background-primary-soft",
            "color-background-primary-surface",
            "color-border-primary-outline",
            "color-text-primary",
        ],
    ),
    (
        "Secondary",
        &[
            "color-background-secondary-solid",
            "color-background-secondary-soft",
            "color-border-secondary-outline",
            "color-text-secondary",
        ],
    ),
    (
        "Info",
        &[
            "color-background-info-solid",
            "color-background-info-soft",
            "color-background-info-surface",
            "color-border-info-outline",
            "color-text-info",
        ],
    ),
    (
        "Success",
        &[
            "color-background-success-solid",
            "color-background-success-soft",
            "color-background-success-surface",
            "color-border-success-outline",
            "color-text-success",
        ],
    ),
    (
        "Warning",
        &[
            "color-background-warning-solid",
            "color-background-warning-soft",
            "color-background-warning-surface",
            "color-border-warning-outline",
            "color-text-warning",
        ],
    ),
    (
        "Caution",
        &[
            "color-background-caution-solid",
            "color-background-caution-soft",
            "color-background-caution-surface",
            "color-border-caution-outline",
            "color-text-caution",
        ],
    ),
    (
        "Danger",
        &[
            "color-background-danger-solid",
            "color-background-danger-soft",
            "color-background-danger-surface",
            "color-border-danger-outline",
            "color-text-danger",
        ],
    ),
    (
        "Discovery",
        &[
            "color-background-discovery-solid",
            "color-background-discovery-soft",
            "color-background-discovery-surface",
            "color-border-discovery-outline",
            "color-text-discovery",
        ],
    ),
];

/// The type scale: `--font-<name>-{size,line-height,weight,tracking}`.
pub const TYPE_SCALE: &[&str] = &[
    "heading-5xl",
    "heading-4xl",
    "heading-3xl",
    "heading-2xl",
    "heading-xl",
    "heading-lg",
    "heading-md",
    "heading-sm",
    "heading-xs",
    "text-lg",
    "text-md",
    "text-sm",
    "text-xs",
    "text-2xs",
    "text-3xs",
];

/// Radius tokens, without `--`.
pub const RADII: &[&str] = &[
    "radius-2xs",
    "radius-xs",
    "radius-sm",
    "radius-md",
    "radius-lg",
    "radius-xl",
    "radius-2xl",
    "radius-3xl",
    "radius-4xl",
    "radius-full",
];

/// Shadow tokens, without `--`.
pub const SHADOWS: &[&str] = &[
    "shadow-hairline",
    "shadow-100",
    "shadow-200",
    "shadow-300",
    "shadow-400",
];

/// The generated `static/components/catalog-tokens.css`.
#[must_use]
pub fn tokens_css() -> String {
    let mut out = String::from(
        "/* Generated by openagents-ui from src/catalog/foundations.rs (OPENAGENTS_UI_BLESS=1 cargo test -p openagents-ui). Do not edit.\n   One rule per catalog swatch: the site CSP forbids inline styles. */\n",
    );
    for (_, tokens) in COLOR_GROUPS {
        for token in *tokens {
            out.push_str(&format!(
                "\n.oa-catalog-swatch__chip[data-token=\"{token}\"] {{\n  background: var(--{token});\n}}\n"
            ));
        }
    }
    for name in TYPE_SCALE {
        out.push_str(&format!(
            "\n.oa-catalog-type__sample[data-token=\"{name}\"] {{\n  font-size: var(--font-{name}-size);\n  line-height: var(--font-{name}-line-height);\n  font-weight: var(--font-{name}-weight);\n  letter-spacing: var(--font-{name}-tracking);\n}}\n"
        ));
    }
    for token in RADII {
        out.push_str(&format!(
            "\n.oa-catalog-shape[data-token=\"{token}\"] {{\n  border-radius: var(--{token});\n}}\n"
        ));
    }
    for token in SHADOWS {
        out.push_str(&format!(
            "\n.oa-catalog-shape[data-token=\"{token}\"] {{\n  box-shadow: var(--{token});\n}}\n"
        ));
    }
    out
}

fn hex(color: Rgba) -> String {
    let channel = |v: f64| (v.clamp(0.0, 1.0) * 255.0).round() as u8;
    let rgb = format!(
        "#{:02x}{:02x}{:02x}",
        channel(color.r),
        channel(color.g),
        channel(color.b)
    );
    if color.a < 0.999 {
        format!("{rgb} / {}%", (color.a * 100.0).round())
    } else {
        rgb
    }
}

pub(super) fn colors(pane: Pane) -> Markup {
    let resolver = Resolver::new();
    html! {
        @for (title, tokens) in COLOR_GROUPS {
            div class="oa-catalog-swatches" {
                p class="oa-catalog-specimen__title" { (title) }
                ul class="oa-catalog-swatches__list" role="list" {
                    @for token in *tokens {
                        @let value = resolver.color(&format!("--{token}"), pane.scheme()).map(hex);
                        li class="oa-catalog-swatch" {
                            span class="oa-catalog-swatch__chip" data-token=(token) {}
                            code class="oa-catalog-swatch__name" { "--" (token) }
                            @if let Some(value) = value {
                                span class="oa-catalog-swatch__value" { (value) }
                            }
                        }
                    }
                }
            }
        }
    }
}

pub(super) fn typography(_pane: Pane) -> Markup {
    html! {
        ul class="oa-catalog-type" role="list" {
            @for name in TYPE_SCALE {
                li class="oa-catalog-type__row" {
                    code class="oa-catalog-type__name" { (name) }
                    span class="oa-catalog-type__sample" data-token=(name) { "Agents at work" }
                }
            }
        }
        p class="oa-catalog-type__mono" { "font-mono: cargo test -p openagents-ui" }
    }
}

pub(super) fn radius_shadow(_pane: Pane) -> Markup {
    html! {
        p class="oa-catalog-specimen__title" { "Radius" }
        ul class="oa-catalog-shapes" role="list" {
            @for token in RADII {
                li class="oa-catalog-shapes__item" {
                    span class="oa-catalog-shape" data-kind="radius" data-token=(token) {}
                    (caption(token))
                }
            }
        }
        p class="oa-catalog-specimen__title" { "Shadow" }
        ul class="oa-catalog-shapes" role="list" {
            @for token in SHADOWS {
                li class="oa-catalog-shapes__item" {
                    span class="oa-catalog-shape" data-kind="shadow" data-token=(token) {}
                    (caption(token))
                }
            }
        }
    }
}

pub(super) fn icons(_pane: Pane) -> Markup {
    let sizes = [
        (IconSize::Xs, "xs"),
        (IconSize::Sm, "sm"),
        (IconSize::Md, "md"),
        (IconSize::Lg, "lg"),
        (IconSize::Xl, "xl"),
        (IconSize::Xxl, "2xl"),
    ];
    html! {
        (specimen("SizedIcon", "Sizes", row(html! {
            @for (size, name) in sizes {
                span class="oa-catalog-labelled" { (Icon::Sparkles.size(size)) (caption(name)) }
            }
        })))
        (specimen("Icon", &format!("All {} icons", Icon::ALL.len()), stack(html! {
            ul class="oa-catalog-icons" role="list" {
                @for icon in Icon::ALL {
                    li class="oa-catalog-icons__item" title=(icon.name()) {
                        (PreEscaped(format!(
                            r##"<svg class="oa-icon" data-size="lg" aria-hidden="true" focusable="false" width="1em" height="1em"><use href="#{}"></use></svg>"##,
                            sprite_id(icon)
                        )))
                        span class="oa-catalog-icons__name" { (icon.name()) }
                    }
                }
            }
        })))
    }
}

fn sprite_id(icon: Icon) -> String {
    format!("catalog-icon-{}", icon.name())
}

/// Every icon once, as `<symbol>`s the icon grids in both panes `<use>`:
/// drawing 755 inline SVGs twice would double the page. Hidden without
/// `display: none`, which would break the brand icons' clip paths.
pub(super) fn icon_sprite() -> Markup {
    let mut out =
        String::from(r#"<svg class="oa-catalog-sprite" aria-hidden="true" focusable="false">"#);
    for icon in Icon::ALL {
        let svg = icon.render().into_string();
        // `<svg class="oa-icon" aria-hidden="true" focusable="false"
        // width="1em" height="1em" ATTRS>BODY</svg>`
        let open_end = svg.find('>').expect("svg open tag");
        let attrs = svg[..open_end]
            .split_once(r#"height="1em""#)
            .map_or("", |(_, rest)| rest);
        let body = &svg[open_end + 1..svg.len() - "</svg>".len()];
        out.push_str(&format!(
            r#"<symbol id="{}"{attrs}>{body}</symbol>"#,
            sprite_id(icon)
        ));
    }
    out.push_str("</svg>");
    PreEscaped(out)
}
