#!/usr/bin/env node
/**
 * Vendor the agent-experience-memory modules the coder's memory runs on.
 *
 * The CLI ships standalone — `pnpm pack` and a global install with no
 * workspace around it — so it cannot carry a runtime dependency on the
 * unpublished workspace package. The canonical sources stay in
 * `packages/agent-experience-memory` and `packages/atif`; this script copies
 * the exact closure into `src/memory/` with only import specifiers rewritten.
 * `test/vendored-memory-drift.test.ts` re-runs the same transform and fails
 * when the vendored tree no longer matches the canonical sources, so the two
 * copies cannot drift silently.
 *
 * Run from the package root: `node scripts/vendor-memory.mjs`
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const packagesRoot = join(packageRoot, "..");

/** source path (from packages/) → vendored name, with specifier rewrites. */
export const VENDORED = [
  ["atif/src/redaction.ts", "redaction.ts", [["./bip39-wordlist.ts", "./bip39-wordlist.js"]]],
  ["atif/src/bip39-wordlist.ts", "bip39-wordlist.ts", []],
  ["agent-experience-memory/src/internal/sha256.ts", "sha256.ts", []],
  ["agent-experience-memory/src/internal/canonical.ts", "canonical.ts", []],
  ["agent-experience-memory/src/contract/refs.ts", "refs.ts", []],
  ["agent-experience-memory/src/contract/pattern.ts", "pattern.ts", [["./refs.js", "./refs.js"]]],
  ["agent-experience-memory/src/ranking.ts", "ranking.ts", []],
  [
    "agent-experience-memory/src/engram.ts",
    "engram.ts",
    [
      ["@openagentsinc/atif/redaction", "./redaction.js"],
      ["./internal/canonical.js", "./canonical.js"],
      ["./internal/sha256.js", "./sha256.js"],
    ],
  ],
  [
    "agent-experience-memory/src/projection.ts",
    "projection.ts",
    [
      ["./internal/canonical.js", "./canonical.js"],
      ["./internal/sha256.js", "./sha256.js"],
    ],
  ],
  [
    "agent-experience-memory/src/consolidation.ts",
    "consolidation.ts",
    [
      ["./contract/pattern.js", "./pattern.js"],
      ["./contract/refs.js", "./refs.js"],
      ["./internal/canonical.js", "./canonical.js"],
      ["./internal/sha256.js", "./sha256.js"],
    ],
  ],
  [
    "agent-experience-memory/src/subagent-memory.ts",
    "subagent-memory.ts",
    [
      ["./contract/pattern.js", "./pattern.js"],
      ["./contract/refs.js", "./refs.js"],
      ["./internal/canonical.js", "./canonical.js"],
      ["./internal/sha256.js", "./sha256.js"],
    ],
  ],
];

const HEADER = (source) =>
  `// Vendored from packages/${source} by scripts/vendor-memory.mjs — do not edit here.\n` +
  `// The drift guard (test/vendored-memory-drift.test.ts) fails when this copy\n` +
  `// no longer matches the canonical source.\n`;

/** The vendored text for one entry, derived from the canonical source. */
export const renderVendored = (source, rewrites) => {
  let text = readFileSync(join(packagesRoot, source), "utf8");
  for (const [from, to] of rewrites) {
    text = text.replaceAll(`"${from}"`, `"${to}"`);
  }
  return HEADER(source) + text;
};

const BARREL = `// The barrel coder-memory.ts consumes; regenerated by scripts/vendor-memory.mjs.
export * from "./engram.js";
export * from "./consolidation.js";
export * from "./subagent-memory.js";
export * from "./projection.js";
`;

export const writeAll = () => {
  const out = join(packageRoot, "src", "memory");
  mkdirSync(out, { recursive: true });
  for (const [source, name, rewrites] of VENDORED) {
    writeFileSync(join(out, name), renderVendored(source, rewrites));
  }
  writeFileSync(join(out, "index.ts"), BARREL);
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeAll();
  console.log(`vendored ${VENDORED.length} modules into src/memory/`);
}
