<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobState.proto

namespace App\Grpc\nostr\GPBMetadata;

class JobState
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        \App\Grpc\nostr\GPBMetadata\Log::initOnce();
        \App\Grpc\nostr\GPBMetadata\JobStatus::initOnce();
        \App\Grpc\nostr\GPBMetadata\JobResult::initOnce();
        $pool->internalAddGeneratedFile(
            '
–
JobState.protoJobStatus.protoJobResult.proto"©
JobState

acceptedAt (

acceptedBy (	
status (2
.JobStatus
logs (2.Log
	timestamp (
result (2
.JobResult
acceptedByNode (	B.ÊApp\\Grpc\\nostrâApp\\Grpc\\nostr\\GPBMetadatabproto3', true);

        static::$is_initialized = true;
    }
}
