// Generated by `schema/generate.py`.
use crate::models::*;
impl crate::Client {
    /// Call `DELETE /environments/{environmentId}/secret-files`.
    pub async fn delete_environment_secret_file(
        &self,
        params: &DeleteEnvironmentSecretFileParams,
    ) -> crate::Result<EnvironmentItemChangeResponse> {
        let path = self.path(&[
            "environments",
            &params.environment_id.to_string(),
            "secret-files",
        ])?;
        let query: Vec<(&str, String)> = vec![("path", params.path.to_string())];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::DELETE,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /environments/{environmentId}/repos`.
    pub async fn add_environment_repo(
        &self,
        params: &AddEnvironmentRepoParams,
    ) -> crate::Result<EnvironmentItemChangeResponse> {
        let path = self.path(&["environments", &params.environment_id.to_string(), "repos"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `DELETE /environments/{environmentId}/repos/{repositoryId}`.
    pub async fn delete_environment_repo(
        &self,
        params: &DeleteEnvironmentRepoParams,
    ) -> crate::Result<EnvironmentItemChangeResponse> {
        let path = self.path(&[
            "environments",
            &params.environment_id.to_string(),
            "repos",
            &params.repository_id.to_string(),
        ])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::DELETE,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /sandboxes`.
    pub async fn sandboxes(&self, params: &SandboxesParams) -> crate::Result<SandboxListResponse> {
        let path = self.path(&["sandboxes"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.org {
            query.push(("org", value.to_string()));
        }
        if let Some(value) = &params.limit {
            query.push(("limit", value.to_string()));
        }
        if let Some(value) = &params.cursor {
            query.push(("cursor", value.to_string()));
        }
        if let Some(value) = &params.sort {
            query.push(("sort", value.to_string()));
        }
        if let Some(value) = &params.state {
            query.push(("state", value.to_string()));
        }
        let mut headers: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.x_boat_org {
            headers.push(("X-Boat-Org", value.to_string()));
        }
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: true,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /sandboxes`.
    pub async fn create(&self, params: &CreateParams) -> crate::Result<CreateSandboxResponse> {
        let path = self.path(&["sandboxes"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.org {
            query.push(("org", value.to_string()));
        }
        let mut headers: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.idempotency_key {
            headers.push(("Idempotency-Key", value.to_string()));
        }
        if let Some(value) = &params.x_boat_org {
            headers.push(("X-Boat-Org", value.to_string()));
        }
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::IfKeyed,
                org: true,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            params
                .body
                .as_ref()
                .map(serde_json::to_value)
                .transpose()
                .map_err(crate::Error::encode)?,
        )
        .await
    }
    /// Call `GET /sandboxes/{sandboxId}`.
    pub async fn get(&self, params: &GetParams) -> crate::Result<SandboxInfoResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `PATCH /sandboxes/{sandboxId}`.
    pub async fn update(&self, params: &UpdateParams) -> crate::Result<SandboxInfoResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::PATCH,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `DELETE /sandboxes/{sandboxId}`.
    pub async fn delete_sandbox(
        &self,
        params: &DeleteSandboxParams,
    ) -> crate::Result<DeletionOperationResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![(
            "X-Ascii-Confirm-Delete",
            params.x_ascii_confirm_delete.to_string(),
        )];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::DELETE,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/stop`.
    pub async fn stop(&self, params: &StopParams) -> crate::Result<SandboxActionResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "stop"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            params
                .body
                .as_ref()
                .map(serde_json::to_value)
                .transpose()
                .map_err(crate::Error::encode)?,
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/share`.
    pub async fn share(&self, params: &ShareParams) -> crate::Result<ShareResponseBody> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "share"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
}
