// Generated by `schema/generate.py`.
use crate::models::*;
impl crate::Client {
    /// Call `POST /sandboxes/{sandboxId}/resume`.
    pub async fn resume(&self, params: &ResumeParams) -> crate::Result<SandboxActionResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "resume"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            params
                .body
                .as_ref()
                .map(serde_json::to_value)
                .transpose()
                .map_err(crate::Error::encode)?,
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/fork`.
    pub async fn fork(&self, params: &ForkParams) -> crate::Result<SandboxActionResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "fork"])?;
        let query: Vec<(&str, String)> = vec![];
        let mut headers: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.idempotency_key {
            headers.push(("Idempotency-Key", value.to_string()));
        }
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::IfKeyed,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            params
                .body
                .as_ref()
                .map(serde_json::to_value)
                .transpose()
                .map_err(crate::Error::encode)?,
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/prompt`.
    pub async fn prompt(&self, params: &PromptParams) -> crate::Result<PromptResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "prompt"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /sandboxes/{sandboxId}/events`.
    pub async fn events(&self, params: &EventsParams) -> crate::Result<EventsResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "events"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.limit {
            query.push(("limit", value.to_string()));
        }
        if let Some(value) = &params.cursor {
            query.push(("cursor", value.to_string()));
        }
        if let Some(value) = &params.sort {
            query.push(("sort", value.to_string()));
        }
        if let Some(value) = &params.type_ {
            query.push(("type", value.to_string()));
        }
        if let Some(value) = &params.conversation {
            query.push(("conversation", value.to_string()));
        }
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /sandboxes/{sandboxId}/conversations`.
    pub async fn conversations(
        &self,
        params: &ConversationsParams,
    ) -> crate::Result<ConversationsResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "conversations"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /sandboxes/{sandboxId}/prompts/{promptId}`.
    pub async fn prompt_run_status(
        &self,
        params: &PromptRunStatusParams,
    ) -> crate::Result<PromptRunResponse> {
        let path = self.path(&[
            "sandboxes",
            &params.sandbox_id.to_string(),
            "prompts",
            &params.prompt_id.to_string(),
        ])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /sandboxes/{sandboxId}/files`.
    pub async fn read_file(&self, params: &ReadFileParams) -> crate::Result<FileReadResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "files"])?;
        let mut query: Vec<(&str, String)> = vec![("path", params.path.to_string())];
        if let Some(value) = &params.encoding {
            query.push(("encoding", value.to_string()));
        }
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `PUT /sandboxes/{sandboxId}/files`.
    pub async fn write_file(&self, params: &WriteFileParams) -> crate::Result<FileWriteResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "files"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::PUT,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/commands`.
    pub async fn command(&self, params: &CommandParams) -> crate::Result<CommandResponseBody> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "commands"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /sandboxes/{sandboxId}/commands/{processId}`.
    pub async fn command_status(
        &self,
        params: &CommandStatusParams,
    ) -> crate::Result<CommandStatusResponse> {
        let path = self.path(&[
            "sandboxes",
            &params.sandbox_id.to_string(),
            "commands",
            &params.process_id.to_string(),
        ])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.tail_bytes {
            query.push(("tailBytes", value.to_string()));
        }
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
}
