// Generated by `schema/generate.py`.
use crate::models::*;
impl crate::Client {
    /// Call `GET /me`.
    pub async fn me(&self) -> crate::Result<MeResponse> {
        let path = self.path(&["me"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /orgs`.
    pub async fn list_organizations(&self) -> crate::Result<OrgListResponse> {
        let path = self.path(&["orgs"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `PATCH /orgs/active`.
    pub async fn set_active_organization(
        &self,
        params: &SetActiveOrganizationParams,
    ) -> crate::Result<ActiveOrgResponse> {
        let path = self.path(&["orgs", "active"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::PATCH,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /account/data-retention`.
    pub async fn get_data_retention(&self) -> crate::Result<DataRetentionPolicyResponse> {
        let path = self.path(&["account", "data-retention"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `PATCH /account/data-retention`.
    pub async fn update_data_retention(
        &self,
        params: &UpdateDataRetentionParams,
    ) -> crate::Result<DataRetentionPolicyResponse> {
        let path = self.path(&["account", "data-retention"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::PATCH,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /deletion-operations/{operationId}`.
    pub async fn get_deletion_operation(
        &self,
        params: &GetDeletionOperationParams,
    ) -> crate::Result<DeletionOperationResponse> {
        let path = self.path(&["deletion-operations", &params.operation_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /limits`.
    pub async fn limits(&self, params: &LimitsParams) -> crate::Result<LimitsResponse> {
        let path = self.path(&["limits"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.org {
            query.push(("org", value.to_string()));
        }
        if let Some(value) = &params.team_id {
            query.push(("teamId", value.to_string()));
        }
        let mut headers: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.x_boat_org {
            headers.push(("X-Boat-Org", value.to_string()));
        }
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: true,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /repos`.
    pub async fn repos(&self, params: &ReposParams) -> crate::Result<ReposResponse> {
        let path = self.path(&["repos"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.sync {
            query.push(("sync", value.to_string()));
        }
        if let Some(value) = &params.limit {
            query.push(("limit", value.to_string()));
        }
        if let Some(value) = &params.cursor {
            query.push(("cursor", value.to_string()));
        }
        if let Some(value) = &params.sort {
            query.push(("sort", value.to_string()));
        }
        if let Some(value) = &params.q {
            query.push(("q", value.to_string()));
        }
        if let Some(value) = &params.selected {
            query.push(("selected", value.to_string()));
        }
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /repos`.
    pub async fn select_repo(
        &self,
        params: &SelectRepoParams,
    ) -> crate::Result<RepoSelectionResponse> {
        let path = self.path(&["repos"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /api-keys`.
    pub async fn api_keys(&self) -> crate::Result<ApiKeysResponse> {
        let path = self.path(&["api-keys"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
}
