// Generated by `schema/generate.py`.
use crate::models::*;
impl crate::Client {
    /// Call `POST /api-keys/scoped`.
    pub async fn create_scoped_api_key(
        &self,
        params: &CreateScopedApiKeyParams,
    ) -> crate::Result<ApiKeySecretResponse> {
        let path = self.path(&["api-keys", "scoped"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `DELETE /api-keys/{apiKeyId}`.
    pub async fn revoke_api_key(
        &self,
        params: &RevokeApiKeyParams,
    ) -> crate::Result<ApiKeyRevokeResponse> {
        let path = self.path(&["api-keys", &params.api_key_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::DELETE,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /api-keys/{apiKeyId}/rotate`.
    pub async fn rotate_api_key(
        &self,
        params: &RotateApiKeyParams,
    ) -> crate::Result<ApiKeySecretResponse> {
        let path = self.path(&["api-keys", &params.api_key_id.to_string(), "rotate"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /api-keys/{apiKeyId}/usage`.
    pub async fn api_key_usage(
        &self,
        params: &ApiKeyUsageParams,
    ) -> crate::Result<ApiKeyUsageResponse> {
        let path = self.path(&["api-keys", &params.api_key_id.to_string(), "usage"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `GET /webhooks`.
    pub async fn list_webhooks(&self) -> crate::Result<WebhookListResponse> {
        let path = self.path(&["webhooks"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /webhooks`.
    pub async fn create_webhook(
        &self,
        params: &CreateWebhookParams,
    ) -> crate::Result<WebhookSecretResponse> {
        let path = self.path(&["webhooks"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /webhooks/{webhookId}`.
    pub async fn get_webhook(&self, params: &GetWebhookParams) -> crate::Result<WebhookResponse> {
        let path = self.path(&["webhooks", &params.webhook_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `PATCH /webhooks/{webhookId}`.
    pub async fn update_webhook(
        &self,
        params: &UpdateWebhookParams,
    ) -> crate::Result<WebhookResponse> {
        let path = self.path(&["webhooks", &params.webhook_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::PATCH,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `DELETE /webhooks/{webhookId}`.
    pub async fn delete_webhook(
        &self,
        params: &DeleteWebhookParams,
    ) -> crate::Result<WebhookDeleteResponse> {
        let path = self.path(&["webhooks", &params.webhook_id.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::DELETE,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /webhooks/{webhookId}/rotate`.
    pub async fn rotate_webhook_signing_secret(
        &self,
        params: &RotateWebhookSigningSecretParams,
    ) -> crate::Result<WebhookSecretResponse> {
        let path = self.path(&["webhooks", &params.webhook_id.to_string(), "rotate"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
}
