// Generated by `schema/generate.py`.
use crate::models::*;
impl crate::Client {
    /// Call `GET /sandboxes/{sandboxId}/artifacts`.
    pub async fn artifact(&self, params: &ArtifactParams) -> crate::Result<crate::Download> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "artifacts"])?;
        let query: Vec<(&str, String)> = vec![("path", params.path.to_string())];
        let headers: Vec<(&str, String)> = vec![];
        self.download(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/steer`.
    pub async fn steer(&self, params: &SteerParams) -> crate::Result<SteerResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "steer"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.conversation {
            query.push(("conversation", value.to_string()));
        }
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/interrupt`.
    pub async fn interrupt(
        &self,
        params: &InterruptParams,
    ) -> crate::Result<SandboxActionResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "interrupt"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.conversation {
            query.push(("conversation", value.to_string()));
        }
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/desktop`.
    pub async fn desktop(&self, params: &DesktopParams) -> crate::Result<DesktopResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "desktop"])?;
        let mut query: Vec<(&str, String)> = vec![];
        if let Some(value) = &params.vnc {
            query.push(("vnc", value.to_string()));
        }
        if let Some(value) = &params.theme {
            query.push(("theme", value.to_string()));
        }
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            params
                .body
                .as_ref()
                .map(serde_json::to_value)
                .transpose()
                .map_err(crate::Error::encode)?,
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/host`.
    pub async fn host_port(&self, params: &HostPortParams) -> crate::Result<HostPortResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "host"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `POST /sandboxes/{sandboxId}/sshkey`.
    pub async fn ssh_key(&self, params: &SshKeyParams) -> crate::Result<SshKeyResponse> {
        let path = self.path(&["sandboxes", &params.sandbox_id.to_string(), "sshkey"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /named-snapshots`.
    pub async fn list_named_snapshots(&self) -> crate::Result<NamedSnapshotListResponse> {
        let path = self.path(&["named-snapshots"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `POST /named-snapshots`.
    pub async fn save_named_snapshot(
        &self,
        params: &SaveNamedSnapshotParams,
    ) -> crate::Result<NamedSnapshotSavingResponse> {
        let path = self.path(&["named-snapshots"])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::POST,
            path,
            &query,
            &headers,
            Some(serde_json::to_value(&params.body).map_err(crate::Error::encode)?),
        )
        .await
    }
    /// Call `GET /named-snapshots/{name}`.
    pub async fn get_named_snapshot(
        &self,
        params: &GetNamedSnapshotParams,
    ) -> crate::Result<NamedSnapshotInfoResponse> {
        let path = self.path(&["named-snapshots", &params.name.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Read,
                org: false,
            },
            reqwest::Method::GET,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
    /// Call `DELETE /named-snapshots/{name}`.
    pub async fn delete_named_snapshot(
        &self,
        params: &DeleteNamedSnapshotParams,
    ) -> crate::Result<NamedSnapshotDeletedResponse> {
        let path = self.path(&["named-snapshots", &params.name.to_string()])?;
        let query: Vec<(&str, String)> = vec![];
        let headers: Vec<(&str, String)> = vec![];
        self.json(
            crate::client::Op {
                retry: crate::client::Retry::Never,
                org: false,
            },
            reqwest::Method::DELETE,
            path,
            &query,
            &headers,
            None,
        )
        .await
    }
}
