import * as stylex from '@stylexjs/stylex'

import {
  stylexFallback,
  stylexRuntimeFallbackEnabled,
} from './stylex-foldkit'

export const workroomStyles = stylexRuntimeFallbackEnabled()
  ? {
      chatSurface: stylexFallback('oa-ui-workroom-chat-surface'),
      text12Regular: stylexFallback('oa-ui-workroom-text-12-regular'),
      text14Regular: stylexFallback('oa-ui-workroom-text-14-regular'),
      sessionTurn: stylexFallback('oa-ui-workroom-session-turn'),
      sessionMessageContainer: stylexFallback(
        'oa-ui-workroom-session-message-container',
      ),
      sessionMessageContent: stylexFallback(
        'oa-ui-workroom-session-message-content',
      ),
      assistantContent: stylexFallback('oa-ui-workroom-assistant-content'),
      textPart: stylexFallback('oa-ui-workroom-text-part'),
      textPartBody: stylexFallback('oa-ui-workroom-text-part-body'),
      toolPartWrapper: stylexFallback('oa-ui-workroom-tool-part-wrapper'),
      collapsible: stylexFallback('oa-ui-workroom-collapsible'),
      toolCollapsible: stylexFallback('oa-ui-workroom-tool-collapsible'),
      collapsibleTrigger: stylexFallback(
        'oa-ui-workroom-collapsible-trigger',
      ),
      collapsibleContent: stylexFallback(
        'oa-ui-workroom-collapsible-content',
      ),
      toolTrigger: stylexFallback('oa-ui-workroom-tool-trigger'),
      toolTriggerContent: stylexFallback(
        'oa-ui-workroom-tool-trigger-content',
      ),
      toolIndicator: stylexFallback('oa-ui-workroom-tool-indicator'),
      toolInfo: stylexFallback('oa-ui-workroom-tool-info'),
      toolInfoStructured: stylexFallback(
        'oa-ui-workroom-tool-info-structured',
      ),
      toolInfoMain: stylexFallback('oa-ui-workroom-tool-info-main'),
      toolTitle: stylexFallback('oa-ui-workroom-tool-title'),
      toolSubtitle: stylexFallback('oa-ui-workroom-tool-subtitle'),
      toolOutput: stylexFallback('oa-ui-workroom-tool-output'),
      toolOutputPre: stylexFallback('oa-ui-workroom-tool-output-pre'),
      toolOutputCode: stylexFallback('oa-ui-workroom-tool-output-code'),
      bashOutput: stylexFallback('oa-ui-workroom-bash-output'),
      bashScroll: stylexFallback('oa-ui-workroom-bash-scroll'),
      bashPre: stylexFallback('oa-ui-workroom-bash-pre'),
      bashCode: stylexFallback('oa-ui-workroom-bash-code'),
      diffs: stylexFallback('oa-ui-workroom-diffs'),
      diffsHeader: stylexFallback('oa-ui-workroom-diffs-header'),
      diffsLabel: stylexFallback('oa-ui-workroom-diffs-label'),
      diffsContent: stylexFallback('oa-ui-workroom-diffs-content'),
      diffTrigger: stylexFallback('oa-ui-workroom-diff-trigger'),
      diffPath: stylexFallback('oa-ui-workroom-diff-path'),
      diffFilename: stylexFallback('oa-ui-workroom-diff-filename'),
      diffMeta: stylexFallback('oa-ui-workroom-diff-meta'),
      writeTrigger: stylexFallback('oa-ui-workroom-write-trigger'),
      messageTitleArea: stylexFallback('oa-ui-workroom-message-title-area'),
      messageTitle: stylexFallback('oa-ui-workroom-message-title'),
      messageTitleText: stylexFallback('oa-ui-workroom-message-title-text'),
      messageTitleFilename: stylexFallback(
        'oa-ui-workroom-message-title-filename',
      ),
      messageActions: stylexFallback('oa-ui-workroom-message-actions'),
      writeContent: stylexFallback('oa-ui-workroom-write-content'),
    }
  : stylex.create({
      chatSurface: {
        '--font-family-mono': 'var(--font-family-chat-mono)',
        fontFamily: 'var(--font-family-chat-mono)',
      },
      text12Regular: {
        fontFamily: 'var(--font-family-sans)',
        fontSize: 'var(--font-size-small)',
        fontStyle: 'normal',
        fontWeight: 'var(--font-weight-regular)',
        lineHeight: 'var(--line-height-large)',
        letterSpacing: 'var(--letter-spacing-normal)',
      },
      text14Regular: {
        fontFamily: 'var(--font-family-sans)',
        fontSize: 'var(--font-size-base)',
        fontStyle: 'normal',
        fontWeight: 'var(--font-weight-regular)',
        lineHeight: 'var(--line-height-x-large)',
        letterSpacing: 'var(--letter-spacing-normal)',
      },
      sessionTurn: {
        '--sticky-header-height':
          'calc(var(--session-title-height, 0px) + 24px)',
        height: '100%',
        minHeight: 0,
        minWidth: 0,
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
      },
      sessionMessageContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        alignSelf: 'stretch',
        minWidth: 0,
        gap: 0,
        overflowAnchor: 'none',
      },
      sessionMessageContent: {
        marginTop: 0,
        width: '100%',
        minWidth: 0,
        maxWidth: '100%',
      },
      assistantContent: {
        width: '100%',
        minWidth: 0,
        display: 'flex',
        flexDirection: 'column',
        alignSelf: 'stretch',
        gap: 12,
      },
      textPart: {
        width: '100%',
        marginTop: 24,
      },
      textPartBody: {
        marginTop: 0,
      },
      toolPartWrapper: {
        width: '100%',
      },
      collapsible: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'transparent',
        border: 'none',
        transition: 'background-color 0.15s ease',
        borderRadius: 'var(--radius-md)',
        overflow: 'visible',
      },
      toolCollapsible: {
        '--tool-content-gap': '4px',
        gap: 'var(--tool-content-gap)',
      },
      collapsibleTrigger: {
        width: '100%',
        display: 'flex',
        height: 32,
        padding: 0,
        alignItems: 'center',
        alignSelf: 'stretch',
        cursor: 'default',
        userSelect: 'none',
        color: 'var(--text-base)',
        fontFamily: 'var(--font-family-sans)',
        fontSize: 'var(--font-size-small)',
        fontStyle: 'normal',
        fontWeight: 'var(--font-weight-medium)',
        lineHeight: 'var(--line-height-large)',
        letterSpacing: 'var(--letter-spacing-normal)',
      },
      collapsibleContent: {
        overflow: 'hidden',
      },
      toolTrigger: {
        contentVisibility: 'auto',
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        alignSelf: 'stretch',
        gap: 0,
        justifyContent: 'flex-start',
      },
      toolTriggerContent: {
        flex: '0 1 auto',
        width: 'auto',
        maxWidth: 'calc(100% - 24px)',
        minWidth: 0,
        display: 'flex',
        alignItems: 'center',
        alignSelf: 'stretch',
        gap: 8,
      },
      toolIndicator: {
        width: 16,
        height: 16,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
      },
      toolInfo: {
        flex: '0 1 auto',
        minWidth: 0,
        maxWidth: '100%',
        fontSize: 13,
      },
      toolInfoStructured: {
        flex: '0 1 auto',
        width: 'auto',
        maxWidth: '100%',
        minWidth: 0,
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        justifyContent: 'flex-start',
      },
      toolInfoMain: {
        display: 'flex',
        alignItems: 'baseline',
        gap: 8,
        minWidth: 0,
        overflow: 'hidden',
      },
      toolTitle: {
        flexShrink: 0,
        fontFamily: 'var(--font-family-sans)',
        fontSize: 13,
        fontStyle: 'normal',
        fontWeight: 'var(--font-weight-medium)',
        lineHeight: 'var(--line-height-large)',
        letterSpacing: 'var(--letter-spacing-normal)',
        color: 'var(--text-strong)',
      },
      toolSubtitle: {
        flexShrink: 1,
        minWidth: 0,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontFamily: 'var(--font-family-sans)',
        fontVariantNumeric: 'tabular-nums',
        fontSize: 13,
        fontStyle: 'normal',
        fontWeight: 'var(--font-weight-regular)',
        lineHeight: 'var(--line-height-large)',
        letterSpacing: 'var(--letter-spacing-normal)',
        color: 'var(--text-base)',
      },
      toolOutput: {
        whiteSpace: 'pre',
        padding: 0,
        marginBottom: 24,
        height: 'fit-content',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        color: 'var(--text-base)',
        fontFamily: 'var(--font-family-mono)',
        fontSize: 12,
        lineHeight: 'var(--line-height-large)',
        scrollbarWidth: 'none',
        msOverflowStyle: 'none',
      },
      toolOutputPre: {
        margin: 0,
        padding: 0,
        background: 'none',
      },
      toolOutputCode: {
        fontFamily: 'var(--font-family-mono)',
        fontFeatureSettings: 'var(--font-family-mono--font-feature-settings)',
        fontSize: 12,
        lineHeight: 'var(--line-height-large)',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
        color: 'var(--text-base)',
      },
      bashOutput: {
        width: '100%',
        border: '1px solid var(--border-weak-base)',
        borderRadius: 6,
        background: 'transparent',
        position: 'relative',
        overflow: 'hidden',
      },
      bashScroll: {
        width: '100%',
        overflowY: 'auto',
        overflowX: 'hidden',
        maxHeight: 240,
        scrollbarWidth: 'none',
        msOverflowStyle: 'none',
      },
      bashPre: {
        margin: 0,
        padding: 12,
      },
      bashCode: {
        fontFamily: 'var(--font-family-mono)',
        fontFeatureSettings: 'var(--font-family-mono--font-feature-settings)',
        fontSize: 12,
        lineHeight: 'var(--line-height-large)',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
        color: 'var(--text-base)',
      },
      diffs: {
        width: '100%',
        minWidth: 0,
      },
      diffsHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        paddingTop: 4,
        paddingBottom: 12,
        backgroundColor: 'var(--background-stronger)',
        height: 44,
      },
      diffsLabel: {
        fontVariantNumeric: 'tabular-nums',
        color: 'var(--text-strong)',
        fontFamily: 'var(--font-family-sans)',
        fontSize: 'var(--font-size-base)',
        fontWeight: 'var(--font-weight-medium)',
        lineHeight: 'var(--line-height-large)',
      },
      diffsContent: {
        paddingTop: 0,
        display: 'flex',
        flexDirection: 'column',
      },
      diffTrigger: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        width: '100%',
        minWidth: 0,
      },
      diffPath: {
        display: 'flex',
        flexGrow: 1,
        minWidth: 0,
        fontFamily: 'var(--font-family-sans)',
        fontSize: 'var(--font-size-small)',
        lineHeight: 'var(--line-height-large)',
      },
      diffFilename: {
        minWidth: 0,
        color: 'var(--text-strong)',
        fontWeight: 'var(--font-weight-medium)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
      },
      diffMeta: {
        flexShrink: 0,
        display: 'inline-flex',
        alignItems: 'center',
        gap: 10,
      },
      writeTrigger: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        width: '100%',
      },
      messageTitleArea: {
        flexGrow: 1,
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        minWidth: 0,
      },
      messageTitle: {
        flex: '1 1 auto',
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        minWidth: 0,
        fontFamily: 'var(--font-family-sans)',
        fontSize: 13,
        fontStyle: 'normal',
        fontWeight: 'var(--font-weight-medium)',
        lineHeight: 'var(--line-height-large)',
        letterSpacing: 'var(--letter-spacing-normal)',
        color: 'var(--text-base)',
      },
      messageTitleText: {
        flexShrink: 0,
        color: 'var(--text-strong)',
      },
      messageTitleFilename: {
        minWidth: 0,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontWeight: 'var(--font-weight-regular)',
      },
      messageActions: {
        display: 'flex',
        gap: 16,
        alignItems: 'center',
        justifyContent: 'flex-end',
        flexShrink: 0,
      },
      writeContent: {
        borderRadius: 'inherit',
        borderTop: '1px solid var(--border-weaker-base)',
        overflowX: 'hidden',
        overflowY: 'visible',
        scrollbarWidth: 'none',
        msOverflowStyle: 'none',
      },
    })
