<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

/**
 * Represents the expected outcome of an AuditModulesRequest. If PASS is provided, then
 * the audit returns modules which conform to the checkfile. If FAIL is provided, then
 * the audit returns modules which do not conform to the checkfile.
 *
 * Protobuf type <code>AuditOutcome</code>
 */
class AuditOutcome
{
    /**
     * Generated from protobuf enum <code>PASS = 0;</code>
     */
    const PASS = 0;
    /**
     * Generated from protobuf enum <code>FAIL = 1;</code>
     */
    const FAIL = 1;

    private static $valueToName = [
        self::PASS => 'PASS',
        self::FAIL => 'FAIL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

