<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace App\Services\Extism\Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * PUT /api/v1/plugin:
 *
 * Generated from protobuf message <code>InstallPluginRequest</code>
 */
class InstallPluginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string identifier = 1;</code>
     */
    protected $identifier = '';

    /**
     * Generated from protobuf field <code>optional string name = 2;</code>
     */
    protected $name = null;

    /**
     * Generated from protobuf field <code>string location = 3;</code>
     */
    protected $location = '';

    /**
     * bytes config = 5;
     *
     * Generated from protobuf field <code>bytes wasm = 4;</code>
     */
    protected $wasm = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $identifier
     * @type string $name
     * @type string $location
     * @type string $wasm
     *              bytes config = 5;
     *              }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string identifier = 1;</code>
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Generated from protobuf field <code>string identifier = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkString($var, true);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string name = 2;</code>
     *
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string location = 3;</code>
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>string location = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, true);
        $this->location = $var;

        return $this;
    }

    /**
     * bytes config = 5;
     *
     * Generated from protobuf field <code>bytes wasm = 4;</code>
     *
     * @return string
     */
    public function getWasm()
    {
        return $this->wasm;
    }

    /**
     * bytes config = 5;
     *
     * Generated from protobuf field <code>bytes wasm = 4;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setWasm($var)
    {
        GPBUtil::checkString($var, false);
        $this->wasm = $var;

        return $this;
    }
}
