<?php
/**
 * Agents may belong to many Threads.
 * Threads can have many Agents.
 */

use App\Models\Agent;
use App\Models\User;
use Laravel\Sanctum\Sanctum;

use function Pest\Laravel\get;

test('can list agent threads via api', function () {

    $user = User::factory()->create();
    Sanctum::actingAs($user);

    $agent = Agent::factory()->create();
    $agent->threads()->create(['title' => 'Test Thread']);

    get("/api/v1/agents/{$agent->id}/threads")
        ->assertStatus(200)
        ->assertJson([
            'success' => true,
            'message' => 'Agent threads retrieved successfully',
            'data' => [
                // You can't predict the 'thread_id' as it's generated by the database
            ],
        ])
        ->assertJsonStructure([
            'success',
            'message',
            'data' => [
                '*' => ['id', 'title', 'created_at', 'updated_at'],
            ],
        ]);
});
