<?php

use App\Models\User;

use function Pest\Laravel\post;

test('can create agent via api', function () {
    $user = User::factory()->create();

    $this->actingAs($user);

    post(route('api.agents.store'), [
        'name' => 'Test Agent',
        'description' => 'This is a test agent',
        'instructions' => 'This is a test instruction',
    ])
        ->assertStatus(201)
        ->assertJson([
            'success' => true,
            'message' => 'Agent created successfully.',
            'data' => [
                // You can't predict the 'agent_id' as it's generated by the database
            ],
        ])
        ->assertJsonStructure([
            'success',
            'message',
            'data' => ['agent_id'],
        ]);

    // Optionally, you can also assert that the agent was indeed created in the database
    $this->assertDatabaseHas('agents', [
        'name' => 'Test Agent',
        'description' => 'This is a test agent',
        'instructions' => 'This is a test instruction',
    ]);
});
