//! Application-owned input values; native mounts translate their window events.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KeyCode {
    AltLeft,
    AltRight,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Backquote,
    Backslash,
    Backspace,
    BracketLeft,
    BracketRight,
    CapsLock,
    Comma,
    ControlLeft,
    ControlRight,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Enter,
    Equal,
    Escape,
    F1,
    Fn,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadMultiply,
    NumpadSubtract,
    PageDown,
    PageUp,
    Period,
    Quote,
    Semicolon,
    ShiftLeft,
    ShiftRight,
    Slash,
    Space,
    SuperLeft,
    SuperRight,
    Unidentified,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NamedKey {
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Backspace,
    Delete,
    End,
    Enter,
    Escape,
    F1,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F2,
    F20,
    F21,
    F22,
    F23,
    F24,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    Home,
    Insert,
    PageDown,
    PageUp,
    Space,
    Tab,
    Unidentified,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Logical {
    Character(String),
    Named(NamedKey),
    Dead(Option<char>),
    Unidentified,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ModifiersState(u8);
impl ModifiersState {
    pub const SHIFT: Self = Self(1);
    pub const CONTROL: Self = Self(2);
    pub const ALT: Self = Self(4);
    pub const SUPER: Self = Self(8);
    pub const fn empty() -> Self {
        Self(0)
    }
    pub const fn shift_key(self) -> bool {
        self.0 & 1 != 0
    }
    pub const fn control_key(self) -> bool {
        self.0 & 2 != 0
    }
    pub const fn alt_key(self) -> bool {
        self.0 & 4 != 0
    }
    pub const fn super_key(self) -> bool {
        self.0 & 8 != 0
    }
}
impl std::ops::BitOr for ModifiersState {
    type Output = Self;
    fn bitor(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }
}
#[derive(Clone, Debug)]
pub struct KeyIn {
    pub code: KeyCode,
    pub logical: Logical,
    pub text: Option<String>,
    pub plain: Option<String>,
    pub pressed: bool,
    pub repeat: bool,
    /// Focus synchronization generated by the OS is not a person's approval.
    pub synthetic: bool,
}
