//! The labeled route sets as Gym suites (#9925, #9936).
//!
//! `crates/gym/suites/chat-router-v2.json` is generated from
//! `crates/coder/fixtures/chat-router/routes-v2.json`: one `route` item per
//! row, its state the one the router's judgment reads, its truth the
//! labeled route. Held-out rows are the locked partition, so the Gym's
//! ledger records the one read of them. The question text,
//! `crates/gym/questions/chat-router-route-v3.json`, is
//! [`coder::router_eval::route_question`], which is the production router's
//! structured `route` question ([`coder::router::judge::route`]), so Gym
//! scores measure what production asks. These tests fail when the fixture
//! or the router's route question changes and the Gym files were not
//! regenerated:
//!
//! ```text
//! ROUTER_SUITE_WRITE=1 cargo test -p coder --test router_suite -- --ignored
//! ```
//!
//! `chat-router-v1.json` and its question set `chat-router-route-v2.json`
//! are kept as they were recorded: the twelve-route question the v1 scores
//! were measured with, and the suite generated from `routes-v1.json`.

use std::path::{Path, PathBuf};

use coder::generate::{Message, Role};
use coder::router_eval::{
    SUITE, SUITE_QUESTIONS, SUITE_QUESTIONS_V1, SUITE_V1, Set, partition_of, route_question,
};
use gym::suite::{Item, Partition, Suite};
use serde_json::{Value, json};

fn gym(path: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../gym")
        .join(path)
}

fn suite(set: &Set, name: &str, questions: &str, description: &str) -> Suite {
    let items: Vec<Item> = set
        .rows
        .iter()
        .map(|row| {
            let transcript: Vec<Message> = row
                .messages
                .iter()
                .map(|m| Message {
                    role: if m.role == "assistant" {
                        Role::Assistant
                    } else {
                        Role::User
                    },
                    text: m.text.clone(),
                })
                .collect();
            Item {
                id: format!("route/{}", row.id),
                family: "route".to_string(),
                kind: "choice".to_string(),
                state: coder::first::state(row.latest(), &transcript),
                question: None,
                truth: row.route.clone(),
                partition: match partition_of(row) {
                    "locked" => Partition::Locked,
                    "calibration" => Partition::Calibration,
                    _ => Partition::Development,
                },
                label_source: None,
                label_rule: Some(
                    "author: the route a correct chat router takes for the latest message, \
                     per docs/coder/design/2026-09-28-chat-router.md"
                        .to_string(),
                ),
            }
        })
        .collect();
    let mut suite = Suite {
        schema: "openagents.gym.suite.v1".to_string(),
        name: name.to_string(),
        description: description.to_string(),
        created: set.created.clone(),
        digest: String::new(),
        tier: Some("scored".to_string()),
        gate: None,
        questions: Some(questions.to_string()),
        sampling: None,
        exposure: None,
        items,
    };
    suite.digest = suite.compute_digest().expect("the items digest");
    suite
}

fn v1() -> Suite {
    suite(
        &Set::v1(),
        SUITE_V1,
        SUITE_QUESTIONS_V1,
        "The chat router's labeled route set (#9925), from \
         crates/coder/fixtures/chat-router/routes-v1.json: realistic first \
         messages across the 12 routes, labeled with the route a correct router \
         takes. The fixture's held-out rows are the locked partition.",
    )
}

fn v2() -> Suite {
    suite(
        &Set::fixture(),
        SUITE,
        SUITE_QUESTIONS,
        "The chat router's labeled route set for chat-router-v2 (#9936), from \
         crates/coder/fixtures/chat-router/routes-v2.json: the v1 rows and rows for \
         the Gym and eval routes, across 18 routes, labeled with the route a correct \
         router takes. The fixture's held-out rows are the locked partition.",
    )
}

fn questions() -> Value {
    json!({
        "$comment": [
            "Generated by crates/coder/tests/router_suite.rs from coder::router::judge::route, the structured route question the production chat router asks Jev."
        ],
        "schema": "openagents.gym.question_set.v1",
        "id": SUITE_QUESTIONS,
        "suite": SUITE,
        "questions": { "route": jev::Question::from(route_question()) },
    })
}

fn committed(name: &str) -> Suite {
    Suite::load(
        &std::fs::read_to_string(gym(&format!("suites/{name}.json"))).expect("the suite exists"),
    )
    .expect("the committed suite loads")
}

#[test]
fn the_gym_suites_are_the_labeled_sets() {
    let v2_committed = committed(SUITE);
    assert_eq!(v2_committed.digest, v2().digest, "regenerate the suite");
    assert_eq!(v2_committed.questions.as_deref(), Some(SUITE_QUESTIONS));
    // The v1 suite is kept as recorded.
    let v1_committed = committed(SUITE_V1);
    assert_eq!(v1_committed.digest, v1().digest);
    assert_eq!(v1_committed.questions.as_deref(), Some(SUITE_QUESTIONS_V1));
    gym::questions::load(SUITE_QUESTIONS_V1).expect("the v1 question set still reads");
}

#[test]
fn the_gym_question_is_the_route_question() {
    let committed: Value = serde_json::from_str(
        &std::fs::read_to_string(gym(&format!("questions/{SUITE_QUESTIONS}.json")))
            .expect("the question set exists"),
    )
    .expect("parses");
    assert_eq!(
        committed["questions"],
        questions()["questions"],
        "regenerate the question set"
    );
    gym::questions::load(SUITE_QUESTIONS).expect("the Gym reads it");
}

/// The Gym asks the `route` question the deployed router asks, whatever
/// the bank, facts, command groups, or tools: one source, not a copy.
#[test]
fn the_gym_question_is_the_production_route_question() {
    let facts = coder::router::worker_facts(
        coder::generate::DEFAULT_MODEL,
        Some(coder::generate::DEFAULT_DOOR_URL),
        Some((6, 40)),
        &coder::router::Seams::default(),
    );
    let production =
        coder::router::judge::questions(coder::router::Bank::builtin(), &facts, &[], &[]);
    let production = serde_json::to_value(production.get("route")).expect("serializes");
    let served = gym::questions::load(SUITE_QUESTIONS).expect("the Gym reads it");
    for item in &committed(SUITE).items {
        assert_eq!(
            served.ask(item).expect("the set covers every item"),
            &production,
            "{}: the Gym asks the router's route question",
            item.id
        );
    }
}

#[test]
#[ignore = "writes the Gym files"]
fn write_the_gym_suite() {
    if std::env::var_os("ROUTER_SUITE_WRITE").is_none() {
        return;
    }
    std::fs::write(
        gym(&format!("suites/{SUITE}.json")),
        serde_json::to_string_pretty(&v2()).expect("serializes") + "\n",
    )
    .expect("writes the suite");
    std::fs::write(
        gym(&format!("questions/{SUITE_QUESTIONS}.json")),
        serde_json::to_string_pretty(&questions()).expect("serializes") + "\n",
    )
    .expect("writes the question set");
}
