//! The labeled route set as a Gym suite (#9925).
//!
//! `crates/gym/suites/chat-router-v1.json` is generated from
//! `crates/coder/fixtures/chat-router/routes-v1.json`: one `route` item per
//! row, its state the one the router's judgment reads, its truth the
//! labeled route. Held-out rows are the locked partition, so the Gym's
//! ledger records the one read of them. The question text,
//! `crates/gym/questions/chat-router-route-v1.json`, is
//! [`coder::router_eval::route_question`]. These tests fail when the fixture
//! or the route descriptions change and the Gym files were not regenerated:
//!
//! ```text
//! ROUTER_SUITE_WRITE=1 cargo test -p coder --test router_suite -- --ignored
//! ```

use std::path::{Path, PathBuf};

use coder::generate::{Message, Role};
use coder::router_eval::{SUITE, SUITE_QUESTIONS, Set, partition_of, route_question};
use gym::suite::{Item, Partition, Suite};
use serde_json::{Value, json};

fn gym(path: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../gym")
        .join(path)
}

fn suite() -> Suite {
    let set = Set::fixture();
    let items: Vec<Item> = set
        .rows
        .iter()
        .map(|row| {
            let transcript: Vec<Message> = row
                .messages
                .iter()
                .map(|m| Message {
                    role: if m.role == "assistant" {
                        Role::Assistant
                    } else {
                        Role::User
                    },
                    text: m.text.clone(),
                })
                .collect();
            Item {
                id: format!("route/{}", row.id),
                family: "route".to_string(),
                kind: "choice".to_string(),
                state: coder::first::state(row.latest(), &transcript),
                question: None,
                truth: row.route.clone(),
                partition: match partition_of(row) {
                    "locked" => Partition::Locked,
                    "calibration" => Partition::Calibration,
                    _ => Partition::Development,
                },
                label_source: None,
                label_rule: Some(
                    "author: the route a correct chat router takes for the latest message, \
                     per docs/coder/design/2026-09-28-chat-router.md"
                        .to_string(),
                ),
            }
        })
        .collect();
    let mut suite = Suite {
        schema: "openagents.gym.suite.v1".to_string(),
        name: SUITE.to_string(),
        description: "The chat router's labeled route set (#9925), from \
                      crates/coder/fixtures/chat-router/routes-v1.json: realistic first \
                      messages across the 12 routes, labeled with the route a correct router \
                      takes. The fixture's held-out rows are the locked partition."
            .to_string(),
        created: set.created.clone(),
        digest: String::new(),
        tier: Some("scored".to_string()),
        gate: None,
        questions: Some(SUITE_QUESTIONS.to_string()),
        sampling: None,
        exposure: None,
        items,
    };
    suite.digest = suite.compute_digest().expect("the items digest");
    suite
}

fn questions() -> Value {
    json!({
        "$comment": [
            "Generated by crates/coder/tests/router_suite.rs from coder::router_eval::route_question, the route descriptions the chat router's Jev question reads."
        ],
        "schema": "openagents.gym.question_set.v1",
        "id": SUITE_QUESTIONS,
        "suite": SUITE,
        "questions": { "route": jev::Question::from(route_question()) },
    })
}

#[test]
fn the_gym_suite_is_the_labeled_set() {
    let committed = Suite::load(
        &std::fs::read_to_string(gym("suites/chat-router-v1.json")).expect("the suite exists"),
    )
    .expect("the committed suite loads");
    let generated = suite();
    assert_eq!(committed.digest, generated.digest, "regenerate the suite");
    assert_eq!(committed.questions.as_deref(), Some(SUITE_QUESTIONS));
}

#[test]
fn the_gym_question_is_the_route_question() {
    let committed: Value = serde_json::from_str(
        &std::fs::read_to_string(gym(&format!("questions/{SUITE_QUESTIONS}.json")))
            .expect("the question set exists"),
    )
    .expect("parses");
    assert_eq!(
        committed["questions"],
        questions()["questions"],
        "regenerate the question set"
    );
    gym::questions::load(SUITE_QUESTIONS).expect("the Gym reads it");
}

#[test]
#[ignore = "writes the Gym files"]
fn write_the_gym_suite() {
    if std::env::var_os("ROUTER_SUITE_WRITE").is_none() {
        return;
    }
    std::fs::write(
        gym("suites/chat-router-v1.json"),
        serde_json::to_string_pretty(&suite()).expect("serializes") + "\n",
    )
    .expect("writes the suite");
    std::fs::write(
        gym(&format!("questions/{SUITE_QUESTIONS}.json")),
        serde_json::to_string_pretty(&questions()).expect("serializes") + "\n",
    )
    .expect("writes the question set");
}
