apiVersion: v1
kind: Service
metadata:
  name: livekit-server-turn
  labels:
    openagents.com/component: livekit-turn
spec:
  externalTrafficPolicy: Local
  ports:
    - name: turn-tls
      port: 443
      targetPort: 5349
      protocol: TCP
