// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct ApiKeyScope {
    #[serde(
        rename = "expiresAt",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub expires_at: crate::Nullable<String>,
    #[serde(rename = "actions", default, skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<String>>,
    #[serde(rename = "sandboxes", default, skip_serializing_if = "Option::is_none")]
    pub sandboxes: Option<ApiKeyScopeSandboxes>,
    #[serde(
        rename = "environments",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub environments: Option<ApiKeyScopeEnvironments>,
    #[serde(
        rename = "grandfathered",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub grandfathered: Option<bool>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for ApiKeyScope {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ApiKeyScope").finish_non_exhaustive()
    }
}
