// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct CommandResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "exitCode")]
    pub exit_code: Option<i64>,
    #[serde(
        rename = "signal",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub signal: crate::Nullable<String>,
    #[serde(rename = "oomKilled", default, skip_serializing_if = "Option::is_none")]
    pub oom_killed: Option<bool>,
    #[serde(rename = "stdout")]
    pub stdout: String,
    #[serde(rename = "stderr")]
    pub stderr: String,
    #[serde(
        rename = "stdoutTruncated",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stdout_truncated: Option<bool>,
    #[serde(
        rename = "stderrTruncated",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stderr_truncated: Option<bool>,
    #[serde(rename = "timedOut")]
    pub timed_out: bool,
    #[serde(rename = "cwd", default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    #[serde(rename = "startedAt", default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(
        rename = "finishedAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub finished_at: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for CommandResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CommandResponse").finish_non_exhaustive()
    }
}
