// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct CommandStatusParams {
    #[serde(rename = "sandboxId")]
    pub sandbox_id: String,
    #[serde(rename = "processId")]
    pub process_id: i64,
    #[serde(rename = "tailBytes", default, skip_serializing_if = "Option::is_none")]
    pub tail_bytes: Option<i64>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for CommandStatusParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CommandStatusParams")
            .finish_non_exhaustive()
    }
}
