// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct Conversation {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: Option<String>,
    #[serde(rename = "lastPromptAt")]
    pub last_prompt_at: Option<String>,
    #[serde(rename = "prompts")]
    pub prompts: i64,
    #[serde(rename = "running")]
    pub running: bool,
    #[serde(rename = "lastHarness")]
    pub last_harness: Option<String>,
    #[serde(rename = "lastModel")]
    pub last_model: Option<String>,
    #[serde(rename = "lastPromptPreview")]
    pub last_prompt_preview: Option<String>,
    #[serde(rename = "current")]
    pub current: bool,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for Conversation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Conversation").finish_non_exhaustive()
    }
}
