// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct CreateParams {
    #[serde(
        rename = "Idempotency-Key",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub idempotency_key: Option<String>,
    #[serde(rename = "org", default, skip_serializing_if = "Option::is_none")]
    pub org: Option<String>,
    #[serde(
        rename = "X-Boat-Org",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x_boat_org: Option<String>,
    #[serde(rename = "body", default, skip_serializing_if = "Option::is_none")]
    pub body: Option<CreateSandboxRequest>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for CreateParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CreateParams").finish_non_exhaustive()
    }
}
