// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct CreateScopedApiKeyParams {
    #[serde(rename = "body")]
    pub body: CreateScopedApiKeyParamsBody,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for CreateScopedApiKeyParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CreateScopedApiKeyParams")
            .finish_non_exhaustive()
    }
}
