// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct DataRetentionUpdateRequest {
    #[serde(rename = "enabled", default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(
        rename = "snapshotsOff",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub snapshots_off: Option<bool>,
    #[serde(
        rename = "confirmation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub confirmation: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for DataRetentionUpdateRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DataRetentionUpdateRequest")
            .finish_non_exhaustive()
    }
}
