// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct DataRetentionPolicyResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "enabledAt")]
    pub enabled_at: Option<String>,
    #[serde(
        rename = "queuedSandboxes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queued_sandboxes: Option<i64>,
    #[serde(
        rename = "acceptedDeletionOperationsIrreversible",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub accepted_deletion_operations_irreversible: Option<bool>,
    #[serde(
        rename = "snapshotsOff",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub snapshots_off: Option<bool>,
    #[serde(
        rename = "snapshotsOffAt",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub snapshots_off_at: crate::Nullable<String>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for DataRetentionPolicyResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DataRetentionPolicyResponse")
            .finish_non_exhaustive()
    }
}
