// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct DesktopRequest {
    #[serde(
        rename = "publicAccess",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub public_access: Option<bool>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for DesktopRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DesktopRequest").finish_non_exhaustive()
    }
}
