// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct DesktopParams {
    #[serde(rename = "sandboxId")]
    pub sandbox_id: String,
    #[serde(rename = "vnc", default, skip_serializing_if = "Option::is_none")]
    pub vnc: Option<i64>,
    #[serde(rename = "theme", default, skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    #[serde(rename = "body", default, skip_serializing_if = "Option::is_none")]
    pub body: Option<DesktopRequest>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for DesktopParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DesktopParams").finish_non_exhaustive()
    }
}
