// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct EnvironmentItemChangeResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "versionId", default, skip_serializing_if = "Option::is_none")]
    pub version_id: Option<String>,
    #[serde(
        rename = "versionNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub version_number: Option<i64>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for EnvironmentItemChangeResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EnvironmentItemChangeResponse")
            .finish_non_exhaustive()
    }
}
