// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct GetSnapshotTreeParams {
    #[serde(rename = "snapshotId")]
    pub snapshot_id: String,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for GetSnapshotTreeParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GetSnapshotTreeParams")
            .finish_non_exhaustive()
    }
}
