// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct LimitsResponseCurrentLimits {
    #[serde(
        rename = "activeSandboxes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub active_sandboxes: Option<i64>,
    #[serde(
        rename = "creationRatePerMinute",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub creation_rate_per_minute: Option<i64>,
    #[serde(
        rename = "creationRequestsPerHour",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub creation_requests_per_hour: crate::Nullable<i64>,
    #[serde(
        rename = "creationRequestsPerDay",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub creation_requests_per_day: crate::Nullable<i64>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for LimitsResponseCurrentLimits {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LimitsResponseCurrentLimits")
            .finish_non_exhaustive()
    }
}
