// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct PromptEventData {
    #[serde(rename = "prompt")]
    pub prompt: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "is_reverted",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_reverted: Option<bool>,
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(
        rename = "attachments",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attachments: Option<Vec<PromptEventDataAttachmentsItem>>,
    #[serde(rename = "citations", default, skip_serializing_if = "Option::is_none")]
    pub citations: Option<Vec<PromptEventDataCitationsItem>>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for PromptEventData {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PromptEventData").finish_non_exhaustive()
    }
}
