// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct ResponseEvent {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(
        rename = "taskId",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub task_id: crate::Nullable<String>,
    #[serde(
        rename = "conversationId",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub conversation_id: crate::Nullable<String>,
    #[serde(rename = "data")]
    pub data: ResponseEventData,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for ResponseEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ResponseEvent").finish_non_exhaustive()
    }
}
