// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SandboxEnvironmentListResponse {
    #[serde(rename = "ok", default, skip_serializing_if = "Option::is_none")]
    pub ok: Option<bool>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    #[serde(rename = "environments")]
    pub environments: Vec<SandboxEnvironment>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SandboxEnvironmentListResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SandboxEnvironmentListResponse")
            .finish_non_exhaustive()
    }
}
