// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SandboxEnvironmentVersionSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "versionNumber")]
    pub version_number: i64,
    #[serde(rename = "sandboxCount")]
    pub sandbox_count: i64,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SandboxEnvironmentVersionSummary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SandboxEnvironmentVersionSummary")
            .finish_non_exhaustive()
    }
}
