// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SandboxActionResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "sandbox",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub sandbox: crate::Nullable<Sandbox>,
    #[serde(
        rename = "giftLimitNotice",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub gift_limit_notice: Option<String>,
    #[serde(
        rename = "conversationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub conversation_id: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SandboxActionResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SandboxActionResponse")
            .finish_non_exhaustive()
    }
}
