// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SandboxListResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "sandboxes")]
    pub sandboxes: Vec<Sandbox>,
    #[serde(rename = "pageInfo", default, skip_serializing_if = "Option::is_none")]
    pub page_info: Option<PageInfo>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SandboxListResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SandboxListResponse")
            .finish_non_exhaustive()
    }
}
