// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SandboxEnvironment {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "isDefault")]
    pub is_default: bool,
    #[serde(rename = "latestVersionId")]
    pub latest_version_id: Option<String>,
    #[serde(
        rename = "latestVersionNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_version_number: Option<i64>,
    #[serde(
        rename = "safetyAnsweredAt",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub safety_answered_at: crate::Nullable<String>,
    #[serde(rename = "safeForThirdParties")]
    pub safe_for_third_parties: bool,
    #[serde(rename = "passGithub")]
    pub pass_github: bool,
    #[serde(rename = "passSecrets")]
    pub pass_secrets: bool,
    #[serde(rename = "passSandboxCredentials")]
    pub pass_sandbox_credentials: bool,
    #[serde(rename = "passAgentsCredentials")]
    pub pass_agents_credentials: bool,
    #[serde(rename = "envContents")]
    pub env_contents: String,
    #[serde(rename = "secretFiles")]
    pub secret_files: Vec<SecretFile>,
    #[serde(
        rename = "selectedRepositories",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub selected_repositories: Option<Vec<SelectedRepository>>,
    #[serde(rename = "versions")]
    pub versions: Vec<SandboxEnvironmentVersionSummary>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SandboxEnvironment {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SandboxEnvironment").finish_non_exhaustive()
    }
}
