// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SandboxUsageResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "sandboxId")]
    pub sandbox_id: String,
    #[serde(rename = "sandboxType")]
    pub sandbox_type: String,
    #[serde(rename = "billingMultiplier")]
    pub billing_multiplier: f64,
    #[serde(rename = "since")]
    pub since: String,
    #[serde(rename = "until")]
    pub until: String,
    #[serde(rename = "seconds")]
    pub seconds: i64,
    #[serde(rename = "dollars")]
    pub dollars: f64,
    #[serde(rename = "secondsPerDollar")]
    pub seconds_per_dollar: i64,
    #[serde(rename = "running")]
    pub running: bool,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SandboxUsageResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SandboxUsageResponse")
            .finish_non_exhaustive()
    }
}
