// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SecretsUpdateRequest {
    #[serde(
        rename = "envContents",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub env_contents: Option<String>,
    #[serde(
        rename = "secretFiles",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub secret_files: Option<Vec<SecretFile>>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SecretsUpdateRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SecretsUpdateRequest")
            .finish_non_exhaustive()
    }
}
