// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SecretFile {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "contents")]
    pub contents: String,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SecretFile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SecretFile").finish_non_exhaustive()
    }
}
