// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SshKeyResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "success", default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(
        rename = "machineIp",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub machine_ip: crate::Nullable<String>,
    #[serde(rename = "sshUser", default, skip_serializing_if = "Option::is_none")]
    pub ssh_user: Option<String>,
    #[serde(
        rename = "sshEndpoint",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub ssh_endpoint: crate::Nullable<String>,
    #[serde(rename = "hostKey", default, skip_serializing_if = "Option::is_none")]
    pub host_key: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SshKeyResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SshKeyResponse").finish_non_exhaustive()
    }
}
