// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SteerResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    #[serde(rename = "promptId")]
    pub prompt_id: String,
    #[serde(rename = "native")]
    pub native: bool,
    #[serde(rename = "mode", default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SteerResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SteerResponse").finish_non_exhaustive()
    }
}
