// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct SteerEventData {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "native")]
    pub native: bool,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for SteerEventData {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SteerEventData").finish_non_exhaustive()
    }
}
