// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct UnknownEvent {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for UnknownEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UnknownEvent").finish_non_exhaustive()
    }
}
