// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct WebhookEventData {
    #[serde(rename = "sandbox")]
    pub sandbox: WebhookEventDataSandbox,
    #[serde(
        rename = "previousState",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub previous_state: Option<String>,
    #[serde(rename = "state", default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(
        rename = "reason",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub reason: crate::Nullable<String>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for WebhookEventData {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WebhookEventData").finish_non_exhaustive()
    }
}
