// Generated by `schema/generate.py`.
use super::*;
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct WebhookCreateRequest {
    #[serde(
        rename = "name",
        default,
        skip_serializing_if = "crate::Nullable::is_unset"
    )]
    pub name: crate::Nullable<String>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "events")]
    pub events: Vec<WebhookEventType>,
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
impl std::fmt::Debug for WebhookCreateRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WebhookCreateRequest")
            .finish_non_exhaustive()
    }
}
