import type { KhalaCodeDesktopRpcMethodName } from "../shared/rpc.js"

// Read-only preview mode classification. EVERY RPC method must appear in
// exactly one of these sets; the coverage test fails closed on drift.
export const mutatingPreviewRpcMethods = new Set<KhalaCodeDesktopRpcMethodName>([
  "claudeApprovalRespond",
  "codexAppServerRestart",
  "codexAppServerStart",
  "codexAppServerStop",
  "codexApprovalRespond",
  "architectPlanDecision",
  "architectPlanRun",
  "composerNativeClipboardImageRead",
  "composerNativeDirectoryPickerOpen",
  "composerNativeFileGrantRead",
  "composerNativeFileGrantRelease",
  "composerNativeFilePickerOpen",
  "composerNativeSaveDialogOpen",
  "codexBackgroundTerminalsClean",
  "codexBackgroundTerminalsTerminate",
  "codexConfigValueWrite",
  "codexExternalAgentConfigImport",
  "codexFleetDelegateRun",
  "codexFleetPromoteThread",
  "codexFsWriteFile",
  "codexMarketplaceAdd",
  "codexMarketplaceRemove",
  "codexMarketplaceUpgrade",
  "codexMcpOauthLogin",
  "codexMcpServerReload",
  "codexMcpToolCall",
  "codexModelRolePresetApply",
  "codexPluginInstall",
  "codexPluginUninstall",
  "codexSkillsConfigWrite",
  "codexSkillsExtraRootsSet",
  "codexThreadArchive",
  "codexThreadCompact",
  "codexThreadDelete",
  "codexThreadFork",
  "codexThreadRename",
  "codexThreadResume",
  "codexThreadStart",
  "codexThreadUnarchive",
  "codexTurnInterrupt",
  "codexTurnStart",
  "codexTurnSteer",
  "connectCodexAccount",
  "consumeCodexRateLimitResetCredit",
  "fleetRunControl",
  "fleetRunStart",
  "fleetWorkerControl",
  "forumRequest",
  "harnessSettingWrite",
  "khalaCodeOpenAgentsAuthPoll",
  "khalaCodeOpenAgentsAuthStart",
  "khalaSyncChatAppendMessage",
  "khalaSyncChatCreateThread",
  "khalaSyncChatRenameThread",
  "khalaSyncFleetMutate",
  "khalaSyncFleetReportAccountState",
  "khalaCodeTraceCaptureConsentWrite",
  "khalaCodeOutsideUserRunReport",
  "khalaCodePlanPurchase",
  "modelRoleRegistryWrite",
  "openExternalUrl",
  "removeCodexAccount",
  "setCodexAccountPaused",
  "slashCommandDispatch",
  "submitChatMessage",
  // #8440 in-app updater plumbing: check/download/install each cause a real
  // network fetch, disk write, or app quit-and-relaunch side effect.
  "updaterCheck",
  "updaterDownload",
  "updaterInstall",
  // Diagnostics (issue #8441): relaunch/quit terminate or respawn the whole
  // app process, which is squarely a mutation of app/process state.
  "diagnosticsRelaunch",
  "diagnosticsQuit",
  // #8442 follow-up: new window/reload/zoom/devtools actions mutate native
  // app/window chrome.
  "nativeWindowAction",
])

export const readOnlySafePreviewRpcMethods = new Set<KhalaCodeDesktopRpcMethodName>([
  "appInfo",
  "appleFmReadiness",
  "claudeApprovalPending",
  "claudeSettingsRead",
  "codexAccountsStatus",
  "codexAppServerStatus",
  "codexBackgroundTerminalsList",
  "codexEcosystemRead",
  "codexExternalAgentConfigDetect",
  "codexExternalAgentConfigImportHistoriesRead",
  "codexFleetStatus",
  "codexFsGetMetadata",
  "codexFsReadFile",
  "codexHarnessStatus",
  "codexMcpResourceRead",
  "codexMentionCandidates",
  "codexSettingsRead",
  "codexThreadList",
  "codexThreadRead",
  "codingStatus",
  "editorDirectoryRead",
  "editorFileRead",
  "editorProviderList",
  "editorWorkspaceRead",
  "fleetRunList",
  "fleetRunStatus",
  "harnessSettingRead",
  "khalaCodeOpenAgentsAuthStatus",
  "khalaCodePlanCatalog",
  "khalaCodePlanStatus",
  "khalaCodeTraceCaptureStatus",
  "khalaSyncChatMessages",
  "khalaSyncChatThreads",
  "khalaSyncFleetState",
  "modelRoleRegistryRead",
  "onDeviceDeciderStatus",
  "pylonStatus",
  "qaMetricSample",
  "qaMetrics",
  "reviewDiffRead",
  "sessionCatalog",
  "slashCommandList",
  "threadTokenSummary",
  "tokenAccountingStatus",
  "toolCatalog",
  // #8440 in-app updater plumbing: read-only status snapshot, no side effects.
  "updaterStatus",
  // Diagnostics (issue #8441): these read/append to the local diagnostics
  // log store and (for export) write a debug-log archive to disk, but never
  // touch product/app state (threads, fleet, accounts, ...), so they are
  // safe for a read-only preview session.
  "diagnosticsSnapshot",
  "diagnosticsExport",
  "diagnosticsRendererHeartbeat",
  "diagnosticsReportRendererFatalError",
  // #8442 follow-up: signals renderer boot readiness so bun can flush a
  // buffered deep link; idempotent, no product/app state mutation.
  "rendererReady",
])
