apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 556.0.0
    run.googleapis.com/creator: chris@openagents.com
    run.googleapis.com/lastModifier: chris@openagents.com
    run.googleapis.com/operation-id: 1ecdbe98-c7f1-4177-8e50-155f8197914d
  creationTimestamp: '2026-02-21T23:25:19.309863Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1
    run.googleapis.com/lastUpdatedTime: '2026-02-21T23:25:19.309863Z'
  name: openagents-maintenance-down
  namespace: '157437760789'
  resourceVersion: AAZLXdngp1A
  selfLink: /apis/run.googleapis.com/v1/namespaces/157437760789/jobs/openagents-maintenance-down
  uid: 45ada447-6d95-4921-b244-f9ce233e63ff
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 556.0.0
        run.googleapis.com/cloudsql-instances: openagentsgemini:us-central1:l402-aperture-db
        run.googleapis.com/execution-environment: gen2
      labels:
        client.knative.dev/nonce: reh_hom_quv
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - args:
            - artisan
            - down
            - --secret=eccc406c-9968-47c9-b630-6ac81ee6980c
            - --retry=60
            - --render=errors.503
            command:
            - php
            env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: 'false'
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: /cloudsql/openagentsgemini:us-central1:l402-aperture-db
            - name: DB_DATABASE
              value: openagents_web
            - name: DB_USERNAME
              value: openagents_web
            - name: APP_MAINTENANCE_DRIVER
              value: cache
            - name: APP_MAINTENANCE_STORE
              value: database
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-web-app-key
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-web-db-password
            image: us-central1-docker.pkg.dev/openagentsgemini/openagents-web/laravel:72cae86ae
            resources:
              limits:
                cpu: '1'
                memory: 512Mi
          maxRetries: 3
          serviceAccountName: 157437760789-compute@developer.gserviceaccount.com
          timeoutSeconds: '600'
status:
  conditions:
  - lastTransitionTime: '2026-02-21T23:25:19.672366Z'
    status: 'True'
    type: Ready
  observedGeneration: 1
