apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 556.0.0
    run.googleapis.com/creator: chris@openagents.com
    run.googleapis.com/lastModifier: chris@openagents.com
    run.googleapis.com/operation-id: 3920b8c5-759f-4d10-893b-8e4df7864acf
  creationTimestamp: '2026-02-21T23:25:15.225526Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1
    run.googleapis.com/lastUpdatedTime: '2026-02-21T23:25:15.225526Z'
  name: openagents-migrate
  namespace: '157437760789'
  resourceVersion: AAZLXdmiz9E
  selfLink: /apis/run.googleapis.com/v1/namespaces/157437760789/jobs/openagents-migrate
  uid: 61f2be5f-406d-41ef-a886-5a14da582529
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 556.0.0
        run.googleapis.com/cloudsql-instances: openagentsgemini:us-central1:l402-aperture-db
        run.googleapis.com/execution-environment: gen2
      labels:
        client.knative.dev/nonce: doh_yil_nag
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - args:
            - artisan
            - migrate
            - --force
            command:
            - php
            env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: '0'
            - name: LOG_CHANNEL
              value: stderr
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: /cloudsql/openagentsgemini:us-central1:l402-aperture-db
            - name: DB_DATABASE
              value: openagents_web
            - name: DB_USERNAME
              value: openagents_web
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-web-app-key
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openagents-web-db-password
            image: us-central1-docker.pkg.dev/openagentsgemini/openagents-web/laravel:latest
            resources:
              limits:
                cpu: '1'
                memory: 512Mi
          maxRetries: 0
          serviceAccountName: 157437760789-compute@developer.gserviceaccount.com
          timeoutSeconds: '600'
status:
  conditions:
  - lastTransitionTime: '2026-02-21T23:25:15.624943Z'
    status: 'True'
    type: Ready
  observedGeneration: 1
