import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { formatDistanceToNowStrict } from "date-fns";
import * as QRCode from "qrcode";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SITE_TITLE } from "@/consts";
import { getApiBase } from "@/lib/api";
import { buildHead } from "@/lib/seo";

export const Route = createFileRoute("/_app/openclaw/earn")({
  component: RouteComponent,
  head: () =>
    buildHead({
      title: `Pay OpenClaw | ${SITE_TITLE}`,
      description: "Public Lightning invoice generated by OpenClaw and served by OpenAgents.com.",
    }),
});

type ApiResponse<T> = {
  ok: boolean;
  data?: T | null;
  error?: string | null;
};

type InvoicePayload = {
  payment_request: string;
  amount_sats: number;
  description?: string | null;
  expires_at: string;
  expires_at_ms: number;
  created_at?: string;
  updated_at?: string;
};

type FetchState = "loading" | "ready" | "empty" | "error";

type CopyState = "idle" | "copied" | "failed";

const POLL_INTERVAL_MS = 45_000;

function RouteComponent() {
  const apiBase = useMemo(() => getApiBase(), []);
  const [state, setState] = useState<FetchState>("loading");
  const [invoice, setInvoice] = useState<InvoicePayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [lastFetched, setLastFetched] = useState<number | null>(null);
  const [copyState, setCopyState] = useState<CopyState>("idle");
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  const fetchInvoice = useCallback(
    async (silent = false) => {
      if (!silent) setState("loading");
      setError(null);
      try {
        const res = await fetch(`${apiBase}/openclaw/invoice`, {
          headers: { Accept: "application/json" },
        });
        if (res.status === 404 || res.status === 410) {
          setInvoice(null);
          setState("empty");
          setLastFetched(Date.now());
          return;
        }
        const payload = (await res.json()) as ApiResponse<InvoicePayload>;
        if (!res.ok || !payload.ok || !payload.data) {
          setState("error");
          setError(payload.error ?? `Request failed (${res.status})`);
          return;
        }
        setInvoice(payload.data);
        setState("ready");
        setLastFetched(Date.now());
      } catch (err) {
        const message = err instanceof Error ? err.message : "Unknown error";
        setState("error");
        setError(message);
      }
    },
    [apiBase]
  );

  useEffect(() => {
    fetchInvoice();
    const interval = setInterval(() => fetchInvoice(true), POLL_INTERVAL_MS);
    return () => clearInterval(interval);
  }, [fetchInvoice]);

  useEffect(() => {
    if (!invoice?.payment_request || !canvasRef.current) return;
    QRCode.toCanvas(
      canvasRef.current,
      invoice.payment_request,
      {
        width: 220,
        margin: 1,
        color: { dark: "#0f172a", light: "#ffffff" },
      },
      () => undefined
    );
  }, [invoice?.payment_request]);

  const expiresLabel = useMemo(() => {
    if (!invoice?.expires_at_ms) return null;
    try {
      return formatDistanceToNowStrict(new Date(invoice.expires_at_ms), { addSuffix: true });
    } catch {
      return null;
    }
  }, [invoice?.expires_at_ms]);

  const handleCopy = useCallback(async () => {
    if (!invoice?.payment_request) return;
    try {
      await navigator.clipboard.writeText(invoice.payment_request);
      setCopyState("copied");
      setTimeout(() => setCopyState("idle"), 1800);
    } catch {
      setCopyState("failed");
      setTimeout(() => setCopyState("idle"), 2000);
    }
  }, [invoice?.payment_request]);

  const amountLabel = invoice ? Number(invoice.amount_sats).toLocaleString() : "";
  const statusLabel =
    state === "ready"
      ? "Live invoice"
      : state === "empty"
        ? "Awaiting invoice"
        : state === "error"
          ? "Fetch error"
          : "Loading";

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-1 flex-col px-4 py-10">
      <div className="flex flex-col gap-4 pb-6">
        <Badge variant={state === "ready" ? "default" : "secondary"}>{statusLabel}</Badge>
        <div className="space-y-2">
          <h1 className="text-3xl font-semibold tracking-tight">Pay OpenClaw</h1>
          <p className="text-muted-foreground max-w-[70ch]">
            This invoice is generated by OpenClaw and published through OpenAgents.com. Payments land directly
            in the OpenClaw wallet (Breez/Spark).
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
          <span>Source: OpenClaw tool to OpenAgents API</span>
          {lastFetched ? <span>Last checked: {new Date(lastFetched).toLocaleTimeString()}</span> : null}
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-[minmax(0,1fr)_minmax(240px,280px)]">
        <Card className="border-border/70">
          <CardHeader className="space-y-2">
            <CardTitle className="text-xl">Invoice</CardTitle>
            <p className="text-sm text-muted-foreground">
              Use any Lightning wallet. If the invoice is expired, refresh or ask OpenClaw to generate a new one.
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            {state === "loading" && (
              <div className="rounded-lg border border-dashed border-border p-4 text-sm text-muted-foreground">
                Fetching the latest invoice...
              </div>
            )}
            {state === "error" && (
              <div className="rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
                {error ?? "Unable to load invoice."}
              </div>
            )}
            {state === "empty" && (
              <div className="rounded-lg border border-dashed border-border p-4 text-sm text-muted-foreground">
                No active invoice yet. Check back soon or trigger a new invoice from OpenClaw.
              </div>
            )}
            {state === "ready" && invoice && (
              <div className="space-y-4">
                <div className="space-y-2">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">Amount</span>
                    <span className="font-mono text-base text-foreground">{amountLabel} sats</span>
                  </div>
                  {invoice.description ? (
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">Description</span>
                      <span className="text-foreground">{invoice.description}</span>
                    </div>
                  ) : null}
                  {expiresLabel ? (
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">Expires</span>
                      <span className="text-foreground">{expiresLabel}</span>
                    </div>
                  ) : null}
                </div>
                <div className="rounded-lg border border-border bg-muted/30 p-3">
                  <p className="break-all font-mono text-xs text-muted-foreground">{invoice.payment_request}</p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Button onClick={handleCopy} variant="outline" size="sm">
                    {copyState === "copied" ? "Copied" : copyState === "failed" ? "Copy failed" : "Copy invoice"}
                  </Button>
                  <Button asChild size="sm">
                    <a href={`lightning:${invoice.payment_request}`}>Open in wallet</a>
                  </Button>
                  <Button variant="ghost" size="sm" onClick={() => fetchInvoice()}>
                    Refresh
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="border-border/70">
          <CardHeader className="space-y-2">
            <CardTitle className="text-xl">QR</CardTitle>
            <p className="text-sm text-muted-foreground">Scan in any Lightning wallet.</p>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center gap-3">
            <div className="flex size-[240px] items-center justify-center rounded-2xl border border-border bg-white">
              {invoice?.payment_request ? (
                <canvas ref={canvasRef} className="size-[220px]" />
              ) : (
                <div className="text-xs text-muted-foreground">Waiting for invoice...</div>
              )}
            </div>
            <div className="text-center text-xs text-muted-foreground">
              {invoice?.payment_request ? "Scan to pay OpenClaw." : "No invoice to display yet."}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="mt-6 border-border/70">
        <CardHeader className="space-y-2">
          <CardTitle className="text-lg">How this works</CardTitle>
          <p className="text-sm text-muted-foreground">
            OpenClaw generates a Bolt11 invoice via the Breez/Spark stack. The OpenAgents API publishes it here. This
            page never touches the mnemonic or keys.
          </p>
        </CardHeader>
        <CardContent className="grid gap-4 text-sm text-muted-foreground md:grid-cols-3">
          <div className="space-y-2">
            <p className="font-medium text-foreground">1) OpenClaw issues</p>
            <p>Invoice created by the OpenClaw wallet tool and sent to the API.</p>
          </div>
          <div className="space-y-2">
            <p className="font-medium text-foreground">2) You pay</p>
            <p>Use the QR or invoice string in any Lightning wallet.</p>
          </div>
          <div className="space-y-2">
            <p className="font-medium text-foreground">3) Verify</p>
            <p>
              OpenClaw and the OpenAgents wallet view show the received payment. See{" "}
              <a href="/wallet" className="text-primary hover:underline">
                /wallet
              </a>{" "}
              for the UI.
            </p>
          </div>
        </CardContent>
      </Card>

      <div className="mt-6 flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
        <a href="/kb/openclaw-wallets" className="text-primary hover:underline">
          OpenClaw wallet setup
        </a>
        <span>-</span>
        <a href="/wallet" className="text-primary hover:underline">
          OpenAgents wallet
        </a>
      </div>
    </div>
  );
}
