//! Reusable CAD domain foundation for OpenAgents.
//!
//! This crate intentionally starts with a minimal, product-agnostic API surface.
//! Higher-level CAD workflows are introduced incrementally via the CAD backlog.

pub mod analysis;
pub mod assembly;
pub mod boolean;
pub mod chat_adapter;
pub mod cli;
pub mod contracts;
pub mod dispatch;
pub mod document;
pub mod drafting;
pub mod error;
pub mod eval;
pub mod events;
pub mod export;
pub mod feature_graph;
pub mod features;
pub mod finishing_ops;
pub mod format;
pub mod glb;
pub mod hash;
pub mod history;
pub mod intent;
pub mod kernel;
pub mod kernel_booleans;
pub mod kernel_fillet;
pub mod kernel_geom;
pub mod kernel_math;
pub mod kernel_nurbs;
pub mod kernel_predicates;
pub mod kernel_primitives;
pub mod kernel_shell;
pub mod kernel_step;
pub mod kernel_tessellate;
pub mod kernel_text;
pub mod kernel_topology;
pub mod keys;
pub mod materials;
pub mod mcp_tools;
pub mod measurement;
pub mod mesh;
pub mod params;
pub mod parity;
pub mod policy;
pub mod primitives;
pub mod query;
pub mod rack;
pub mod section;
pub mod selection;
pub mod semantic_refs;
pub mod sketch;
pub mod sketch_feature_ops;
pub mod sketch_interaction;
pub mod step_checker;
pub mod step_import;
pub mod step_import_metadata;
pub mod step_roundtrip;
pub mod stl;
pub mod tessellation;
pub mod topology_repair;
pub mod validity;
pub use error::{CadError, CadErrorCode, CadErrorEvent, CadResult};
