import { describe, expect, test } from "bun:test"

import packageJson from "../package.json"

const mobileRoot = new URL("../", import.meta.url)
const read = (path: string) => Bun.file(new URL(path, mobileRoot)).text()

describe("Khala mobile Storybook setup", () => {
  test("exposes local-only Storybook scripts and aligned on-device dependencies", () => {
    expect(packageJson.scripts.storybook).toBe(
      "STORYBOOK_ENABLED=true EXPO_PUBLIC_STORYBOOK_ENABLED=true expo start",
    )
    expect(packageJson.scripts["storybook:ios"]).toBe(
      "STORYBOOK_ENABLED=true EXPO_PUBLIC_STORYBOOK_ENABLED=true expo start --ios",
    )
    expect(packageJson.scripts["storybook:android"]).toBe(
      "STORYBOOK_ENABLED=true EXPO_PUBLIC_STORYBOOK_ENABLED=true expo start --android",
    )
    expect(packageJson.scripts["storybook-generate"]).toBe("sb-rn-get-stories")

    for (const dependencyName of [
      "@storybook/addon-ondevice-actions",
      "@storybook/addon-ondevice-backgrounds",
      "@storybook/addon-ondevice-controls",
      "@storybook/react-native",
    ]) {
      expect(packageJson.devDependencies).toHaveProperty(dependencyName)
      expect(packageJson.devDependencies[dependencyName as keyof typeof packageJson.devDependencies]).toBe(
        "^10.4.7",
      )
    }
  })

  test("wraps Metro with Storybook without replacing NativeWind", async () => {
    const metroConfig = await read("metro.config.cjs")

    expect(metroConfig).toContain("@storybook/react-native/withStorybook")
    expect(metroConfig).toContain('require("nativewind/metro")')
    expect(metroConfig).toContain("withStorybook(withNativeWind(config")
  })

  test("defines public-safe primitive stories through the React Native Storybook config", async () => {
    const [main, preview, requires] = await Promise.all([
      read(".rnstorybook/main.ts"),
      read(".rnstorybook/preview.tsx"),
      read(".rnstorybook/storybook.requires.ts"),
    ])

    expect(main).toContain('../src/**/*.stories.?(ts|tsx)')
    expect(main).toContain("@storybook/addon-ondevice-actions")
    expect(main).toContain("@storybook/addon-ondevice-backgrounds")
    expect(main).toContain("@storybook/addon-ondevice-controls")

    expect(preview).toContain("KhalaThemeProvider")
    expect(preview).toContain("SafeAreaProvider")
    expect(preview).toContain("../global.css")

    expect(requires).toContain("do not change this file, it is auto generated by storybook")
    expect(requires).toContain('@storybook/addon-ondevice-actions/register')
    expect(requires).toContain('@storybook/addon-ondevice-backgrounds/register')
    expect(requires).toContain('@storybook/addon-ondevice-controls/register')
    expect(requires).toContain("require.context")
    expect(requires).toContain("../src")
    expect(requires).toContain("**/*.stories.?(ts|tsx)")
  })

  test("keeps Storybook out of hosted build automation", async () => {
    const allStorybookText = (
      await Promise.all([
        read(".rnstorybook/main.ts"),
        read(".rnstorybook/preview.tsx"),
        read(".rnstorybook/index.ts"),
        read("package.json"),
      ])
    ).join("\n")

    expect(allStorybookText).not.toContain("eas build")
    expect(allStorybookText).not.toContain(".github/workflows")
  })
})
