<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace App\Grpc\nostr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpcIsJobDone</code>
 */
class RpcIsJobDone extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isDone = 1;</code>
     */
    protected $isDone = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isDone
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\nostr\GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isDone = 1;</code>
     * @return bool
     */
    public function getIsDone()
    {
        return $this->isDone;
    }

    /**
     * Generated from protobuf field <code>bool isDone = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDone($var)
    {
        GPBUtil::checkBool($var);
        $this->isDone = $var;

        return $this;
    }

}

