<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace App\Grpc\nostr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpcJobLog</code>
 */
class RpcJobLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string jobId = 1;</code>
     */
    protected $jobId = '';
    /**
     * Generated from protobuf field <code>string log = 2;</code>
     */
    protected $log = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $jobId
     *     @type string $log
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\nostr\GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string jobId = 1;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->jobId;
    }

    /**
     * Generated from protobuf field <code>string jobId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->jobId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string log = 2;</code>
     * @return string
     */
    public function getLog()
    {
        return $this->log;
    }

    /**
     * Generated from protobuf field <code>string log = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLog($var)
    {
        GPBUtil::checkString($var, True);
        $this->log = $var;

        return $this;
    }

}

