<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace App\Grpc\nostr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpcSubscribeToEventsRequest</code>
 */
class RpcSubscribeToEventsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the group id of the event, will be used for gc, etc. If generated by a job it should be set to the job id
     *
     * Generated from protobuf field <code>string groupId = 1;</code>
     */
    protected $groupId = '';
    /**
     * Generated from protobuf field <code>repeated string filters = 2;</code>
     */
    private $filters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $groupId
     *           the group id of the event, will be used for gc, etc. If generated by a job it should be set to the job id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $filters
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\nostr\GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * the group id of the event, will be used for gc, etc. If generated by a job it should be set to the job id
     *
     * Generated from protobuf field <code>string groupId = 1;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->groupId;
    }

    /**
     * the group id of the event, will be used for gc, etc. If generated by a job it should be set to the job id
     *
     * Generated from protobuf field <code>string groupId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string filters = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * Generated from protobuf field <code>repeated string filters = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->filters = $arr;

        return $this;
    }

}

