//! Application chrome tokens; world materials retain their owning renderer's colors.

use wasm_bindgen::{JsCast, JsValue};
use web_sys::{Document, HtmlElement};

pub fn linear(value: u32, alpha: f32) -> [f32; 4] {
    let [r, g, b] = verse::palette::linear(value);
    [r, g, b, alpha]
}

/// Sets trusted application tokens through the DOM style API, which works
/// under the site's policy without an inline stylesheet.
pub fn install(document: &Document) -> Result<(), JsValue> {
    let root = document
        .document_element()
        .ok_or(JsValue::NULL)?
        .dyn_into::<HtmlElement>()?;
    let variables = coder_ui::coder_noir::css_variables();
    let properties = variables
        .strip_prefix(":root{")
        .and_then(|value| value.strip_suffix('}'))
        .ok_or_else(|| JsValue::from_str("Invalid application theme tokens"))?;
    declarations(&root, properties)
}

/// Applies declarations generated by Rust, without an inline style attribute.
pub fn declarations(element: &HtmlElement, properties: &str) -> Result<(), JsValue> {
    for declaration in properties.split(';').filter(|value| !value.is_empty()) {
        let (name, value) = declaration
            .split_once(':')
            .ok_or_else(|| JsValue::from_str("Invalid application style declaration"))?;
        element.style().set_property(name, value)?;
    }
    Ok(())
}

pub fn control(element: &HtmlElement) -> Result<(), JsValue> {
    declarations(
        element,
        "background:var(--noir-surface);color:var(--noir-content);border-color:var(--noir-stroke);caret-color:var(--noir-cursor);outline-color:var(--noir-accent)",
    )
}
