//! The closed actions a desktop chat view admits.
use serde::Serialize;
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(tag = "action", rename_all = "snake_case")]
pub enum Action {
    SavedSelect { id: String },
    SavedRefresh,
    SavedMore,
    SavedPrevious,
    SavedEarlier,
    SavedContinue,
    SavedRetry,
    SavedList,
    Card { key: String },
    Palette,
    Profile,
    Menu,
    DismissOverlay,
    Command { key: String },
    Send,
    Pin,
    Rename,
    SaveName,
    CancelRename,
    AttachImage,
    PasteImage,
    RemoveImage { id: String },
    Stop,
    Retry,
    Archive,
    Restore,
    Earlier,
    Latest,
    Followup { text: String },
}
