pub(crate) mod layout;
pub(crate) mod rendering;
pub(crate) mod theme;

pub(crate) use layout::{split_into_words_for_layout, wrap_text};
pub(crate) use rendering::{
    agent_list_layout, agent_modal_content_top, hook_event_layout, modal_y_in_content,
    new_session_button_bounds, render_app, session_list_layout, sidebar_layout, skill_list_layout,
    skill_modal_content_top, INPUT_PADDING, OUTPUT_PADDING, SESSION_MODAL_HEIGHT, STATUS_BAR_HEIGHT,
    HELP_MODAL_HEIGHT, HELP_MODAL_WIDTH, HOOK_MODAL_HEIGHT, HOOK_MODAL_WIDTH,
    SESSION_MODAL_PADDING, SESSION_MODAL_WIDTH, SETTINGS_MODAL_HEIGHT, SETTINGS_MODAL_WIDTH,
    SETTINGS_ROW_HEIGHT, SETTINGS_TAB_HEIGHT, DSPY_MODAL_HEIGHT, DSPY_MODAL_WIDTH,
    GATEWAY_MODAL_HEIGHT, GATEWAY_MODAL_WIDTH, LM_ROUTER_MODAL_HEIGHT, LM_ROUTER_MODAL_WIDTH,
    NEXUS_MODAL_HEIGHT, NEXUS_MODAL_WIDTH, SPARK_WALLET_MODAL_HEIGHT, SPARK_WALLET_MODAL_WIDTH,
    OANIX_MODAL_HEIGHT, OANIX_MODAL_WIDTH, DIRECTIVES_MODAL_HEIGHT, DIRECTIVES_MODAL_WIDTH,
    ISSUES_MODAL_HEIGHT, ISSUES_MODAL_WIDTH, AUTOPILOT_ISSUES_MODAL_HEIGHT, AUTOPILOT_ISSUES_MODAL_WIDTH,
    NIP28_MODAL_HEIGHT, NIP28_MODAL_WIDTH, NIP90_MODAL_HEIGHT, NIP90_MODAL_WIDTH,
    RLM_MODAL_HEIGHT, RLM_MODAL_WIDTH, RLM_TRACE_MODAL_HEIGHT, RLM_TRACE_MODAL_WIDTH,
    PYLON_EARNINGS_MODAL_HEIGHT, PYLON_EARNINGS_MODAL_WIDTH, DVM_MODAL_HEIGHT, DVM_MODAL_WIDTH,
    HOOK_EVENT_ROW_HEIGHT, TOOL_PANEL_GAP, INPUT_HEIGHT, INPUT_AREA_HEIGHT, SESSION_CARD_HEIGHT,
    SESSION_CARD_GAP, SKILL_CARD_HEIGHT, STATUS_BAR_FONT_SIZE,
};
pub(crate) use theme::{palette_for, theme_label, ThemeSetting, UiPalette};
