import * as stylex from "@stylexjs/stylex"
import {
  stylexFallback,
  stylexRuntimeFallbackEnabled,
} from "@openagentsinc/ui/stylex-foldkit"

export const desktopRootStyles = stylexRuntimeFallbackEnabled()
  ? {
      networkShell: stylexFallback("oa-desktop-root-network-shell"),
      shellShell: stylexFallback("oa-desktop-root-shell-shell"),
    }
  : stylex.create({
      networkShell: {
        position: "fixed",
        inset: 0,
        overflow: "hidden",
        backgroundColor: "#000",
      },
      shellShell: {
        position: "fixed",
        inset: 0,
        overflow: "hidden",
        backgroundColor: "#000",
      },
    })

export const desktopShellStyles = stylexRuntimeFallbackEnabled()
  ? {
      pane: stylexFallback("oa-desktop-shell-pane"),
      conversation: stylexFallback("oa-desktop-shell-conversation"),
      turn: stylexFallback("oa-desktop-shell-turn"),
      turnRole: stylexFallback("oa-desktop-shell-turn-role"),
      turnText: stylexFallback("oa-desktop-shell-turn-text"),
      turnTextYou: stylexFallback("oa-desktop-shell-turn-text-you"),
      stream: stylexFallback("oa-desktop-shell-stream"),
      streamPart: stylexFallback("oa-desktop-shell-stream-part"),
      streamPartAnswer: stylexFallback("oa-desktop-shell-stream-part-answer"),
      streamPartTool: stylexFallback("oa-desktop-shell-stream-part-tool"),
      streamPartResult: stylexFallback("oa-desktop-shell-stream-part-result"),
      streamPartStatus: stylexFallback("oa-desktop-shell-stream-part-status"),
      streamPartTokens: stylexFallback("oa-desktop-shell-stream-part-tokens"),
      streamPartLabel: stylexFallback("oa-desktop-shell-stream-part-label"),
      streamPartBody: stylexFallback("oa-desktop-shell-stream-part-body"),
      streamPartBodyReasoning: stylexFallback(
        "oa-desktop-shell-stream-part-body-reasoning",
      ),
      streamPartBodyMuted: stylexFallback(
        "oa-desktop-shell-stream-part-body-muted",
      ),
      streamPre: stylexFallback("oa-desktop-shell-stream-pre"),
      streamAnswer: stylexFallback("oa-desktop-shell-stream-answer"),
      bar: stylexFallback("oa-desktop-shell-bar"),
      targetTabs: stylexFallback("oa-desktop-shell-target-tabs"),
      targetTab: stylexFallback("oa-desktop-shell-target-tab"),
      targetTabActive: stylexFallback("oa-desktop-shell-target-tab-active"),
      input: stylexFallback("oa-desktop-shell-input"),
      returnButton: stylexFallback("oa-desktop-shell-return"),
    }
  : stylex.create({
      pane: {
        position: "absolute",
        inset: 0,
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-end",
        backgroundColor: "#000",
      },
      conversation: {
        flex: "1 1 auto",
        overflowY: "auto",
        display: "flex",
        flexDirection: "column",
        gap: "1rem",
        padding: "clamp(1rem, 4vw, 3rem)",
        maxWidth: "52rem",
        width: "100%",
        margin: "0 auto",
      },
      turn: {
        display: "flex",
        flexDirection: "column",
        gap: "0.25rem",
      },
      turnRole: {
        fontSize: "0.7rem",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        color: "rgb(255 255 255 / 0.35)",
      },
      turnText: {
        color: "var(--text, #e6e9ef)",
        whiteSpace: "pre-wrap",
        wordBreak: "break-word",
        lineHeight: 1.5,
      },
      turnTextYou: {
        color: "rgb(255 255 255 / 0.92)",
      },
      stream: {
        display: "flex",
        flexDirection: "column",
        gap: "0.55rem",
      },
      streamPart: {
        display: "grid",
        gridTemplateColumns: "minmax(4.5rem, 6rem) minmax(0, 1fr)",
        gap: "0.65rem",
        alignItems: "start",
        minWidth: 0,
        padding: "0.5rem 0.65rem",
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "rgb(255 255 255 / 0.12)",
        borderLeftColor: "rgb(255 255 255 / 0.34)",
        borderRadius: "4px",
        backgroundColor: "rgb(255 255 255 / 0.035)",
      },
      streamPartAnswer: {
        borderColor: "transparent",
        borderLeftColor: "rgb(255 255 255 / 0.22)",
        backgroundColor: "transparent",
      },
      streamPartTool: {
        backgroundColor: "rgb(255 255 255 / 0.045)",
      },
      streamPartResult: {
        backgroundColor: "rgb(255 255 255 / 0.028)",
      },
      streamPartStatus: {
        paddingTop: "0.4rem",
        paddingBottom: "0.4rem",
        backgroundColor: "transparent",
      },
      streamPartTokens: {
        paddingTop: "0.4rem",
        paddingBottom: "0.4rem",
        backgroundColor: "transparent",
      },
      streamPartLabel: {
        minWidth: 0,
        color: "rgb(255 255 255 / 0.42)",
        fontFamily: "ui-monospace, monospace",
        fontSize: "0.68rem",
        letterSpacing: 0,
        lineHeight: 1.45,
        overflow: "hidden",
        textOverflow: "ellipsis",
        textTransform: "uppercase",
        whiteSpace: "nowrap",
      },
      streamPartBody: {
        minWidth: 0,
        color: "rgb(255 255 255 / 0.74)",
        lineHeight: 1.48,
      },
      streamPartBodyReasoning: {
        color: "rgb(255 255 255 / 0.62)",
      },
      streamPartBodyMuted: {
        color: "rgb(255 255 255 / 0.5)",
      },
      streamPre: {
        maxHeight: "18rem",
        margin: 0,
        overflow: "auto",
        whiteSpace: "pre-wrap",
        wordBreak: "break-word",
        fontFamily: "ui-monospace, monospace",
        fontSize: "0.78rem",
        lineHeight: 1.5,
      },
      streamAnswer: {
        color: "var(--text, #e6e9ef)",
        whiteSpace: "pre-wrap",
        wordBreak: "break-word",
      },
      bar: {
        flex: "0 0 auto",
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        padding: "clamp(0.75rem, 2vw, 1.25rem)",
        backgroundColor: "#000",
      },
      targetTabs: {
        flex: "0 0 auto",
        display: "flex",
        alignItems: "center",
        gap: "0.2rem",
        minWidth: 0,
        padding: "0.25rem",
        border: "1px solid rgb(255 255 255 / 0.18)",
        borderRadius: "6px",
        backgroundColor: "rgb(255 255 255 / 0.035)",
      },
      targetTab: {
        height: "2rem",
        minWidth: "3.25rem",
        padding: "0 0.55rem",
        border: "1px solid rgb(255 255 255 / 0.12)",
        borderRadius: "3px",
        backgroundColor: "transparent",
        color: "rgb(255 255 255 / 0.52)",
        cursor: "pointer",
        fontFamily: "ui-monospace, monospace",
        fontSize: "0.68rem",
        letterSpacing: 0,
        lineHeight: 1,
        ":hover": {
          color: "rgb(255 255 255 / 0.86)",
          borderColor: "rgb(255 255 255 / 0.28)",
          outlineStyle: "none",
        },
        ":focus-visible": {
          color: "rgb(255 255 255 / 0.86)",
          borderColor: "rgb(255 255 255 / 0.28)",
          outlineStyle: "none",
        },
      },
      targetTabActive: {
        backgroundColor: "rgb(255 255 255 / 0.13)",
        borderColor: "rgb(255 255 255 / 0.42)",
        color: "rgb(255 255 255 / 0.94)",
      },
      input: {
        flex: "1 1 auto",
        minWidth: 0,
        backgroundColor: "rgb(255 255 255 / 0.04)",
        border: "1px solid rgb(255 255 255 / 0.12)",
        borderRadius: "10px",
        color: "var(--text, #e6e9ef)",
        fontFamily: "inherit",
        fontSize: "1rem",
        padding: "0.75rem 1rem",
        outlineStyle: "none",
        "::placeholder": {
          color: "rgb(255 255 255 / 0.25)",
        },
        ":focus": {
          borderColor:
            "color-mix(in srgb, var(--hud-primary) 32%, transparent)",
          boxShadow:
            "0 0 0 1px color-mix(in srgb, var(--hud-primary) 14%, transparent)",
        },
        ":disabled": {
          opacity: 0.55,
        },
      },
      returnButton: {
        position: "fixed",
        top: "0.5rem",
        left: "0.5rem",
        zIndex: 9999,
        backgroundColor: "rgb(0 0 0 / 0.6)",
        border: "1px solid rgb(255 255 255 / 0.18)",
        borderRadius: "8px",
        color: "rgb(255 255 255 / 0.6)",
        cursor: "pointer",
        fontFamily: "inherit",
        fontSize: "0.75rem",
        letterSpacing: "0.04em",
        padding: "0.35rem 0.6rem",
        ":hover": {
          color: "rgb(255 255 255 / 0.95)",
          borderColor: "rgb(255 255 255 / 0.4)",
        },
      },
    })

export const desktopPaneStyles = stylexRuntimeFallbackEnabled()
  ? {
      layer: stylexFallback("oa-desktop-pane-layer"),
      window: stylexFallback("oa-desktop-pane-window"),
      titlebar: stylexFallback("oa-desktop-pane-window-titlebar"),
      title: stylexFallback("oa-desktop-pane-window-title"),
      close: stylexFallback("oa-desktop-pane-window-close"),
      body: stylexFallback("oa-desktop-pane-window-body"),
      resize: stylexFallback("oa-desktop-pane-window-resize"),
      resizeHorizontal: stylexFallback("oa-desktop-pane-window-resize-horizontal"),
      resizeVertical: stylexFallback("oa-desktop-pane-window-resize-vertical"),
      resizeTop: stylexFallback("oa-desktop-pane-window-resize-top"),
      resizeBottom: stylexFallback("oa-desktop-pane-window-resize-bottom"),
      resizeLeft: stylexFallback("oa-desktop-pane-window-resize-left"),
      resizeRight: stylexFallback("oa-desktop-pane-window-resize-right"),
      resizeCorner: stylexFallback("oa-desktop-pane-window-resize-corner"),
      resizeTopLeft: stylexFallback("oa-desktop-pane-window-resize-topleft"),
      resizeTopRight: stylexFallback("oa-desktop-pane-window-resize-topright"),
      resizeBottomLeft: stylexFallback(
        "oa-desktop-pane-window-resize-bottomleft",
      ),
      resizeBottomRight: stylexFallback(
        "oa-desktop-pane-window-resize-bottomright",
      ),
    }
  : stylex.create({
      layer: {
        position: "fixed",
        inset: 0,
        zIndex: 30,
        pointerEvents: "none",
      },
      window: {
        position: "absolute",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
        border: "1px solid rgb(255 255 255 / 0.16)",
        borderRadius: "12px",
        backgroundColor: "rgb(6 9 13 / 0.96)",
        boxShadow: "0 24px 64px rgb(0 0 0 / 0.6)",
        pointerEvents: "auto",
        transitionProperty: "border-color, box-shadow",
        transitionDuration: "0.14s",
        transitionTimingFunction: "ease",
      },
      titlebar: {
        position: "relative",
        zIndex: 1,
        flex: "0 0 auto",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "0.5rem",
        padding: "0.4rem 0.6rem",
        borderBottom:
          "1px solid color-mix(in srgb, var(--hud-primary) 16%, transparent)",
        background:
          "linear-gradient(to right, color-mix(in srgb, var(--hud-neutral, #9aa6b2) 10%, transparent), transparent 60%), rgb(255 255 255 / 0.03)",
        cursor: "move",
        userSelect: "none",
        touchAction: "none",
      },
      title: {
        fontSize: "0.72rem",
        letterSpacing: "0.07em",
        textTransform: "uppercase",
        color: "var(--hud-secondary, #f2f4f8)",
      },
      close: {
        flex: "0 0 auto",
        width: "1.4rem",
        height: "1.4rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        border: "1px solid rgb(255 255 255 / 0.12)",
        borderRadius: "6px",
        backgroundColor: "transparent",
        color: "rgb(255 255 255 / 0.55)",
        cursor: "pointer",
        fontSize: "1rem",
        lineHeight: 1,
        ":hover": {
          color: "var(--hud-primary, #fff)",
          borderColor: "color-mix(in srgb, var(--hud-primary) 50%, transparent)",
          backgroundColor:
            "color-mix(in srgb, var(--hud-primary) 12%, transparent)",
        },
      },
      body: {
        position: "relative",
        zIndex: 1,
        flex: "1 1 auto",
        overflow: "auto",
        padding: "0.75rem",
        color: "var(--text, #e6e9ef)",
      },
      resize: {
        position: "absolute",
        zIndex: 3,
        touchAction: "none",
      },
      resizeHorizontal: {
        left: "8px",
        right: "8px",
        height: "6px",
        cursor: "ns-resize",
      },
      resizeVertical: {
        top: "8px",
        bottom: "8px",
        width: "6px",
        cursor: "ew-resize",
      },
      resizeTop: {
        top: "-3px",
      },
      resizeBottom: {
        bottom: "-3px",
      },
      resizeLeft: {
        left: "-3px",
      },
      resizeRight: {
        right: "-3px",
      },
      resizeCorner: {
        width: "12px",
        height: "12px",
      },
      resizeTopLeft: {
        top: "-4px",
        left: "-4px",
        cursor: "nwse-resize",
      },
      resizeTopRight: {
        top: "-4px",
        right: "-4px",
        cursor: "nesw-resize",
      },
      resizeBottomLeft: {
        bottom: "-4px",
        left: "-4px",
        cursor: "nesw-resize",
      },
      resizeBottomRight: {
        bottom: "-4px",
        right: "-4px",
        cursor: "nwse-resize",
      },
    })
