import {
  MulletSimulationRunExport,
  decodeMulletScenario,
  decodeMulletSimulationRun,
} from '@openagentsinc/mullet-schema'
import { Schema as S } from 'effect'

export const mulletFixtureTimestamp = '2026-06-08T00:00:00.000Z'

export const mulletFixtureSourceRef = {
  id: 'source_mullet_repository_fixture',
  label: 'Mullet repository fixture',
  uri: 'workers/api/src/mullet/test-fixtures.test-support.ts',
  capturedAt: mulletFixtureTimestamp,
}

export const provenancedNumberFixture = (value: number, unit: string) => ({
  value,
  unit,
  provenance: 'modeled',
  confidence: 0.72,
  source: mulletFixtureSourceRef,
  lastUpdated: mulletFixtureTimestamp,
  needsDiligence: true,
})

export const provenancedStringFixture = (value: string) => ({
  value,
  unit: 'text',
  provenance: 'modeled',
  confidence: 0.72,
  source: mulletFixtureSourceRef,
  lastUpdated: mulletFixtureTimestamp,
  needsDiligence: true,
})

export const scenarioFixture = (notes?: string) =>
  decodeMulletScenario({
    id: 'mullet_scenario_repo_fixture',
    name: 'Repository fixture scenario',
    schemaVersion: '2026-06-08.v1',
    kind: 'tinybox_shc_power',
    createdAt: mulletFixtureTimestamp,
    updatedAt: mulletFixtureTimestamp,
    dateRange: {
      startAt: mulletFixtureTimestamp,
      endAt: '2026-06-09T00:00:00.000Z',
    },
    facility: {
      id: 'facility_repo_fixture',
      siteId: 'site_repo_fixture',
      name: 'Repository fixture site',
      market: 'ERCOT',
      zone: 'LZ_WEST',
      capacityMw: provenancedNumberFixture(1, 'megawatts'),
      powerContractType: 'fixed_fixture',
      fixedPriceUsdPerMwh: provenancedNumberFixture(45, 'usd_per_mwh'),
      maxAiAllocationMw: provenancedNumberFixture(0.002, 'megawatts'),
      curtailmentPolicy: 'manual',
      gridServiceTerms: 'none',
      siteOpsCostUsdPerMwh: provenancedNumberFixture(5, 'usd_per_mwh'),
      coolingMultiplier: provenancedNumberFixture(1.1, 'score'),
      remoteHandsMonthlyUsd: provenancedNumberFixture(100, 'usd'),
      physicalReadiness: {
        interconnectionStatus: provenancedStringFixture('fixture'),
        energizedCapacityMw: provenancedNumberFixture(1, 'megawatts'),
        transformerStatus: provenancedStringFixture('fixture'),
        switchgearStatus: provenancedStringFixture('fixture'),
        coolingCapacityKw: provenancedNumberFixture(20, 'kilowatts'),
        pue: provenancedNumberFixture(1.2, 'score'),
        fiberOrNetworkStatus: provenancedStringFixture('fixture'),
        redundancyTier: provenancedStringFixture('fixture'),
        remoteHandsSla: provenancedStringFixture('fixture'),
        uptimeCommitment: provenancedNumberFixture(0.95, 'percent'),
        liquidatedDamagesExposureUsd: provenancedNumberFixture(0, 'usd'),
        permittingOrCommunityRisk: provenancedStringFixture('fixture'),
      },
      customerSlaReserveUsdPerMwh: provenancedNumberFixture(25, 'usd_per_mwh'),
      siteClassification: 'mining_led_ai_pilot_not_mullet',
      readinessState: 'benchmark_passed',
      capacityLifecycleState: 'eligible',
    },
    miningFleet: {
      asicModel: 'S21 fixture',
      count: 0,
      wattsPerUnit: 3500,
      thPerUnit: 200,
      joulesPerTh: 17.5,
      capexPerUnitUsd: 4000,
      depreciationMonths: 36,
      poolFeePercent: 0.02,
      firmwareOpsCostUsdPerMwh: 2,
    },
    computeNodes: [
      {
        nodeId: 'node_repo_fixture',
        nodeType: 'tinybox_red_v2',
        ownerParty: 'openagents',
        operatorParty: 'fixture_provider',
        siteId: 'site_repo_fixture',
        gpuModel: 'AMD 9070 XT',
        gpuCount: 4,
        vramGb: 64,
        interconnect: 'pcie',
        cpu: 'fixture',
        ramGb: 128,
        storageGb: 2000,
        networkGbps: 1,
        capexUsd: 12000,
        depreciationMonths: 36,
        idlePowerKw: 0.35,
        loadPowerKw: 1.6,
        powerLimitKw: 1.6,
        supportMonthlyUsd: 150,
        fallbackMarketEligible: true,
        trustTier: 'pilot',
        readinessState: 'benchmark_passed',
        capacityLifecycleState: 'admitted',
        workloadFit: ['work_class_repo_fixture'],
      },
    ],
    runtimeBenchmarks: [
      {
        nodeId: 'node_repo_fixture',
        workClassId: 'work_class_repo_fixture',
        modelId: 'fixture-local-model',
        framework: 'fixture',
        precision: 'fp16',
        batchSize: 1,
        attemptsPerInstanceHour: 12,
        tokensPerSecond: 80,
        joulesPerToken: 10,
        kwhPerAttempt: 0.08,
        wallSecondsPerAttempt: 300,
        observedFailureRate: 0.08,
        source: mulletFixtureSourceRef,
        confidence: 0.72,
      },
    ],
    workClasses: [
      {
        id: 'work_class_repo_fixture',
        label: 'Repository fixture work',
        latencyClass: 'batch',
        buyerPriceUsd: 2.5,
        acceptanceRate: 0.9,
        targetMargin: 0.25,
        riskReserveUsd: 0.15,
        frontierInputTokens: 1000,
        frontierOutputTokens: 200,
        frontierInputPriceUsdPerMillion: 1.25,
        frontierOutputPriceUsdPerMillion: 10,
        cheapModelCostUsd: 0.05,
        workroomRuntimeHours: 0.1,
        workroomHourlyCostUsd: 0.25,
        providerComputeHours: 0.1,
        providerPowerKw: 1.6,
        validatorCount: 2,
        validatorPayoutEachUsd: 0.05,
        graderCostUsd: 0.05,
        humanReviewMinutes: 0,
        humanReviewHourlyCostUsd: 60,
        artifactStorageCostUsd: 0.01,
        settlementCostUsd: 0.01,
        supportOverheadUsd: 0.03,
        retryOrFailureCostUsd: 0.04,
        flexibility: {
          canPause: true,
          canResume: true,
          canMigrate: true,
          checkpointIntervalMinutes: 10,
          maxDelayMinutes: 1440,
          deadlineMinutes: 1440,
          customerImpactIfDelayed: 'low',
          privacyTier: 'public_safe',
          stateLocality: 'portable',
          requiredTools: ['artifact-store'],
        },
        demandBacklog: 100,
        eligibleNodeTypes: ['tinybox_red_v2'],
        minimumTrustTier: 'pilot',
      },
    ],
    providerPolicies: [
      {
        nodeType: 'tinybox_red_v2',
        providerMinimumBidUsdPerHour: 1,
        providerMinimumBidUsdPerJob: 0.1,
        wearUsdPerKwh: 0.05,
        bandwidthUsdPerJob: 0.01,
        desiredProfitUsdPerJob: 0.1,
        operatorMarginUsdPerMwh: 25,
        miningFloorPolicy: 'modeled',
        rawGpuFloorPolicy: 'modeled',
        vpsColocationFloorPolicy: 'not_applicable',
        curtailmentGridServiceFloorPolicy: 'none',
      },
    ],
    partySplit: {
      buyerPaysUsd: 2.5,
      openagentsKeepsUsd: 0.7,
      providerReceivesUsd: 1.2,
      facilityOperatorReceivesUsd: 0.2,
      hardwareOwnerReceivesUsd: 0.3,
      validatorsReceiveUsd: 0.1,
      reviewersReceiveUsd: 0,
      settlementCostUsd: 0.01,
      riskReserveUsd: 0.15,
    },
    capitalAssumptions: {
      hardwareCapexUsd: provenancedNumberFixture(12000, 'usd'),
      depreciationMonths: provenancedNumberFixture(36, 'months'),
      discountRatePercent: provenancedNumberFixture(12, 'percent'),
      debtServiceMonthlyUsd: provenancedNumberFixture(0, 'usd'),
      residualValueUsd: provenancedNumberFixture(4000, 'usd'),
    },
    demandAssumptions: {
      acceptedWorkBacklog: provenancedNumberFixture(100, 'outcomes'),
      demandFillPercent: provenancedNumberFixture(0.55, 'percent'),
      rawGpuMarketFillPercent: provenancedNumberFixture(0.35, 'percent'),
      tokenApiFillPercent: provenancedNumberFixture(0.1, 'percent'),
    },
    sourceRefs: [mulletFixtureSourceRef],
    ...(notes === undefined ? {} : { notes }),
  })

export const candidateFixture = (
  mode: 'mine' | 'openagents_accepted_work',
) => ({
  timestamp: mulletFixtureTimestamp,
  mode,
  buyerRevenueUsd: mode === 'mine' ? 100 : 12.5,
  providerPayoutUsd: mode === 'mine' ? 0 : 6,
  openagentsMarginUsd: mode === 'mine' ? 45 : 4.5,
  providerNetUsdPerMwh: mode === 'mine' ? 0 : 3750,
  acceptedOutcomes: mode === 'mine' ? 0 : 5,
  acceptedOutcomesPerMwh: mode === 'mine' ? 0 : 3125,
  energyMwh: 0.0016,
  riskAdjustedNetUsdPerMwh: mode === 'mine' ? 45 : 2812.5,
  clearsReadiness: true,
  clearsDemand: true,
  clearsProviderFloor: true,
  reasonCode:
    mode === 'mine'
      ? 'mining_best_available'
      : 'accepted_work_clears_all_gates',
})

export const simulationRunFixture = () => {
  const scenario = scenarioFixture()

  return decodeMulletSimulationRun({
    id: 'mullet_run_repo_fixture',
    scenarioId: scenario.id,
    ownerUserId: 'user_chris',
    ownerEmail: 'chris@openagents.com',
    status: 'succeeded',
    createdAt: mulletFixtureTimestamp,
    updatedAt: mulletFixtureTimestamp,
    completedAt: mulletFixtureTimestamp,
    scenario,
    dispatchResults: [
      {
        timestamp: mulletFixtureTimestamp,
        effectivePriceUsdPerMwh: 45,
        selectedMode: 'openagents_accepted_work',
        candidates: [
          candidateFixture('mine'),
          candidateFixture('openagents_accepted_work'),
        ],
        miningRevenueUsd: 100,
        miningProfitUsd: 45,
        rawGpuRevenueUsd: 0,
        tokenApiRevenueUsd: 0,
        acceptedWorkBuyerRevenueUsd: 12.5,
        acceptedWorkProviderPayoutUsd: 6,
        acceptedWorkOpenagentsMarginUsd: 4.5,
        acceptedOutcomes: 5,
        acceptedOutcomesPerMwh: 3125,
        proofPacketIds: [],
        marketMemoryUpdateIds: [],
        energyTelemetryRecordIds: [],
        energyMwh: 0.0016,
        curtailedMw: 0,
        idleMw: 0,
        reasonCode: 'accepted_work_clears_all_gates',
        provenance: 'modeled',
        confidence: 0.72,
      },
    ],
    capitalReturns: [],
    proofPackets: [],
    marketMemory: [],
    energyTelemetry: [],
    providerSettlementState: 'not_payable',
    powerDataState: 'modeled',
  })
}

export const runExportFixture = (
  run: ReturnType<typeof simulationRunFixture>,
) =>
  S.decodeUnknownSync(MulletSimulationRunExport)({
    runId: run.id,
    scenarioId: run.scenarioId,
    generatedAt: mulletFixtureTimestamp,
    format: 'json',
    privateVisibility: true,
    redactionStatus: 'not_checked',
    modeledValueCount: 1,
    measuredValueCount: 0,
    acceptedValueCount: 0,
    paidValueCount: 0,
    settledValueCount: 0,
    contentRef: 'artifact.mullet.private.repo_fixture',
  })
