#!/usr/bin/env node
/**
 * Sign the Omega download manifest (#9280).
 *
 * Reads the human-edited source manifest
 * `src/omega-release/omega-download-manifest.json`, validates it against the
 * `openagents.omega.download_manifest.v1` contract, signs the EXACT file
 * bytes with the OpenAgents release/provenance Ed25519 key (the same key and
 * custody ladder as `apps/oa-updates/scripts/sign-release.ts` — see
 * `apps/oa-updates/docs/release-signing-runbook.md`), self-verifies the
 * result through the resolver's exact client seam, and writes the generated
 * module `src/omega-release/omega-download-manifest.gen.ts` that the server
 * resolver embeds.
 *
 * Publishing a new Omega RC:
 *   1. Edit `src/omega-release/omega-download-manifest.json` (version, tag,
 *      URL, sha256, byteLength, notarization truth, limitations).
 *   2. `node --import tsx apps/openagents.com/apps/start/scripts/sign-omega-download-manifest.ts`
 *   3. Commit both files, push, deploy the Cloud Run service.
 *
 * The private key is loaded, in priority order, from:
 *   1) env `OPENAGENTS_RELEASE_SIGNING_PRIVATE_JWK_D` (+ `_KID`)
 *   2) the local secrets file `~/work/.secrets/openagents-release-signing.env`
 *   3) GCP Secret Manager (`openagents-release-signing-key`)
 * The key is NEVER printed, logged, or written anywhere.
 */
import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import {
  signReleasePayload,
  type ReleaseSigningKey,
} from '../../../../../apps/openagents-desktop/src/release-publish.ts'
import { PRODUCTION_RELEASE_KEY_PIN } from '../../../../../apps/openagents-desktop/src/update-contract.ts'
import { verifySignedOmegaDownloadManifest } from '../src/omega-download-resolver.server.ts'

const LOCAL_SECRETS =
  process.env['OPENAGENTS_RELEASE_SECRETS_PATH'] ??
  `${process.env['HOME']}/work/.secrets/openagents-release-signing.env`
const GCP_PROJECT = process.env['OPENAGENTS_GCP_PROJECT'] ?? 'openagentsgemini'
const GCP_SECRET = 'openagents-release-signing-key'

const parseEnv = (text: string): Record<string, string> =>
  Object.fromEntries(
    text
      .split('\n')
      .filter(line => line !== '' && !line.startsWith('#') && line.includes('='))
      .map(line => {
        const index = line.indexOf('=')
        return [line.slice(0, index).trim(), line.slice(index + 1).trim()]
      }),
  )

const loadKey = (): ReleaseSigningKey => {
  const envSeed = process.env['OPENAGENTS_RELEASE_SIGNING_PRIVATE_JWK_D']
  if (envSeed !== undefined && envSeed !== '') {
    return { d: envSeed, kid: process.env['OPENAGENTS_RELEASE_SIGNING_KID'] ?? 'env' }
  }
  if (existsSync(LOCAL_SECRETS)) {
    const entries = parseEnv(readFileSync(LOCAL_SECRETS, 'utf8'))
    const seed = entries['OPENAGENTS_RELEASE_SIGNING_PRIVATE_JWK_D']
    if (seed !== undefined && seed !== '') {
      return { d: seed, kid: entries['OPENAGENTS_RELEASE_SIGNING_KID'] ?? 'local' }
    }
  }
  // GCP Secret Manager fallback (our cloud) — never echoes the value.
  const raw = execSync(
    `gcloud secrets versions access latest --secret=${GCP_SECRET} --project=${GCP_PROJECT}`,
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
  )
  const entries = parseEnv(raw)
  const seed = entries['OPENAGENTS_RELEASE_SIGNING_PRIVATE_JWK_D']
  if (seed === undefined || seed === '') {
    throw new Error('release signing key not found (env / .secrets / GCP Secret Manager)')
  }
  return { d: seed, kid: entries['OPENAGENTS_RELEASE_SIGNING_KID'] ?? 'gcp' }
}

const here = import.meta.dirname
const manifestPath = path.resolve(here, '../src/omega-release/omega-download-manifest.json')
const generatedPath = path.resolve(
  here,
  '../src/omega-release/omega-download-manifest.gen.ts',
)

const payloadText = readFileSync(manifestPath, 'utf8')
const key = loadKey()
const { envelope, pin } = signReleasePayload(new TextEncoder().encode(payloadText), key)

if (pin.kid !== PRODUCTION_RELEASE_KEY_PIN.kid || pin.x !== PRODUCTION_RELEASE_KEY_PIN.x) {
  throw new Error(
    `signing key (kid ${pin.kid}) is not the pinned production release key; refusing to write`,
  )
}

// Self-verify through the exact resolver seam before writing anything: a
// manifest the resolver would reject can never be generated.
const verified = verifySignedOmegaDownloadManifest(payloadText, envelope, pin)
if (!verified.ok) {
  throw new Error(`signed manifest failed self-verification: ${verified.reason}`)
}

const generated = `// GENERATED by scripts/sign-omega-download-manifest.ts — DO NOT EDIT BY HAND.
// Signed Omega download manifest (#9280): the payload string is the EXACT
// byte-for-byte content of omega-download-manifest.json at signing time, and
// the envelope is its detached Ed25519 signature by the pinned OpenAgents
// release key (kid ${pin.kid}). The server resolver verifies both
// against the production pin before serving anything.
export const omegaDownloadManifestPayload: string = ${JSON.stringify(payloadText)}

export const omegaDownloadManifestSignature = ${JSON.stringify(envelope, null, 2)} as const
`

writeFileSync(generatedPath, generated)
console.log(
  `signed ${path.relative(process.cwd(), manifestPath)} (${verified.manifest.version}, sha256 ${envelope.sha256}) -> ${path.relative(process.cwd(), generatedPath)}`,
)
