import { existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const desktopRoot = fileURLToPath(new URL(".", import.meta.url));
const workspaceMokshaAssetSource =
  "node_modules/@openagentsinc/three-effect/packages/core/src/assets/moksha";
const rootMokshaAssetSource =
  "../../node_modules/@openagentsinc/three-effect/packages/core/src/assets/moksha";
const workspaceThreePlayerControllerAssetSource =
  "node_modules/@openagentsinc/three-effect/packages/core/src/assets/three-player-controller";
const rootThreePlayerControllerAssetSource =
  "../../node_modules/@openagentsinc/three-effect/packages/core/src/assets/three-player-controller";

export const mokshaAssetSource = existsSync(
  join(desktopRoot, workspaceMokshaAssetSource),
)
  ? workspaceMokshaAssetSource
  : rootMokshaAssetSource;

export const threePlayerControllerAssetSource = existsSync(
  join(desktopRoot, workspaceThreePlayerControllerAssetSource),
)
  ? workspaceThreePlayerControllerAssetSource
  : rootThreePlayerControllerAssetSource;

export default {
  app: {
    name: "Autopilot",
    identifier: "com.openagents.autopilot.desktop",
    // #5046: Autopilot stable desktop release.
    version: "1.0.1"
  },
  // #5040: default-on OTA. Electrobun's Updater fetches the per-platform
  // update.json + BSDIFF/tarball artifacts from our GCP feed (the oa-updates
  // Cloud Run service on updates.openagents.com). RC builds use the canary
  // channel; stable is the production release channel.
  release: {
    baseUrl: "https://updates.openagents.com/desktop"
  },
  build: {
    bun: {
      entrypoint: "src/bun/index.ts"
    },
    views: {
      "autopilot-desktop": {
        entrypoint: "src/ui/main.ts"
      }
    },
    copy: {
      "src/ui/index.html": "views/autopilot-desktop/index.html",
      // CL-53: the Tailwind v4 stylesheet generated by `bun run build:css`
      // (run before electrobun build). Lands at views/autopilot-desktop/styles.css
      // and is linked from index.html.
      "src/ui/styles.out.css": "views/autopilot-desktop/styles.css",
      // The network-home pylon diamond renderer is shared with openagents.com
      // and resolves its GLB/font/image assets relative to the bundled view
      // module (`views://autopilot-desktop/assets/moksha/...`). Copy the whole
      // asset directory so WebKit does not get empty `views://` responses.
      [mokshaAssetSource]: "views/autopilot-desktop/assets/moksha",
      // The Verse third-person controller now uses a real model from the
      // imported three-player-controller GLB pack instead of a procedural
      // placeholder, so package that shared model next to the view bundle too.
      [threePlayerControllerAssetSource]:
        "views/autopilot-desktop/assets/three-player-controller",
      // #5027 (Phase 2, packaged build): the bundled headless Pylon node, built
      // by `bun run build:pylon-node` before electrobun build. electrobun copies
      // `build.copy` dests under `<RESOURCES_FOLDER>/app/`, so this dest lands at
      // `Contents/Resources/app/pylon-node/index.js` — exactly where the Bun
      // main process's `findPackagedPylonEntry` (PACKAGED_PYLON_DIR =
      // `app/pylon-node`, joined onto PATHS.RESOURCES_FOLDER) resolves it. That
      // lets a packaged install launch the local node with the bundled Bun,
      // matching the dev bring-up (#5011).
      "resources/pylon-node/index.js": "pylon-node/index.js"
    }
  }
};
