export default {
  app: {
    name: "Autopilot Desktop",
    identifier: "com.openagents.autopilot.desktop",
    version: "0.0.1"
  },
  build: {
    bun: {
      entrypoint: "src/bun/index.ts"
    },
    views: {
      "autopilot-desktop": {
        entrypoint: "src/ui/main.ts"
      }
    },
    copy: {
      "src/ui/index.html": "views/autopilot-desktop/index.html",
      // CL-53: the Tailwind v4 stylesheet generated by `bun run build:css`
      // (run before electrobun build). Lands at views/autopilot-desktop/styles.css
      // and is linked from index.html.
      "src/ui/styles.out.css": "views/autopilot-desktop/styles.css",
      // #5027 (Phase 2, packaged build): the bundled headless Pylon node, built
      // by `bun run build:pylon-node` before electrobun build. electrobun copies
      // `build.copy` dests under `<RESOURCES_FOLDER>/app/`, so this dest lands at
      // `Contents/Resources/app/pylon-node/index.js` — exactly where the Bun
      // main process's `findPackagedPylonEntry` (PACKAGED_PYLON_DIR =
      // `app/pylon-node`, joined onto PATHS.RESOURCES_FOLDER) resolves it. That
      // lets a packaged install launch the local node with the bundled Bun,
      // matching the dev bring-up (#5011).
      "resources/pylon-node/index.js": "pylon-node/index.js"
    }
  }
};
