#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASELINE_FILE="$ROOT_DIR/docs/ci/allow-attribute-baseline.env"
MODE="${1:-check}"

count_allow_attributes() {
  local path="$1"
  local total=0
  local unjustified=0

  while IFS= read -r file; do
    local file_total=0
    local file_unjustified=0
    read -r file_total file_unjustified < <(
      awk '
        BEGIN { prev = ""; total = 0; unjustified = 0 }
        {
          if ($0 ~ /^[[:space:]]*#\[allow\(/) {
            total++;
            if (prev !~ /lint-allow-justified:/) {
              unjustified++;
            }
          }
          prev = $0;
        }
        END { printf "%d %d\n", total, unjustified }
      ' "$file"
    )
    total=$((total + file_total))
    unjustified=$((unjustified + file_unjustified))
  done < <(find "$ROOT_DIR/$path" -type f -name '*.rs' | sort)

  printf "%d %d\n" "$total" "$unjustified"
}

read -r APPS_RUNTIME_TOTAL APPS_RUNTIME_UNJUSTIFIED < <(count_allow_attributes "apps/runtime")
read -r APPS_CONTROL_TOTAL APPS_CONTROL_UNJUSTIFIED < <(count_allow_attributes "apps/openagents.com/service")
read -r APPS_AUTOPILOT_DESKTOP_TOTAL APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED < <(count_allow_attributes "apps/autopilot-desktop")
read -r CRATES_AUTOPILOT_CORE_TOTAL CRATES_AUTOPILOT_CORE_UNJUSTIFIED < <(count_allow_attributes "crates/autopilot-core")
read -r CRATES_AUTOPILOT_TOTAL CRATES_AUTOPILOT_UNJUSTIFIED < <(count_allow_attributes "crates/autopilot")

TOTAL_ALLOW_ATTRS=$(( 
  APPS_RUNTIME_TOTAL
    + APPS_CONTROL_TOTAL
    + APPS_AUTOPILOT_DESKTOP_TOTAL
    + CRATES_AUTOPILOT_CORE_TOTAL
    + CRATES_AUTOPILOT_TOTAL
))
TOTAL_UNJUSTIFIED_ALLOW_ATTRS=$(( 
  APPS_RUNTIME_UNJUSTIFIED
    + APPS_CONTROL_UNJUSTIFIED
    + APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED
    + CRATES_AUTOPILOT_CORE_UNJUSTIFIED
    + CRATES_AUTOPILOT_UNJUSTIFIED
))

print_counts() {
  echo "allow-attribute counts (critical crates):"
  echo "  apps/runtime total=${APPS_RUNTIME_TOTAL} unjustified=${APPS_RUNTIME_UNJUSTIFIED}"
  echo "  apps/openagents.com/service total=${APPS_CONTROL_TOTAL} unjustified=${APPS_CONTROL_UNJUSTIFIED}"
  echo "  apps/autopilot-desktop total=${APPS_AUTOPILOT_DESKTOP_TOTAL} unjustified=${APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED}"
  echo "  crates/autopilot-core total=${CRATES_AUTOPILOT_CORE_TOTAL} unjustified=${CRATES_AUTOPILOT_CORE_UNJUSTIFIED}"
  echo "  crates/autopilot total=${CRATES_AUTOPILOT_TOTAL} unjustified=${CRATES_AUTOPILOT_UNJUSTIFIED}"
  echo "  total=${TOTAL_ALLOW_ATTRS} unjustified=${TOTAL_UNJUSTIFIED_ALLOW_ATTRS}"
}

write_baseline() {
  mkdir -p "$(dirname "$BASELINE_FILE")"
  cat > "$BASELINE_FILE" <<BASELINE
# Generated by scripts/allow-attribute-gate.sh snapshot
ALLOW_ATTR_BASELINE_APPS_RUNTIME_TOTAL=${APPS_RUNTIME_TOTAL}
ALLOW_ATTR_BASELINE_APPS_RUNTIME_UNJUSTIFIED=${APPS_RUNTIME_UNJUSTIFIED}
ALLOW_ATTR_BASELINE_APPS_CONTROL_TOTAL=${APPS_CONTROL_TOTAL}
ALLOW_ATTR_BASELINE_APPS_CONTROL_UNJUSTIFIED=${APPS_CONTROL_UNJUSTIFIED}
ALLOW_ATTR_BASELINE_APPS_AUTOPILOT_DESKTOP_TOTAL=${APPS_AUTOPILOT_DESKTOP_TOTAL}
ALLOW_ATTR_BASELINE_APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED=${APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED}
ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_CORE_TOTAL=${CRATES_AUTOPILOT_CORE_TOTAL}
ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_CORE_UNJUSTIFIED=${CRATES_AUTOPILOT_CORE_UNJUSTIFIED}
ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_TOTAL=${CRATES_AUTOPILOT_TOTAL}
ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_UNJUSTIFIED=${CRATES_AUTOPILOT_UNJUSTIFIED}
ALLOW_ATTR_BASELINE_TOTAL=${TOTAL_ALLOW_ATTRS}
ALLOW_ATTR_BASELINE_UNJUSTIFIED_TOTAL=${TOTAL_UNJUSTIFIED_ALLOW_ATTRS}
BASELINE
}

check_unjustified_growth() {
  local failed=0

  if (( APPS_RUNTIME_UNJUSTIFIED > ALLOW_ATTR_BASELINE_APPS_RUNTIME_UNJUSTIFIED )); then
    echo "allow-attribute gate failed: apps/runtime unjustified suppressions grew" >&2
    failed=1
  fi
  if (( APPS_CONTROL_UNJUSTIFIED > ALLOW_ATTR_BASELINE_APPS_CONTROL_UNJUSTIFIED )); then
    echo "allow-attribute gate failed: apps/openagents.com/service unjustified suppressions grew" >&2
    failed=1
  fi
  if (( APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED > ALLOW_ATTR_BASELINE_APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED )); then
    echo "allow-attribute gate failed: apps/autopilot-desktop unjustified suppressions grew" >&2
    failed=1
  fi
  if (( CRATES_AUTOPILOT_CORE_UNJUSTIFIED > ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_CORE_UNJUSTIFIED )); then
    echo "allow-attribute gate failed: crates/autopilot-core unjustified suppressions grew" >&2
    failed=1
  fi
  if (( CRATES_AUTOPILOT_UNJUSTIFIED > ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_UNJUSTIFIED )); then
    echo "allow-attribute gate failed: crates/autopilot unjustified suppressions grew" >&2
    failed=1
  fi
  if (( TOTAL_UNJUSTIFIED_ALLOW_ATTRS > ALLOW_ATTR_BASELINE_UNJUSTIFIED_TOTAL )); then
    echo "allow-attribute gate failed: total unjustified suppressions grew" >&2
    failed=1
  fi

  return "$failed"
}

case "$MODE" in
  snapshot)
    print_counts
    write_baseline
    echo "wrote baseline: $BASELINE_FILE"
    ;;
  check)
    if [[ ! -f "$BASELINE_FILE" ]]; then
      echo "missing allow-attribute baseline: $BASELINE_FILE" >&2
      echo "run: scripts/allow-attribute-gate.sh snapshot" >&2
      exit 1
    fi

    # shellcheck source=/dev/null
    source "$BASELINE_FILE"

    print_counts
    echo "allow-attribute baseline:"
    echo "  apps/runtime total=${ALLOW_ATTR_BASELINE_APPS_RUNTIME_TOTAL} unjustified=${ALLOW_ATTR_BASELINE_APPS_RUNTIME_UNJUSTIFIED}"
    echo "  apps/openagents.com/service total=${ALLOW_ATTR_BASELINE_APPS_CONTROL_TOTAL} unjustified=${ALLOW_ATTR_BASELINE_APPS_CONTROL_UNJUSTIFIED}"
    echo "  apps/autopilot-desktop total=${ALLOW_ATTR_BASELINE_APPS_AUTOPILOT_DESKTOP_TOTAL} unjustified=${ALLOW_ATTR_BASELINE_APPS_AUTOPILOT_DESKTOP_UNJUSTIFIED}"
    echo "  crates/autopilot-core total=${ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_CORE_TOTAL} unjustified=${ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_CORE_UNJUSTIFIED}"
    echo "  crates/autopilot total=${ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_TOTAL} unjustified=${ALLOW_ATTR_BASELINE_CRATES_AUTOPILOT_UNJUSTIFIED}"
    echo "  total=${ALLOW_ATTR_BASELINE_TOTAL} unjustified=${ALLOW_ATTR_BASELINE_UNJUSTIFIED_TOTAL}"

    if ! check_unjustified_growth; then
      exit 1
    fi

    echo "allow-attribute gate passed"
    ;;
  *)
    echo "usage: scripts/allow-attribute-gate.sh [check|snapshot]" >&2
    exit 2
    ;;
esac
