#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASELINE_FILE="$ROOT_DIR/docs/ci/architecture-budget-baseline.env"
MODE="${1:-check}"

measure_service_route_count() {
  rg -n '\.route\(' "$ROOT_DIR/apps/openagents.com/src/route_domains.rs" \
    | wc -l \
    | tr -d ' '
}

measure_prod_max_file() {
  local record
  record="$(
    (
      cd "$ROOT_DIR"
      find apps/runtime/src apps/openagents.com/src apps/autopilot-desktop/src crates/autopilot/src crates/autopilot-core/src \
        -type f -name '*.rs' \
        ! -name '*tests.rs' \
        ! -path '*/tests/*' \
        ! -path '*/test/*' \
        ! -path '*/fixtures/*' \
        -print0 \
        | xargs -0 wc -c \
        | awk '$2 != "total"' \
        | sort -nr \
        | awk 'NR==1 { print $1, $2 }'
    )
  )"

  if [[ -z "$record" ]]; then
    echo "failed to compute production max file metric" >&2
    exit 1
  fi

  printf '%s\n' "$record"
}

resolve_exception_file() {
  local exception_file="${OA_ARCH_BUDGET_EXCEPTION_FILE:-}"
  if [[ -z "$exception_file" ]]; then
    return 1
  fi

  if [[ -f "$exception_file" ]]; then
    printf '%s\n' "$exception_file"
    return 0
  fi

  if [[ -f "$ROOT_DIR/$exception_file" ]]; then
    printf '%s\n' "$ROOT_DIR/$exception_file"
    return 0
  fi

  echo "architecture-budget exception file not found: $exception_file" >&2
  return 1
}

metric_exception_approved() {
  local metric="$1"
  local exception_path

  if ! exception_path="$(resolve_exception_file)"; then
    return 1
  fi

  if ! rg -q 'ARCH_BUDGET_EXCEPTION_APPROVED' "$exception_path"; then
    echo "architecture-budget exception file missing approval token: ARCH_BUDGET_EXCEPTION_APPROVED" >&2
    return 1
  fi

  if ! rg -q "ARCH_BUDGET_EXCEPTION_APPROVED:[[:space:]]*${metric}" "$exception_path"; then
    echo "architecture-budget exception file missing metric approval for '${metric}'" >&2
    return 1
  fi

  printf '%s\n' "$exception_path"
  return 0
}

SERVICE_ROUTE_COUNT="$(measure_service_route_count)"
read -r PROD_MAX_FILE_BYTES PROD_MAX_FILE_PATH < <(measure_prod_max_file)

print_metrics() {
  echo "architecture budget metrics:"
  echo "  service_route_count=${SERVICE_ROUTE_COUNT}"
  echo "  prod_max_file_bytes=${PROD_MAX_FILE_BYTES}"
  echo "  prod_max_file_path=${PROD_MAX_FILE_PATH}"
}

write_baseline() {
  mkdir -p "$(dirname "$BASELINE_FILE")"
  cat > "$BASELINE_FILE" <<BASELINE
# Generated by scripts/architecture-budget-gate.sh snapshot
ARCH_BUDGET_BASELINE_SERVICE_ROUTE_COUNT=${SERVICE_ROUTE_COUNT}
ARCH_BUDGET_BASELINE_PROD_MAX_FILE_BYTES=${PROD_MAX_FILE_BYTES}
ARCH_BUDGET_BASELINE_PROD_MAX_FILE_PATH=${PROD_MAX_FILE_PATH}
BASELINE
}

check_allow_suppression_budget() {
  echo "==> architecture budget sub-check: allow-attribute debt"
  "$ROOT_DIR/scripts/allow-attribute-gate.sh" check
}

case "$MODE" in
  snapshot)
    print_metrics
    write_baseline
    echo "wrote baseline: $BASELINE_FILE"
    ;;
  check)
    if [[ ! -f "$BASELINE_FILE" ]]; then
      echo "missing architecture budget baseline: $BASELINE_FILE" >&2
      echo "run: scripts/architecture-budget-gate.sh snapshot" >&2
      exit 1
    fi

    # shellcheck source=/dev/null
    source "$BASELINE_FILE"

    print_metrics
    echo "architecture budget baseline:"
    echo "  service_route_count=${ARCH_BUDGET_BASELINE_SERVICE_ROUTE_COUNT}"
    echo "  prod_max_file_bytes=${ARCH_BUDGET_BASELINE_PROD_MAX_FILE_BYTES}"
    echo "  prod_max_file_path=${ARCH_BUDGET_BASELINE_PROD_MAX_FILE_PATH}"

    failed=0

    if (( SERVICE_ROUTE_COUNT > ARCH_BUDGET_BASELINE_SERVICE_ROUTE_COUNT )); then
      if exception_path="$(metric_exception_approved "service_route_count")"; then
        echo "budget exception applied for service_route_count via ${exception_path}"
      else
        echo "architecture budget failed: service route count grew (${SERVICE_ROUTE_COUNT} > ${ARCH_BUDGET_BASELINE_SERVICE_ROUTE_COUNT})" >&2
        failed=1
      fi
    fi

    if (( PROD_MAX_FILE_BYTES > ARCH_BUDGET_BASELINE_PROD_MAX_FILE_BYTES )); then
      if exception_path="$(metric_exception_approved "prod_max_file_bytes")"; then
        echo "budget exception applied for prod_max_file_bytes via ${exception_path}"
      else
        echo "architecture budget failed: production max file size grew (${PROD_MAX_FILE_BYTES} > ${ARCH_BUDGET_BASELINE_PROD_MAX_FILE_BYTES})" >&2
        failed=1
      fi
    fi

    if ! check_allow_suppression_budget; then
      failed=1
    fi

    if (( failed != 0 )); then
      exit 1
    fi

    echo "architecture budget gate passed"
    ;;
  *)
    echo "usage: scripts/architecture-budget-gate.sh [check|snapshot]" >&2
    exit 2
    ;;
esac
