#!/usr/bin/env python3
"""Keep bench run output in a bucket and a small sha256 manifest in git.

Captures (mp4, png, wav.gz), record archives (tar.gz) and large reports
from `bench/` runs live in a private bucket, one object per content hash
(`gs://openagents-bench-artifacts/sha256/<hex>`). Objects are never
overwritten or deleted. Each run directory keeps:

* `bench-artifacts.json`, the manifest: every offloaded file's path
  (relative to the run directory), byte count, and sha256.
* a `.gitignore` block naming those files, so a restored or freshly
  written copy never lands in git again.

Commands (gcloud must be authenticated; agents on the owner's Mac prefix
`CLOUDSDK_CONFIG=/Users/christopherdavid/work/.secrets/gcloud-sa-config`):

    scripts/bench-artifacts.py push RUN_DIR...   upload a run's captures and
                                                 large files, write manifest
    scripts/bench-artifacts.py restore [PATH...] download every manifest file
                                                 under PATH (default bench/)
    scripts/bench-artifacts.py verify [PATH...]  check every manifest entry
                                                 exists in the bucket
                                                 (--download re-hashes them)

`push` keeps the local files; it only uploads them and makes git ignore
them. Nothing here deletes a local file or a bucket object.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BUCKET = "gs://openagents-bench-artifacts"
PREFIX = "sha256/"
MANIFEST = "bench-artifacts.json"
SCHEMA = 1
MIN_BYTES = 1024 * 1024
# Captures and archives move regardless of size.
MEDIA = (
    ".mp4", ".webm", ".mov", ".png", ".jpg", ".jpeg", ".gif", ".wav",
    ".gz", ".tgz", ".zip", ".npy",
)
BEGIN = "# bench-artifacts: begin (generated by scripts/bench-artifacts.py)"
END = "# bench-artifacts: end"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def gcloud(*args: str, stdin: str | None = None) -> str:
    out = subprocess.run(
        ["gcloud", "storage", *args], input=stdin, text=True,
        capture_output=True,
    )
    if out.returncode != 0:
        raise SystemExit(f"gcloud storage {args[0]} failed:\n{out.stderr.strip()}")
    return out.stdout


def remote_sizes(bucket: str) -> dict[str, int]:
    """Every stored object's hash and size."""
    out = subprocess.run(
        ["gcloud", "storage", "ls", "-l", f"{bucket}/{PREFIX}"],
        text=True, capture_output=True,
    )
    if out.returncode != 0:
        if "matched no objects" in out.stderr or "One or more URLs matched no objects" in out.stderr:
            return {}
        raise SystemExit(f"gcloud storage ls failed:\n{out.stderr.strip()}")
    sizes = {}
    for line in out.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[-1].startswith(f"{bucket}/{PREFIX}"):
            sizes[parts[-1].rsplit("/", 1)[1]] = int(parts[0])
    return sizes


def load(manifest: Path) -> dict:
    data = json.loads(manifest.read_text())
    if data.get("schema_version") != SCHEMA:
        raise SystemExit(f"{manifest}: unsupported schema")
    for rel, rec in data["files"].items():
        if rel.startswith("/") or ".." in Path(rel).parts:
            raise SystemExit(f"{manifest}: unsafe path {rel!r}")
        if not re.fullmatch(r"[0-9a-f]{64}", rec["sha256"]):
            raise SystemExit(f"{manifest}: bad digest for {rel}")
    return data


def manifests(paths: list[str]) -> list[Path]:
    found = []
    for p in paths or ["bench"]:
        p = (REPO / p) if not os.path.isabs(p) else Path(p)
        if p.is_file() and p.name == MANIFEST:
            found.append(p)
        elif p.is_dir():
            found.extend(sorted(p.rglob(MANIFEST)))
        else:
            # A path inside a run: walk up to its manifest.
            for parent in p.parents:
                if (parent / MANIFEST).is_file():
                    found.append(parent / MANIFEST)
                    break
    return sorted(set(found))


def eligible(path: Path, min_bytes: int, large_only: bool = False) -> bool:
    if path.name in (MANIFEST, ".gitignore"):
        return False
    if path.stat().st_size > min_bytes:
        return True
    return not large_only and path.name.lower().endswith(MEDIA)


def ignore_line(rel: str) -> str:
    return "/" + re.sub(r"([\\*?\[\]!# ])", r"\\\1", rel)


def write_gitignore(run: Path, rels: list[str]) -> None:
    gi = run / ".gitignore"
    text = gi.read_text() if gi.exists() else ""
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1] if END in rest else ""
        text = head.rstrip("\n") + ("\n" if head.strip() else "") + tail.lstrip("\n")
    block = "\n".join([BEGIN, *(ignore_line(r) for r in sorted(rels)), END])
    gi.write_text((text.rstrip("\n") + "\n\n" if text.strip() else "") + block + "\n")


def stage(files: dict[str, Path], stage_dir: Path) -> None:
    for digest, src in files.items():
        dst = stage_dir / digest
        try:
            os.link(src, dst)
        except OSError:
            shutil.copyfile(src, dst)


def push(args) -> None:
    bucket = args.bucket
    runs: dict[Path, list[Path]] = {}
    for run in args.runs:
        run = Path(run).resolve()
        if not run.is_dir():
            raise SystemExit(f"{run}: not a directory")
        chosen = [p for p in sorted(run.rglob("*")) if p.is_file() and not p.is_symlink()
                  and ".git" not in p.parts and eligible(p, args.min_bytes, args.large_only)]
        runs[run] = chosen
    if args.files_from:
        # Explicit files: each is assigned to the run directory given with it.
        for line in Path(args.files_from).read_text().splitlines():
            if not line.strip():
                continue
            run_s, file_s = line.split("\t")
            runs.setdefault((REPO / run_s).resolve(), []).append((REPO / file_s).resolve())
    plan = []  # (run, rel, digest, size, path)
    for run, files in runs.items():
        for f in files:
            plan.append((run, f.relative_to(run).as_posix(), sha256(f), f.stat().st_size, f))
    if not plan:
        print("bench-artifacts: nothing to push")
        return
    have = remote_sizes(bucket)
    todo = {d: p for _, _, d, _, p in plan if d not in have}
    print(f"bench-artifacts: {len(plan)} files, {sum(s for *_, s, _ in plan)} bytes; "
          f"{len(todo)} new objects to upload")
    if todo:
        base = REPO / "target" if (REPO / "target").is_dir() else None
        with tempfile.TemporaryDirectory(prefix="bench-artifacts-", dir=base) as tmp:
            stage(todo, Path(tmp))
            gcloud("cp", "--no-clobber", "--quiet", f"{tmp}/*", f"{bucket}/{PREFIX}")
        have = remote_sizes(bucket)
    for _, rel, d, size, _ in plan:
        if have.get(d) != size:
            raise SystemExit(f"bench-artifacts: {rel} ({d}) is not in the bucket at {size} bytes")
    for run in runs:
        entries = [(rel, d, size) for r, rel, d, size, _ in plan if r == run]
        if not entries:
            continue
        mf = run / MANIFEST
        data = load(mf) if mf.exists() else {
            "schema_version": SCHEMA, "bucket": bucket, "object": PREFIX + "<sha256>",
            "restore": "scripts/bench-artifacts.py restore " + run.relative_to(REPO).as_posix(),
            "files": {},
        }
        for rel, d, size in entries:
            data["files"][rel] = {"bytes": size, "sha256": d}
        data["files"] = dict(sorted(data["files"].items()))
        mf.write_text(json.dumps(data, indent=1) + "\n")
        write_gitignore(run, list(data["files"]))
        print(f"bench-artifacts: {mf.relative_to(REPO)} ({len(data['files'])} files)")


def wanted(paths: list[str]) -> list[tuple[Path, str, dict, str]]:
    rows = []
    for mf in manifests(paths):
        data = load(mf)
        for rel, rec in data["files"].items():
            rows.append((mf.parent / rel, rel, rec, data.get("bucket", BUCKET)))
    return rows


_TOKEN: list[str] = []


def token() -> str:
    """An access token from the active gcloud account; never printed."""
    if not _TOKEN:
        out = subprocess.run(["gcloud", "auth", "print-access-token"],
                             text=True, capture_output=True)
        if out.returncode != 0:
            raise SystemExit("bench-artifacts: gcloud has no usable credentials")
        _TOKEN.append(out.stdout.strip())
    return _TOKEN[0]


def fetch(bucket: str, digest: str, dest: Path | None) -> str:
    """Stream one object, returning its sha256; write it to dest if given."""
    name = bucket.removeprefix("gs://")
    url = (f"https://storage.googleapis.com/storage/v1/b/{name}/o/"
           f"{urllib.parse.quote(PREFIX + digest, safe='')}?alt=media")
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token()}"})
    h = hashlib.sha256()
    out = None
    tmp = None
    if dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        tmp = dest.with_name(dest.name + ".bench-artifacts-part")
        out = tmp.open("wb")
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            for chunk in iter(lambda: resp.read(1 << 20), b""):
                h.update(chunk)
                if out:
                    out.write(chunk)
    finally:
        if out:
            out.close()
    got = h.hexdigest()
    if tmp is not None:
        if got == digest:
            os.replace(tmp, dest)
        else:
            tmp.unlink()
    return got


def fetch_all(jobs: list[tuple[str, str, Path | None]]) -> list[str]:
    """Fetch (bucket, digest, dest) jobs in parallel; returns the failures."""
    failures = []
    done = 0
    with ThreadPoolExecutor(max_workers=8) as pool:
        futures = {pool.submit(fetch, b, d, p): (d, p) for b, d, p in jobs}
        for fut in as_completed(futures):
            d, p = futures[fut]
            done += 1
            try:
                if fut.result() != d:
                    failures.append(f"content does not match sha256 {d} ({p or 'object'})")
            except Exception as exc:  # noqa: BLE001 - reported, not hidden
                failures.append(f"fetch of {d} failed: {exc}")
            if done % 100 == 0:
                print(f"bench-artifacts: {done}/{len(jobs)} fetched", flush=True)
    return failures


def restore(args) -> None:
    rows = wanted(args.paths)
    missing = []
    for path, rel, rec, bucket in rows:
        if path.is_file() and path.stat().st_size == rec["bytes"] and (
            args.fast or sha256(path) == rec["sha256"]):
            continue
        missing.append((bucket, rec["sha256"], path))
    print(f"bench-artifacts: {len(rows)} files listed, {len(missing)} to fetch", flush=True)
    failures = fetch_all(missing)
    for f in failures:
        print(f, file=sys.stderr)
    if failures:
        raise SystemExit(1)
    print("bench-artifacts: restored")


def verify(args) -> None:
    rows = wanted(args.paths)
    bad = 0
    for bucket in {b for *_, b in rows}:
        have = remote_sizes(bucket)
        sub = [(p, r) for p, _, r, b in rows if b == bucket]
        for path, rec in sub:
            if have.get(rec["sha256"]) != rec["bytes"]:
                bad += 1
                print(f"missing or wrong size in bucket: {path.relative_to(REPO)}")
        if args.download:
            # Stream every object and re-hash it; nothing touches disk.
            digests = sorted({r["sha256"] for _, r in sub})
            failures = fetch_all([(bucket, d, None) for d in digests])
            for f in failures:
                print(f)
            bad += len(failures)
    print(f"bench-artifacts: {len(rows)} files checked, {bad} problems")
    if bad:
        raise SystemExit(1)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("push", help="upload a run's captures and large files")
    p.add_argument("runs", nargs="*")
    p.add_argument("--min-bytes", type=int, default=MIN_BYTES)
    p.add_argument("--large-only", action="store_true",
                   help="only files over --min-bytes, not small captures")
    p.add_argument("--bucket", default=BUCKET)
    p.add_argument("--files-from", help="TSV of RUN_DIR<TAB>FILE, repo-relative")
    p.set_defaults(fn=push)
    r = sub.add_parser("restore", help="download manifest files under PATH")
    r.add_argument("paths", nargs="*")
    r.add_argument("--fast", action="store_true", help="trust files whose size matches")
    r.set_defaults(fn=restore)
    v = sub.add_parser("verify", help="check manifest entries against the bucket")
    v.add_argument("paths", nargs="*")
    v.add_argument("--download", action="store_true", help="download and re-hash every object")
    v.set_defaults(fn=verify)
    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
