/**
 * Allowlist for scripts/bun-api-perimeter-scan.ts (BUN-1, openagents#8779).
 *
 * Two tiers:
 *
 * - `bunApiPerimeter` — the NAMED Bun perimeter: files that are allowed to
 *   touch Bun-specific APIs on purpose, each with a reviewed reason. This
 *   list should stay short; it is where a future runtime move would look
 *   first.
 * - `bunApiGrandfathered` — every production source file that already used
 *   `bun:*` imports or `Bun.*` APIs when the seam landed (2026-07-13). This
 *   is a BURN-DOWN list: entries should only ever be REMOVED (as files move
 *   onto seams like @openagentsinc/sqlite-runtime) or, rarely, promoted to
 *   `bunApiPerimeter` with a reason. Adding a new grandfathered entry to
 *   bless fresh Bun usage defeats the containment gate and must not pass
 *   review. Regenerate for burn-down maintenance with:
 *   `bun scripts/bun-api-perimeter-scan.ts --emit-allowlist`.
 */

export type BunApiCategory = "bun-import" | "bun-global"

export type BunApiPerimeterEntry = {
  readonly path: string
  readonly category: BunApiCategory
  readonly reason: string
}

export type BunApiGrandfatheredEntry = {
  readonly path: string
  readonly categories: readonly BunApiCategory[]
}

export const bunApiPerimeter = [
  {
    category: "bun-global",
    path: "apps/pylon/src/harness-mcp-server.ts",
    reason:
      "Named Bun perimeter: the FEED-1 per-session harness MCP server (c7044f5a28) — a loopback-only Bun.serve on 127.0.0.1 gated by a minted per-session bearer credential. Landed after the 2026-07-13 grandfather freeze; the Pylon Bun app has no dual-runtime HTTP-serve seam yet, so this is the reviewed serve boundary for wrapped-harness MCP.",
  },
  {
    category: "bun-import",
    path: "packages/sqlite-runtime/src/bun-database.ts",
    reason:
      "Named Bun perimeter: the bun:sqlite client of the dual-runtime SQLite seam (#8779). All production embedded-SQLite access routes through this seam.",
  },
] satisfies readonly BunApiPerimeterEntry[]

export const bunApiGrandfathered = [
  { path: "apps/aiur/src/cloudrun/server.ts", categories: ["bun-global"] },
  { path: "apps/khala-capture/src/server.ts", categories: ["bun-global"] },
  { path: "apps/khala-live-hub/src/scope-hub.ts", categories: ["bun-import"] },
  { path: "apps/khala-live-hub/src/server.ts", categories: ["bun-global", "bun-import"] },
  { path: "apps/oa-queue-worker/src/main.ts", categories: ["bun-global"] },
  { path: "apps/oa-updates/scripts/e2e-local.ts", categories: ["bun-global"] },
  { path: "apps/oa-updates/scripts/e2e-real-export.ts", categories: ["bun-global"] },
  { path: "apps/oa-updates/scripts/publish-desktop-release.ts", categories: ["bun-global"] },
  { path: "apps/oa-updates/scripts/publish-pylon-release.ts", categories: ["bun-global"] },
  { path: "apps/oa-updates/src/serve.ts", categories: ["bun-global"] },
  { path: "apps/oa-updates/src/server.ts", categories: ["bun-global"] },
  { path: "apps/openagents-audio-edge/src/cloudrun.ts", categories: ["bun-global"] },
  { path: "apps/openagents-audio/scripts/live-barge-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents-audio/scripts/live-microphone-long-fault-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents-audio/scripts/live-microphone-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents-audio/scripts/live-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents-audio/scripts/live-tts-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents-audio/src/cloud-sql.ts", categories: ["bun-import"] },
  { path: "apps/openagents-audio/src/server.ts", categories: ["bun-global", "bun-import"] },
  { path: "apps/openagents-desktop/scripts/build.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/scripts/local-turn-restart-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/scripts/prepare-macos-maker.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/scripts/publish-release.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/scripts/release-preflight.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/scripts/run-live-proof.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/scripts/run-mvp-proof.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/scripts/run-release-acceptance.ts", categories: ["bun-global"] },
  { path: "apps/openagents-desktop/src/codex-history.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/apps/start/cloudrun/server.mjs", categories: ["bun-global"] },
  { path: "apps/openagents.com/scripts/backlog-faucet-list.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/scripts/gym-harbor-full-trace-archive.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/services/mdk-tips-buffer/scripts/smoke.mjs", categories: ["bun-global"] },
  { path: "apps/openagents.com/services/mdk-treasury/scripts/smoke.mjs", categories: ["bun-global"] },
  { path: "apps/openagents.com/services/mdk-treasury/src/spark-bun-storage.ts", categories: ["bun-import"] },
  { path: "apps/openagents.com/workers/api/scripts/agent-readiness-fleet-report-run.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/scripts/cs336-a1-real-gradient.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/scripts/khala-glm-fleet-durability.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/scripts/khala-glm-nvfp4-pilot.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/scripts/nip90-compute-live-buy-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/scripts/portal-browser-smoke.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/scripts/tassadar-trace-factory-generate-w3.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/src/cloudrun/forum-ui.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/src/cloudrun/portal-ui.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/src/cloudrun/preload.ts", categories: ["bun-import"] },
  { path: "apps/openagents.com/workers/api/src/cloudrun/server.ts", categories: ["bun-global"] },
  { path: "apps/openagents.com/workers/api/src/product-promises.ts", categories: ["bun-global"] },
  { path: "apps/pylon/deploy/agent-computer/portable-session-control.ts", categories: ["bun-global"] },
  { path: "apps/pylon/packages/runtime/src/backends/apple-fm/tools.ts", categories: ["bun-global"] },
  { path: "apps/pylon/packages/runtime/src/cli.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/claude-agent-task-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/claude-owner-local-permission-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/codex-agent-task-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/concurrent-checkout-proof.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/dev-proof-run.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/drive-accepted-labor-job.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/drive-labor-chain.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/multi-session-run.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/nip90-provider-loop-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/nip90-provider-serve.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/overnight-proof-run.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/rc-presence-test.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/recover-assignment-prs.ts", categories: ["bun-global"] },
  { path: "apps/pylon/scripts/stranger-probe-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/account-connect.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/assignment.ts", categories: ["bun-global", "bun-import"] },
  { path: "apps/pylon/src/auth.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/blueprint-gates/fleet-liveness.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/claude-agent-task-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/claude-composer.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/codex-agent-executor.ts", categories: ["bun-global", "bun-import"] },
  { path: "apps/pylon/src/codex-agent-task-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/codex-composer.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/codex-direct-local-usage-reporter.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/codex-pr-publisher.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/dev-doctor.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/dev-loop.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/fleet-run-live-smoke.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/forge-verification-runner.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/harness-mcp-server.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/index.ts", categories: ["bun-global", "bun-import"] },
  { path: "apps/pylon/src/khala-mcp.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/labor-market.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/labor.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/mixed-harness-fleet-run-smoke.ts", categories: ["bun-import"] },
  { path: "apps/pylon/src/node/apple-fm-bridge-launcher.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/node/composer-store.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/node/control-cli.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/node/control-server.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/node/control-sessions.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/node/deploy-cloud.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/node/keybinds.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/node/log-persist.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/opencode-run.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/orchestration/fleet-run-owned-capacity.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/orchestration/fleet-run-owned-grok-runner.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/orchestration/fleet-run-runtime.ts", categories: ["bun-import"] },
  { path: "apps/pylon/src/orchestration/runtime-intent-enforcement.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/orchestration/runtime-intent-supervisor.ts", categories: ["bun-global", "bun-import"] },
  { path: "apps/pylon/src/orchestration/store.ts", categories: ["bun-import"] },
  { path: "apps/pylon/src/orchestration/supervisor-state.ts", categories: ["bun-global", "bun-import"] },
  { path: "apps/pylon/src/portable-session-checkpoint-artifact.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/portable-session-local-rehydrator.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/portable-session-operation-ledger.ts", categories: ["bun-import"] },
  { path: "apps/pylon/src/portable-session-target.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/pylon-services.ts", categories: ["bun-global"] },
  { path: "apps/pylon/src/spark-bun-storage.ts", categories: ["bun-import"] },
  { path: "apps/pylon/src/wallet.ts", categories: ["bun-global"] },
  { path: "apps/qa-runner/scripts/build.ts", categories: ["bun-global"] },
  { path: "apps/qa-runner/src/api-server.ts", categories: ["bun-global"] },
  { path: "apps/qa-runner/src/distiller.ts", categories: ["bun-import"] },
  { path: "clients/khala-mobile/tests/support/rn-test-environment.ts", categories: ["bun-import"] },
  { path: "packages/assurance-spec/src/cli.ts", categories: ["bun-global"] },
  { path: "packages/durable-stream/src/test-server.ts", categories: ["bun-global"] },
  { path: "packages/grok-harness/src/mock-acp-server.ts", categories: ["bun-global"] },
  { path: "packages/grok-harness/src/worker-executor.ts", categories: ["bun-global"] },
  { path: "packages/harness-conformance/src/runner.ts", categories: ["bun-import"] },
  { path: "packages/khala-qa-harness/src/architect-coder-judge-live-smoke.ts", categories: ["bun-global"] },
  { path: "packages/khala-qa-harness/src/bless-ios-mobile-visual-baselines.ts", categories: ["bun-global"] },
  { path: "packages/khala-qa-harness/src/desktop-smoke-helpers.ts", categories: ["bun-global"] },
  { path: "packages/khala-sync-client/src/store-semantics.testkit.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-agent-runtime-remainder.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-agent-runtime.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-artanis.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-billing.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-business.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-crm-email.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-forge.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-forum-content.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-forum-remainder.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-gym-evals.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-identity-auth.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-inference-entitlements.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-khala-code-product-state.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-pylon-control-plane.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-pylon.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-sites-content.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-supervision-longtail.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-token-ledger.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-training.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/backfill-treasury.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/scripts/compact.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/src/capture.ts", categories: ["bun-import"] },
  { path: "packages/khala-sync-server/src/migrate.ts", categories: ["bun-import"] },
  { path: "packages/khala-tools/src/glob.ts", categories: ["bun-global"] },
  { path: "packages/khala-tools/src/grep.ts", categories: ["bun-global"] },
  { path: "packages/khala-tools/src/mcp.ts", categories: ["bun-global"] },
  { path: "packages/khala-tools/src/process-sandbox-macos.ts", categories: ["bun-global"] },
  { path: "packages/oa-infra/src/conformance/blob-store.ts", categories: ["bun-import"] },
  { path: "packages/oa-infra/src/conformance/durable-stream.ts", categories: ["bun-import"] },
  { path: "packages/oa-infra/src/conformance/job-queue.ts", categories: ["bun-import"] },
  { path: "packages/oa-infra/src/conformance/kv-store.ts", categories: ["bun-import"] },
  { path: "packages/oa-infra/src/conformance/mutex.ts", categories: ["bun-import"] },
  { path: "packages/oa-infra/src/job-queue-postgres.ts", categories: ["bun-import"] },
  { path: "packages/oa-infra/src/migrate.ts", categories: ["bun-import"] },
  { path: "packages/oa-infra/src/sql.ts", categories: ["bun-import"] },
  { path: "packages/probe/packages/runtime/scripts/generate-openagents-study-packet.ts", categories: ["bun-global"] },
  { path: "packages/probe/packages/runtime/src/backends/apple-fm/tools.ts", categories: ["bun-global"] },
  { path: "packages/probe/packages/runtime/src/cli.ts", categories: ["bun-global"] },
  { path: "packages/product-spec/src/cli.ts", categories: ["bun-global"] },
  { path: "packages/pylon-core/src/custody/account-connect.ts", categories: ["bun-global"] },
  { path: "packages/pylon-core/src/custody/account-usage.ts", categories: ["bun-global"] },
  { path: "packages/pylon-core/src/executor/claude-agent-executor.ts", categories: ["bun-global", "bun-import"] },
  { path: "packages/pylon-core/src/executor/claude-agent.ts", categories: ["bun-global"] },
  { path: "packages/pylon-core/src/executor/claude-second-pass-reviewer.ts", categories: ["bun-global"] },
  { path: "packages/pylon-core/src/executor/codex-agent.ts", categories: ["bun-global"] },
  { path: "packages/pylon-core/src/executor/workspace-materializer.ts", categories: ["bun-global"] },
  { path: "packages/pylon-core/src/shared/inventory.ts", categories: ["bun-global"] },
] satisfies readonly BunApiGrandfatheredEntry[]
