#!/usr/bin/env bash

set -euo pipefail

build_flag="--release"
target_dir="release"
open_result=false
local_install=false
can_code_sign=false

IDENTITY="${MACOS_SIGNING_IDENTITY:-Developer ID Application: OpenAgents, Inc. (HQWSG26L43)}"

help_info() {
  echo "
Usage: ${0##*/} [options] [architecture=host]
Build the application bundle for macOS.

Options:
  -d    Compile in debug mode
  -o    Open dir with the resulting DMG or launch the app itself in local mode.
  -i    Install the resulting DMG into /Applications.
  -h    Display this help and exit.
  "
}

while getopts 'dloh' flag
 do
    case "${flag}" in
        o) open_result=true;;
        d)
            export CARGO_INCREMENTAL=true
            export CARGO_BUNDLE_SKIP_BUILD=true
            build_flag=""
            target_dir="debug"
            ;;
        i) local_install=true;;
        h)
           help_info
           exit 0
           ;;
    esac
 done

shift $((OPTIND-1))

export AUTOPILOT_BUNDLE=true

cargo_bundle_version=$(cargo -q bundle --help 2>&1 | head -n 1 || echo "")
if [ "$cargo_bundle_version" != "cargo-bundle v0.6.1-zed" ]; then
    cargo install cargo-bundle --git https://github.com/zed-industries/cargo-bundle.git --branch zed-deploy
fi

# Deal with versions of macOS that don't include libstdc++ headers
export CXXFLAGS="-stdlib=libc++"

version_info=$(rustc --version --verbose)
host_line=$(echo "$version_info" | grep host)
target_triple=${host_line#*: }
if [[ $# -gt 0 && -n "$1" ]]; then
    target_triple="$1"
fi
arch_suffix=""

if [[ "$target_triple" = "x86_64-apple-darwin" ]]; then
    arch_suffix="x86_64"
elif [[ "$target_triple" = "aarch64-apple-darwin" ]]; then
    arch_suffix="aarch64"
else
    echo "Unsupported architecture $target_triple"
    exit 1
fi

rustup target add $target_triple

echo "Compiling autopilot-desktop"
cargo build ${build_flag} --package autopilot-desktop --target $target_triple

echo "Creating application bundle"
pushd apps/autopilot-desktop
app_path=$(cargo bundle ${build_flag} --target $target_triple --format osx | head -n 1 | xargs)
popd

echo "Bundled ${app_path}"

if [[ -n "${MACOS_CERTIFICATE:-}" && -n "${MACOS_CERTIFICATE_PASSWORD:-}" && -n "${APPLE_NOTARIZATION_KEY:-}" && -n "${APPLE_NOTARIZATION_KEY_ID:-}" && -n "${APPLE_NOTARIZATION_ISSUER_ID:-}" ]]; then
    can_code_sign=true

    echo "Setting up keychain for code signing..."
    security create-keychain -p "$MACOS_CERTIFICATE_PASSWORD" autopilot.keychain || echo ""
    security default-keychain -s autopilot.keychain
    security unlock-keychain -p "$MACOS_CERTIFICATE_PASSWORD" autopilot.keychain
    # Calling set-keychain-settings without `-t` disables the auto-lock timeout
    security set-keychain-settings autopilot.keychain
    echo "$MACOS_CERTIFICATE" | base64 --decode > /tmp/autopilot-certificate.p12
    security import /tmp/autopilot-certificate.p12 -k autopilot.keychain -P "$MACOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
    rm /tmp/autopilot-certificate.p12
    security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CERTIFICATE_PASSWORD" autopilot.keychain

    function cleanup() {
        echo "Cleaning up keychain"
        security default-keychain -s login.keychain
        security delete-keychain autopilot.keychain
    }

    trap cleanup EXIT
fi

function sign_app_bundle() {
    if [[ $can_code_sign = true ]]; then
        echo "Code signing app bundle"
        /usr/bin/codesign --deep --force --timestamp --options runtime \
            --entitlements apps/autopilot-desktop/resources/autopilot.entitlements \
            --sign "$IDENTITY" "${app_path}" -v
    else
        echo "One or more of the following variables are missing: MACOS_CERTIFICATE, MACOS_CERTIFICATE_PASSWORD, APPLE_NOTARIZATION_KEY, APPLE_NOTARIZATION_KEY_ID, APPLE_NOTARIZATION_ISSUER_ID"
        echo "Unsigned bundle will be produced."
    fi

    bundle_name=$(basename "$app_path")

    if [ "$local_install" = true ]; then
        rm -rf "/Applications/$bundle_name"
        mv "$app_path" "/Applications/$bundle_name"
        echo "Installed application bundle: /Applications/$bundle_name"
        if [ "$open_result" = true ]; then
            echo "Opening /Applications/$bundle_name"
            open "/Applications/$bundle_name"
        fi
    elif [ "$open_result" = true ]; then
        open "$app_path"
    fi

    if [[ "$target_dir" = "debug" ]]; then
        echo "Debug build detected - skipping DMG creation and signing"
        if [ "$local_install" = false ]; then
            echo "Created application bundle:"
            echo "$app_path"
        fi
    else
        dmg_target_directory="target/${target_triple}/${target_dir}"
        dmg_source_directory="${dmg_target_directory}/dmg"
        dmg_file_path="${dmg_target_directory}/Autopilot-${arch_suffix}.dmg"
        xcode_bin_dir_path="$(xcode-select -p)/usr/bin"

        rm -rf ${dmg_source_directory}
        mkdir -p ${dmg_source_directory}
        mv "${app_path}" "${dmg_source_directory}"
        notarization_key_file=$(mktemp)

        echo "Adding symlink to /Applications to ${dmg_source_directory}"
        ln -s /Applications ${dmg_source_directory}

        echo "Creating final DMG at ${dmg_file_path} using ${dmg_source_directory}"
        hdiutil create -volname Autopilot -srcfolder "${dmg_source_directory}" -ov -format UDZO "${dmg_file_path}"

        echo "Removing symlink to /Applications from ${dmg_source_directory}"
        rm ${dmg_source_directory}/Applications

        if [[ -f scripts/terms/terms.json ]]; then
            echo "Adding license agreement to DMG"
            npm install --global dmg-license minimist
            dmg-license scripts/terms/terms.json "${dmg_file_path}"
        fi

        if [[ $can_code_sign = true ]]; then
            echo "Notarizing DMG with Apple"
            /usr/bin/codesign --deep --force --timestamp --options runtime --sign "$IDENTITY" "$(pwd)/${dmg_file_path}" -v
            echo "$APPLE_NOTARIZATION_KEY" > "$notarization_key_file"
            "${xcode_bin_dir_path}/notarytool" submit --wait --key "$notarization_key_file" --key-id "$APPLE_NOTARIZATION_KEY_ID" --issuer "$APPLE_NOTARIZATION_ISSUER_ID" "${dmg_file_path}"
            rm "$notarization_key_file"
            "${xcode_bin_dir_path}/stapler" staple "${dmg_file_path}"
        fi

        if [ "$open_result" = true ]; then
            open $dmg_target_directory
        fi
    fi
}

sign_app_bundle
