[package]
name = "codex-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.6", features = ["ws"] }
clap = { version = "4.5.50", features = ["derive", "env"] }
futures = "0.3.31"
libc = "0.2.169"
serde_json = "1.0.145"
shlex = "1.3.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "process", "io-std", "io-util", "net", "sync"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"] }
which = "8.0.0"
