// Generated by ts-rs (pretty formatted copy). Do not edit if you regenerate.
export type MessageRowTs = {
  id: bigint;
  thread_id: string;
  role: string | null;
  kind: string;
  text: string | null;
  item_id: string | null;
  partial: bigint | null;
  seq: bigint | null;
  ts: bigint;
  created_at: bigint;
  updated_at: bigint | null;
};

