// Generated by ts-rs (pretty formatted copy). Do not edit if you regenerate.
export type SyncWatchedDirTs = {
  provider: string;
  base: string;
  files: bigint;
  last_read: bigint;
};

export type SyncStatusTs = {
  enabled: boolean;
  two_way: boolean;
  watched: SyncWatchedDirTs[];
};

