//! The #9683 TB4 board: Microcoder on the pre-registered study's held-out
//! Terminal-Bench 4 tasks, rounds 2 to 4, against Fable 5.1 low's
//! cheapest winning run. So far it is a negative board: no held-out pass.
//!
//! The study committed no machine-readable file for its TB4 rounds; each
//! round's results are the tables its `report.py` generated into the
//! results page, under a `### Tables (generated by report.py --round rN)`
//! heading. This adapter reads only those generated tables (never the
//! page's prose): each held-out run, the Fable-fails pool's runs, the
//! faults, and the generated `So far` tallies. It recomputes every run's
//! cost and time win and refuses to build when that disagrees with the
//! row's own `Cost win` and `Time win` cells, when a row's bar disagrees
//! with the one computed from the public replays, or when the counted rows
//! disagree with the generated tallies.

use std::collections::BTreeMap;

use crate::contract::{
    Attempt, Bar, Benchmark, Board, BoardKind, Caveat, Cost, CostBasis, Label, Miss, Provenance,
    Reference, Spend, Split, Subject, Tally, TaskKnowledge, TaskRow, TaskStatus,
};
use crate::evidence::{Reader, Result, count, fail};

/// The board's identity.
pub const BOARD_ID: &str = "tb4-oos-microcoder-9683";

/// The results page whose generated tables are read.
pub const RESULTS: &str = "docs/terminal-bench/2026-09-26-out-of-sample-study-results.md";
const PRE_REGISTRATION: &str = "docs/terminal-bench/2026-09-26-out-of-sample-study.md";
/// The complete rounds. Round 1 was paused on a provider limit and has no
/// generated tables.
const ROUNDS: [&str; 3] = ["r2", "r3", "r4"];
const STUDIED: &str = "†";

/// One generated table: its header and rows, as trimmed cells.
struct Table {
    header: Vec<String>,
    rows: Vec<Vec<String>>,
}

impl Table {
    fn cell<'a>(&self, row: &'a [String], column: &str) -> Result<&'a str> {
        let i = self
            .header
            .iter()
            .position(|h| h == column)
            .ok_or_else(|| fail!("no column {column:?}"))?;
        row.get(i)
            .map(String::as_str)
            .ok_or_else(|| fail!("a row without {column:?}"))
    }
}

/// The table under `### <heading>` in `section`.
fn table(section: &str, heading: &str) -> Result<Table> {
    let start = section
        .lines()
        .position(|l| l.starts_with("### ") && l[4..].starts_with(heading))
        .ok_or_else(|| fail!("no table {heading:?}"))?;
    let lines: Vec<&str> = section
        .lines()
        .skip(start + 1)
        .skip_while(|l| !l.trim_start().starts_with('|'))
        .take_while(|l| l.trim_start().starts_with('|'))
        .collect();
    let split = |line: &str| -> Vec<String> {
        line.trim()
            .trim_matches('|')
            .split('|')
            .map(|c| c.trim().to_owned())
            .collect()
    };
    let header = lines
        .first()
        .map(|l| split(l))
        .ok_or_else(|| fail!("table {heading:?} is empty"))?;
    let rows = lines
        .iter()
        .skip(2)
        .map(|l| split(l))
        .filter(|r| r.first().is_some_and(|c| c != "(none)"))
        .collect();
    Ok(Table { header, rows })
}

/// A generated round section: from its tables heading to the next `## `.
fn section<'a>(page: &'a str, round: &str) -> Result<&'a str> {
    let heading = format!("### Tables (generated by `report.py --round {round}`)");
    let start = page
        .find(&heading)
        .ok_or_else(|| fail!("{RESULTS}: no generated tables for round {round}"))?;
    let end = page[start..]
        .find("\n## ")
        .map_or(page.len(), |i| start + i);
    Ok(&page[start..end])
}

/// The numbers of the generated `So far` line, in order.
fn so_far(section: &str, round: &str) -> Result<Vec<u32>> {
    let line = section
        .lines()
        .find(|l| l.starts_with("**So far:**"))
        .ok_or_else(|| fail!("round {round}: no generated tallies"))?;
    let numbers: Vec<u32> = line
        .split(|c: char| !c.is_ascii_digit())
        .filter(|w| !w.is_empty())
        .filter_map(|w| w.parse().ok())
        .collect();
    // passes, graded, cost wins, time wins, confirmed, pool passes, faults, running
    if numbers.len() != 8 {
        return Err(fail!("round {round}: can't read {line:?}"));
    }
    Ok(numbers)
}

/// `35:10` or `1:55:46` as seconds.
fn seconds(cell: &str) -> Option<f64> {
    let parts: Vec<f64> = cell
        .split(':')
        .map(|p| p.parse::<f64>().ok())
        .collect::<Option<_>>()?;
    match parts.as_slice() {
        [m, s] => Some(m * 60.0 + s),
        [h, m, s] => Some(h * 3600.0 + m * 60.0 + s),
        _ => None,
    }
}

/// `$0.3299`, `unknown`, or `unknown, $0.42 to $0.71 (upper bound, …)`.
fn cost(cell: &str) -> Option<Cost> {
    let dollars = |t: &str| t.trim().trim_start_matches('$').parse::<f64>().ok();
    if let Some(usd) = cell.strip_prefix('$').and_then(|_| dollars(cell)) {
        return Some(Cost::Reported { usd });
    }
    let rest = cell.strip_prefix("unknown")?;
    if rest.is_empty() {
        return Some(Cost::Unknown {
            lower_bound_usd: None,
            upper_bound_usd: None,
        });
    }
    let range = rest.trim_start_matches(',').split('(').next()?;
    let (low, high) = range.split_once(" to ")?;
    Some(Cost::Unknown {
        lower_bound_usd: Some(dollars(low)?),
        upper_bound_usd: Some(dollars(high)?),
    })
}

fn task_name(cell: &str) -> (String, bool) {
    let studied = cell.contains(STUDIED);
    (
        cell.replace(STUDIED, "")
            .trim()
            .trim_matches('`')
            .to_owned(),
        studied,
    )
}

/// A round's counts outside the held-out graded runs.
#[derive(Default)]
struct RoundNotes {
    pool_runs: u32,
    pool_passes: Vec<String>,
    faults: Vec<(String, String)>,
}

/// Builds the board.
pub fn build(reader: &Reader) -> Result<Board> {
    let (page, results_file) = reader.text(RESULTS)?;
    let (replays, replays_file) = reader.json(crate::tb4_delegate_dev::REPLAYS)?;
    let evidence = vec![
        results_file,
        reader.bytes(PRE_REGISTRATION)?.1,
        replays_file,
    ];

    let mut attempts = Vec::new();
    let mut bars: BTreeMap<String, Bar> = BTreeMap::new();
    let mut order: Vec<String> = Vec::new();
    let mut studied: BTreeMap<String, bool> = BTreeMap::new();
    let mut notes: Vec<(String, RoundNotes)> = Vec::new();
    for round in ROUNDS {
        let section = section(&page, round)?;
        let tallies = so_far(section, round)?;
        let number = round.trim_start_matches('r');
        let series = format!("round {number}");
        let held = table(section, "Held-out tasks: graded runs")?;
        let mut cost_wins = 0;
        let mut time_wins = 0;
        for row in &held.rows {
            let (task, was_studied) = task_name(held.cell(row, "Task")?);
            studied.insert(task.clone(), was_studied);
            if !bars.contains_key(&task) {
                let bar = crate::tb4_delegate_dev::bar_of(&replays, &task)?;
                order.push(task.clone());
                bars.insert(task.clone(), bar);
            }
            let bar = &bars[&task];
            check_bar(&held, row, &task, bar)?;
            let a = attempt(&held, row, &task, &series, round, bar)?;
            let time_win = a.beat && a.time_ratio.is_some_and(|t| t < 1.0);
            for (column, got) in [("Cost win", a.beat), ("Time win", time_win)] {
                let cell = held.cell(row, column)?;
                if cell.starts_with("yes") != got {
                    return Err(fail!(
                        "round {round} {task}: recomputed {column} {got} but the table says {cell:?}"
                    ));
                }
            }
            cost_wins += u32::from(a.beat);
            time_wins += u32::from(time_win);
            attempts.push(a);
        }
        let mine: Vec<&Attempt> = attempts.iter().filter(|a| a.series == series).collect();
        let pool = table(section, "Fable-fails pool")?;
        let mut round_notes = RoundNotes {
            pool_runs: count(pool.rows.len()),
            ..RoundNotes::default()
        };
        for row in &pool.rows {
            if pool.cell(row, "Result")? == "Pass" {
                round_notes
                    .pool_passes
                    .push(task_name(pool.cell(row, "Task")?).0);
            }
        }
        let faults = table(section, "Faults (not results)")?;
        for row in &faults.rows {
            if faults.cell(row, "Pool")? == "held-out" {
                round_notes.faults.push((
                    task_name(faults.cell(row, "Task")?).0,
                    faults.cell(row, "Detail")?.to_owned(),
                ));
            }
        }
        let counted = [
            count(mine.iter().filter(|a| a.passed).count()),
            count(mine.len()),
            cost_wins,
            time_wins,
            count(round_notes.pool_passes.len()),
            count(faults.rows.len()),
        ];
        let recorded = [
            tallies[0], tallies[1], tallies[2], tallies[3], tallies[5], tallies[6],
        ];
        if counted != recorded {
            return Err(fail!(
                "round {round}: counted (passes, graded, cost wins, time wins, pool passes, faults) {counted:?}, the generated tallies say {recorded:?}"
            ));
        }
        notes.push((series, round_notes));
    }

    let tasks: Vec<TaskRow> = order
        .iter()
        .map(|task| {
            let mine: Vec<&Attempt> = attempts.iter().filter(|a| &a.task == task).collect();
            let passes = count(mine.iter().filter(|a| a.passed).count());
            let beats = count(mine.iter().filter(|a| a.beat).count());
            TaskRow {
                task: task.clone(),
                bar: bars[task].clone(),
                knowledge: TaskKnowledge::OtherTasksOnly,
                attempts: mine.iter().map(|a| a.id.clone()).collect(),
                passes,
                beats,
                status: if beats > 0 {
                    TaskStatus::Beat
                } else if passes > 0 {
                    TaskStatus::PassedWithoutBeat
                } else {
                    TaskStatus::NeverPassed
                },
            }
        })
        .collect();

    let tally_of = |filter: &dyn Fn(&Attempt) -> bool, faults: u32| {
        let set: Vec<&Attempt> = attempts.iter().filter(|a| filter(a)).collect();
        Tally {
            attempts: count(set.len()),
            passes: count(set.iter().filter(|a| a.passed).count()),
            beats: count(set.iter().filter(|a| a.beat).count()),
            faults,
            cost_unknown: count(set.iter().filter(|a| a.cost.known().is_none()).count()),
        }
    };
    let splits: Vec<Split> = notes
        .iter()
        .map(|(series, n)| Split {
            name: series.clone(),
            tally: tally_of(&|a| &a.series == series, count(n.faults.len())),
        })
        .collect();
    let totals = tally_of(&|_| true, splits.iter().map(|s| s.tally.faults).sum());

    let reported_usd: f64 = attempts.iter().filter_map(|a| a.cost.known()).sum();
    let bound = |upper: bool| -> f64 {
        attempts
            .iter()
            .filter_map(|a| match a.cost {
                Cost::Unknown {
                    lower_bound_usd,
                    upper_bound_usd,
                } => {
                    if upper {
                        upper_bound_usd
                    } else {
                        lower_bound_usd
                    }
                }
                Cost::Reported { .. } => None,
            })
            .sum()
    };
    let bounded = attempts.iter().any(|a| {
        matches!(
            a.cost,
            Cost::Unknown {
                upper_bound_usd: Some(_),
                ..
            }
        )
    });
    let spend = Spend {
        basis: CostBasis::Mixed,
        reported_usd,
        estimated_lower_bound_usd: bounded.then(|| bound(false)),
        estimated_upper_bound_usd: bounded.then(|| bound(true)),
    };

    let per_round: Vec<String> = splits
        .iter()
        .map(|s| format!("{} of {} in {}", s.tally.passes, s.tally.attempts, s.name))
        .collect();
    let headline = if totals.passes == 0 {
        format!(
            "No held-out TB4 pass yet: {} of {} graded held-out runs passed across {} rounds ({}), so no cost win and no confirmed out-of-sample win.",
            totals.passes,
            totals.attempts,
            splits.len(),
            per_round.join(", ")
        )
    } else {
        format!(
            "Passed {} of {} graded held-out runs across {} rounds ({}); {} beat Fable 5.1 low's cheapest winning run.",
            totals.passes,
            totals.attempts,
            splits.len(),
            per_round.join(", "),
            totals.beats
        )
    };

    let caveats = caveats(&attempts, &tasks, &notes, &studied, &page);
    let mut labels = vec![
        Label::PreRegistered,
        Label::OutOfSample,
        Label::KnowledgeAssisted,
        Label::ReferenceOtherConditions,
    ];
    if attempts
        .iter()
        .any(|a| a.cost_basis == Some(CostBasis::ListPrice))
    {
        labels.push(Label::ListPrice);
    }
    if totals.cost_unknown > 0 {
        labels.push(Label::CostBound);
    }
    labels.sort();

    Ok(Board {
        id: BOARD_ID.into(),
        title: "Microcoder on TB4 held-out tasks, rounds 2 to 4".into(),
        benchmark: Benchmark {
            name: "Terminal-Bench".into(),
            version: "4.0".into(),
        },
        kind: BoardKind::CostBelowCheapestWin,
        question: "With knowledge only from the shared base, none of it written from these tasks, does Microcoder pass pre-registered held-out TB4 tasks for less than Fable 5.1 low's cheapest winning run, confirmed on at least 2 of 3 runs?".into(),
        headline,
        provenance: Provenance {
            issues: vec![9683, 9717, 9680],
            report: RESULTS.into(),
            frozen_commit: None,
            evidence,
        },
        subject: Subject {
            agent: "Microcoder".into(),
            arm: "on: --kb candidates, entries synced only from the relay".into(),
            model: "gpt-6-luna".into(),
            effort: None,
            artifact: None,
        },
        reference: Reference {
            name: "Fable 5.1 low".into(),
            rule: "A cost win is a pass whose known total cost (model, Jev, and embeddings) is below Fable 5.1 low's cheapest winning run on the task; a time win is a cost win that also finishes faster than its fastest win. A task is a confirmed out-of-sample win when at least 2 of its 3 knowledge-on runs are cost wins. On this board an unknown cost can't beat.".into(),
            conditions: "Fable 5.1 low's public Claude Code trials, on another host with each task's full timeout; its time is the trial's wall time and its cost the public record's.".into(),
        },
        labels,
        caveats,
        totals,
        splits,
        spend,
        tasks,
        attempts,
        reference_rows: Vec::new(),
        snapshot: None,
    })
}

/// The row's printed bar must be the one the replays give, to its
/// printed precision: dollars to the cent, time to the second.
fn check_bar(table: &Table, row: &[String], task: &str, bar: &Bar) -> Result<()> {
    let cost_cell = table.cell(row, "Fable low cheapest win")?;
    let time_cell = table.cell(row, "Fable low fastest win")?;
    let printed_cost = cost_cell
        .trim_start_matches('$')
        .parse::<f64>()
        .map_err(|_| fail!("{task}: can't read the bar {cost_cell:?}"))?;
    let printed_time =
        seconds(time_cell).ok_or_else(|| fail!("{task}: can't read the bar {time_cell:?}"))?;
    let (cost, time) = (
        bar.cost_usd.unwrap_or(f64::NAN),
        bar.seconds.unwrap_or(f64::NAN),
    );
    if (printed_cost - cost).abs() > 0.005 + 1e-9 || (printed_time - time).abs() > 1.0 {
        return Err(fail!(
            "{task}: the table's bar ({cost_cell}, {time_cell}) isn't the replays' ({cost}, {time} s)"
        ));
    }
    Ok(())
}

fn attempt(
    table: &Table,
    row: &[String],
    task: &str,
    series: &str,
    round: &str,
    bar: &Bar,
) -> Result<Attempt> {
    let result = table.cell(row, "Result")?;
    let passed = match result {
        "Pass" => true,
        "Fail" => false,
        other => {
            return Err(fail!(
                "round {round} {task}: result {other:?} isn't a grade"
            ));
        }
    };
    let time_cell = table.cell(row, "Time")?;
    let seconds =
        Some(seconds(time_cell).ok_or_else(|| fail!("{task}: can't read time {time_cell:?}"))?);
    let cost_cell = table.cell(row, "Cost")?;
    let cost = cost(cost_cell).ok_or_else(|| fail!("{task}: can't read cost {cost_cell:?}"))?;
    let cost_basis = match table.cell(row, "Cost basis")? {
        "billed" => Some(CostBasis::Billed),
        "list_price" => Some(CostBasis::ListPrice),
        other => return Err(fail!("{task}: cost basis {other:?}")),
    };
    let cheapest = bar.cost_usd.ok_or_else(|| fail!("{task}: no cost bar"))?;
    let mut misses = Vec::new();
    if !passed {
        misses.push(Miss::Failed);
    }
    match cost.known() {
        None => misses.push(Miss::CostUnknown),
        Some(c) if c >= cheapest => misses.push(Miss::Cost),
        Some(_) => {}
    }
    let beat = misses.is_empty();
    let (cost_ratio, cost_ratio_is_bound) = match cost {
        Cost::Reported { usd } => (Some(usd / cheapest), false),
        Cost::Unknown {
            lower_bound_usd, ..
        } => (lower_bound_usd.map(|l| l / cheapest), true),
    };
    let time_ratio = seconds.zip(bar.seconds).map(|(s, b)| s / b);
    let entries: u32 = table.cell(row, "Entries")?.parse().unwrap_or(0);
    let mut labels = vec![Label::OutOfSample];
    if table.cell(row, "Arm")? == "on" && entries > 0 {
        labels.push(Label::KnowledgeAssisted);
    }
    if cost_basis == Some(CostBasis::ListPrice) {
        labels.push(Label::ListPrice);
    }
    if cost.known().is_none() {
        labels.push(Label::CostBound);
    }
    labels.sort();
    Ok(Attempt {
        id: format!("{round}.{task}"),
        task: task.to_owned(),
        series: series.to_owned(),
        trial: format!("round {round}, {task}"),
        reward: Some(if passed { 1.0 } else { 0.0 }),
        passed,
        seconds,
        phases: None,
        cost,
        cost_ratio,
        cost_ratio_is_bound,
        time_ratio,
        beat,
        misses,
        labels,
        how_it_ended: Some(table.cell(row, "How it ended")?.to_owned()),
        jev: None,
        verifier: None,
        trace: None,
        cost_basis,
        caveats: Vec::new(),
    })
}

fn caveats(
    attempts: &[Attempt],
    tasks: &[TaskRow],
    notes: &[(String, RoundNotes)],
    studied: &BTreeMap<String, bool>,
    page: &str,
) -> Vec<Caveat> {
    let mut out = Vec::new();
    // Coverage: which held-out tasks each round graded, faulted, or left.
    let mut faulted: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for (series, n) in notes {
        for (task, detail) in &n.faults {
            faulted
                .entry(task.clone())
                .or_default()
                .push((series.clone(), detail.clone()));
        }
    }
    let graded_per_round: Vec<String> = notes
        .iter()
        .map(|(series, _)| {
            let n = attempts.iter().filter(|a| &a.series == series).count();
            format!("{n} in {series}")
        })
        .collect();
    let fault_text: Vec<String> = faulted
        .iter()
        .map(|(task, rounds)| {
            let names: Vec<&str> = rounds.iter().map(|(s, _)| s.as_str()).collect();
            let missing: Vec<&str> = notes
                .iter()
                .map(|(s, _)| s.as_str())
                .filter(|s| {
                    !names.contains(s)
                        && !attempts.iter().any(|a| a.series == *s && &a.task == task)
                })
                .collect();
            format!(
                "{task} was a fault in {}, where {}{}",
                names.join(" and "),
                rounds[0].1,
                if missing.is_empty() {
                    String::new()
                } else {
                    format!(", and wasn't run in {}", missing.join(" or "))
                }
            )
        })
        .collect();
    out.push(Caveat {
        code: "coverage".into(),
        text: format!(
            "{} held-out tasks were graded ({}). {}. Faults aren't results and aren't in the denominators.",
            tasks.len(),
            graded_per_round.join(", "),
            if fault_text.is_empty() {
                "No held-out run was a fault".to_owned()
            } else {
                fault_text.join("; ")
            }
        ),
    });
    let studied_n = tasks
        .iter()
        .filter(|t| studied.get(&t.task).copied().unwrap_or(false))
        .count();
    // The results page's generated notes name burned tasks.
    let burned: Vec<String> = page
        .lines()
        .filter(|l| l.starts_with("- `") && l.contains("` is burned"))
        .filter_map(|l| l.split('`').nth(1).map(str::to_owned))
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    out.push(Caveat {
        code: "exclusions".into(),
        text: format!(
            "{studied_n} of the {} graded held-out tasks were studied by earlier harnesses (marked † in the results); a reader can drop them. {}",
            tasks.len(),
            if burned.is_empty() {
                "No task is burned.".to_owned()
            } else {
                format!(
                    "Burned and left out of the held-out pool: {} (its runs are in-sample).",
                    burned.join(", ")
                )
            }
        ),
    });
    let pool_runs: u32 = notes.iter().map(|(_, n)| n.pool_runs).sum();
    let pool_passes: Vec<String> = notes
        .iter()
        .flat_map(|(series, n)| {
            n.pool_passes
                .iter()
                .map(move |t| format!("{t} in {series}"))
        })
        .collect();
    out.push(Caveat {
        code: "fable_fails_pool".into(),
        text: format!(
            "Not on this board: the Fable-fails pool, tasks Fable 5.1 low never passed, where a pass beats Fable outright once a second pass confirms it. {} of its {pool_runs} graded runs passed{}.",
            pool_passes.len(),
            if pool_passes.is_empty() {
                String::new()
            } else {
                format!(" ({})", pool_passes.join(", "))
            }
        ),
    });
    out.push(Caveat {
        code: "upper_bound_rule".into(),
        text: format!(
            "The study also counts a pass whose cost is partly unknown as a cost win when its upper bound is under the bar. This board never counts an unknown cost as a beat, and would refuse to build if a table's win rested on a bound; {} held-out runs passed, so none does.",
            attempts.iter().filter(|a| a.passed).count()
        ),
    });
    out.push(Caveat {
        code: "round_1".into(),
        text: "Round 1 was paused by a provider usage limit before it finished and has no generated tables, so it isn't on this board.".into(),
    });
    out.push(Caveat {
        code: "source".into(),
        text: "The study committed no machine-readable file for its TB4 rounds. This board reads the tables report.py generated into the results page, never its prose, and checks every row's verdict and bar and each round's generated tallies.".into(),
    });
    out.push(Caveat {
        code: "no_traces".into(),
        text: "The rounds' run records aren't retained in the repository, so these attempts have no trace bundles.".into(),
    });
    let by_basis = |b: CostBasis| attempts.iter().filter(|a| a.cost_basis == Some(b)).count();
    out.push(Caveat {
        code: "cost_basis".into(),
        text: format!(
            "{} runs' costs are what OpenRouter billed and {} are GPT-6 Luna's list price for the tokens the Codex login reported, not a bill; each row says which. Time is Microcoder's loop time; Fable 5.1 low's is the trial's wall time.",
            by_basis(CostBasis::Billed),
            by_basis(CostBasis::ListPrice)
        ),
    });
    out
}

#[cfg(test)]
mod tests {
    use super::{cost, seconds};
    use crate::contract::Cost;

    #[test]
    fn generated_cells_parse() {
        assert_eq!(seconds("35:10"), Some(2110.0));
        assert_eq!(seconds("1:55:46"), Some(6946.0));
        assert_eq!(seconds("—"), None);
        assert_eq!(cost("$0.3299"), Some(Cost::Reported { usd: 0.3299 }));
        assert_eq!(
            cost("unknown"),
            Some(Cost::Unknown {
                lower_bound_usd: None,
                upper_bound_usd: None
            })
        );
        assert_eq!(
            cost("unknown, $0.4242 to $0.7137 (upper bound, reconstructed)"),
            Some(Cost::Unknown {
                lower_bound_usd: Some(0.4242),
                upper_bound_usd: Some(0.7137)
            })
        );
        assert_eq!(cost("n/a"), None);
    }
}
