[package]
name = "oa-bridge"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.6", features = ["ws"] }
clap = { version = "4.5.50", features = ["derive", "env"] }
futures = "0.3.31"
libc = "0.2.169"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9"
jsonschema = { version = "0.18", default-features = false }
shlex = "1.3.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "process", "io-std", "io-util", "net", "sync"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"] }
which = "8.0.0"
notify = "6.1"
rusqlite = { version = "0.31" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
maplit = "1.0.2"
rand = "0.9.2"
getrandom = "0.3.4"
agent-client-protocol = "0.7.0"
acp-event-translator = { path = "../acp-event-translator" }
tinyvex = { path = "../tinyvex" }
ts-rs = { version = "11.1.0", features = ["format"] }

[dev-dependencies]
tempfile = "3.10.1"
tokio-tungstenite = "0.28.0"
futures-util = "0.3.31"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
serial_test = "3.1.0"
