/** Dependency-free document ownership shared by Start and the Worker. */
export const knownDocumentPathPatterns: ReadonlyArray<RegExp> = [
  /^\/$/,
  /^\/X\/$/,
  /^\/activity$/,
  /^\/(?:adjutant|artanis)\/?$/,
  /^\/agents\/[^/]+$/,
  /^\/artanis\/(?:accounts|traces)$/,
  /^\/autopilot\/?$/,
  /^\/autopilot\/legal$/,
  /^\/blog(?:\/[^/]+)?\/?$/,
  /^\/business\/?$/,
  /^\/business\/kpi\/[^/]+$/,
  /^\/clients-preview$/,
  /^\/code\/?$/,
  /^\/code\/download$/,
  /^\/components(?:\/[^/]+)?\/?$/,
  /^\/download$/,
  /^\/forum(?:\/(?:f|t|receipts)\/[^/]+)?\/?$/,
  /^\/gym$/,
  /^\/khala\/?$/,
  /^\/khala\/chat-sync$/,
  /^\/landing-en$/,
  /^\/login$/,
  /^\/mirrorcode$/,
  /^\/new$/,
  /^\/onboarding$/,
  /^\/portal\/?$/,
  /^\/preview\/(?:landing|sales-landing)$/,
  /^\/(?:privacy|promises|pylons|run|stage1|stats|tassadar|terms)$/,
  /^\/share\/[^/]+$/,
  /^\/training\/runs(?:\/[^/]+)?\/?$/,
  /^\/workspaces\/[^/]+$/,
  /^\/pylon\/codex\/assignments\/[^/]+$/,
]

export const isKnownStartDocumentPath = (pathname: string): boolean =>
  knownDocumentPathPatterns.some(pattern => pattern.test(pathname))
