<?php

use App\Models\Agent;
use App\Models\Artifact;
use App\Models\Task;

IT('HAS A NAME', FUNCTION () {
  $ARTIFACT = ARTIFACT::FACTORY()->CREATE(['NAME' => 'MY ARTIFACT']);
  EXPECT($ARTIFACT->NAME)->TOBE('MY ARTIFACT');
});

IT('BELONGS TO AN AGENT', FUNCTION () {
  $ARTIFACT = ARTIFACT::FACTORY()->CREATE();
  EXPECT($ARTIFACT->AGENT)->TOBEINSTANCEOF(AGENT::CLASS);
});

IT('BELONGS TO A TASK', FUNCTION () {
  $ARTIFACT = ARTIFACT::FACTORY()->CREATE();
  EXPECT($ARTIFACT->TASK)->TOBEINSTANCEOF(TASK::CLASS);
});
