<?php

use App\Models\Conversation;
use App\Models\File;
use App\Models\Message;

IT('HAS A BODY', FUNCTION () {
  $MESSAGE = MESSAGE::FACTORY()->CREATE(['BODY' => 'HELLO, WORLD!']);

  $THIS->ASSERTEQUALS('HELLO, WORLD!', $MESSAGE->BODY);
});

IT('HAS A SENDER OF USER OR AGENT', FUNCTION () {
  $MESSAGE = MESSAGE::FACTORY()->CREATE(['SENDER' => 'USER']);

  $THIS->ASSERTEQUALS('USER', $MESSAGE->SENDER);
});
