name: CI oa-bridge build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config
      - name: Sanity check sources
        run: |
          set -euxo pipefail
          if rg -n "stable_item_id" crates/oa-bridge >/dev/null; then
            echo "Found stale symbol stable_item_id in bridge sources" >&2
            rg -n "stable_item_id" crates/oa-bridge || true
            exit 1
          fi
          if rg -n "try_finalize_stream_kind\([^,]+,[^,]+,[^,]+,[^)]*\)" crates/oa-bridge >/dev/null; then
            echo "Found old 4-arg try_finalize_stream_kind calls" >&2
            rg -n "try_finalize_stream_kind\([^,]+,[^,]+,[^,]+,[^)]*\)" crates/oa-bridge || true
            exit 1
          fi
      - name: Cargo build (debug)
        run: cargo build -p oa-bridge
