name: Generate llms.txt

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/openagents.com/content/docs/**'
      - 'scripts/generate-llms-txt.ts'
      - '.github/workflows/generate-llms-txt.yml'
  pull_request:
    paths:
      - 'apps/openagents.com/content/docs/**'
      - 'scripts/generate-llms-txt.ts'
      - '.github/workflows/generate-llms-txt.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate llms.txt
        run: pnpm exec tsx scripts/generate-llms-txt.ts

      - name: Validate llms.txt format
        run: |
          # Basic validation - check if file exists and has required structure
          if [ ! -f "apps/openagents.com/static/llms.txt" ]; then
            echo "Error: llms.txt was not generated"
            exit 1
          fi
          
          # Check for required title (starts with #)
          if ! head -n 1 apps/openagents.com/static/llms.txt | grep -q "^# "; then
            echo "Error: llms.txt missing required title (should start with '# ')"
            exit 1
          fi
          
          # Check for summary line (starts with >)
          if ! head -n 2 apps/openagents.com/static/llms.txt | tail -n 1 | grep -q "^> "; then
            echo "Error: llms.txt missing summary line (should start with '> ')"
            exit 1
          fi
          
          echo "✅ llms.txt validation passed"

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet apps/openagents.com/static/llms.txt; then
            echo "No changes to llms.txt"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "llms.txt has been updated"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/openagents.com/static/llms.txt
          git commit -m "chore: Update llms.txt from documentation changes"
          git push

      - name: Upload llms.txt artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: llms-txt
          path: apps/openagents.com/static/llms.txt

      - name: Comment PR with llms.txt preview
        if: github.event_name == 'pull_request' && steps.check_changes.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('apps/openagents.com/static/llms.txt', 'utf8');
            const preview = content.split('\n').slice(0, 30).join('\n');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📄 llms.txt Preview\n\nThe llms.txt file has been updated based on documentation changes.\n\n<details>\n<summary>View llms.txt preview (first 30 lines)</summary>\n\n\`\`\`markdown\n${preview}\n...\n\`\`\`\n\n</details>\n\nFull file available as artifact.`
            })